### ISSUE TITLE
Taking a item when used as a trigger

### ISSUE THREAD

**Issue by MinionToGaming** [DRE2N/DungeonsXL#1000]
**The feature you'd like to know more about**
Is it possible to take a item from a player when used to to trigger something

**What did you already try?**
The attached picture is a door i was testing. It works but you keep the diamond.
![2021-03-25_03 55 03](https://user-images.githubusercontent.com/81378512/112508226-c1594b00-8d65-11eb-913b-d257b7b6e740.png)

**Comment by Sataniel98** [comment]
DXL does not have a shortcut for this, but you can use a command sign with the same trigger and use the Vanilla clear command. Should be something like /minecraft:clear %player% diamond 1 IIRC.

**Comment by MinionToGaming** [comment]
So i have it working with scripts signs and essentials clear command. Now my server is sending the command twice. 
My command script looks like this
commands:
  - clear %player% diamond 1 
  My sign script sign looks like this
  0:
  - "[trigger]"
  - "80"
  - ""
  - "UDIAMOND"
1:
  - "[cmd]"
  - "Removekey"
  - "0,op"
  - "UDIAMOND"

**Comment by Sataniel98** [comment]
Command signs have been fixed and improved since the last build was published. The patch will be released soon.
