### ISSUE TITLE
Cannot launch on 1.16.5

### ISSUE THREAD

**Issue by kittylegitcheck** [DRE2N/DungeonsXL#1003]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

1.16.5 plugin does not work

**Expected behavior**

working

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/79789524/113997971-e5825500-9858-11eb-9c77-d5e6b09ee090.png)

![image](https://user-images.githubusercontent.com/79789524/113998163-15c9f380-9859-11eb-875f-7ca8adaf78e8.png)

**Comment by Sataniel98** [comment]
Stacktrace doesn't seem to be complete. Please search for errors starting with "at de.erethon.dungeonsxl".
