### ISSUE TITLE
im confused

### ISSUE THREAD

**Issue by HighlightedTwin** [DRE2N/DungeonsXL#1006]
**The feature you'd like to know more about**
Multifloor dungeons

**What did you already try?**
So I looked through the wiki and even asked about how to set up multi-floor dungeons and it still doesn't make sense to me. After reading through the wiki I don't understand if every floor is supposed to have its own world or if I'm just doing everything wrong. The part I'm talking about is how it stated that every floor needs a start and end sign and which I did and proceeded to set up the config file as well. After finishing that, I did /dxl play and it teleported me to the very last floor/top floor. I honestly don't know what to really do at this point.

**Relevant configuration files**
The file I'm using:

![Screenshot (38)](https://user-images.githubusercontent.com/80426715/114284097-7dc83780-9a1b-11eb-8653-19dfd7dcf558.png)

**Comment by Sataniel98** [comment]
> After reading through the wiki I don't understand if every floor is supposed to have its own world or if I'm just doing everything wrong.

Well yes, multi floor dungeons have multiple floors.

> After finishing that, I did /dxl play and it teleported me to the very last floor/top floor. I honestly don't know what to really do at this point.

/dxl play UndeadTower will take you to the start floor.

**Comment by HighlightedTwin** [comment]
> > After reading through the wiki I don't understand if every floor is supposed to have its own world or if I'm just doing everything wrong.
> 
> Well yes, multi floor dungeons have multiple floors.
> 
> > After finishing that, I did /dxl play and it teleported me to the very last floor/top floor. I honestly don't know what to really do at this point.
> 
> /dxl play UndeadTower will take you to the start floor.

Thats great but that didn't really help me or the issue. I stated it took me to the last floor/top floor when it's supposed to put at the bottom one. There's not really clear instructions on how it works. I put a start sign per every floor and end sign per every floor like the wiki said yet that happens.

**Comment by Sataniel98** [comment]
If I understodd the problem correctly, the latest PR should fix this.
