### ISSUE TITLE
Removing a dungeon portal

### ISSUE THREAD

**Issue by iBobross** [DRE2N/DungeonsXL#1011]
**The feature you'd like to know more about**
Removing Dungeon Portals
(e.g. game rules)

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/getting-started
**What did you already try?**
/dxl break - I executed the command then broke a portal block, the whole portal disappeared but when I do /dxl reload it re-appears.

**Comment by jbaptisteq** [comment]
same issue here
