### ISSUE TITLE
Failed to get resource info from spiget.org

### ISSUE THREAD

**Issue by LoneDevilX** [DRE2N/DungeonsXL#1012]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
Failed to get resource info from spiget.org when starting server

**Reproduce**

(List steps to reproduce, e.g.:
1. Start server
2. Warn

**Relevant configuration files**
[latest.log](https://github.com/DRE2N/DungeonsXL/files/6351755/latest.log)

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Warns are rightly printed if the connection to Spiget fails.
