### ISSUE TITLE
The team cannot start the game normally.

### ISSUE THREAD

**Issue by Crysta11ize** [DRE2N/DungeonsXL#1015]
**Description**

I have tested all versions after DugeonsXL b1066. In the version after b1066, teams with more than two people cannot start the game normally. After the team enters the dungeon, all signs are unresponsive and visible.

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon group with /dxl group create 123 And invite players
2. After the player agrees, enter the dungeon
3. No response, no dungeon title, no error, no response, this is only for the team. Single player dungeon games are completely normal。
4. Now we can only use /dxl leave to leave the dungeon

**Expected behavior**

I hope the team dungeon can play normally, just like the Dungeons version B1066

DungeonsXL Version: b1070,b1081,b1087
Server Type: Tuinity
Server Version: 1.16.5

**Comment by Sataniel98** [comment]
I've tested it with two players and it seems to work as it should. The title appears and signs are initialized as expected. Not really sure what triggers this. Are you sure the ready sign is triggered correctly by all players?

**Comment by Crysta11ize** [comment]
> I've tested it with two players and it seems to work as it should. The title appears and signs are initialized as expected. Not really sure what triggers this. Are you sure the ready sign is triggered correctly by all players?



I don't know what caused it. . But this never happens in version b1066, I will continue to test to find the reason

**Comment by Crysta11ize** [comment]
> I've tested it with two players and it seems to work as it should. The title appears and signs are initialized as expected. Not really sure what triggers this. Are you sure the ready sign is triggered correctly by all players?

After many tests, I found that this is caused by the "READY" sign. Most of the maps on my server use the CUSTOM game type. In versions after B1066, this type of sign cannot be used for team games.

**Comment by Sataniel98** [comment]
Game types have been removed for a long time. Whatever you write in the second line of the ready sign will be ignored.
