### ISSUE TITLE
Group Leader Issue

### ISSUE THREAD

**Issue by Yippu** [DRE2N/DungeonsXL#1017]
**Description**

When a group leader attempts to leave a dungeon with multiple other players in the group, nothing happens, except for "You have to join a group first." in chat.

**Reproduce**

- Create a group with Player A (`/dxl group create DungeonTest_G1`)
- Join dungeon with Player A (`/dxl play TestDungeon`)
- Join the group with Player B (`/dxl group join DungeonTest_G1`)
- Join dungeon with Player B (`/dxl play TestDungeon`)
- Attempt to leave with Player A (`/dxl leave`)

This should result in the "You have to join a group first." text to appear in chat, while not leaving the dungeon until Player B does.

**Expected behavior**

Group leader should be able to leave the dungeon after using `/dxl leave`. The lead should then be passed to another player, or such.

**Screenshots / GIFs / videos**

https://youtu.be/b5OFSXKcTCY

**Relevant configuration files**

```
N/A
```

**Comment by Yippu** [comment]
Note, the Player A also gets their inventory wiped when this happens

**Comment by Sataniel98** [comment]
Thank you for the report. The bug in this case is that Player B using /dxl group join DungeonTest_G1 should be prevented. It shouldn't be possible to join groups when a dungeon game has already been initialized. Instead, Player B should join the group before Player A uses /dxl play, and doing so should teleport all group members.

**Comment by Sataniel98** [comment]
Fixed.
