### ISSUE TITLE
Portal Remove | Bug 

### ISSUE THREAD

**Issue by ToniSevHD** [DRE2N/DungeonsXL#1018]
**Description**

I Have problema when my first portal / dungeon on: 

**Minecraft versión:** 1.16.5 (Spigot)

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a test Map
2. Create a Portal
3. Edit Details and Save.
4. Delete Map, Delete signs, Delete Block of Portal... but... this is the problem...

I keep seeing indications of the Portal, still not being visible.

When I perform the "/ qxl reload" task, this portal appears again.

I have deleted all the content of Maps from the Mod, the yml file that contains the portal data and it keeps coming back ...

What should I do? Where has this information left that causes its reappearance and passive functioning?

Sorry for my bad english. 
I'm going to try to remove the plugin, but it won't let me delete the folder, because of the Maps folder, it's protected or something.

**Comment by ToniSevHD** [comment]
When I reinstall it, the portal appears, but using /dxl break has allowed it to break, but this error has appeared in the console.

![image](https://user-images.githubusercontent.com/83134630/115967984-c1e82b80-a535-11eb-9b36-ad8df6935848.png)

**Comment by ToniSevHD** [comment]
I can see this message when I pass through the area where the portal was.
![image](https://user-images.githubusercontent.com/83134630/115968052-18556a00-a536-11eb-8a31-6717ae640d4b.png)

**Comment by ToniSevHD** [comment]
When I use / dxl reload, this happens:

![image](https://user-images.githubusercontent.com/83134630/115968102-5eaac900-a536-11eb-94be-b16ce663aa52.png)

**Comment by ToniSevHD** [comment]
I have deleted all Edits from WorldGuard worlds.

The same thing keeps happening, each reload reappears, I had to disable the plugin temporarily until a solution on their part.

By the way, it has potential, I hope these bugs can be solved. Congratulations.

**Comment by ToniSevHD** [comment]
The Fix is... Stop Server, Delete Data Portal, Run Server... 

Sorry and Thanks for your Discord Community!

**Comment by Sataniel98** [comment]
Thank you for the report, but this is the same bug as #1011 and it has already been fixed. Updated binaries will be available soon.
