### ISSUE TITLE
Dungeon doesn't even generate. Player frozen, can't execute commands.

### ISSUE THREAD

**Issue by GazpaNova** [DRE2N/DungeonsXL#1022]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

I was having a bug before in which players sometimes entered a DXL and got completely frozen, unable to move or execute commands. The dungeon didn't execute any of the signs either. I've updated to the latest version and it's gotten worse: Now the dungeon doesn't even generate, and players are stuck on an empty, void world. Still unable to move, execute commands, or do anything.

**Reproduce**

(List steps to reproduce, e.g.:
1. Enter a dungeon's lobby through a portal.
2. Mark yourself as ''ready'' with a sign
3. Enter the actual dungeon
4. At random, the dungeon will be blank, and the aformentioned bug will occur. (read description)

**Expected behavior**

I guess being able to actually play.

**Screenshots / GIFs / videos**

https://media.discordapp.net/attachments/655148099337060354/841381958697353287/2021-05-10_15.31.21.png

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

This came out on the main log upon dungeon generation, and consecuent error: https://pastebin.com/EEyBVMMa

This is my main configuration file: https://pastebin.com/cXTqgqSq

This is the dungeon config, shouldn't be relevant because it has happened in all of my dungeons but anyways: https://pastebin.com/12Z6Kiii

**Comment by Sataniel98** [comment]
Couldn't reproduce, but the latest commit hopefully makes this more robust.
