### ISSUE TITLE
Players unable to enter dxl portals on their own/unable to use ready sign in dungeon lobby

### ISSUE THREAD

**Issue by PrismaticShades** [DRE2N/DungeonsXL#1024]
**Description**

So, this issue is very strange to me, its probably something stupid im missing, but players who aren't opped(or have been opped) I think, are unable to start a dungeon, they will join a group as leader, and go through the portal, but the portal takes them nowhere, I can ofc force them in if I or another opped person is the group leader, but then they only show up after I(or the op) readys up, and then they themselves are unable to ready up. This issue happens not at all with players who are opped or have been opped, I tested by deopping one of my builders and sending them in and they could still do everything just fine.

**Reproduce**

Not sure how it happened so not sure how to reproduce.

**Expected behavior**

It should've been that the players could join groups and then go through the portal, as the dungeons are to act a lot like instance dungeons in most MMORPGS

**Relevant configuration files**

This issue has been happening since the dungeon portal was first made, I had made no configuration changes and everything was/is on default. 0.18 snapshot 1087 btw

**Comment by Sataniel98** [comment]
DXL portals don't check for permissions. Please try it in a clean environment without other plugins to make sure this is caused by DXL.
