### ISSUE TITLE
Respawn Locations don't seem to function

### ISSUE THREAD

**Issue by GodPuffin** [DRE2N/DungeonsXL#1028]
**Description**

The escapeLocation and finishLocation gamerules appear to have no effect

**Reproduce**

Set the escapeLocation or finishLocation in config while following the parameters [here](https://github.com/DRE2N/DungeonsXL/wiki/game-rules#respawn-options)

**Expected behavior**

Teleported to corresponding coordinates when escaping/finishing the dungeon

**Relevant configuration files**

My code incase I wrote smt wrong:

```
escapeLocation: "spawnworld,166.0,63.0,-126.0"
```

**Comment by Sataniel98** [comment]
Just tested them and both game rules work fine for me. Are you sure your world is called "spawnworld"? This is probably case-sensitive.

**Comment by GodPuffin** [comment]
aha, my main world is simply called “world”

thank you very much !
