### ISSUE TITLE
to many maps instantiated

### ISSUE THREAD

**Issue by G4RR1SON** [DRE2N/DungeonsXL#1031]
Hello,

I have some custom made maps on my server that i downloaded and DXL is not letting me test them more than 3 times of more than 1 dungeon. when I try to test 1 of the different dungeons more than once, after the 3rd time its telling me that i have "to many maps instantiated". Im not sure what is causing this issue to occur, if someone could please explain to me why this is happening, that would be great.

Thanks

```

```

**Comment by Sataniel98** [comment]
The message is sent when instantiating a world fails for any reason. Some unintended ones have been fixed since your bug report. If you still have issues, please let me know.
