### ISSUE TITLE
when member leave the game(logout) ,then can't join next dungeon

### ISSUE THREAD

**Issue by smalluouo** [DRE2N/DungeonsXL#1034]
If there are >2 player inside the dungeon, one of the member leave the game(logout) and that logout player will stuck at enter next dungeon game,he cant join next dungeon.
process:
A join the group -> enter dungeon -> use the start sign -> dungeon start -> leave server (logout) -> join server -> join the group enter dungeon -> use the start sign -> stuck: other member start the game but A will stuck in the lobby

**Comment by Sataniel98** [comment]
Thanks, fixed!
