### ISSUE TITLE
The player was killed by DungeonsXL

### ISSUE THREAD

**Issue by Crysta11ize** [DRE2N/DungeonsXL#1037]
**Description**
When the player leaves the dungeon or completes the dungeon game, DXL will kill the player

**Reproduce**

1. Enter any dungeon game.
2. Use the command /dxl leave to leave the dungeon game
3. The player was executed

**Expected behavior**

...

**Screenshots / GIFs / videos**

![G@182O_0NGN1HT SF}_C0LC](https://user-images.githubusercontent.com/71912346/124487374-eb7fc780-ddae-11eb-83c9-f734fabfe27a.png)

**Relevant configuration files**

Server 

DungeonsXL Version:  DungeonsXL-0.18b1100
ItmesXL Version: ItemsXL 1.0.1
Server Type: Tuinity
Server Version: tuinity-b14-CB1.17

**Comment by Sataniel98** [comment]
DungeonsXL is not compatible with 1.17.
