### ISSUE TITLE
Can't click ready sign after disconnecting

### ISSUE THREAD

**Issue by call911nowplz** [DRE2N/DungeonsXL#1038]
Everytime a player gets disconnected during a dungeon, they are unable to join a new instance after they re-join

To produce this issue, join a dungeon, Ready up, and disconnect before finishing the dungeon. 
Next time you try to join a new instance it won't let you until the plugin is reloaded or server is restarted 

Currently using v0.18-SNAPSHOT-1097
Spigot 1.16.5

**Comment by Sataniel98** [comment]
Thank you for the report.

**Comment by Sataniel98** [comment]
Fixed.
