### ISSUE TITLE
dungeon fee bug.

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#1039]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

(A clear and concise description of what the bug is, e.g.:
after all player confirm ready through [ready] sign and start dungeon,
when one player clicked ready sign again, all player moved start point and spend fee again.

and can you add dungeon time limit features (i was set time survival mode, but it can't leave dungeons until the time is over) 
![2021-07-07_20 14 08](https://user-images.githubusercontent.com/25452835/124750018-e9109f80-df5f-11eb-8608-41d1e24fdc2c.png)
,execute console command when players finished dungeons? ex) give %player% diamond 1

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/pig/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the pig spawn sign)

**Expected behavior**

(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
1. Requirements are checked twice and charged once. This is intended behavior. I couldn't reproduce that players are charged twice in any case.
2. Might be reworked in the future, but not for 0.18.
3. Use a command sign.

Please open one issue per actual issue in the future :) This helps me keep things organized.

**Comment by Ecilpse** [comment]
wave don't count monster killed by fire aspect enchanted weapon.
i think killed by fire treat as natural death
so many players don't teleport through [Teleport] P 0/1 sign.

 
![2021-07-08_13 22 47](https://user-images.githubusercontent.com/25452835/124862019-9c74a500-dfef-11eb-907c-069d189edb84.png)

**Comment by Sataniel98** [comment]
> wave don't count monster killed by fire aspect enchanted weapon.
> i think killed by fire treat as natural death
> so many players don't teleport through [Teleport] P 0/1 sign.
> 
> ![2021-07-08_13 22 47](https://user-images.githubusercontent.com/25452835/124862019-9c74a500-dfef-11eb-907c-069d189edb84.png)

Sad but _please_ open one issue per issue. Waves aren't supported anymore.
