### ISSUE TITLE
Randomized loot from loot tables

### ISSUE THREAD

**Issue by snapopotamos** [DRE2N/DungeonsXL#104]
It would be great If there was a way to randomize loot from dungeons. If you put a [Chest] sign on a minecraft loot chest ( /setblock ~ ~ ~ minecraft:chest 0 replace {LootTable:"minecraft:chests/simple_dungeon"} ), the game does not generate the loot, so nothing is received from the chest. If it is more convenient to add random loot some other way, like with a sign, that would be fine as well.

**Comment by Sataniel98** [comment]
Seems like a nice idea.

**Comment by snapopotamos** [comment]
This is broken again; same problem as before

**Comment by snapopotamos** [comment]
never mind just read the wiki and I'm not using the loot table option. Thats my fault.

**Comment by snapopotamos** [comment]
Never mind I was right– there isn't a way to get chests to spawn with default Minecraft loot, you have to make and use a custom table (which I can't since I don't have access to the server files).

**Comment by Sataniel98** [comment]
Nothing but DXL loot table scripts is supposed to work.
