### ISSUE TITLE
Daily lockout number 

### ISSUE THREAD

**Issue by T3mpOst** [DRE2N/DungeonsXL#1044]
Within my server I wanted my players to have daily lockouts of 3 per dungeon, right now all I can do is set a time between 1 attempt. 

I would love a new setting that allows me to not only set the time between attempts, but the number of attempts, using this I would create a system of 3 Attempts per 24 hour period per dungeon for my players.

**Comment by Sataniel98** [comment]
I'm not against the idea per se, but I don't see much of a demand for it. If you find someone who'd like to contribute such an addition, feel free to PR it.
