### ISSUE TITLE
keep inv not working when player join dungeon.

### ISSUE THREAD

**Issue by boyOnFire** [DRE2N/DungeonsXL#1047]
title:
  title: "&4OldTown"
  subtitle: "&bFind a way to escape!"
requirements:
  feeLevel: 
  feeMoney: 
  permission:
  groupSize:
    minimum: 1
    maximum: 2
  forbiddenItems:
  keyItems:
keepInventoryOnEnter: true
keepInventoryOnEscape: true
keepInventoryOnFinish: true
keepInventoryOnDeath: true

this is my config of the map everything seems to be working fine except the keep inv one can someone help me i really want help.

**Comment by Sataniel98** [comment]
Do you use Multiverse-Inventories or a similar plugin?

**Comment by JenevieveShe** [comment]
I have encountered the same issue, I even tried setting both main config and dungeon config to 
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
but I still lose my intentory on enter
I'm using Multiverse-core, but not multiverse-inventories, I do have KeepInventory plugin installed tho, could that be the issue?
