### ISSUE TITLE
requirements: feeLevel is invalid

### ISSUE THREAD

**Issue by Function-Z** [DRE2N/DungeonsXL#1048]
**Description**

The requirements: feeLevel in the map's config.yml file is invalid
(地图文件中的config.yml文件中requirements：feeLevel设置不能正确读取玩家的级别）

**Reproduce**

1. Write the following code in the map's config.yml（在地图的config.yml中写下如下代码）
```
requirements:
  feeLevel: 2
```
2. Enter command /dxl reload at the console（后台输入指令/dxl reload）
3. Ordinary players try to enter the dungeon（普通玩家尝试进入副本）
4. Even if the player’s level actually meets the requirements, the chat bar still prompts that the level does not meet the requirements（即便玩家的等级实际上符合要求，聊天栏依然提示等级不满足要求）

**Expected behavior**

I hope that the level requirements can be used normally.
Another suggestion is that the level requirements are divided into two modes, one is to enter a dungeon after reaching a certain level, and the other is to enter a dungeon after deducting a specified amount of level or experience.
My English is not very well. These words are basically modified by translation, I also wrote the original text, I hope there is no problem with my expression
我希望等级需求能正常使用。
还有一个建议是等级需求分为两种模式，一种是达到某个等级可以进入副本，一种是扣除指定数量等级或经验才可以进入副本
我的英语不是很好，这些话基本都是由翻译修改来的，我还写了原文，希望我的表述没有什么问题

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/28294104/127762296-60176fc6-2732-4a60-bb71-aae5b84390c8.png)

![image](https://user-images.githubusercontent.com/28294104/127763180-353168de-5e57-4c0c-818a-edb26f2dafed.png)

![image](https://user-images.githubusercontent.com/28294104/127762404-2590d580-111e-40d8-a7c1-ff2de0fa1641.png)

**Relevant configuration files**

```
requirements:
  feeLevel: 2
```

**Comment by Sataniel98** [comment]
Thank you for the report. The bug is fixed.
