### ISSUE TITLE
Kill all NPCs before a game instance is closed

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#1050]

**Comment by draakkin** [comment]
This feature would be appreciated. 
I often encounter errors with random MythicMobs skills attempting to continue after the world is unloaded. It would also (hopefully) help reduce the file size of active-mobs.json in MythicMobs as it thinks the mobs still exist somewhere and are permanently saved there.

For anyone else using MythicMobs who encounters this issue, a temporary workaround is to NOT use **Despawn: false** and **Persistent: true** for all of your dungeon mobs.

**Comment by Smart0926** [comment]
Me too...
