### ISSUE TITLE
Minor wiki correction

### ISSUE THREAD

**Issue by PikaMug** [DRE2N/DungeonsXL#1051]
In the Maven details section, there is a missing angle bracket:

`<artifactId>dungeonsxl-api/artifactId>`

should be

`<artifactId>dungeonsxl-api</artifactId>`

**Link to the wiki article (in case it exists)**

https://github.com/DRE2N/DungeonsXL/wiki/api-tutorial#how-to-get-the-api

**Comment by Sataniel98** [comment]
Thanks, fixed.
