### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by 0tickpulse** [DRE2N/DungeonsXL#1052]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Every time I reload, it receives "An internal error has occurred while attempting to perform this command."
Console: https://hst.sh/zejocozozu.apache
It doesn't affect any gameplay

**Reproduce**

I'm not sure what to put here, and I'm not putting my DXL file for... certain reasons. If you really need it I might send it.

**Expected behavior**

It should not receive an error.

DungeonsXL v0.18-SNAPSHOT-1112
Purpur git-Purpur-1084 (MC: 1.16.5)

**Comment by VoChiDanh** [comment]
i have same :( https://pastebin.com/70AvHhGp

**Comment by Sataniel98** [comment]
Fixed.
