### ISSUE TITLE
Critical Issue with mythic mobs

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#1053]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
this problem occurs with using mythic mobs with dungeonsxl
when dungeon was closed (DXL game world dissapear), Mythicmobs scheduler error was occur.
this problem is very critical. until the server resetarting, player can't kill mobs and not spawning.

so i contact mythicmobs developer, he said it's not mythicmobs's problems.
i think so. this problem is occur from world delete.
so can you add delete all mobs when DXL game's world was closed?

i think if server developer use mythicmobs with dungeonsxl, this error will must happen.

i uploaded server log files too.
I know it's bothersome, but I hope you look at this problem.

[2021-08-19-4.log](https://github.com/DRE2N/DungeonsXL/files/7021705/2021-08-19-4.log)

**Comment by Sataniel98** [comment]
While I already plan to kill all mobs in game instances when they are unloaded (#1050), I strongly disagree that this is "not MythicMobs' problem". It is, and killing all mobs is just a workaround for _their_ error. Worlds being unloaded at runtime is an intended function of the Bukkit API, and therefore a case MythicMobs **needs** to take it into account. What a chutzpah of these guys to let users of a semi-premium plugin down with this and dump their garbage on me.
