### ISSUE TITLE
How to download dev build??? Idk what can i do with link to dev build in spigot

### ISSUE THREAD

**Issue by VoChiDanh** [DRE2N/DungeonsXL#1055]
How to download dev build??? Idk what can i do with link to dev build in spigot, i need lastest version now to fix gameruler author just fix yesterday but spigot doesnt update it, where can i download it?
Sorry, i'm not good at English!

**Comment by VoChiDanh** [comment]
and i need help with end sign in last floor in dungeon!!!!!! 
I USE

[END]


but it repeat last floor in dungeon again, in the second time when click to board, it end!


TYSM ! I'M NOT GOOD AT ENGLISH!

**Comment by Sataniel98** [comment]
I don't plan to release new development builds anymore before the next release is finished. There will most likely be a release candidate some time next month.

The fix in this case was just error handling if the script of a multi floor dungeon doesn't have the overrideValues und defaultValues sections in it. It will work fine if you use a correct script.

**Comment by VoChiDanh** [comment]
https://pastebin.com/7a01ivpL
that's my file in scriptp
