### ISSUE TITLE
Time to finish does not kick players out of Dungeon

### ISSUE THREAD

**Issue by MARODEUR** [DRE2N/DungeonsXL#1057]
**Description**

I set up a Dungeon with the Rule:

timeToFinish: 1200

But sometimes (not always) players are not kicked out of the Dungeon when the countdown reaches 0. The Countdown then starts to count in negative Value (3..2..1..0... -1...-2...-3..). RewardChests after completing the Dungeon are not working (Reward Inventory not working after dungeon leave). No errors in console.

**Reproduce**

1. Create a new dungeon with /dxl create
2. Configure timetoFinish
4. Test with /dxl play
5. Just wait until the time runs off. It counts into negative and is not kicking players. (Does not appear always)

**Expected behavior**

(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Relevant configuration files**

Used Dungeon Config:
https://pastebin.com/AFM4iSkd

**Comment by Sataniel98** [comment]
Is the game goal set to `gameGoal: TIME_SURVIVAL` or `gameGoal: TIME_SCORE`?

**Comment by MARODEUR** [comment]
No, i oversee that setting and set it. Error has not appeared since then. 
So you always have to set both of the settings for a dungeon for working properly?

**Comment by Sataniel98** [comment]
Yes. The default game goal is END which ends the dungeon when the end sign is reached.
