### ISSUE TITLE
choose your class first

### ISSUE THREAD

**Issue by NgoGManh** [DRE2N/DungeonsXL#1059]
I have already chosen class but it still said: "choose your class first"
Can someone help me, thanks!
Sorry my english bad!
![image](https://user-images.githubusercontent.com/20620556/133965285-383790b7-5a89-446b-bc18-bfc380fc8b18.png)

**Comment by NgoGManh** [comment]
Someone! pls help me

**Comment by Sataniel98** [comment]
Could you please share the class script?

**Comment by NgoGManh** [comment]
[class.zip](https://github.com/DRE2N/DungeonsXL/files/7231345/class.zip)
thank you so much for reply me!

> Could you please share the class script?

**Comment by ShitBLue** [comment]
thank you very for reply me!

**Comment by NgoGManh** [comment]
@Sataniel98 hi can u help me more. im tired with it

**Comment by Sataniel98** [comment]
The classes work as expected for me. Is there an error in the log (possibly somewhere else)?

**Comment by NgoGManh** [comment]
> The classes work as expected for me. Is there an error in the log (possibly somewhere else)?

if member has perm dxl.ignorerequirements, they can join dungeon. But it ignore all requirements on config

**Comment by Sataniel98** [comment]
What are your requirements (including mustFinish, timeToNextPlay game rules)?

**Comment by NgoGManh** [comment]
> What are your requirements (including mustFinish, timeToNextPlay game rules)?

yeah, all of them

**Comment by Sataniel98** [comment]
But what did you set up? Can you please share the relevant configs (DungeonsXL/config.yml, DungeonsXL/maps/[map]/config.yml)?

**Comment by NgoGManh** [comment]
https://pastebin.com/XHjv0cur
https://pastebin.com/tkAU7Zja
Here, thanks.

> But what did you set up? Can you please share the relevant configs (DungeonsXL/config.yml, DungeonsXL/maps/[map]/config.yml)?

**Comment by Sataniel98** [comment]
This map configuration looks like it's copied from the wiki. You can't do that. It includes mutually exclusive rules (initialLives and initialGroupLives) and two requirements sections. You'll have to start with a new file and add the rules you actually want.

**Comment by NgoGManh** [comment]
> This map configuration looks like it's copied from the wiki. You can't do that. It includes mutually exclusive rules (initialLives and initialGroupLives) and two requirements sections. You'll have to start with a new file and add the rules you actually want.

ooh okay, but does it conflict with the class??

**Comment by Sataniel98** [comment]
Since the config file is the one difference between when I tried the class scripts and when you did, yes, I think so.

**Comment by NgoGManh** [comment]
ooh okay, ill try create a new config and tell u a result, much thank!
