### ISSUE TITLE
Mobs cant spawn!

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#1063]
I have watched like 10 tutorials and none worked whats wrong can someone help me?

**Comment by Sataniel98** [comment]
Have you read the wiki article? https://github.com/DRE2N/DungeonsXL/wiki/dungeon-npcs

**Comment by ghost** [comment]
> Have you read the wiki article? https://github.com/DRE2N/DungeonsXL/wiki/dungeon-npcs

Yes

**Comment by Sataniel98** [comment]
So what did you do?

**Comment by ghost** [comment]
Here is what the sighn read

[Mob]
bz (That was the name of my mythic mob)
1,1,MM
D 10

Version 1.12.2

**Comment by Sataniel98** [comment]
Does it say the sign was created correctly, is the ready sign triggered?

**Comment by ghost** [comment]
> Does it say the sign was created correctly, is the ready sign triggered?

It does

**Comment by ghost** [comment]
Here is a picture of it (I did /dxl play dungeon1 (Name of the dungeon)


![Skyblock Client 10_25_2021 10_04_43 AM](https://user-images.githubusercontent.com/82849790/138739368-31a275d9-b221-4dd9-9c81-c192c838b7ed.png)
)

I tried a normal mob and it still does not work

**Comment by ghost** [comment]
> Does it say the sign was created correctly, is the ready sign triggered?

It says it works

**Comment by Sataniel98** [comment]
If the sign isn't replaced by air in /dxl play, then either the sign isn't set up correctly (which seems not to be the case) or the ready sign isn't triggered.

**Comment by ghost** [comment]
> If the sign isn't replaced by air in /dxl play, then either the sign isn't set up correctly (which seems not to be the case) or the ready sign isn't triggered.

I forgot to make a ready signh LOL thanks so mutch for the help
