### ISSUE TITLE
Permissions are stuck on players after they are exiting dungeons

### ISSUE THREAD

**Issue by armandkoltai** [DRE2N/DungeonsXL#1073]
Hi!

I just found out that dungeon permissions are stuck on players after they left the dungeons. I'm using LuckPerms for the permissions.
Any help is appreciated

**Comment by Sataniel98** [comment]
Hi,
thank you for your report. I've forwarded it to LP since it seems to be an issue with their implementation of Vault's transient permission API. I'll let you know once I get a response.

**Comment by Sataniel98** [comment]
Issue has been resolved by LuckPerms.
