### ISSUE TITLE
A new placeholder

### ISSUE THREAD

**Issue by tiradorus** [DRE2N/DungeonsXL#1074]
**Please describe the use case or the problem your request is related to.**

Add the placeholder "%dxl_game_world%"
or "%dxl_game_player_world%"
That give us the name of the world generated by DungeonXl.

_(Actualy, the names are DXL_Game_X)_

**Describe the solution you'd like**

And why would it be usefull?
Because world placeholders from multiverse does not works into DXL worlds, and if you want to target the world of the command block that enterred a command, you can't into a DXL game ^^'
You have to create a path between the player, the %player_world% and the console.
A placeholder from Dxl itself can avoid this.

Have a nice day! =)

**Describe alternatives you've considered**

None

**Comment by Sataniel98** [comment]
What would be the difference between this and %player_world%? https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player
