### ISSUE TITLE
Multiverse

### ISSUE THREAD

**Issue by goldenkuky209** [DRE2N/DungeonsXL#1076]
Everytime i try to edit a dungeon this message shows up in the console:

02.01 12:29:05 [Server] WARN Hmm Multiverse does not know about this world but it's loaded in memory.
02.01 12:29:05 [Server] WARN To let Multiverse know about it, use:
02.01 12:29:05 [Server] WARN /mv import DXL_Edit_1 NORMAL

Idk how to fix it, even if i do the command, after restarting the server it still shows up.

**Comment by Sataniel98** [comment]
Just ignore it and don't add DXL worlds to Multiverse.
