### ISSUE TITLE
Sending player to dungeon lobby with command

### ISSUE THREAD

**Issue by Lawnstub** [DRE2N/DungeonsXL#1077]
**The feature you'd like to know more about**

/Play, but to send someone rather than someone self-sending a command. (Trying to abstract commands from players.)

**Link to the wiki article (in case it exists)**

**What did you already try?**

/help (The command wiki documentation has fewer commands than /help)

I can only find invite to edit.

**Comment by Sataniel98** [comment]
/dxl play is an admin command for testing purposes. Players enter dungeons through group signs & portals: https://github.com/DRE2N/DungeonsXL/wiki/global-structures

**Comment by Lawnstub** [comment]
Are there no ways to send someone to a lobby via command?

**Comment by Sataniel98** [comment]
No, there is no command for this.
