### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Spleggeti** [DRE2N/DungeonsXL#1082]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Had this error when the server started up

**Reproduce**

Have the latest version.

**Expected behavior**

18.01 17:37:01 [Server] ERROR Error occurred while enabling DungeonsXL v0.18-PRE-02 (Is it up to date?)
18.01 17:37:01 [Server] INFO java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
18.01 17:37:01 [Server] INFO at de.erethon.dungeonsxl.util.commons.misc.FileUtil.copyDir(FileUtil.java:82) ~[Dungeonsxl.jar:?]
18.01 17:37:01 [Server] INFO at de.erethon.dungeonsxl.DungeonsXL.checkState(DungeonsXL.java:451) ~[Dungeonsxl.jar:?]
18.01 17:37:01 [Server] INFO at de.erethon.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:253) ~[Dungeonsxl.jar:?]
18.01 17:37:01 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-110]
18.01 17:37:01 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
18.01 17:37:01 [Server] INFO [DungeonsXL] Disabling DungeonsXL v0.18-PRE-02

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Looks like there's an I/O error when a backup of a leftover instance world is made (Java's old File API error messages are garbage). If a world named DXL_Edit_[ID] exists in the root directory of the server on startup, DXL copies it to plugins/DungeonsXL/backups/. Make sure the server software has all permissions it needs and there's enough disc space.
