### ISSUE TITLE
error message after upgrading server to 1.18.2

### ISSUE THREAD

**Issue by MelonMan55** [DRE2N/DungeonsXL#1089]
**Description**

try to edit the dungeon and leave the dungeon, after leaving it console spam error, then dungeon commands send error message in chat until server restart 

**Reproduce**

go to a dungeons world, then leave, then try to rejoin

**Expected behavior**

able to join dungeons and leave them without error messages

![image](https://user-images.githubusercontent.com/101737589/158646761-3cc37bbe-1a2d-4f27-9516-e1745a9ef8db.png)

console logs -
(https://pastebin.com/FW8SLQxc)

**Comment by Sataniel98** [comment]
Fixed in the latest build.
