### ISSUE TITLE
Plugin not enabling after updating to 1.18.2

### ISSUE THREAD

**Issue by doctorblanket** [DRE2N/DungeonsXL#1095]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

Just as it says, the plugin won't enable, and here are the logs: https://mcpaste.io/03e2875d61be3cea

(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

I've restarted the server several time since updating and it never enabled for any of the restarts.

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/pig/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the pig spawn sign)

The plugin to enable and run

(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

https://mcpaste.io/03e2875d61be3cea

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
https://mcpaste.io/f2c5cbe077227c5b
```

**Comment by Sataniel98** [comment]
Did you update ItemsXL and is CaliComp installed?

**Comment by doctorblanket** [comment]
i was missing calicomp, sorry and thank you for the help!
