### ISSUE TITLE
Can't use [Ready] signs, error

### ISSUE THREAD

**Issue by Wihunda** [DRE2N/DungeonsXL#111]
Using the [Ready] sign in any dungeon, with any gamemode and an [end] sign 

12.07 16:15:40 [Server] ERROR Could not pass event PlayerInteractEvent to DungeonsXL v0.14
12.07 16:15:40 [Server] INFO org.bukkit.event.EventException
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:111) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:834) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
12.07 16:15:40 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
12.07 16:15:40 [Server] INFO Caused by: java.lang.NullPointerException
12.07 16:15:40 [Server] INFO at io.github.dre2n.dungeonsxl.sign.ReadySign.ready(ReadySign.java:159) ~[?:?]
12.07 16:15:40 [Server] INFO at io.github.dre2n.dungeonsxl.sign.ReadySign.onPlayerTrigger(ReadySign.java:118) ~[?:?]
12.07 16:15:40 [Server] INFO at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:169) ~[?:?]
12.07 16:15:40 [Server] INFO at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:112) ~[?:?]
12.07 16:15:40 [Server] INFO at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:49) ~[?:?]
12.07 16:15:40 [Server] INFO at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:283) ~[?:?]
12.07 16:15:40 [Server] INFO at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]
12.07 16:15:40 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
12.07 16:15:40 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO ... 18 more

**Comment by Sataniel98** [comment]
Thank you for the report, fixed it and released v0.14.1 :)
