### ISSUE TITLE
Door signs giving error and thus not locking doors

### ISSUE THREAD

**Issue by Thrill12** [DRE2N/DungeonsXL#1110]
**Description**

I am trying to make a door unlock when a certain mob is killed.
Currently, the mob spawning sign is as follows:
-----------
[Mob]
DeepslateKing
1,0,MM
D 5
-----------
The mob spawns perfectly.

For the door, I have 2 signs set up. One for the trigger for the mob being killed as it wont fit on one line in the door sign
---------
[Trigger]
2

DeepslateKing
---------
The other sign is the door sign. It is placed on the door itself by shift-right clicking, and is as follows:
-------
[Door]

T 2
-------
**Reproduce**

1. Create a new dungeon with /dxl create
2. Place the signs above.
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Look at the door sign, there is an error at least for me

**Expected behavior**

I expected this to keep the door locked until the mob "DeepslateKing" is killed, then the players can open the door.

Instead, the door sign has the error where it tells players to contact an admin.

**Comment by Sataniel98** [comment]
Fixed
