### ISSUE TITLE
Mmocore Party with DungeonXL

### ISSUE THREAD

**Issue by JakeHunt93** [DRE2N/DungeonsXL#1112]
Trying to make mmocore-party system into dungeonxls party system will appear this bug on console:
[20:21:39 WARN]: [MMOCore] Task #335119 for MMOCore v1.9.4 generated an exception
java.lang.NoSuchMethodError: 'de.erethon.dungeonsxl.util.commons.player.PlayerCollection de.erethon.dungeonsxl.api.player.PlayerGroup.getMembers()'

To reproduce this erro just set
party-plugin: dungeonsxl
on mmocore config.yml file. Join a dungeon with some friends and just watch the console.

**Comment by Sataniel98** [comment]
DXL doesn't have an Integration for MMOCore. Must be something they did on their end.
