### ISSUE TITLE
Ready sign issue

### ISSUE THREAD

**Issue by Cruwzky** [DRE2N/DungeonsXL#112]
Since I updated to v0.14 this error comes then sombody tries to use the [Ready] sign inside at dungeon. The sign setup up is like this:
1 [Ready]
2 Default
3
4

Then I change back to v0.13 everything works. I have also tried and delete all the DungeonXL files, and generate them again, and setup a dungeon as new, still doenst work, I hope you can help.

http://pastebin.com/sNuXdbkC

**Comment by Sataniel98** [comment]
I'm almost sure that's one of the bugs I've fixed in 0.14.1 (see #111). Thank you anyway for the report, I highly appreciate it in principle :)
