### ISSUE TITLE
Classes? How do i Set them up?

### ISSUE THREAD

**Issue by DarkNightPanda253** [DRE2N/DungeonsXL#114]
Ive made a .yml file in the file under classes with 
items:
- 261,1
- 262,64
- 268,1
- 298,1
- 299,1
- 300,1
- 301,1
- 364,3
- 363,10
  dog: true
  in it and when i make the sign it says "The sign was not written correctly"
  [Classes]
  DogeMaster
  is all thats on the sign and the class file is named DogeMaster.yml

**Comment by Sataniel98** [comment]
Would you please add ´´´ or use Pastebin sothat I can see the formatting? Also, which is your version? (Use /dxl or have a look at the server log to get it)

**Comment by DarkNightPanda253** [comment]
i used the example straight from here
and version 1_10_r1

**Comment by DarkNightPanda253** [comment]
Could you by chance send me a Premade class i can use as an outline?

**Comment by Sataniel98** [comment]
I mean the version of DungeonsXL

**Comment by DarkNightPanda253** [comment]
0.14.2

**Comment by DarkNightPanda253** [comment]
Hello?

**Comment by Sataniel98** [comment]
Nothing to add here. Can't reproduce this, provided you're doing what you said
