### ISSUE TITLE
mod support？

### ISSUE THREAD

**Issue by EthanO3O** [DRE2N/DungeonsXL#115]
If DungeonsXL support mod's mob? like custom NPC or other item
I tried to understand and made a dungeon
It's too hard to understand and use  XD
I saw u r making GUI
If u need art resources I think I can do sth : 3
ah  Can the GUI work on 1.7.10 ? btw

**Comment by Sataniel98** [comment]
DungeonsXL supports all mob providers that provide a spawn command with mob name, world and coordinate parameters - just add them to the external mob providers in the main config. Cauldron itself though might work more or less, but it is not supported.

The GUIs are a feature in the extended version I'm working on and I don't plan anything that would break compatibility.

**Comment by EthanO3O** [comment]
yeah  as u said    i use the Cauldron and not work well
Thanks a lot
