### ISSUE TITLE
Portals not loading world and teleporting groups to world

### ISSUE THREAD

**Issue by Wihunda** [DRE2N/DungeonsXL#119]
Tested with group signs;
If a player is in a group and uses a portal, it teleports them to the nether

Even though portals don't work, using /dxl play to go to the same map works fine

**Comment by Sataniel98** [comment]
Does this occur in a clean environment, too?

**Comment by Sataniel98** [comment]
Is there a stacktrace?

**Comment by Wihunda** [comment]
Doesn't give me a stacktrace.. just tp's me to the nether, doing /dxl shows no maps were loaded.

running this build http://puu.sh/qfECV/4d7c4de880.png with DXL 0.14.4

**Comment by Sataniel98** [comment]
It works fine for me. Is it possible that you're using a plugin that catchs portal events and are you sure that your portal and signs are setup correctly?

**Comment by Wihunda** [comment]
I don't believe so, it worked in the same environment before. The only thing that changed from last time it functioned was the dxl update to 0.14.4.

I've updated to the spigot 7-26 build and now loading the server up gives me an error and DXL doesn't seem to work at all.

27.07 12:59:00 [Server] WARN java.lang.reflect.InvocationTargetException
27.07 12:59:00 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
27.07 12:59:00 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
27.07 12:59:00 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
27.07 12:59:00 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
27.07 12:59:00 [Server] WARN at io.github.dre2n.caliburn.item.ItemType.instantiate(ItemType.java:78)
27.07 12:59:00 [Server] WARN at io.github.dre2n.caliburn.item.UniversalItemStack.<init>(UniversalItemStack.java:37)
27.07 12:59:00 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
27.07 12:59:00 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
27.07 12:59:00 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
27.07 12:59:00 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:96)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:133)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
27.07 12:59:00 [Server] WARN at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130)
27.07 12:59:00 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179)
27.07 12:59:00 [Server] WARN at io.github.dre2n.dungeonsxl.loottable.DLootTable.<init>(DLootTable.java:101)
27.07 12:59:00 [Server] WARN at io.github.dre2n.dungeonsxl.loottable.DLootTables.<init>(DLootTables.java:34)
27.07 12:59:00 [Server] WARN at io.github.dre2n.dungeonsxl.DungeonsXL.loadDLootTables(DungeonsXL.java:534)
27.07 12:59:00 [Server] WARN at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:273)
27.07 12:59:00 [Server] WARN at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:136)
27.07 12:59:00 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
27.07 12:59:00 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
27.07 12:59:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
27.07 12:59:00 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
27.07 12:59:00 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
27.07 12:59:00 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
27.07 12:59:00 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
27.07 12:59:00 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
27.07 12:59:00 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
27.07 12:59:00 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
27.07 12:59:00 [Server] WARN at java.lang.Thread.run(Thread.java:745)
27.07 12:59:00 [Server] WARN Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
27.07 12:59:00 [Server] WARN at io.github.dre2n.caliburn.item.CustomItem.<init>(CustomItem.java:120)
27.07 12:59:00 [Multicraft] Skipped 25 lines due to rate limit (100/s)
27.07 12:59:00 [Server] Startup Done (7.844s)! For help, type "help" or "?"
27.07 12:59:00 [Server] WARN [DungeonsXL] [Updater] API connection returned response code 520
27.07 12:59:00 [Server] WARN java.io.IOException: Server returned HTTP response code: 520 for URL: https://api.inventivetalent.org/spigot/resource-simple/9488
27.07 12:59:00 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
27.07 12:59:00 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
27.07 12:59:00 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
27.07 12:59:00 [Server] WARN at io.github.dre2n.dungeonsxl.util.commons.update.spigot.SpigotUpdater.run(SpigotUpdater.java:131)

Thank you for the help so far, by the way!

**Comment by Wihunda** [comment]
correction; dxl doesn't give me an error on running any commands but also doesn't do anything

**Comment by Sataniel98** [comment]
This one is an error in a loot table. Caliburn (the item deserialzation API) is not very tolerant even with minor mistakes at the moment. You probably just have an ambiguous numeric variable that it cannot fetch as a double (like 2 instead of 2.0).

**Comment by drixle** [comment]
the same happened to me , so I destroyed the lobby sign that was attached to the wall and put it on the floor and then work now but I have another problem now, if I put a cooldown (using timeToNextPlay), like for 6 hours for the player to a dungeon , when he comes in for a dungeon in which he's cooldown , it goes to the nether or to a random place in the world.

**Comment by Sataniel98** [comment]
Fixed.
