### ISSUE TITLE
/dxl reload not working and giving error

### ISSUE THREAD

**Issue by Wihunda** [DRE2N/DungeonsXL#121]
Doing dxl reload in any condition causes this

28.07 11:08:05 [Server] INFO Wihunda issued server command: /dxl reload
28.07 11:08:05 [Server] ERROR null
28.07 11:08:05 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.14.4
28.07 11:08:05 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
28.07 11:08:05 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
28.07 11:08:05 [Server] INFO Caused by: java.lang.IllegalArgumentException: The permission dxl.break is already defined!
28.07 11:08:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO at io.github.dre2n.dungeonsxl.player.DPermissions.register(DPermissions.java:205) ~[?:?]
28.07 11:08:05 [Server] INFO at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:261) ~[?:?]
28.07 11:08:05 [Server] INFO at io.github.dre2n.dungeonsxl.command.ReloadCommand.onExecute(ReloadCommand.java:70) ~[?:?]
28.07 11:08:05 [Server] INFO at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
28.07 11:08:05 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10_BT52_07_26.jar:git-Spigot-078e2f8-21e3b05]
28.07 11:08:05 [Server] INFO ... 15 more

^ tested with no maps loaded on 0.14.4
on the spigot 7-26 build

**Comment by Sataniel98** [comment]
Take a thank you doge, good Sir.

![](https://media.giphy.com/media/a3IWyhkEC0p32/giphy.gif)

Fixed it in DXL 0.15-SNAPSHOT-03 :)
