### ISSUE TITLE
Remove legacy support

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#123]
Legacy support will get removed entirely when the plugin is finished to keep the code clean and up to date.
- [ ] Remove /dxl deleteportal command (-> /dxl break)
- [ ] Remove MythicMobs signs (-> ExternalMob)
- [ ] Remove support for 1.7.x and 1.8.x (-> 1.9+ :P)

**Comment by drixle** [comment]
Please do not remove MM , dungeonxl will only serve if I can spawn MM within the dungeons , I've created over 25 dungeons to my server using MM sings :(

**Comment by Sataniel98** [comment]
Of course, you can still spawn MythicMobs NPCs. Signs like described in the wiki, for example

[ExternalMob]

SkeletalKnight

2,5,MM

D 5

Will always work. Just legacy signs, which are deprecated for multiple major updates now, will be removed:

[MythicMobs]

SkeletalKnight

2,5

D 5

However, this is scheduled for an update that will probably be finished in 2017 or even later...

**Comment by drixle** [comment]
ok , now I understand , thank you , enjoying this conversation , could you tell me where my team is missing . when we create a dungeon and a player who is on cooldown in it, he is teleported to the nether or to a random area in the world?

**Comment by Sataniel98** [comment]
Could we please discuss this in a serperate issue? ^^ #124

**Comment by Sataniel98** [comment]
See #333
