### ISSUE TITLE
Random teleport on cooldown

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#124]
Quote

"ok , now I understand , thank you , enjoying this conversation , could you tell me where my team is missing . when we create a dungeon and a player who is on cooldown in it, he is teleported to the nether or to a random area in the world?"

**Comment by Sataniel98** [comment]
Could you please explain in detail what happens?

**Comment by drixle** [comment]
When a player completes the Dungeon ( A) , I would like him to go on cooldown in it, so I used < timeToNextPlay > in the  confing.yml of dungeon (A ) but if he reenters the gungeon group ( A) instead it can not use the portal, it is teleported to the nether or some random part in the world

**Comment by Sataniel98** [comment]
Aaaaah, I think I get it.

**Comment by drixle** [comment]
I disabled the nether now and when a player in cooldown reenters the group he goes to the location ( X , Y , Z ) in the world where the lobby sign would be in the dungeon he is on cooldown
