### ISSUE TITLE
Teleporting to nether

### ISSUE THREAD

**Issue by Endothelium** [DRE2N/DungeonsXL#131]
Hello,

First of, very nice plugin, great job.

I have an issue : when player enter a dungeon, it often teleport the player to the nether.
The state of the game on the sign is still "full" and not "is playing".

If i tp back and retry to enter, it may success but sometimes after clearing the dungeon the sign state is still "is playing" with no name under it.

I am running the last version "0.14.4", Spigot 1.9.4. 
I have few plugins installed :
- Worldedit
- EssentialsX
- MythicMobs
- ProtocolLibs
- LibDisguise

Edit: it give me often a flat map too.

Thank you :)

**Comment by Sataniel98** [comment]
Hi,
yes, this is a known bug (see #124). It has been fixed recently and the fix will be included in v0.15. Dev builds are available [here](http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl).
