### ISSUE TITLE
Floor config issue

### ISSUE THREAD

**Issue by VinLoman** [DRE2N/DungeonsXL#132]
If I drop a floor configuration into my map/%mapname folder, the plugin won't run at all after restarting. I edit the config to fit my map/floor.

**Comment by Sataniel98** [comment]
Is there an error log?

**Comment by VinLoman** [comment]
No there's nothing at all.

**Comment by VinLoman** [comment]
It's like the plugin is disabled, but it isn't in /pl and loads up fine.

**Comment by Sataniel98** [comment]
May I see the config?

**Comment by VinLoman** [comment]
http://pastebin.com/dQVwRz3V

**Comment by SnUncle** [comment]
same problem

**Comment by wysohn** [comment]
I believe that this is caused by the wrong documentation problem

see #145

**Comment by Sataniel98** [comment]
Created a task oriented issue here: #159
