### ISSUE TITLE
Timed dungeons  / Hardcore mode

### ISSUE THREAD

**Issue by MCrashtest** [DRE2N/DungeonsXL#133]
Hey there ! :)

Would it be possible to add a timer for solo / group play that i could use for a website ladder ?
Basicaly entering dungeon / timer start / end when you exit dungeon and saved for the player or group.
Update if player / group release a better timer on a further run and so on ...

Second question that mostly require your developer opinion is mostly specific to my server project.
I'm planning on storylined game where you basicaly have to clear one dungeon to unlock the next one thing is really did like to make things harder ( full sadism ) where dying mean starting again from first dungeon and so on.
Any plans with DungeonXL to add such possibility or any way i could do that with an alternative way ?

Best regards,

Crash

**Comment by Sataniel98** [comment]
I'm not sure about the first thing, but the second one should be easily possible with a small addon. Provided that your setup with mustFinish and initialLives is correct, it should be sufficient to listen to the DGamePlayerDeathEvent and clear the finished dungeons / times in the player data:

event.getDPlayer().getData().getTimeLastPlayed().clear();

**Comment by MCrashtest** [comment]
Going to look further into this then.
The timer was mostly the most interesting feature tought; if you find any way in the futur to offer such option it would be the cherry on top this plugin is almost perfect right now !

Thanks for this fast answer, have a nice day :)
