### ISSUE TITLE
Dungeon signs not functioning

### ISSUE THREAD

**Issue by astralgemini** [DRE2N/DungeonsXL#135]
I've been trying to get this plugin to work for several weeks now, i've read through again and again the wiki and manual for it, and i can't seem to get it to work. i'm not seeing any errors in the console, it just seems to fail to activate the sign functions. please help

**Comment by Sataniel98** [comment]
Did you setup the dungeon with lobby, ready and start sign?

**Comment by astralgemini** [comment]
Oh, i didn't realize that was necessary. Is there an option to allow players to take their own inventory into the Dungeon, rather than getting a "class kit" ?

**Comment by Sataniel98** [comment]
Yes, the name of the rule is "keepInventoryOnEnter".

**Comment by astralgemini** [comment]
is there a command to use to set that, or do i set that in the config files?

**Comment by astralgemini** [comment]
also, there seems to be a small error, when a player leaves or exits a dungeon with over 20 HP.

**Comment by Sataniel98** [comment]
Still? There used to be a bug but it was confirmed to be fixed, may I know which is your version?

**Comment by astralgemini** [comment]
0.14.4 i believe

**Comment by astralgemini** [comment]
also, is there a way to change the set name of a dungeon, or change the message that pops up when a player starts the dungeon?

**Comment by Sataniel98** [comment]
Well, it's always the name of the dungeon and the name of the floor (or just one if they are the same). "_" is automatically replaced with a space for convenience

**Comment by Sataniel98** [comment]
You can also set sendFloorTitle to false in the main config.
