### ISSUE TITLE
Set rules and create msgs

### ISSUE THREAD

**Issue by Theidiotwhoknowsnothing** [DRE2N/DungeonsXL#138]
I can't create messages, and where do I go to set my rule of keepInventoryOnEnter to true? Additionally, how can I get a command to run at the end of my level?

**Comment by Sataniel98** [comment]
Didn't you read the wiki?

**Comment by Theidiotwhoknowsnothing** [comment]
I did, I couldn't figure it out. Sorry.

**Comment by Theidiotwhoknowsnothing** [comment]
The command to run I see, but the set rule I can't

**Comment by snapopotamos** [comment]
you have to edit the server files, there isn't a command to do it.

**Comment by Sataniel98** [comment]
Well, there actually is a command for messages (/dxl msg). It works in edit mode.
