### ISSUE TITLE
Questions about DXL

### ISSUE THREAD

**Issue by Callial** [DRE2N/DungeonsXL#139]
First question, if you are having multiple groups in a game do we have to use 0 and 1 or can we use 1 and 2, or maybe 1, 2, 3?

**Comment by DragonHeart98361** [comment]
Also my server has implemented your plugin and we are having issues, any help would be greatly appreciated :) we talked a while ago in pm on spigot and my username was reltuc295

**Comment by Callial** [comment]
Second question, is there a way to disable friendly fire for people in a group?

**Comment by Sataniel98** [comment]
Just set friendlyFire to false. Groups numbers are just for internal usage, so there shouldn't be a problem with '0'. Java array and collection index numbers start with '0', so the first group that joins the dungeon will use this number.

**Comment by Sataniel98** [comment]
If it's about colors: You can change the colors in the main config.yml.

**Comment by Callial** [comment]
also /dxl break and /dxl reload and possibly a few more give internal errors when either I or any of my co staff try to use them, any ideas?

**Comment by Sataniel98** [comment]
Update the plugin to the latest build.

**Comment by Callial** [comment]
I will tell the owner about that one thanks :)

**Comment by Callial** [comment]
also one glitch I have noticed, sometimes when you leave or finish a dungeon it sends you back to the dungeon rather than your original world

**Comment by Sataniel98** [comment]
Under which circumstances does this happen?

**Comment by Callial** [comment]
It seems to be random sometimes it happens sometime it doesn't

**Comment by azerty5** [comment]
Hi,

Dragon and I are working on a server using your very, very lovely plugin. Though, it seems that somehow we lose our permissions without evening doing anything. One time, Dragon just logged on and he couldn't do any of the /dxl commands. Then just now, I went AFK for about 5 minutes and returned and I could not do any of the /dxl commands either. I was wondering if the server owner possibly installed something wrong or it's our ranks/prefix's interfering with it? 

Last time when it happened to Dragon (if I recall right) we had the owner re-install the plugin and that seemed to fix everything. It just kind of seems of odd, and it would be very stressful if this happened once we had everything up any running.

If this is nothing on your side, all apologies for bothering you; and dragon and I will make another world to store maps just in case something like this happens again. -

Thank you for reading, and thank you for making a very awesome plugin. Hope to hear from you soon! 

UPDATE:

Before posting I was trying out a few other things, and it looks like I also can't join Group Signs, or join groups.

**Comment by Sataniel98** [comment]
I'm not sure about the permission issue. DungeonsXL has a kind of hacky feature to add transient per dungeon or edit mode only permissions which might lead to misunderstandings if used incorrectly, but most of this transient permission system is provided by Vault and therefore shouldn't be prone to bugs. Another possible reason for your issue is the tutorial feature which might has assigned a wrong group to you.

Your issue with group signs might be a cause of the reinstallation you mentioned. Group sign blocks will not be removed or changed automatically if the plugin or the data get removed, but they will not work anymore. If this is not the case, it would be very helpful if you could provide a console error log.

Thank you for your feedback, please feel free to ask further questions :)

**Comment by azerty5** [comment]
Alright, thank you:)

**Comment by Callial** [comment]
we will send you any further problems we have, and we have the owner getting the console log for you.

**Comment by Callial** [comment]
I was asked by the owner to confirm that version 0.14.4 is in fact 1.7.9 through 1.10? Because we appear to be having an issue where every once in a while the plugin breaks and certain commands stop doing anything at all. Our server is bungeecorded 1.8-1.9 I believe

**Comment by Callial** [comment]
The only fix we have found for the issue is to completely reinstall the plugin and we don't want to be constantly doing this

**Comment by Sataniel98** [comment]
1.9-1.10.2 servers are fully supported and the extended support covers 1.7.9-1.8.x. BungeeCord and any other proxy software should not affect the plugin. The only thing that does affect compatibility is the Minecraft / Spigot / CraftBukkit version (/version). The /dxl status command might help you to see incompatibilities (even though an X does not necessarily have to mean the server will explode if you ignore it ;) ). Is it possible that you're using the /reload command or a plugin like Plugman to reload the plugin? If yes, I'm afraid but I cannot guarantee these kind of dynamic reloading to work. Especially the instantiation system doesn't like it much. However, is there a red message like "an internal error occurred..." in the chat when you try to enter a command or just no reaction at all?

**Comment by Sataniel98** [comment]
Also, if you're server software is for 1.7.x or 1.8.x, please have a look at [this](https://github.com/DRE2N/DungeonsXL/wiki/legacy-support). Just to avoid misunderstandings, I'm almost sure your issues have nothing to do with the server version

**Comment by Callial** [comment]
there is no error at all, and the reload command we were trying was the one included in dxl

**Comment by Callial** [comment]
also what are the performance tweaks that we need to disable? if we are in 1.8 minimum

**Comment by Callial** [comment]
https://gyazo.com/5c18eaeab4109e29d1529f43d55b3ffa
There is our plugin list if there are any that could be causing the issues we will remove them ;)

**Comment by Sataniel98** [comment]
There's an option in the main configuration file, "tweaksEnabled: true/false", that cannot be enabled if you use 1.7 or 1.8. If enabled, a lot of resource intensive tasks are done in an asynchronous thread instead of the main thread, such as loading worlds and copying files. This is quite hacky because Bukkit itself does not support concurrency. If worlds are loaded in the main thread, you'll definitely notice a short lag of 0.5 to 2 seconds depending on the size of the world. The asynchronous world loader resolves this problem completely. The average performance is barely affected and should be fine anyway, though.

**Comment by Sataniel98** [comment]
There's not really a plugin that seems to be "suspicious" except PlugMan.

**Comment by Callial** [comment]
We have updated the server to 1.10.2 and we are testing it now, we will report any issues here :)

**Comment by Callial** [comment]
We are still having issues with commands just vanishing and no longer working, we get no internal error, they just do nothing any help would be greatly appreciated.

**Comment by azerty5** [comment]
Adding onto what Dragon said above: I found one command that gives off an Internal error, and that command is ./dxl portal.

**Comment by azerty5** [comment]
Hi,

We're still pushing forwards with our work. But the crashing of the plugin is still a problem. We were wondering if you have looked into any possibly reasons why it would be doing this. We fully updated to 1.10.2, and this time we just logged on and we tried to /dxl edit one of our maps and nothing happened, no error; and, like said above most other commands broke, too. Again, as stated above the /dxl portal command sends off an Internal error. 

We are kind of stuck at what to do to avoid this from happening and to not have to re-install the plugin every time this happens.

If you are free and would like to get on yourself and see, our Head-Admin and us are willing to give you permissions to /dxl. Though we cannot help with console logs, as the owner only has access to that.

Hope to hear a reply soon, thanks.

**Comment by Sataniel98** [comment]
I was not able to reproduce your problems, so without any kind of log and setup (DXL data files, config, custom scripts), it's like trying to catch smoke with bare hands...

**Comment by Sataniel98** [comment]
The only thing I could imagine is data corruption caused by crashs or unsafe stops or any other kind of invalid input that cause errors even before subcommands are registered. In this case, details would still be extremely useful sothat I can spot where exactly the exception occurs and improve the error checks.

**Comment by azerty5** [comment]
Working on getting you some error messages. Hopefully we'll receive them within the next day! 

And thank you, for giving us your time to try and fix our little problem:)  I'll write to you again once I have some errors :)

**Comment by Callial** [comment]
Our headadmin would be happy to whitelist you if you would be ok coming to check things out on our end?

**Comment by Sataniel98** [comment]
Thank you, but there is currently no need to check anything in game. Config, script, data files and logs would be more helpful.

**Comment by Callial** [comment]
We think we have discovered the issue, there was a problem with itemsXL and any ixl command we typed gave an internal error however as soon as we uninstalled IXL DXL seems to be working perfectly. if we have any other issues they will be posted here ;)

**Comment by Callial** [comment]
Also I noticed there are certain threads you have marked with a "premium" tag and I was wondering if there is a premium version of dxl when will it be released?

**Comment by Sataniel98** [comment]
I'm working on an extended version of DungeonsXL with improved, mainly cosmetic features (such as options GUIs, scoreboards, a dungeon setup assistant and stats) with low priority. The core is more important and still neither finished nor tested thoroughly at the moment. I don't think the extended version will be published in the forseeable future.

**Comment by Maho24** [comment]
Dear Sataniel98,
is there a way you can add per dungeon server resource pack
also, is where i should post requests? i have no idea how this works (ma first time using github)

Greetings Maho24

**Comment by Sataniel98** [comment]
@Maho24 
Hi,
just create a new issue with a detailed description about your issue (be it a bug report, a feature request or a simple question) here:
https://github.com/DRE2N/DungeonsXL/issues/new

At the moment, there is no such feature.

**Comment by Callial** [comment]
Is there any way to make classes cost in game money?

**Comment by Callial** [comment]
When I try to create a message with /dxl msg it gives me an internal error. This is the command I used /dxl msg 4 "Hmm, This door is locked. Maybe there is a way to unlock it elsewhere?"

**Comment by Sataniel98** [comment]
Don't worry, I've fixes this a few days ago. You can also still add the messages to the config manually.

**Comment by Callial** [comment]
when will the fix be uploaded? or has it already

**Comment by Sataniel98** [comment]
It is at least included in build 12.

**Comment by azerty5** [comment]
Hi, 

we've received an error log and we're hoping you could look at it and try to see what is causing our problem with the plugin just randomly crashing; my only problem being is I don't know what part you want to see, as the hole log is really long... If you could tell us something maybe we should look for? or if you just want us to send the hole thing. 

Thanks for your time.

**Comment by Sataniel98** [comment]
Should look similar to this:

```
12.07 16:15:40 [Server] ERROR Could not pass event PlayerInteractEvent to DungeonsXL v0.14
12.07 16:15:40 [Server] INFO org.bukkit.event.EventException
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10_BT52_07_12.jar:git-Spigot-cf6dea3-ca1bb1c]
12.07 16:15:40 [Server] INFO at 
...
```

and end with

```
12.07 16:15:40 [Server] INFO ... 18 more
```

**Comment by Callial** [comment]
I believe this is what you are looking for?
[ErrorLog.txt](https://github.com/DRE2N/DungeonsXL/files/480938/ErrorLog.txt)

**Comment by Sataniel98** [comment]
This does not seem to cover all of your issues (e.g. the loading bugs), though. Are there any other stacktraces?

**Comment by Callial** [comment]
The commands that were typed first seemed to start it and from there it was just a repeat of this error

**Comment by azerty5** [comment]
[log.txt](https://github.com/DRE2N/DungeonsXL/files/481052/log.txt)

That's the whole log from start to the crash

**Comment by Sataniel98** [comment]
Thank you
![](http://67.media.tumblr.com/tumblr_m0g658Xkrt1rqfhi2o1_500.gif)

**Comment by Callial** [comment]
We have the latest version of Dungeons that is on the spigot page version 0.14.4 but message creation still does not work.

**Comment by Callial** [comment]
Is there any way to use vault to give players money after successfully completing a dungeon?

**Comment by Sataniel98** [comment]
Latest changes are included in dev builds.

Just create a chest and add a money value to the chest sign.

**Comment by Callial** [comment]
Is there any way to make it so either multiple people can claim the same chest or make it so one person can only claim one chest?

**Comment by Sataniel98** [comment]
The group of the player who opened the chest gets the loot. You can use one player per group and multiple groups per dungeon.

**Comment by Callial** [comment]
Thanks :)
Also we are having a problem with Itemxl serialized items in classes, could you tell us what we are doing wrong?

[ClassError.txt](https://github.com/DRE2N/DungeonsXL/files/488741/ClassError.txt)

[archer.txt](https://github.com/DRE2N/DungeonsXL/files/488742/archer.txt)

The archer class is a yml file I just switched it to txt so I could upload it here

**Comment by Sataniel98** [comment]
The scripts need to be valid YAMLs; this one has a syntax error. In this case, the indents are wrong.

A valid YAML would be:

```
items:
  - ==: org.bukkit.inventory.ItemStack
    type: IRON_HELMET
    meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §b§lNewly Forged Iron Cap
    lore:
    - Straight from the Blacksmith!
```

What you've got is:

```
  - ==: org.bukkit.inventory.ItemStack
  type: IRON_HELMET
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §b§lNewly Forged Iron Cap
    lore:
    - Straight from the Blacksmith!
```

[http://www.yamllint.com/](http://www.yamllint.com/) might help you in the future ;)

**Comment by Callial** [comment]
So we have been working on this for a while and we finally seemed to have it working when something strange happened, we were editing our main dungeon and we decided to move the lobby sign up onto a platform, then when we saved it and tried to play the play world seemed to be missing. And when we checked our server directory we saw this.

https://gyazo.com/957169001671b12e37cf894dcd6469e2

**Comment by Callial** [comment]
Never mind we solved it on our own, we had created a hologram with the id of air as the item and because it could not load it broke itself

**Comment by Callial** [comment]
We now have a working beta setup of our server using a few of your amazing plugins ;) and I was wondering if you wanted to maybe check it out sometime?

**Comment by Sataniel98** [comment]
I'd really like to have a look at it. IP? My ingame name is "Sataniel" in case you need it for a whitelist.

**Comment by Callial** [comment]
The ip is play.orbmc.net just remember to use minecraft 1.10+ as we have had issues with bungeecording, once you are logged in it will take you to a hub where you type /dungeons to connect. I will whitelist you now so you can get on and take a look whenever you are ready If you want to meet up with me when I am online I am usually available from about this time for the next 6-7 hours if you just ask a staff member they can contact me :)

**Comment by Callial** [comment]
On weekends I am on a lot longer tho so it might be easier to meet up then :)

**Comment by Sataniel98** [comment]
Well, in my country, this is the time from midnight to 7 AM xD

**Comment by Callial** [comment]
XD
Well you are whitelisted so if you get on just look for the portal and group sign and you can test out our beta dungeon :)

**Comment by Callial** [comment]
[archer.txt](https://github.com/DRE2N/DungeonsXL/files/503961/archer.txt)
When we upload it to our server the class sign still does not work :-;

**Comment by Callial** [comment]
we do have it saved as a yml

**Comment by azerty5** [comment]
We also put it into the yml checker you sent, and it said that it was valid but when we uploaded it the sign did not appear to work:)

**Comment by azerty5** [comment]
Also, it appears when people logg off and their still in the dungeon it does not kick them, and when I'm in a group with one of them and I try to leave the dungeon it gives me an error. Is there a way to disable it so when they do logg off it removes from the group? 

Sorry if that doesn't make any sense

**Comment by Sataniel98** [comment]
It kicks them immediately if you set timeUntilKickOfflinePlayer to 0. If it doesn't work it's a bug.

**Comment by Callial** [comment]
Also where are the configs for each map specifically located? we have just got full access to the plugins folder so it should streamline things from here :)

**Comment by Sataniel98** [comment]
plugins/DungeonsXL/maps/{map name}/config.yml

**Comment by Callial** [comment]
Thanks, also we should be online on the server for the next few hours if you want to check it out :)

**Comment by Callial** [comment]
Also we went to that directory and there was no config.yml 
This is all we saw
[https://gyazo.com/94c39816a76bf7e7d47bd5ae488990aa](url)

**Comment by Sataniel98** [comment]
The wiki and FAQ might help :)

> In case you’re confused because you do not find a config.yml file in your map folder: This is intended because a map does not necessarily need a config file. The values can also be fetched from the dungeon configuration, which is more convenient if a dungeon has multiple floors with the same rules, or from the main configuration, which might be more convenient if the game is very simple or for testing / building purposes.
> ~ [Floor configuration article](https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration)
> 
> Help! There's no config.yml in my dungeon map folder!
> 
> You have to create the file yourself because the floor configuration is optional. Note that the game rules you define in the floor configuration can also be fetched from other sources: If you create a multi floor dungeon with multiple maps, you probably want to have the same config values for all maps. In such a case, it's easier to use the dungeon configuration and to add the values to the defaultValues or to the overrideValues section. Even without a multi floor setup, the default values or the values from the main config or the game type are sometimes sufficient for small projects. Therefore, there's just a file if it is needed either because you've created it or to store the players that are allowed to edit the map without the permission node.
> ~ [FAQ](https://github.com/DRE2N/DungeonsXL/wiki/faq#help-theres-no-configyml-in-my-dungeon-map-folder)

I've had a look at your class script, the YAML syntax is correct but not like Bukkit expects ItemStack formats. It seems you forgot about the indents after meta, like

```
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:swiftness
```

**Comment by Callial** [comment]
Thanks again, :) It is great to have a plugin dev that actually cares about those who use their plugin

**Comment by Callial** [comment]
Also is there anyway that instead of players leaving the "Dungeon" when they die they go into a spectator mode?

**Comment by Sataniel98** [comment]
No

**Comment by Callial** [comment]
Oh well thanks for trying :) we will try to implement another plugin with the feature and get it working that way :)

**Comment by Callial** [comment]
Is there any way for players to only take certain items out of a dungeon?
And on the same note how does the "Treasures" menu work, the one that pops up after a dungeon

**Comment by Callial** [comment]
Also one other thing, Az and myself have been thinking of getting more in depth with plugin development. How would you recommend we start.

**Comment by Sataniel98** [comment]
Just place some reward chests (chests next to [chest] signs) and put something into the chest.

If you'd like to program yourself, most developers will recommend you to learn Java first (there are several books and online documentations) and start with Bukkit development when you know how programming works. I myself did both simultaneously and I think I am good enough for everything Bukkit could do. The golden rule is NEVER watch YouTube tutorials unless you really know how to decide which ones are good and which ones are not.

**Comment by Sataniel98** [comment]
I'll close this now, feel free to create new issues if you have any further questions
