### ISSUE TITLE
Can't invite player to edit a dungeon

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#141]
Another problem o/ 

When i invite player to edit the dungeon, there is no problem, i've got the message that tell me it's done (you successfully blablabla...). However, the player can't edit the dungeon (can't use command, break/put a block etc...). 

Then, when i try to uninvite the player, i have the message "an internal error occure...".

If you have never seen this problem (i see this since 14.2 or 14.1, I don't remember), i will add some logs from the console soon.

**Comment by Sataniel98** [comment]
I'll have a look at it, thank you for the report!

**Comment by Sataniel98** [comment]
Confirmed, working on it

**Comment by Tiplish** [comment]
Great ;) Thx

**Comment by Sataniel98** [comment]
Fixed in build 16. Thank you again :)
