### ISSUE TITLE
wrong documentation or wrong enum type

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#145]
in RequirementTypeDefault.java line 27

identifier of PERMISSION is defined as "permission"

`PERMISSION("permission", PermissionRequirement.class);`

but the documentation says "permissions"

requirements:
  # If the group has too many or not enough members, the players will not be allowed to use the ready sign.
  groupSize:
    minimum: 1
    maximum: 2
  # Players must have these permission nodes to enter the dungeon:
  **permissions:**
    - my.custom.node
    - yet.another.node

---

I hope it throws user friendly message that indicates invalid identifier rather than just throwing NPE

**Comment by Sataniel98** [comment]
Thank you very much for pointing this out!
