### ISSUE TITLE
/dxl play in edit mode is glitched

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#151]
in the edit mode, the player can use /dxl play to play the editing map;

the problem is that after the dungeon is finished, player is returned to the edit world, but DXL will say "you need to be in a group first" on executing command /dxl leave

it seems DXL no longer think that the player is in an edit mode.

or possibly restrict player in edit mode from using /dxl play, so they can't use /dxl play in edit mode.

ps) in 0.15

**Comment by Sataniel98** [comment]
Fixed it! Also did some cleanup stuff that I'd like to test in detail to make sure that it didn't break the command in other contexts, won't take too long
