### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#152]
Die deutsche Übersetzung für DungeonsXL. Falls Ihr Teile dazu beitragen möchtet, postet sie bitte einfach hier rein :)

**Comment by seyfahni** [comment]
Ich kann helfen wo nötig.

**Comment by Sataniel98** [comment]
Ist sehr willkommen. Wenn Du Übersetzungen hast, kannst Du sie gerne posten.
