### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#153]
La traduction française. Si vous voulez contribuer quelque chose, simplement faites un poste avec les textes :)

**Comment by Tiplish** [comment]
Hello, i've done it. I can share you the .doc where i've done my work? If you like it, i will finish it :)

**Comment by Sataniel98** [comment]
![](http://i.imgur.com/uVfMb7X.jpg)
Please share it :)

**Comment by Tiplish** [comment]
https://nefald.fr/wiki/DungeonsXL  
I've done more but i need time to export on our wiki (i've translate the whole sign part too). 

My team help me to make it more comprehensible. You will see some changes during the next days. 

(I'm happy to help you). 

I will poste here a message when we have done if you want?

**Comment by Tiplish** [comment]
Do you need some translation of the language.yml ?

**Comment by Sataniel98** [comment]
Well, that's what I'm waiting for :)

**Comment by Tiplish** [comment]
Hello. I have some questions :

Your script use the UTF8 or not? Because when i translate, there is many "é" "è" ... :)

How do you want to receive the language.yml file?

**Comment by Sataniel98** [comment]
DungeonsXL, or more precise, Bukkit, supports UTF-8 if the YAML file happens to be formatted with UTF-8. I actually can't think of any translation that wouldn't need it, so it's definitely okay :)

http://pastebin.com/

**Comment by Tiplish** [comment]
My first draft of the traduction is done. I am correcting the last errors that I might have missed and I share it

**Comment by Tiplish** [comment]
Enjoy : http://pastebin.com/ELAC39TZ :)

**Comment by Sataniel98** [comment]
Merci beaucoup, I'll do my best to keep it up to date in the future :) I've added it to the translations page.

**Comment by Tiplish** [comment]
Your welcome :) If you add some sentence, i could translate too. Thx YOU for the plugin and all support attached ;)

**Comment by Sataniel98** [comment]
Would be nice if you could tell me if I make any mistakes. I don't speak French frequently anymore and it seems I'm forgetting stuff four times faster than I learn *sigh*

**Comment by Sataniel98** [comment]
I've learned the language for seven f***ing years and now I'm talking to French people in English, WTF xD

**Comment by Tiplish** [comment]
If you want, you speak in french and i answer to you in german o/? I've learned german for seven years too :o (and of course, i forgot sooooooo fast :( ). 

You could show me the sentences and i will correct it if it's needed.

**Comment by Astrareach** [comment]
Hi, i am also willing to help for the french traduction !
I made some minor correction in the pastebin :)
http://pastebin.com/QcYQEAnc

**Comment by Sataniel98** [comment]
Hi, glad to hear that, thank you very much :) I've added your fixes to the file.

I also created a new project branch for translations [here](https://github.com/DRE2N/DungeonsXL/tree/translations/). If you would like to add some fixes, updates  etc., you can fork the project, apply your changes to the branch and create a pull request. Of course, you may just continue to use pastebin as well.
