### ISSUE TITLE
Per dungeon resourcepacks

### ISSUE THREAD

**Issue by Maho24** [DRE2N/DungeonsXL#154]
Dear Sataniel,
A friend of mine had a really cool idea for a dungeon on my server, but we can't build it becouse we need to change some block textures just for the dungeon, would it be hard to add a per server resourcepack?

Maho24

**Comment by Sataniel98** [comment]
I like the idea and would like to add a feature like that. [inventivetalent's ResourcepackAPI](https://www.spigotmc.org/resources/api-resourcepackapi-1-7-1-8-1-9-1-10.2397/) makes it relatively simple to send the packs and to check if the player has received it. Note that this feature wouldn't be available in 1.7.x (except protocol hacks).

Design idea:
- Dungeon resource packs may be set in the game rules (e.g. dungeon or floor config) with a download link to the resource pack zip folder.
- Players that do not use the required resource packs shall not be able to enter the dungeon (question to myself: Is it possible to use the requirement API of DXL for this?)
- Reset the resource pack when the player leaves the dungeon
- In addition (or instead): Would a sign to set the resource pack be useful?
- Download command to get the resource pack (mainly for edit mode) 

What do you think?

**Comment by Maho24** [comment]
that sounds good :) a sign would be useful maybe to overwrite a resourcepack (so you can have 2 signs with resourcepacks ) if you have a low end pc? that cant handle 32 by 32 like my old PC had (i could often not play minigames with resourcepacks)

**Comment by Maho24** [comment]
also i dont know if this is a bugg but after a while my signs are not working anymore, so people cant enter dungeons :(

**Comment by Sataniel98** [comment]
Just your global signs? Are signs the only things that get deleted or are other global protections (portals) affected, too? Are there stacktraces? Does your server crash from time to time or did it crash before this happened?

**Comment by Maho24** [comment]
i have no clue what caused it (i only know that it hapened multiple times)
 but ill try to see what it could be mebe it is the auto restart
no the portals are working but the signs dont work (they look the same still)
ill do some testing tomorow to see if i can find it out

**Comment by Maho24** [comment]
sataniel do you have your own server?

**Comment by Maho24** [comment]
also is there a way i can contact you without using this?

**Comment by Sataniel98** [comment]
I do not own a server at the moment, but I used to be staff member at a Swiss Factions / RPG server (the one for that DungeonsXL has been developed initially). The issue tracker is the best way to contact me for support. I'm also active member of several forums, but I usually disable PMs (received too much rubbish :C )

**Comment by Maho24** [comment]
could you mebe make some plugins for my server?
ill pay for them ofc :)
i need 2 small plugins

**Comment by Sataniel98** [comment]
No, sorry.

**Comment by Maho24** [comment]
oke thx for answering so fast :)
then ill have to look for another dev :)

**Comment by Sataniel98** [comment]
Hi again, I'm back home and felt like doing some experiments with this suggestion.

These are the results:

https://github.com/DRE2N/DungeonsXL/tree/resourcepacks

http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/archives/dungeonsxl-0.15-SNAPSHOT-12.jar

Seems to work fine. To use resourcepack signs, just register the RP in the main config.yml like:

```
resourcePacks:
  TEST: http://feuerstern.bplaced.net/Banners.zip
```

...and create a sign in edit mode like:

```
[ResourcePack]
TEST
```

ResourcePack signs create interact triggers automatically, are protected by default and get enabled before the game starts just like classes or ready signs.

Note that if you upgrade to a 0.15 dev build from 0.14.4 or lower, you'll have to regenerate the groupColorPriority section of your main config.yml.

You **do not** need to install the ResourcePackAPI plugin on your server. It is shaded into DungeonsXL.

**Comment by Sataniel98** [comment]
See PR #157 for further discussion etc.
