### ISSUE TITLE
Something went horribly wrong error

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#155]
tested with deleting all the config files

all the configs are generated by plugin

when I enter the dungeon, it says Something sent horribly wrong when loading your inventory!

and when the dungeon is over, I lost all the items I had in my wild world

I'm using PerWorldInventory though

do you think they are related?

**Comment by wysohn** [comment]
I found that it's caused from PlayerUtil.secureTeleport() method

check the line 111 of DGamePlayer class

**Comment by Sataniel98** [comment]
I don't think that's a DXL error message. I can well imagine that a plugin like PerWorldInventory doesn't like the instantiation system of DXL.

secureTeleport does nothing but checking if the player is riding any vehicle. If he does so, he dismounts first before he is teleported.

**Comment by wysohn** [comment]
ohhh that totally make sense then. Because I was looking for that message in DXL plugin and couldn't really find until I reached the secureTeleport() method. I'm pretty sure that PWI is problematic here.

So what's your resolution about that? are you going to add support for the PWI plugin? it's pretty common plugin for most of the multi world based server, and they will not like it if exiting the dungeon will make them lose all the items.

In fact, I remember it wasn't happened for the version currently on the Spigot right now. So something has changed and PWI doesn't really like that.

Plus, I definitely want to use the DXL's item separation feature while also using PWI; I hope you come up with a good solution about that :+1:

**Comment by Sataniel98** [comment]
The instantiation system has been overhauled in 0.14 and 0.15. I agree that PWI support would be nice, but it depends on how extensive its API is. We'd need to somehow make PWI ignore DXL worlds.
