### ISSUE TITLE
Different groups join a same Dungeons?

### ISSUE THREAD

**Issue by SnUncle** [DRE2N/DungeonsXL#160]
Just like the title 
DXL 1.44 test on spigot 1.10.2
I set the announcers like this 

description:
# The name of a map if multiFloor is false, the name of a dungeon if multiFloor is true.

identifier: 死人营地
# If the dungeon to play has multiple floors.

multiFloor: false
# The game starts automatically thirty seconds after the minimum requirements are fulfilled.

minGroupsPerGame: 1
minPlayersPerGroup: 2
maxGroupsPerGame: 5
maxPlayersPerGroup: 2

After two players of group_0 enter the game. another player join other group 
and the Dungeons be reset ! three pepole into the Dungeons It's a BUG or something?

And sometimes people killed by mobs they will death twice and lost all items  

plz help!

**Comment by Sataniel98** [comment]
I'm sorry, but I'm not really sure what you're trying to say... Could you please explain in detail what you're trying to achieve and what you'r e doing?

**Comment by SnUncle** [comment]
Sorry bro  my Eng is bad 
Sometimes my players died in Dungeon and the lost two lives and lost all items

**Comment by Sataniel98** [comment]
No problem. Do you know of any circumstances that could cause your issue? Is there an error log in the console?
