### ISSUE TITLE
Give an ID/name for a group of mobs

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#161]
Hi,

I would like to know if it's possible to create a group of mob and a trigger when this group is dead without the wave trigger (which couldn't be triggered if there is mobs in an other place in the dungeon). 

Or if this feature will be added later? 

Thx :)

**Comment by Sataniel98** [comment]
I think you can stack signs with scripts to accomplish what you want.

**Comment by Tiplish** [comment]
Ok, it's just because sign are more userfriendly than script so that's why i was looking for just a sign. No problem, thx :)

**Comment by Tiplish** [comment]
Is it possible to count the number of mobs that was killed?

**Comment by Sataniel98** [comment]
You could use a W 0.x trigger.

**Comment by Tiplish** [comment]
When i use W 1 trigger (to ensure that there is no mob alive, it doesn't work :s that's why i'm looking for an other way to do what i need (explain in my post for issue 163).

**Comment by Sataniel98** [comment]
I'll close this now, anything else related to this may be posted into #163
