### ISSUE TITLE
PvE throws exception in 1.8.x and lower

### ISSUE THREAD

**Issue by rowan-smith** [DRE2N/DungeonsXL#162]
Hi, I recently downloaded the latest version of DungeonsXL, started a server with no plugins besides Dungeons, all seemed fine until a mob or another player was hit, then it threw this error

http://pastebin.com/kcSP4Nnt

It appears to happen every time, someone hits a mob or player.

Server Version: https://gyazo.com/ab73d9b4f8c494a3969b061727049e48

Any help would be appreciated :)

**Comment by Sataniel98** [comment]
I'm pretty sure it's because of 1.8. Should be an easy fix.

**Comment by Sataniel98** [comment]
Thank you for the report, fixed it!
