### ISSUE TITLE
Wave trigger doesn't work

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#163]
Hello,

For my dungeon, i try to put multiple trigger : "W1,M Zombie". 

The goal is to open a door only if all mobs are dead and the last dead was a Zombie (to ensure that the W1 is not triggered when another mob die). 

It works during some session of game but now, i can't reproduce this mecanic. My door is never opened.

I try to trigger something else and nothing happend. 

Could you help me please?

**Comment by Sataniel98** [comment]
Which build do you use? Door signs are not fully implemented in bulds earlier than 0.15.

**Comment by Tiplish** [comment]
By door i mean block which becomes ID 0 when the trigger is triggered. Maybe it's more clear.

**Comment by Sataniel98** [comment]
Is this and your other issue still relevant?

**Comment by Tiplish** [comment]
For the moment, i'm focus on the problem with ready sign. I will test again my old issues as soon as possible :)

**Comment by Sataniel98** [comment]
See #383
