### ISSUE TITLE
Citizens Problem

### ISSUE THREAD

**Issue by JennaDiamonds** [DRE2N/DungeonsXL#166]
Spigot Latest Version 1.10
DungeonsXL & CommandXL Recommended builds
Latest versions of Citizens 2 and Sentinel.
Errors: None

Issue:
Currently when using External Mob signs to spawn a citizen, only certain parts of the citizen are being brought over to the dungeon. The skin, lookclose, health, held item and sentinel trait are not coming with the NPC. It seems as though the only thing that is being brought to the dungeon is the name given to the NPC.  Is this an issue on my end or does DungeonsXL not support using Citizen NPCs with traits/features/behaviors?

Workarounds tried:
   -I tried using CommandXL to create a new citizen and give all the required traits and behaviors.
The NPC Create [Name] command in CXL doesn't seem to understand where to put the NPC. Doesn't give any errors. It just does nothing from what I can see
   -I tried pre-creating the citizen with all traits and behaviors in same world. When the world location name changes the citizen location doesn't change with it. The location is still handled by Citizens since it was created using /npc create and not a sign.
   -Tried doing a simple tphere using a CMD sign.. world location was still an issue.

Thanks for reading

Update:
Cannot use /NPC Select while playing dungeon to try to use commands on it through a CMD sign.. /NPC List does not show the spawned Citizen therefore using CMD signs with triggers to add behaviors or traits to the citizen during the dungeon playing does not work either.

**Comment by Sataniel98** [comment]
First of all, thank you for your report. I'm actually using the same method like Citizens to copy the NPCs, but I might have missed something. I'll take a look at it as soon as possible :)

**Comment by JennaDiamonds** [comment]
You're welcome, if you need any other information or help recreating the issue, or a video of what is happening please let me know. I'll check back here daily. I really would love to use this plugin for the rpg i'm working on.

**Comment by JennaDiamonds** [comment]
You mentioned you're using the same method. Are you using citizens? And using the mothods I'm using? And the sentinel traits carry over into the dungeon for you?? That would mean it's possibly a problem on my end. What versions of spigot/bukkit, DungeonXL, citizen, sentinel are you using if so? I'll try to re-create a successful build using what you have

**Comment by Sataniel98** [comment]
By method, I mean the Java code structure (net.citizensnpcs.api.npc.AbstractNPC#clone())

**Comment by JennaDiamonds** [comment]
Aha. lol.. I'm a bit of an amateur coder to be honest. That is.. I have to google pretty much everything :)

**Comment by JennaDiamonds** [comment]
bump :(

**Comment by Sataniel98** [comment]
I know I know. I recently moved and started to study law. I'll need a week or two to settle down, but I won't forget it :)

**Comment by JennaDiamonds** [comment]
:)

**Comment by JennaDiamonds** [comment]
Did the new update address this issue?

**Comment by Sataniel98** [comment]
Nope, but I'm finally back and working on it :)

**Comment by Sataniel98** [comment]
Fixed it, sorry for the long wait. 0.15.1-SNAPSHOT-02 and newer builds contain the fix. Please tell me if it works somehow inconsistently (or not at all).

http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/

**Comment by JennaDiamonds** [comment]
Still not working.. :(

**Comment by JennaDiamonds** [comment]
Well, it kinda works. lol.. It spawns in an NPC but the NPC has no stats at all. It's just a ghost.

**Comment by Sataniel98** [comment]
I'll close this since other issues concerning Citizens, perhaps because they are regarded as players, are not technically connected to this one and should get a separate one. Please feel free to submit reports if you experience issues :)
