### ISSUE TITLE
Severe error when joining a Dungeon and can't leave it with signs.

### ISSUE THREAD

**Issue by MorenaDaniel** [DRE2N/DungeonsXL#167]
Hello ! I have a bug with DungeonsXL when i join and when i want to leave the game.

First of all, when i join i have this 👍

> [00:43:39] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
> org.bukkit.event.EventException
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.teleport(CraftPlayer.java:444) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.craftbukkit.v1_10_R1.entity.CraftEntity.teleport(CraftEntity.java:226) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at io.github.dre2n.dungeonsxl.util.commons.util.playerutil.PlayerUtil.secureTeleport(PlayerUtil.java:55) [dungeonsxl-0.15.jar:?]
>     at io.github.dre2n.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:113) [dungeonsxl-0.15.jar:?]
>     at io.github.dre2n.dungeonsxl.task.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:65) [dungeonsxl-0.15.jar:?]
>     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-10c10b3]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
> Caused by: java.lang.NullPointerException
>     at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:222) ~[?:?]
>     at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source) ~[?:?]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
>     ... 15 more

And when i want to leave i have this 

> `18/10/2016 00:50:31 java.lang.IllegalArgumentException: Health must be between 0 and 10.0
> 18/10/2016 00:50:31 at org.bukkit.craftbukkit.v1_10_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:95) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
> 18/10/2016 00:50:31 at io.github.dre2n.dungeonsxl.player.DInstancePlayer.clearPlayerData(DInstancePlayer.java:85) ~[?:?]
> 18/10/2016 00:50:31 at io.github.dre2n.dungeonsxl.player.DEditPlayer.<init>(DEditPlayer.java:48) ~[?:?]
> 18/10/2016 00:50:31 at io.github.dre2n.dungeonsxl.task.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:71) ~[?:?]
> 18/10/2016 00:50:31 at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
> 18/10/2016 00:50:31 at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6016ac7-10c10b3]
> 18/10/2016 00:50:31 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot.jar:git-Spigot-6016ac7-10c10b3]
> 18/10/2016 00:50:31 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-6016ac7-10c10b3]
> 18/10/2016 00:50:31 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-6016ac7-10c10b3]
> 18/10/2016 00:50:31 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-10c10b3]
> 18/10/2016 00:50:31 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

I use mythicmobs and Items lore stats, that give me more Health. I saw a post about a problem about health and you linked a snapshot of the version that fix this problem, and I installed it. It didn't change anything. 

Hope you will be able to help me, thanks :)

**Comment by Sataniel98** [comment]
Thank you for your report. Are you using the [latest dev build](http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/)? The error thrown by Multiverse shouldn't occur if you don't add / remove all instances (DXL_Edit_ID and DXL_Game_ID worlds) from Multiverse.
