### ISSUE TITLE
player inventories/MFD's/Group Signs

### ISSUE THREAD

**Issue by astralgemini** [DRE2N/DungeonsXL#169]
I have gone into the Config files and changed every config i can see that should allow players to bring their own inventories into a dungeon to true but it does not seem to work.

I have no idea how to make a MFD.

Group signs seem to only work using 1,2 for the bottom line.

**Comment by Sataniel98** [comment]
1) I'll need more information in order to help you.

2) Just add a dungeon script - that's it.

3) You don't have enough space next to your sign.

**Comment by astralgemini** [comment]
1) um basically, whenever a player enters a dungeon it wipes their inventory

2) how do i do that?

3) do i need to add blank signs next to it? or just generic wall space?

**Comment by Sataniel98** [comment]
1) Which rules did you add where?

2) Go to the dungeon script folder and add a new YAML file. The example in the wiki helps you filling it.

3) Just generic wall space.
