### ISSUE TITLE
Friendly Fire doesn't work ?

### ISSUE THREAD

**Issue by Daxxas** [DRE2N/DungeonsXL#172]
The friendly fire doesn't work when set to off.

Player can still hit each others even in same group !

Maybe another plugin do something, but we don't have any plugin who changes PvP.

**Comment by Sataniel98** [comment]
Really can't reproduce this one :(

Tried DXL 0.15 / Spigot 1.11 (with nothing but IXL, Vault and PEX)

test floor config.yml:

```
friendlyFire: false
playerVersusPlayer: true
```

Works as expected: Group members cannot be punched, other players can be punched.
