### ISSUE TITLE
Put a delay between two parties

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#173]
Hello,

I'm looking for a function : Put a delay before a player could go again in the same dungeon. 

I remember that i've watched this in the config file but now, i can't find it anymore :( 

If you could help me. Thx you!

**Comment by Sataniel98** [comment]
I guess you're looking for

```
# Time until you can play a Dungeon again (in hours)
timeToNextPlay: 6

# Time until a player can get loot for another time
timeToNextLoot: 12

```

**Comment by Tiplish** [comment]
Yes that was that ! i will try to add in "default" in config.yml after upgrading DXL :) Thx you
