### ISSUE TITLE
Error when second player tries to loot a scripted loot chest

### ISSUE THREAD

**Issue by Flemse12** [DRE2N/DungeonsXL#177]
Hey i get this error whenever my mate tries to loot the same chest as i did, so more players in the dungeon can get loot. Im using 0.15 the latest version available on Spigot, also tried upgrading to latest dev build same thing happens
Also the meesage saying you've been given loot comes up on hes screen but when he acutally leaves the dungeon only i get it

Im working on a large dunegon for a server so it kinda sucks only 1 player can get each loot chest.
Great plugin tho!

26-11-2016 15:57:20 [ERROR] Could not pass event PlayerInteractEvent to DungeonsXL v0.15
26-11-2016 15:57:20 org.bukkit.event.EventException
26-11-2016 15:57:20 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:877) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
26-11-2016 15:57:20 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
26-11-2016 15:57:20 Caused by: java.lang.NullPointerException
26-11-2016 15:57:20 at io.github.dre2n.debukkit.DebukkIt.end(DebukkIt.java:74) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.player.DGamePlayer.finishFloor(DGamePlayer.java:774) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.player.DGroup.finishIfMembersFinished(DGroup.java:799) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:517) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:882) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:821) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.sign.EndSign.onPlayerTrigger(EndSign.java:74) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:180) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:114) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:49) ~[?:?]
26-11-2016 15:57:20 at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:247) ~[?:?]
26-11-2016 15:57:20 at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
26-11-2016 15:57:20 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
26-11-2016 15:57:20 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
26-11-2016 15:57:20 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 15:57:20 ... 17 more

**Comment by Flemse12** [comment]
Saw someone further down with the same Crashlog mentioning a hotfix, is that available for download?

**Comment by Sataniel98** [comment]
Thank you for the report. I haven't seen this so far so I doubt there's a fix. Shouldn't take long to fix it, though :)

**Comment by Flemse12** [comment]
Haha thank you :) Was worried i had to postpone the entire project, ty for quick respond :)

**Comment by Sataniel98** [comment]
I couldn't reproduce it, so this is kind of a "blind" try. Please tell me if it works!

http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/

**Comment by Flemse12** [comment]
Sorta worked, we both got our items now but you can duplicate items by keep doing /dxl rewards and i got all these errors

26-11-2016 21:32:16 [ERROR] Could not pass event PlayerInteractEvent to DungeonsXL v0.15.1-SNAPSHOT-05
26-11-2016 21:32:16 org.bukkit.event.EventException
26-11-2016 21:32:16 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:877) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:16 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:16 at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:16 Caused by: java.lang.NullPointerException
26-11-2016 21:32:16 at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:873) ~[?:?]
26-11-2016 21:32:16 at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:813) ~[?:?]
26-11-2016 21:32:16 at io.github.dre2n.dungeonsxl.sign.EndSign.onPlayerTrigger(EndSign.java:74) ~[?:?]
26-11-2016 21:32:16 at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:180) ~[?:?]
26-11-2016 21:32:16 at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:114) ~[?:?]
26-11-2016 21:32:17 at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:49) ~[?:?]
26-11-2016 21:32:17 at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:247) ~[?:?]
26-11-2016 21:32:17 at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
26-11-2016 21:32:17 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:17 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:17 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:17 ... 17 more
26-11-2016 21:32:32 [INFO] Xovious issued server command: /dxl rewards
26-11-2016 21:32:32 [ERROR] null
26-11-2016 21:32:32 org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.15.1-SNAPSHOT-05
26-11-2016 21:32:32 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:32 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:32 Caused by: java.util.ConcurrentModificationException
26-11-2016 21:32:32 at java.util.ArrayList$SubList.checkForComodification(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:32 at java.util.ArrayList$SubList.listIterator(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:32 at java.util.AbstractList.listIterator(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:32 at java.util.ArrayList$SubList.iterator(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:32 at java.util.AbstractCollection.contains(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:32 at java.util.AbstractCollection.removeAll(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:32 at io.github.dre2n.dungeonsxl.command.RewardsCommand.onExecute(RewardsCommand.java:60) ~[?:?]
26-11-2016 21:32:32 at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
26-11-2016 21:32:32 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:32 ... 15 more
26-11-2016 21:32:34 [INFO] Xovious issued server command: /dxl rewards
26-11-2016 21:32:41 [INFO] nokiaman issued server command: /dxl rewards
26-11-2016 21:32:41 [ERROR] null
26-11-2016 21:32:41 org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.15.1-SNAPSHOT-05
26-11-2016 21:32:41 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:41 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
26-11-2016 21:32:41 Caused by: java.util.ConcurrentModificationException
26-11-2016 21:32:41 at java.util.ArrayList$SubList.checkForComodification(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:41 at java.util.ArrayList$SubList.size(Unknown Source) ~[?:1.8.0_111]
26-11-2016 21:32:41 at io.github.dre2n.dungeonsxl.command.RewardsCommand.onExecute(RewardsCommand.java:58) ~[?:?]
26-11-2016 21:32:41 at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
26-11-2016 21:32:41 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
26-11-2016 21:32:41 ... 15 more
26-11-2016 21:32:42 [INFO] Xovious issued server command: /dxl rewards

**Comment by Sataniel98** [comment]
This should resolve the /dxl rewards bug.

**Comment by Flemse12** [comment]
So just dl newet dev build?

**Comment by Sataniel98** [comment]
Yes, build 6

**Comment by Flemse12** [comment]
Sorry i dont quite follow :) do you want me to add something to the config file?

**Comment by Sataniel98** [comment]
No, it should be alright. I haven't fixed everything, yet, but I'm aware of it.

**Comment by Flemse12** [comment]
Ah okay thank you :)

**Comment by Sataniel98** [comment]
Could you please tell me a bit more about the circumstances of the end sign bug (the one that still occurs in the latest build)? Like:
* How many groups are in the dungeon?
* How many players are in the groups?
* How do you let the players setup their group? (e.g. group signs)
* Does it happen in any dungeon or just in a few ones?
* How exactly does the bug influence the game (besides causing a console stacktrace)?

**Comment by Flemse12** [comment]
- Only tested with 1 Group in play but, 3 Groups are able to play at once
- Tested with two players
- Groups signs using Ready Default sing aswell
- Happens in all Dungeons
- The players get ther rewards when leaving, but will have to do /dxl rewards to get rewards other player looted.

**Comment by Sataniel98** [comment]
Not entirely sure why this happens at the moment.

**Comment by Flemse12** [comment]
Has any Progress been made on this?

**Comment by Sataniel98** [comment]
Not yet. Sataniel is kind of an adult, Sataniel got shit to do ¯\\_(ツ)_/¯

**Comment by Flemse12** [comment]
Hehe i understand fully, take your time :)
Still seems like the only game breaking bug i ever encountered :)

**Comment by Sataniel98** [comment]
Glad to hear that, I'm trying to make DXL ready for a production environment at the moment. Please tell me if you notice anything else, even if it's just a minor thing like spelling mistakes or stacktraces without any noticeable impact.

**Comment by Sataniel98** [comment]
Finally found an empty evening & the bug. I really hope that this fix does it for you, worked well when I tested it but it might break some other things so I'll test a bit more before I release it officially. The release candidate is available at the dev build server.

**Comment by Flemse12** [comment]
Tested on 0.15.3 wich i suppose is the build your talking about. And it still is causing the crash log, items where not distriputed probely, i got 3 items and my friends got 1, and still had to use ,/dxl rewards even tho my inv was almost empty.

**Comment by Sataniel98** [comment]
My bad, I uploaded the build but forgot to add it to the list.

Direct download: 
http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/0.15.3-RC-01/dungeonsxl-0.15.3-RC-01.jar

**Comment by Flemse12** [comment]
Good News, the crash log is gone, tho there is still a few problems.
- When Looting one chest you get  the loot from all the chest in the Dungeon.
- You still have to do that extra /dxl rewards when leaving (not sure if intended or not but seems wierd)
- When trying to enter a dungeon through a portal on this build it gives the meesage "This Dungeon dosent Exist)

**Comment by Sataniel98** [comment]
Thank you. I'm sure I'll find time to fix this in the next days or at least right after Christmas.

**Comment by Flemse12** [comment]
Also some of the items for example the Token i made, is an invalid image file so its just a giant purple/black box.
Current Loot table
0:
  item:
    ==: io.github.dre2n.caliburn.item.UniversalItemStack
    type: "CUSTOM_DEFAULT"
    material: "IRON_SWORD"
    durability: 35
    name: "&4Bad Sword"
    amount: 1
    lores:
     - "&4This is the first line."
     - "&6This is the second line."
    enchantments:
      "PROTECTION_ENVIRONMENTAL": 4
      "THORNS": 1
    attributes:
      name:
        type: "GENERIC_ATTACK_DAMAGE"
        slots:
          - "MAIN_HAND"
          - "HEAD"
        operation: "ADD_NUMBER"
        amount: 8.5
  chance: 100
1:
  item:
    ==: io.github.dre2n.caliburn.item.UniversalItemStack
    type: "CUSTOM_DEFAULT"
    material: "gold_nugget"
    durability: 35
    name: "&4Token"
    amount: 1
    lores:
     - "&4This is the first line."
     - "&6This is the second line."
    enchantments:
    attributes:
      name:
        type: "GENERIC_ATTACK_DAMAGE"
        slots:
          - "MAIN_HAND"
          - "HEAD"
        operation: "ADD_NUMBER"
        amount: 8.5
  chance: 100

**Comment by Sataniel98** [comment]
Minecraft does not know gold nuggets with durability 35, so it uses a placeholder texture (since 1.8 or 1.9 AFAIK). I'm not an expert, but it should still be possible to make custom MCPatcher CIT or Vanilla sprites for these items with a resource pack.

**Comment by Sataniel98** [comment]
I couldn't reproduce the first two problems. However, I fixed the portal bug in 0.15.3. Merry Christmas.
