### ISSUE TITLE
Question about config file

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#178]
Hello,

i'm trying to put a delay between two parties for a player for all dungeons/floors. 

At the end of my configfile, the syntax is : 
editPermissions: []
default:
  defaultValues:
    timeToNextPlay: 72
    timeToNextLoot: 72

or 

editPermissions: []
default:
  timeToNextPlay: 72
  timeToNextLoot: 72

Can you help me by giving the correct syntax of this part?
Thx

**Comment by Sataniel98** [comment]
This doesn't help me much. It could be a problem with indents.

**Comment by Tiplish** [comment]
I will be more precise. For exemple, this work : 
http://pastebin.com/V3nKSbub
But this doesn't work : 
http://pastebin.com/rXRXzNUQ

If i read correctly your documentation, in the config file, we are suppose to write the config file like this : 
http://pastebin.com/g3F7PVHR

Have i make a mistake?

**Comment by Sataniel98** [comment]
defaultValues / overrideValues is a section in a dungeon config, default is a section in the main config.

**Comment by Tiplish** [comment]
Yes but if i would have a same parameters for all my floors, regardless of the dungeon, i can't put it in the config file? I have to alwas change the dungeon config file per dungeon?

**Comment by Sataniel98** [comment]
Just put it directly into the default section, like

```
default:
  timeToNextPlay: 72
  timeToNextLoot: 72
```

**Comment by Tiplish** [comment]
It doesn't work :(

I've exactly the same problem as https://github.com/DRE2N/DungeonsXL/issues/174 when i add default part.

This is my full config file which is bugged : 
http://pastebin.com/UvRRsR7x

I hope you could reproduce my problem. I use dxl 0.15.1 dev build n°6.

**Comment by Sataniel98** [comment]
Oh okay, sorry, I'll have a look at it tomorrow.

**Comment by Sataniel98** [comment]
It works well for me. So, you get exactly this error?
`
io.github.dre2n.dungeonsxl.player.DGroup.startGame(DGroup.java:663) ~[?:?] at 
`
And there is no dungeon script or floor config that overrides the values in the case of the dungeon you enter?

**Comment by Tiplish** [comment]
Hi, thanks for you answer. 

I will check it but the only thing that i change is the configFile.

To be sure , my steps will be : 
- Upgrad DXL (i've seen that another version is out ;) )
- Checking if another dungeon script or floor config overrides values
- Find the error that you show
- If previous steps don't work, i will paste the errors that i get. 

That's it?

**Comment by Sataniel98** [comment]
Does this still occur in 0.15.3-RC-01?

**Comment by Tiplish** [comment]
We are still in 1.10.2 on our server. We will go in 1.11 soon but before, we need some test :)

I come back as soon as i've tested it.

**Comment by Tiplish** [comment]
Hi,

Last week-end, i've try a config for my floors and it works o/ sorry for the delay before testing. I've not tested a dungeon config file but i think i will open a new issue if i find another problem. You could close this :)
