### ISSUE TITLE
Still getting an issue when two people loot a scripted chest, and the loot is not distriputed

### ISSUE THREAD

**Issue by Flemse12** [DRE2N/DungeonsXL#179]
29-11-2016 01:40:10 [ERROR] Could not pass event PlayerInteractEvent to DungeonsXL v0.15.1-SNAPSHOT-06
29-11-2016 01:40:10 org.bukkit.event.EventException
29-11-2016 01:40:10 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:877) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
29-11-2016 01:40:10 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:10 at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
29-11-2016 01:40:10 Caused by: java.lang.NullPointerException
29-11-2016 01:40:11 at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:873) ~[?:?]
29-11-2016 01:40:11 at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:813) ~[?:?]
29-11-2016 01:40:11 at io.github.dre2n.dungeonsxl.sign.EndSign.onPlayerTrigger(EndSign.java:74) ~[?:?]
29-11-2016 01:40:11 at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:180) ~[?:?]
29-11-2016 01:40:11 at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:114) ~[?:?]
29-11-2016 01:40:11 at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:49) ~[?:?]
29-11-2016 01:40:11 at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:247) ~[?:?]
29-11-2016 01:40:11 at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
29-11-2016 01:40:11 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
29-11-2016 01:40:11 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
29-11-2016 01:40:11 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.10.2.jar:git-Bukkit-67b2424]
29-11-2016 01:40:11 ... 17 more

**Comment by Flemse12** [comment]
By distriputed i mean that only the player that loots the chest gets the loot even tho it tells everyone they got it.

**Comment by Sataniel98** [comment]
Isn't this exactly the same as the first one?

**Comment by Flemse12** [comment]
Seems like it

**Comment by Sataniel98** [comment]
=> #177
