### ISSUE TITLE
No dmg !

### ISSUE THREAD

**Issue by OkumuraRin** [DRE2N/DungeonsXL#18]
I'm getting this weird bug when joining a dungeon dmg is disabled ! can't get [Mob] signs to work it never triggers ! please help i really love this plugin !

**Comment by Sataniel98** [comment]
Which kind of damage? How does your sign look like?

**Comment by OkumuraRin** [comment]
Physical damage , here's some pictures :
Spawner :
![Image of spawner](http://i.imgur.com/qgxQxrs.png)
the arrows hit me and bounce back without doing any damage !
![Image of spawner](http://i.imgur.com/26vFXwk.png)

**Comment by Sataniel98** [comment]
Did you test it in a clean environment without any other plugins? I cannot reproduce the issue.
