### ISSUE TITLE
Support block DVs

### ISSUE THREAD

**Issue by Flemse12** [DRE2N/DungeonsXL#180]
If your using a block id with a : in it the block will simply be put as air.
For example my map is using yellow stained clay in a puzzle but when putting in the block id 159:4 it shows as air, both as triggered and un-triggerd

**Comment by Sataniel98** [comment]
I'll add support for damage values.

**Comment by Sataniel98** [comment]
My bad, I forgot that block signs do support block DVs... They are seperated with a komma, not with a colon, though.
