### ISSUE TITLE
returned back to [Lobby] when ran out of lives or end

### ISSUE THREAD

**Issue by Faryzal2020** [DRE2N/DungeonsXL#181]
i'm testing a single level dungeon, 1 group, 2 players, i have 1 life left, my friend still have 3, then i got killed by a skeleton then both of us respawned back to the dungeon's [Lobby] with no inventory, cant /dxl leave, it says i dont belong in any group, when i warp back to the portal in the main world my initial inventory returned.
this appears in the log when i died:
http://pastebin.com/d0VRxAWJ

**Comment by Sataniel98** [comment]
.        .

**Comment by Sataniel98** [comment]
The stacktrace does not point to DungeonsXL. It says the plugin BarAPI is missing.

**Comment by Faryzal2020** [comment]
before i installed BarAPI i posted a ticket on Item Lore Stats with this error log:
http://pastebin.com/d0VRxAWJ
and then i installed the latest BarAPI version and tested it again but i got the same problem with different error log: http://pastebin.com/eaVBkJd4

Supavitax said:
Ok just had another look and I've managed to fix it so that it won't cause http://pastebin.com/d0VRxAWJ error again.
The other error is for the DungeonsXL dev.

my ticket on ILS:
https://dev.bukkit.org/bukkit-plugins/item-lore-stats/tickets/271-could-not-pass-event-player-changed-world-event-to/

**Comment by Sataniel98** [comment]
How does the stacktrace look like in the latest build?

**Comment by Faryzal2020** [comment]
okay so i updated the plugin to 0.15, renamed the config so it can generate a new one, then i tested a test map with default config, the map is just chests and [Start] sign close with [End] sign, all works well..
but after i edit the config, when i entered the portal to the test map, the console is spammed with this:
http://pastebin.com/GkskcCMM , and the dungeon signs doesnt work.
my config: http://pastebin.com/0sygm3vw

and also i cant /dxl leave
log: http://pastebin.com/JQrGcyhA

**Comment by Sataniel98** [comment]
Yes but [this](http://pastebin.com/eaVBkJd4), how does it look like in 0.15.1?

**Comment by Faryzal2020** [comment]
with 0.15.1, and edited config: http://pastebin.com/iqWmw4Jm
when i joined a group: http://pastebin.com/LYecYiFK
when i issued /dxl break: http://pastebin.com/acAGp0Ud
console is spammed with this: http://pastebin.com/9sQA2Wsa
i haven't even entered the portal

**Comment by Faryzal2020** [comment]
just tested it again with the latest 0.15.1, with lobby enabled, everything works well but there's this error when we clicked on the [End] sign: http://pastebin.com/LZEP8qvX

**Comment by Sataniel98** [comment]
Really no idea why no DungeonsXL representations are available in your cases. I made it a bit more robust and hope that it helps. If it doesn't help, please post again. Also please tell me if the tests have been done in a clean server environment.
