### ISSUE TITLE
standard gamemode

### ISSUE THREAD

**Issue by Maho24** [DRE2N/DungeonsXL#184]
Dear Sataniel,

can you add a standard edit gm that you can choose in config
or per dungeon edit gm idk if that's  useful tho

**Comment by Sataniel98** [comment]
So that the player gets for example spectator mode instead of creative in the edit world? I'm not quite sure if I understand what you mean.

**Comment by Maho24** [comment]
for me people are are in survival if they edit a dungeon, i want to make that creative

**Comment by Sataniel98** [comment]
Did you add any worlds (DXL_Edit_x) to Multiverse or another world manager? If so, it's an incompatibility caused by the world manager that overrides DXL's creative. You should exclude the world from your plugin.

**Comment by Maho24** [comment]
no i dxl is the only plugin i ever had on my server that could make more than 1 world (i only have a main world, and the dxl dungeons)
i did howerver copy these dungeons from my older (5 months ago) server can that have something to do with it?

**Comment by Sataniel98** [comment]
No. Do you get any errors in the console?

**Comment by Maho24** [comment]
its a incompatibility with gamemode inventory
also if i do /dxl test it says join a group first is this supposed to happen?

**Comment by Sataniel98** [comment]
No, but I'm aware of the problem.

**Comment by Maho24** [comment]
oke is the inventory thing also possible to fix?

**Comment by Sataniel98** [comment]
Yes. Reproduced & fixed it. Expect a new release at SpigotMC.org and at the dev build server in a few days.
