### ISSUE TITLE
Inventar ist nach Tod verschwunden

### ISSUE THREAD

**Issue by xeretic** [DRE2N/DungeonsXL#19]
DungeonsXL version: 0.9.6
Spigot version: 1.8.8

Nach dem man im Dungeon gestorben ist und wieder zurück zum Portal kommt sind zunächst alle ursprünglichen Gegenstände im Inventar. Sobald man jedoch einen Gegenstand anklickt, lösen diese sich auf und sind weg. Eventuell werden die Gegenstände ja mit dem Loot aus dem Dungeon in "AIR" umgewandelt (nur eine vage Vermutung).

Verwendete Plugins:
BasicSpawnReloaded
ClearLag
DungeonsXL
Gringotts
Invisibility_Cloak
ItemsXL
LockSecurity
MassiveCore
MobHealth
Multiworld
MyCommand
MythicMobs
Shopkeepers
SignEditor
SimpleTicketManager
Vault
WarpPortalCommands
WarpPortals
WorldEdit
WorldGuard

**Comment by Sataniel98** [comment]
Mit "ursprünglichen" meinst Du die Items, die man hatte, bevor man den Dungeon betreten hat? Gibt es eine Fehlermeldung in der Konsole?

**Comment by xeretic** [comment]
Ja genau, die Items meine ich. Die Konsole gibt leider keine Fehlermeldung aus...

**Comment by Sataniel98** [comment]
Gibt es irgendeine Regelmäßigkeit? Restarts? Hat der Spieler den Server zwischendurch verlassen?

**Comment by xeretic** [comment]
Das Problem tritt immer nach dem Verlust aller Leben auf. Dabei spielt es keine Rolle ob man sein Inventory mit in den Dungeon nimmt oder mit Klassen spielt. Das ganze läuft auf einem Linuxserver. Ich habe auf meinem Windows-PC zum Test craftbukkit 1.8.8 installiert sowie vault und dungeonsxl(mit meinem dungeon vom Server). Das Problem bestand weiterhin, somit liegt es vermutlich nicht an einem anderen Plugin. Das Problem trat immer noch auf. Einzige Ausnahme die ich feststellen konnte: wenn ich vor dem Betreten des Dungeons in Gamemode 1 bin und nach dem Verlust aller Leben wieder in Gamemode 1 vor dem Portal stehe, lösen sich die Items nicht auf. Beim Verlassen über den Befehl /dxl leave, das Anklicken eines Leave-Schildes oder das Abschließen des Dungeons besteht das Problem nicht und die Gegenstände sind korrekt im Inventar. Ich probiere heute nochmal auf einem Homeserver eine andere Bukkit- und Spigot Version mit einem "frischen" Dungeon. Und melde mich. Kannst du bei einem frischen Server das Problem nicht reproduzieren? Dann liegt der Fehler ja vielleicht irgendwo in der Bukkit bzw. Spigot Version oder aber in dem Dungeon selbst...

**Comment by xeretic** [comment]
So habe nochmal nen neuen Spigot-Server mit neuem Dungeon etc aufgesetzt. Leider immer noch das gleiche Problem... 

Ich hab mal ein Video aufgenommen zum Verdeutlichen des Fehlers. Zunächst mit gamemode 1 (der Fehler bleibt aus) dann mit gamemode 0, der Fehler tritt auf. Hier der Link: https://www.youtube.com/watch?v=yzYlAAqdCaI&feature=youtu.be

**Comment by Sataniel98** [comment]
"Einzige Ausnahme die ich feststellen konnte: wenn ich vor dem Betreten des Dungeons in Gamemode 1 bin und nach dem Verlust aller Leben wieder in Gamemode 1 vor dem Portal stehe, lösen sich die Items nicht auf." Das dürfte schlichtweg daran liegen, dass der Server sich im Creative nicht für das Inventar interessiert und das weitestgehend dem Client überlässt. Könnte aber der Grund sein, wieso ich es bisher nicht reproduzieren konnte... Danke erstmal für die detaillierte Meldung, ich werde mich so schnell wie möglich darum kümmern. Hab schon ein paar Ideen, woran es liegen könnte. Hast Du an den keepInventory-Einstellungen etwas angepasst?

**Comment by xeretic** [comment]
Ja ich habe zum Test auch mit den keepInventoryeinstellungen rumgespielt, in der Hoffnung den Fehler zu beseitigen. Im Changelog hab ich die Änderungen mit keepInventoryOnEnter, ...OnDeath etc. gesehen und ausprobiert. Es scheinen da aber ein paar Sachen bei bestimmten Kombinationen ignoriert zu werden. Ich werde dir später nochmal detailliert die Einstellungen und jeweiligen Auswirkungen schicken (bin gerade unterwegs). Vielleicht hängt damit ja auch der Fehler zusammen. Super tolles Plugin btw und danke für deine Mühe!!

**Comment by Sataniel98** [comment]
Danke - wobei der hauptsächliche Dank nach wie vor den ursprünglichen Autoren gebührt. Das Leben-Feature ist sowieso momentan nicht so schön und wird in der Version 0.10 komplett neu geschrieben sein, dementsprechend passt es mir ganz gut, dass ich da jetzt die Meldung bekomme :)

**Comment by xeretic** [comment]
So hier mal ein paar Kombinationen:

keepInventoryOnEnter: false  -> Beim Betreten blieb das Inventar leer

keepInventoryOnEscape: false -> Beim Verlassen wurde das Inventar wiederhergestellt 

keepInventoryOnFinish: false -> Beim Abschließen des Dungeons Inventar wiederhergestellt

keepInventoryOnDeath: false -> Beim Tod Inventar wiederhergestellt, bis zum Anklicken eines Items

Alles funktioniert korrekt, bis auf die Tatsache das man nach dem Tod (keine Leben mehr) die Items von vor dem Betreten kurz sieht, bis man eines anklickt, dann verschwinden diese. Normalerweise müsste das Inventar jetzt ja sofort leer sein.

---

keepInventoryOnEnter: true  -> Beim Betreten Inventar mitgenommen 

keepInventoryOnEscape: false -> Beim Verlassen/Leave Inventar wiederhergestellt (im Dungeon getrunkene Tränke sind auch wieder voll)

keepInventoryOnFinish: false -> Beim Abschließen des Dungeons wird das Inventar  wiederhergestellt (im Dungeon getrunkene Tränke sind auch wieder voll)

keepInventoryOnDeath: false -> Beim Tod Inventar von vor dem Betreten gelöscht

Alles funktioniert korrekt!

---

keepInventoryOnEnter: true  -> Beim Betreten Inventar leer

keepInventoryOnEscape: true -> Beim Verlassen/Leave Inventar wie vor dem Verlassen des Dungeons (getrunkene Tränke bleiben leer)

keepInventoryOnFinish: true -> Beim Abschließen des Dungeons Inventar wie vor dem Verlassen des Dungeons (getrunkene Tränke bleiben leer)

keepInventoryOnDeath: true -> Beim Tod ist das Inventar leer und man steht am Weltspawnpunkt

Die OnDeath Funktion funktioniert nicht korrekt, nun steht man am Spawnpunkt und das Inventar ist leer.

---

Nun eine unlogische Kombination, wirft aber Fehler auf und hilft dir vielleicht bei der Fehlersuche...

keepInventoryOnEnter: false  -> Beim Betreten Inventar leer

keepInventoryOnEscape: true -> Beim Verlassen/Leave Inventar von vor dem Betreten gelöscht

keepInventoryOnFinish: true -> Beim Abschließen des Dungeons Inventar von vor dem Betreten gelöscht

keepInventoryOnDeath: true -> Beim Tod Inventar von vor dem Betreten gelöscht

Zugegeben die Kombination bei OnEnter: false und OnEscape und Finish true ist komisch, wollte ich aber mal testen. Komischerweise wird das Inventar bei dieser Kombination sowohl beim Verlassen, Beenden als auch beim Tod gelöscht...

---

Man sieht also die Items nach dem Tod (wie im Video) komischerweise nur, wenn onEnter und onDeath false sind. Dann aber auch nur solange, bis ein Item angeklickt wird, dann sind diese weg. Wenn ich keine der keepInventory Argumente in die config eintrage, sehe ich die Items nach dem Tod auch, aber eben auch nur solange bis ich eines anklicke (wie im Video). 

Ich hoffe das hilft dir weiter :)

**Comment by Sataniel98** [comment]
Ich hab den Grund für den Bug nicht finden können, es ist wohl etwas komplizierter. Allerdings hab ich ein kleines Workaround einbauen können, wobei das Wiederherstellen des Inventars einen Tick verzögert passiert und der Fehler so "vorbeizieht" und seine Auswirkungen später "übschrieben" werden. Ein kompiliertes Dev-Build (#4) gibt's auch, allerdings vom 0.10-Branch: http://feuerstern.bplaced.net/files/downloads/dxl

Das Build dürfte so stabil wie 0.9.6 sein und die Daten sollten sich übernehmen lassen, nur der "dungeons"-Ordner muss in "maps" umbenannt werden.

**Comment by Sataniel98** [comment]
**Status**

_Erledigt._

**Comment by Sataniel98** [comment]
(Hoffentlich?) behoben in Build 34.
