### ISSUE TITLE
Help setting up dungeon: Always says it includes 3 maps

### ISSUE THREAD

**Issue by razorrider7** [DRE2N/DungeonsXL#192]
I Have been reading, and rereading, the Docs since yesterday, and have used YAMLlint on the files I have made, but I cannot seem to get my dungeon to load. The files I have made are a loot table that does work, and a dungeon yml that doesn't seem to load my dungeon.

My dungeon's .YML file, [Calvara.yml](http://pastebin.com/HPcjx8FN) makes DungeonsXL think that there are three Maps that are needed, and doesn't load the dungeon because the map Calvara_Map is missing, even though it is in the right folder. The docs weren't that clear on how to make my own dungeon .YML file, they just showed an example, and options for overrides.

Sorry if this is obvious, I'm probably just overlooking something xD

Edit: Now whenever I try /dxl play map Calvara_Map it gives me a NPE. The log is [here](http://pastebin.com/JuaUFJUA).

**Comment by Sataniel98** [comment]
You've added the Calvara_Map three times: As the start floor, as the end floor and once again in the floor list. You do not need a script to link floors if your dungeon has just one map. I will have a look at the NullPointerExceptions, though, and fix the bugs. Thank you very much for your report :)

**Comment by razorrider7** [comment]
If I wanted players to keep their inventories when joining a dungeon with only 1 floor, I would create a floor config, rather than this one, right?

Also, where would I put the floor config, assuming that's what I need to make?

**Comment by Sataniel98** [comment]
That's correct. Alternatively, you can add keepInventory to the default section of the main configuration.

The floor config goes into the floor, so _DungeonsXL/map/%mapName%/config.yml_

An example is available here: https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration

**Comment by razorrider7** [comment]
Also, when I type /dxl leave in a lobby, before the game, the plugin gives an NPE. It also keeps saying the map hasn't been saved to the right directory, although it is there.

I would also recommend using .equalsIgnoreCase() for commands, so commands are recognized even without the right case (/dxl leave or /dxl Leave)

**Comment by Sataniel98** [comment]
I didn't even notice it's case sensitive yet  ¯\_(ツ)_/¯ I'm pretty sure all of these issues you're getting are a result of the same problem. I'm working on it.

**Comment by Sataniel98** [comment]
Should be fixed in 0.15.5.
