### ISSUE TITLE
Gyaz of Chest looting Duplication.

### ISSUE THREAD

**Issue by Flemse12** [DRE2N/DungeonsXL#193]
I even tried making each chest have ther very own loot script, did not change anything
The rest of the duplicated items can be gotten by doing the /dxl rewards command, tested on newest build

Here is a gyaz off the bug happening
https://gyazo.com/169b2536bbc4907268b2d3cb78de498e

Here is the script, which now does work :)

0:
  item:
    ==: io.github.dre2n.caliburn.item.UniversalItemStack
    type: "CUSTOM_DEFAULT"
    material: "IRON_SWORD"
    durability: 35
    name: "&4Crude Sword"
    amount: 1
    lores:
     - "&4Old Sword made from Iron."
    enchantments:
      "DAMAGE_ALL": 4
      "THORNS": 1
  The loot chance in percent
  chance: 100
1:
  item:
    ==: io.github.dre2n.caliburn.item.UniversalItemStack
    type: "CUSTOM_DEFAULT"
    material: "GOLD_NUGGET"
    name: "&4Token"
    amount: 1
    lores:
     - "&6Used to buy items from the Dungeon Vendor"
    enchantments:
  The loot chance in percent
  chance: 100

**Comment by Sataniel98** [comment]
So, you're getting loot two times if you click at each sign one time? How are the edit signs placed?

**Comment by Flemse12** [comment]
https://gyazo.com/fdefffdb36813b680eef090d33652a61

**Comment by Sataniel98** [comment]
I've tested it with two players in one group and in two with exactly the same setup in SFD & MFD - it seemed to work perfectly fine for some reason (except that the loot is split unnecessarily). Could you provide some more information about what exactly you did (like game type, floor / dungeon config etc.)? Did it occur in other cases as well or just with these two chests?

**Comment by Flemse12** [comment]
Sure.
Gametype = Default.
Entire dungeon is one big single Floor.
Happens with every chest placed in the Dungeon

Config:
`timeUntilKickOfflinePlayer: 10000

Time until you can play a Dungeon again (in hours)
timeToNextPlay: 3

Time until a player can get loot for another time
timeToNextLoot: 12

 Time until a new mob waves begins when enough mobs are killed.
timeToNextWave: 120

Dungeons can be played with a timer.
If the group has no time left, the players get kicked.
timeToFinish:

The game mode, SURVIVAL if nothing
gameMode: Default

PvP
playerVersusPlayer: false
Friendly fire refers just to members of the same group
friendlyFire: false

These commands can be used by all players if they are in the dungeon.
DXL commands like /dxl leave are included by default.
gameCommandWhitelist:


MAKE SURE YOU EDIT THIS PART!
One of these Dungeons must be finished ("any" for any dungeon). If you do not want any, leave this empty.
mustFinishOne:
  - any

All of these Dungeons must be finished. If you do not want any, leave this empty.
mustFinishAll:


Max time in hours after the last finish of one of the Dungeons above
timeLastPlayed:

 A list of requirements
requirements:
  feeMoney:
  feeLevel:

Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true
Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: true
Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: true
Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: true

If players can build and destroy blocks in this world.
build: false

Amount of lives a player initially has when he enters a dungeon
initialLives: 3

Messages also to be created with /dxl msg
message:
secureObjects:
- 69
- 76
- 77
- 70

Players who can to edit the Dungeon (/dxl invite)
You can add both UUIDs and names.
invitedPlayers:


A list of permissions players get while they play the game.
The permissions get removed as soon as the player leaves the game.
Requires Vault and a permissions plugin like PermissionsEx.
gamePermissions:


requirements:
 If the group has too many or not enough members, the players will not be allowed to use the ready sign.
  groupSize:
    minimum: 4
    maximum: 5
  Players must have these permission nodes to enter the dungeon:
  permission:`

**Comment by Sataniel98** [comment]
I don't think this influences your actual problem, but: These configs aren't supposed to contain empty values like "timeToFinish:". No value is a value, too, and you will most likely not want this in most cases. For example, "keepInventoryOnDeath:" is a boolean value, which means that it will be recognized as "true" if you set it to "true" or as "false" if you set it to anything else including nothing. That being said, leaving it empty like this will set it to "false" even if you intend to use just the default value (which is "true"). Similar things might happen with numeric values.

**Comment by Flemse12** [comment]
Still no fix to this?
I've tried on my laptop aswell and it still had the same problem? I really cant tell whether this is on your end on mine?
