### ISSUE TITLE
error when trying to play my dungeon

### ISSUE THREAD

**Issue by lord44210** [DRE2N/DungeonsXL#195]
Hi
When I try to do /dxl play (dungeonname) I get teleported but I stay where I was standing before doing this command and in my console I can see this error: http://pastebin.com/KXURmXNR

**Comment by Sataniel98** [comment]
You're using a snapshot of DungeonsXL 0.11. Snapshot builds are published without testing and this one is nearly a year old. You should update to the latest version (by following the instructions in the changelogs at SpigotMC!) and try it again. Please keep DXL up to date, the disclaimers are very serious.

**Comment by lord44210** [comment]
ok thanks! I'll try

**Comment by lord44210** [comment]
I've tried the latest version an it doesn't work too it do the same thing when I issue the command /dxl play the command teleport me for 0.5 seconds into the dungeons and reteleport me where I was before doing this command...
this time I don't have any problem in my console does I am doing something wrong?
and when I do /dxl test it says I'm not in a dungeon, I've created a world with /dxl create

**Comment by lord44210** [comment]
It's okay I've resolved my problem
thanks you you're the best ^^
