### ISSUE TITLE
Link portal with main world

### ISSUE THREAD

**Issue by WeenoPlow** [DRE2N/DungeonsXL#196]
Hello,

I tried to place group sign in my main world as documentation but it didn't work (look screenshot). Can you help me please ?
 Doc: "Players can setup their groups with a group sign in one of the main worlds."

screenshot:
http://image.noelshack.com/fichiers/2017/03/1484651037-mc.png

red words say: You have to join a group first!

Another question:

1 map = 1 dungeon or 1 map = X dungeons ?
http://image.noelshack.com/fichiers/2017/03/1484651037-maps.png

Sorry for my language i'm french ^^

**Comment by Tiplish** [comment]
Maybe i can help you.

it's [DXL] and not [Donjon] ( moreover it's the french word) if i remember. Try it :)
Look at this picture : https://github.com/DRE2N/DungeonsXL/wiki/signs#group

For you last question, 1 map = 1 dungeon A dungeon could have multiple floor.

I hope i've helped you.

I'm french too :)

French : 
Peut-être que je peux vous aider.

Il faut mettre [DXL] tout en haut et non pas Donjon (c'est français ça en plus) si je me souviens bien. Essayez ça :)
Regardez cette image : https://github.com/DRE2N/DungeonsXL/wiki/signs#group

Pour votre dernière question, 1 map = 1 donjon. Un donjon peut-être composé de plusieurs étages.

J'espère vous avoir aidé.


Je suis français aussi :)

**Comment by Sataniel98** [comment]
@Tiplish Merci ;)

@WeenoPlow Il y a aussi une introduction française de Tiplish: https://nefald.fr/wiki/DungeonsXL

**Comment by WeenoPlow** [comment]
Yeah ! thank you so much ! 

I did not understand, i thought we had to put map name on first line. So it's working now !!

@Tiplish @Sataniel98  encore merci pour vos réponses rapides !!
