### ISSUE TITLE
Class Item Atrribute Issue

### ISSUE THREAD

**Issue by Masterofjumping** [DRE2N/DungeonsXL#197]
Hey,

I've been having difficulty with assigning a sword an attack speed and attack damage. Ingame the sword will only ever take on one attribute, in this case the speed attribute. If I remove the damage attribute though and just modify the speed attribute it will only do one damage.

http://pastebin.com/mFRL9KBa

I was able to create a sword ingame using the built in Mojang UUID system with these attributes modified but have been unable to successfully achieve this using the attribute class system.

Hope you are able to help, thanks

**Comment by Sataniel98** [comment]
Not a DXL bug but a Caliburn bug, but yeah. Thank you for the report :)

**Comment by Sataniel98** [comment]
https://github.com/DRE2N/CaliburnAPI/issues/3
