### ISSUE TITLE
Can i remake DXLdata.data without breaking dungeon?

### ISSUE THREAD

**Issue by Flemse12** [DRE2N/DungeonsXL#198]
So i finally figured out how to fix that incredible annoying bug with the double looting when using scripted Chest.
I believe if that your dungeon (like mine) was created on an older build before this bug was "fixed" it will still be present in newer builds where it should be fixed, which explains why you cant recreate the bug.

But the real issue is that i made multiple copy of my Dungeon to make sure nothing bad would happen to the Map when trying to fix that.

First of all when fixing the bug it nullifies every single Sign placed in the dungeon, and i think im well above the 500-700 Signs at this point, and placing all those again and writing those lines is not something im really up for :/
So my question is it possible to remake a DXLdata.data file inside the current Dungeon world file, without breaking the dungeon itself?

*Edit*
/dxl reload wich i thought might save this says it reloads the plugin and then gives this crash log

22:12:51 [javastacktrace] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1384) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
22:12:51 [javastacktrace] 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]
22:12:51 [javastacktrace] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
22:12:51 [javastacktrace] Caused by: java.lang.NullPointerException
22:12:51 [javastacktrace] 	at io.github.dre2n.dungeonsxl.game.Game.<init>(Game.java:98) ~[?:?]
22:12:51 [javastacktrace] 	at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:88) ~[?:?]
22:12:51 [javastacktrace] 	at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
22:12:51 [javastacktrace] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-1.11.2-b1042.jar:git-Paper-1042]

**Comment by Sataniel98** [comment]
There was indeed a bug that caused ghost signs when a sign was removed by breaking the attached block. I think the best way to solve this problem would be to add an extra check that removes DXL sign data if the actual block in the resource world is not a sign or if two DXL signs exist at the same position (not quite sure if this would cause problems with script signs).

Concerning the new bug: Are you sure that this is connected to /dxl reload? It says "PlayCommand" in the stacktrace. However, I'll have a look at it.

My semester break starts in February, so I'll have plenty of time at least in a few weeks. Can't promise anything sooner though due to exams :(

**Comment by Flemse12** [comment]
Alright so either, wait for that fix or delete DLXdata and add every sign in back manually i only options really? 
Either way thanks for the repley and i hope you do well on your exams

**Comment by Sataniel98** [comment]
Theoretically, the ghost sign should disappear if you put a blank one at its exact place(, reload?) and destroy it. Haven't tested this, though.

**Comment by Flemse12** [comment]
Well getting rid of the ghost signs signs dose not seem to be he big issue, its more making sure all the signs (that turn into ghost signs] placed in the dungeon, still work, after deleting DXLdata. Without having to replace everyone single of them manually again.
But im pretty sure im the only one whos been working on this dungeon for so long that im experiencing this problem, might just have to bite the dust and manually replace every sign

**Comment by Sataniel98** [comment]
If you choose to do so (I wouldn't recommend this), I hope you're aware of the stick tool that allows you to copy signs with a right click.

**Comment by Flemse12** [comment]
I was not lol, I've noticed middle mouse docent work tho

**Comment by Sataniel98** [comment]
The reload thing should be fixed.
