### ISSUE TITLE
Invisible sign for DXL GROUP, can't join a group and test my dungeon

### ISSUE THREAD

**Issue by MorenaDaniel** [DRE2N/DungeonsXL#200]
Hi ! I have a problem when i try to join a dungeon. 

I created a dungeon named "bob" for the test. It contain lobby, start, end, ready and leave. I then used /dxl save and /dxl leave to go back to my main world. When i create a sign [DXL] Group bob 1,1 it displays nothing. same when i create [DXL] Game bob. When i try create a group with the commands, i can't go through the portal. It write "Dungeon does not exist".

Can you help me ?

![2017-01-28_21 01 53](https://cloud.githubusercontent.com/assets/7815280/22399449/104de0f6-e59d-11e6-80c0-003b0177c30f.png)
![2017-01-28_21 03 15](https://cloud.githubusercontent.com/assets/7815280/22399456/2d287f06-e59d-11e6-9670-472468af1590.png)
![2017-01-28_21 03 55](https://cloud.githubusercontent.com/assets/7815280/22399460/420ab920-e59d-11e6-896c-003267785fb9.png)
![2017-01-28_21 04 13](https://cloud.githubusercontent.com/assets/7815280/22399462/4cbaf222-e59d-11e6-88ce-fbfd6f54b2b8.png)

**Comment by Sataniel98** [comment]
What does /dxl list say? Are there any errors in the console?

**Comment by MorenaDaniel** [comment]
Thanks for the quick answer.

I have no error in the console , and my server is completly fresh, there is no other plugin than DXL, and the server is in 1.10.2

Also i have the dungeon in /dxl list 

![2017-01-28_21 26 20](https://cloud.githubusercontent.com/assets/7815280/22399611/8e68b012-e5a0-11e6-8391-a4918c6d33ee.png)
![sans titre-1](https://cloud.githubusercontent.com/assets/7815280/22399621/c80cca06-e5a0-11e6-882d-540a1c975cb7.jpg)

**Comment by Sataniel98** [comment]
Can't really explain this, but I did notice several issues with global signs on my own server. Definitely needs fixes as soon as possible.

**Comment by MorenaDaniel** [comment]
Problem Solved by updating the server to 1.11.2 !

**Comment by Sataniel98** [comment]
It shouldn't make any difference between 1.9-1.11.2 - are you sure it's not because you restarted the server in order to update?

**Comment by Maze123** [comment]
Hi there,

Got exactly the same prob. My spiggot is in 1.10.2, and got the same kinds of disagrements...

For example: I create a sign like this

___________________
          [DXL]
         Group
           test
           1,1
___________________

so this should create a sign with something writted on, right ? And when I validate, nothing's displayed. The sign is taken by DXL (meanings I cant destroy it without /dxl break) but nothing appear on it... same for all signs that I put in the MAIN WORLD.

This is embarassing, i already used this plugin and i know how magical it is... Need help :-)

**Comment by Maze123** [comment]
Look at this guys, may it help you ?

![image](https://cloud.githubusercontent.com/assets/25420369/22408146/f67e9846-e673-11e6-82f3-a2ad6a434ada.png)


Pfff I'm in trouble, I was forced to close my serv. cuz of this sudden bug updating it to 1.10.2 ...

EDIT : May the plugin work only with Bukkit ? Because actually I am on spiggot 1.10.2

**Comment by Sataniel98** [comment]
No, it is designed to work with Spigot 1.9.x-1.11.x. Some features don't work with CraftBukkit and 1.7.x / 1.8.x, but Spigot 1.9.x-1.11.x is fully supported.

**Comment by Maze123** [comment]
Hey, I'm working on it about 5 hours, still nothing. This plugin wont work... Could someone on spiggot 1.10.2 tell us if you're okay with DXL ? 

We really need to fix this :-)

Thanks

**Comment by Sataniel98** [comment]
Updates won't happen in the next few weeks, sorry :(

**Comment by MorenaDaniel** [comment]
I can confirm that updating the server to 1.11.2 fixed the issue, i have 2 other friends that can't display the DungeonXL signs on 1.10.2 and when they switch to 1.11.2 it's working. Maybe a problem from spigot with the signs ?

**Comment by Sataniel98** [comment]
Retested it with DXL 0.15.7-SNAPSHOT-08 and the latest version of 1.10.2. It works flawlessly. I will close this for now, please tell me if it occurs again.
