### ISSUE TITLE
Command Question

### ISSUE THREAD

**Issue by fenix12585** [DRE2N/DungeonsXL#202]
I would like to create an item that when used executes a command as the console to teleport a player to the lobby of a dungeon. I have looked through your tutorials and can not find this. In the past I had this setup. Is this still possible? Is there still a command for this?

Also, I have got to be going crazy, I also cannot figure out the permision node to give someone access to do /play. I have tried .dxl.play, dxl.play.*, and dxl.play.dungeonname

Thanks!

**Comment by Sataniel98** [comment]
If want to do this inside a dungeon: Create a [command sign](https://github.com/DRE2N/DungeonsXL/wiki/signs#command) or a [teleport sign](https://github.com/DRE2N/DungeonsXL/wiki/signs#teleport) with a [use item trigger](https://github.com/DRE2N/DungeonsXL/wiki/signs#use-item). If you want this from the main world before the player enters the dungeon, you'll need a different plugin (Maybe [this one](https://dev.bukkit.org/projects/itemcommand)) to link the command to an item. DXL never had a feature like that built-in. You can do this with "/dxl play [dungeon|map name]", but note that this is _not_ a console but a player command. If you really need a console command for this, I'd think about adding an argument to specify the player to /dxl play, but you can also easily achieve the same with "/sudo [player] dxl play [dungeon]" if you use Essentials. The related node is always dxl.[command] unless anything else is clearly stated in the wiki - so dxl.play in this case. I hope I could help. Regards

**Comment by fenix12585** [comment]
you did, I already use skript to have items execute commands then disappear. In this case, I think I will have to have the console give them the permission dxl.play  then sudu the play command and then have the console remove the dxl.play permission

Thanks for the help!
