### ISSUE TITLE
Copy pasting doesn't work as intended?

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#203]
Greetings! I have a small issue about the map

First of all, the map I'm talking about is the world folder located inside DungeonsXL/maps/

When I first time create a map, and just copy paste the **region files** in it, it works just fine.

but when I create another dungeon, and copy paste **whole dungeon files** to it, it doesn't work.

in fact, flat world region data is override on the pasted data.

I think the pasted data is not read properly.

I even tried /dxl reload, but it was still flat world. I did /dxl edit yet still couldn't see any pasted data in it.

I just wanted to rename the dungeon, but it seems DungeonsXL doesn't like it.

any suggestion, or is it a bug?

**Comment by Sataniel98** [comment]
I guess you pasted your data while the edit world was still loaded. After that, DXL saved the loaded edit world - therefore, the region files got overriden. You can simply use /dxl rename instead if you want to rename maps while the server is running. This will also update the name in scripts.

**Comment by wysohn** [comment]
Sweet! just didn't know that there was a such command. Thx!
