### ISSUE TITLE
a problem about ExternalMob

### ISSUE THREAD

**Issue by rock211212** [DRE2N/DungeonsXL#204]
i have a problem about ExternalMob.
i cant spawn a CustomMobs in my dungeon,wen try to spawn it my CMD well get
[07:06:06] [Server thread/INFO]:  [0;36;22m[-  [0;33;22mCustomMobs [0;36;22m -]  [m [0;31;1m1092.5 should be a number! [m
[07:06:06] [Server thread/INFO]:  [0;36;22m[-  [0;33;22mCustomMobs [0;36;22m -]  [m [0;33;22m/ccmob spawn <Name> <worldname> <x> <y> <z> [amount] [0;37;22m -  [0;36;22mConsole and CommandBlock spawn command [m

**Comment by Sataniel98** [comment]
How does your sign look like?

**Comment by rock211212** [comment]
![image 1](https://cloud.githubusercontent.com/assets/25649691/22783773/35535060-ef08-11e6-8604-49ef10a18712.jpg)

**Comment by Sataniel98** [comment]
I can imagine that they changed their syntax, you can still register the /ccmob command with a new identifier in the main config.

**Comment by rock211212** [comment]
Could you please elaborate on how to use it?
![image 2](https://cloud.githubusercontent.com/assets/25649691/22795801/ef3979c6-ef32-11e6-99df-72f37f5cdb2a.jpg)

**Comment by Sataniel98** [comment]
"XY: custommobplugin spawnmob %mob% %world% %x% %y% %z%"
Replace XY with any identifier for the sign. Replace the second part with the command to spawn the mob. That's it.

**Comment by rock211212** [comment]
i register main config But the problem is still there
my config:
externalMobProviders: {IF: ccmob spawn %mob% %world% %x% %y% %z%}
sing: (chicken is my boss name)
![image 3](https://cloud.githubusercontent.com/assets/25649691/22839979/aaf6edbe-f006-11e6-8cbd-7c7386c83ffe.jpg)
cmd:
[03:06:33] [Server thread/INFO]: [0;36;22m[- [0;33;22mCustomMobs[0;36;22m -] [m[0;31;1m1092.5 should be a number![m
[03:06:33] [Server thread/INFO]: [0;36;22m[- [0;33;22mCustomMobs[0;36;22m -] [m[0;33;22m/ccmob spawn <Name> <worldname> <x> <y> <z> [amount][0;37;22m - [0;36;22mConsole and CommandBlock spawn command[m
What am I doing wrong?

**Comment by Sataniel98** [comment]
Does the command work if you use it manually? (e.g. /ccmob spawn chicken DXL_Game_1 0 5 0)

**Comment by rock211212** [comment]
yes
![image 4](https://cloud.githubusercontent.com/assets/25649691/22840500/bb485ea8-f008-11e6-8ac7-a8ad47e0c476.png)

**Comment by Sataniel98** [comment]
I tested it. The problem is that CustomMobs does not recognize .5 values as numeric values. I have no idea why, it wouldn't be more complicated to use doubles instead of ints like Minecraft locations do it anyway. I think I'll submit a PR to CustomMobs and leave it as is in DXL.

**Comment by rock211212** [comment]
I got it! thank

**Comment by Sataniel98** [comment]
Decided to add a simple solution to DXL itself instead, please try 0.15.7 build 6 or higher :)
