### ISSUE TITLE
floor config problem?

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#205]
The dungeon was working completely fine; however, after I created config.yml in the maps/blahblah, the ready sign is not working.

I simply typed "blah blah" in the config.yml in order to create error, and it did show up the error. 

This means that the floor config is loaded properly, but somehow dungeon is not working.

I just looked around to see if another signs are working, but I realized that except "Ready" and "Leave" sign, other signs like Mobs, etc. are remained as sign.

They should be disappeared right?

I haven't restart my server yet, but I couldn't really fix it just using /dxl reload.

I can't really restart server every time when I add floor config, so can you see what's happening here?

**Comment by Sataniel98** [comment]
Most signs won't setup before the game starts. It is supposed to be like this.
