### ISSUE TITLE
/dxl reload is problematic?

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#206]
it seems /dxl reload is breaking the whole mechanics.

For example, Group signs, Leave signs, portal, etc. all of them doesn't work.

Even if I force start game with /dxl play, the signs inside the dungeon doesn't work.

It's similar to the last issue report(#205)

**Comment by wysohn** [comment]
+ Somehow they work fine when I restart the server.

**Comment by Sataniel98** [comment]
Known
