### ISSUE TITLE
/dxl chat not work

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#207]
it says I'm not in a group, yet I am in a group

**Comment by Sataniel98** [comment]
Are you in a dungeon?

**Comment by wysohn** [comment]
No didn't try that. I wasn't in dungeon. Should I be in dungeon in order to use /dxl chat?

**Comment by Sataniel98** [comment]
I think the message was added when groups could only exist inside dungeons, that's why it still says "You have to join a group first" instead of "You have to join a dungeon". However, there is no actual reason why group chats shouldn't work outside now as well.

**Comment by wysohn** [comment]
hmm I'm using 1.5.6-b49

is it outdated?

**Comment by Sataniel98** [comment]
This doesn't look like a DXL version String. By "However, there is no actual reason why group chats shouldn't work outside now as well" I wanted to say that I'm looking forward to make this possible, not that it should already work.

**Comment by wysohn** [comment]
got it!

**Comment by Sataniel98** [comment]
Try 0.15.7 build 04. It also allows you to chat with just your group or everyone in the dungeon ("@all " before the message) and to modify the chat format in the main config.
