### ISSUE TITLE
keepInventoryOnDeath not working

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#210]
I think none of the keepInventory option in the config.yml work

I only confirmed that keepInventoryOnDeath and keepInventoryOnFinish are not working

I'm talking about the floor config.

Actually, I'm not sure if any of the keepInventory options are working.

Perhaps the keepInventoryOnEnter and keepInventoryOnFinish is working because of PerWorldInventory.

Is this because I have * permission?

**Comment by Sataniel98** [comment]
Would really surprise me if it doesn't work, I'll have a look at it.

**Comment by Sataniel98** [comment]
I tested it, all of them seem to work except keepInventoryOnDeath
