### ISSUE TITLE
Group remains even after player goes offline

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#211]
![2017-02-11_02 15 04](https://cloud.githubusercontent.com/assets/8789836/22853049/fd8a2f0c-efff-11e6-97a3-a275f199b4d6.png)
![2017-02-11_02 15 09](https://cloud.githubusercontent.com/assets/8789836/22853050/fd9cafa6-efff-11e6-819b-759489b9179d.png)

as you can see from those images, the sign showing that a Group of three players are now full, but those players are not online.

I don't know the exact procedure of it, but I found it after I came back from break

**Comment by wysohn** [comment]
Plus, they reported me that they are stuck in the dungeon, and they can't use any of the commands

**Comment by Sataniel98** [comment]
What do they mean by "stuck in the dungeon"? It's intended that you can't use any commands in a dungeon.

**Comment by Sataniel98** [comment]
Didn't occur in my most recent tests; hopefully fixed.
