### ISSUE TITLE
can't fight player in a PVP LMS mode

### ISSUE THREAD

**Issue by MorenaDaniel** [DRE2N/DungeonsXL#212]
Hi ! I have a problem when i create a dungeon with the game type PvP LMS (i didn't tried the factionPVP).

I have 2 different groups, and a GAME sign. When we enter the "dungeon" no problem we are in the lobby.
I placed 2 Start point with ID 1 & 0. And when we hit READY, we appear on the good start point but we can't fight. There is no pvp.

The problem don't come from the server because when i leave the dungeon, there is PVP. And i tried using WorldGuard in the dungeon to set the PVP (even if it's already activated) and it don't work either.

![2017-02-12_19 33 44](https://cloud.githubusercontent.com/assets/7815280/22864909/2bf1674c-f15a-11e6-92c0-0e38fe162186.png)

![2017-02-12_19 34 17](https://cloud.githubusercontent.com/assets/7815280/22864917/41c9f28c-f15a-11e6-9628-c5f447caa8a0.png)  (I tried with 1 sign 'Lobby' and didn't worked so i figured that i should add 1 or 0 and it work now.

![2017-02-12_19 35 33](https://cloud.githubusercontent.com/assets/7815280/22864925/6e0251be-f15a-11e6-91b4-403a8d53d67b.png)

![2017-02-12_19 35 45](https://cloud.githubusercontent.com/assets/7815280/22864928/751f08de-f15a-11e6-9ca3-83cd9d7de1d2.png)

**Comment by Sataniel98** [comment]
Like most plugins with world-bound configs, WorldGuard won't work in instance worlds. Does the ready sign display "Ready / PvP LMS" in the instantiated game world lobby?

**Comment by MorenaDaniel** [comment]
No it display "Custom".

Is the sign Case sensitive ? Because i wrote PVP LMS

**Comment by MorenaDaniel** [comment]
Yeah it's working now, thanks i didn't know it was case sensitive ^^

**Comment by Sataniel98** [comment]
Glad to hear that :)
