### ISSUE TITLE
Inventory clearing

### ISSUE THREAD

**Issue by Francisco-Carvalho98** [DRE2N/DungeonsXL#213]
Players are seeing their inventory clear once they leave the dungeon, instead of getting it back as they got it. Have any idea what might be causing this?

**Comment by Sataniel98** [comment]
Does it work correctly without other plugins?

**Comment by Francisco-Carvalho98** [comment]
We dont have an plugins that your guys say are incompatible. We are running a kit dungeon, and you lose your inventory that supposedly gets saved when you join the dungeon.

**Comment by Sataniel98** [comment]
But does it work correctly without other plugins? The incompatibility list does not include plugins that have to be setup in a certain way to work flawlessly alongside DungeonsXL, just those that seriously clash with it. And I haven't tested for incompatibilities, so there could still be many incompatible plugins that I'm not aware of.

**Comment by Francisco-Carvalho98** [comment]
it seems to, doesnt throw any errors thats why I dont know why its doing it. also im using mythic mobs in the dungeons, and once that instance is not needed anymore, the world unloads, but the mythic mobs in it dont. is that on your end or theirs?

**Comment by Sataniel98** [comment]
My CachedMobs.yml is always empty when dungeons are unloaded, not sure what you mean. I'm pretty sure your inventory problem is caused by another plugin that does exactly what it is supposed to do.

**Comment by Francisco-Carvalho98** [comment]
Mob arenas work similarly, they save your inventory. But mob arenas save it, it always comes back. I've noticed that if you complete the dungeon you dont lose your inventory.Do I need to have keepinventoryondeath: true? is that it?

**Comment by Tiplish** [comment]
When you say "leaving the dungeon", by which way you leave the dungeon? /dxl leave ou with sign?

Do you use a plugin to manage creative mod or inventory on different map? I was getting some issues in this cases.
