### ISSUE TITLE
Commands aren't working

### ISSUE THREAD

**Issue by Hikya** [DRE2N/DungeonsXL#214]
Everytime I use a command from this plugin, nothing happens, and it won't show me anything in the chat. can someone please help me?

**Comment by Sataniel98** [comment]
What does your console say?

**Comment by Hikya** [comment]
[Server] INFO aquaman002 issued server command: /dungeonsxl

**Comment by Tiplish** [comment]
I'm not sure but, isn't it "/dxl" which is the real command?

**Comment by Sataniel98** [comment]
/dxl and /dungeon are aliases for /dungeonsxl. But I'll need information about startup errors etc. in order to help you, this won't help me.

**Comment by Sataniel98** [comment]
Hey, are you still experiencing issues? :)

**Comment by Hikya** [comment]
yes

**Comment by Sataniel98** [comment]
Then please give me something that I can work with, like your logs.

**Comment by Sataniel98** [comment]
I'll close this now, please offer information if you post issues.
