### ISSUE TITLE
Creating my first MFD

### ISSUE THREAD

**Issue by KevinBaselTheAnalyst** [DRE2N/DungeonsXL#220]
Hello there!
First of all thanks very much for your amazing job!! I really love this plugin!! And once I'll understand it 100% I will make a video tutorial and post it for you, if that is ok ofc :)

I wrote here to ask you a question about making a multi-floor dungeons. I read a lot of stuff, here in the issue tracker, and what I've understand at the end is that I must create a config.yml file because normally maps don't need that. And what I've found are those links:

(Floor Configuration) ---->  https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration
(Dungeons Configuration) ------>    https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration

So I create a new file (config.yml) into my maps folder and copy the second link, and at the same time crate another config.yml and copy the first link. Is that right?

I'm so confused.... can you please help me to understand ho to set at least 2 floors into one single dungeon and how to set up those config files, because I read a lot of interesting option and I really want them? I'll appreciate that, really.

Please keep always your hard work up!! You're amazing!!

Cheers

**Comment by Sataniel98** [comment]
Hi :)
First of all, you shouldn't copy all game rules into your configuration file but only the ones that you need. If you want to setup a multi floor dungeon, you'll most likely only need the dungeon script and no gamerule scripts in the world folders at all. Why? The game rule inheritance system can fetch all values for the game from the dungeon script as well and there are very few cases where you need different game rules in different floors of the same dungeon. The most common exception that I can think of is different enter titles. As you can see, the example dungeon script contains just one example game rule, "keepInventoryOnEnter". However, all of them work there as well. Creating the dungeon script like in the example is pretty much everything that you have to do in order to create a multi floor dungeon. The name of the dungeon script (without the YAML extension) is the name of the dungeon.

**Comment by KevinBaselTheAnalyst** [comment]
Ok cool!!
I understood how it works now, but still didn't understand where I have to put this file.
Should I create a config.yml file and copy this:

https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration

but inside which folder? Should I need to put it into every multi-floor dungeons folder, or its ok if I upload just once and it will work for every?

For Floor Dungeon File you gave us the direction:
# Floor configuration of DungeonsXL (config.yml in DungeonsXL/map/%mapName% folder)

But what about the other file? Where exactly should I create this file?? 
I'm asking you that because I've tried several times differently but never got a point....

Hope you can help me!! 
Thanks

**Comment by Sataniel98** [comment]
The path is DungeonsXL/scripts/dungeons/MyDungeon.yml (not config.yml).

**Comment by LordDayradon** [comment]
Just to clarify (for my own understanding at least),  the final name can  be anything OTHER than the name of the map and does not HAVE to be MyDungeon.yml?  I could call it BoogerLand.yml  and when I want to setup game sign I would put BoogerLand on line 3?

**Comment by Sataniel98** [comment]
Correct. The name of the dungeon script can be anything as long as is has the .yml extension. This name defines the argument that you use on signs and in commands, like if you call it BoogerLand.yml, you join the dungeon with /dxl play BoogerLand.

**Comment by KevinBaselTheAnalyst** [comment]
That's interesting.... but what I'm looking for is to put command into sign to access to the next floor.
Like this:

Sign with 1st line: [Floor] and 2nd line: [name of the floor]

Are you sure is this the way to create multiple floor? If I want 2 floors for example should I create 2 files, for ex:       1) FirstFloor.yml        2) SecondFloor.yml   ??
Because the dungeons that I've created are into maps folder... I'm still getting so confused xD

**Comment by KevinBaselTheAnalyst** [comment]
Asking all this questions to understand at 360° this beautiful plugin to make an appreciate video tutorial.

Thanks

**Comment by Sataniel98** [comment]
One dungeon needs one dungeon script with all floors in the "floors" list. You **can** add floor configurations for each floor in the respective map folder (DungeonsXL/maps/floorname/config.yml), but in most cases, you can just put your game rules into the "defaultValues" / "overrideValues" sections of the dungeon config. You can then specify the next floor from the list at your floor sign - or leave it empty. In this case, a random floor from the list will be the next one to play.

**Comment by KevinBaselTheAnalyst** [comment]
Ok. I've done what you said but didn't work properly... Write down here step by step so please tell me where I'm wrong:

1) went to folder: dxl-->script--->dungeons--> then created an .yml file with dungeons config into it.
2) went to folder: dxl-->maps---> here I have 2 folder because I have created 2 maps into game when I run the command /dxl create..... and their name are Level1 and Level2 ----> opened Level1 ---> created config.yml file with floor config into it
3) went back to: dxl-->script--->dungeons--> myfilename.yml and edit it. In the section

**A list of all other floors in the dungeon. Needs at least lobby, ready, start and floor signs.
floors:**

I've put:
- Level1
- Level2

Now Into Level1, at the end of the dungeon, I've created the sign: 1st line [Floor] 2nd line: [Level2]
but it's not working... it just teleports me back to the portal and says that the dungeon is complete

**Comment by Sataniel98** [comment]
You still play the map only if you use /dxl play MapName. You have to enter the dungeon with /dxl play DungeonName. Also, you have to adjust the floor count and start / end floor.

**Comment by KevinBaselTheAnalyst** [comment]
I don't enter the map through /dxl MapName, but using the portal. I've created a portal in the main world with /dxl portal and put a sign next to it for Group. After I join the group I pass through the portal and the dungeon begins, and it teleports me into Level1 map that I've created before with /dxl create Level1. Everything works fine: ready sign, start sign, checkpoint sign,.... but at the end I want a Floor Sign so the players will be teleport into another different map (should be Level2), but how I said it's not working, just teleport me back to the portal (main world) saying that the dungeon is complete. What am I missing?

**Comment by KevinBaselTheAnalyst** [comment]
I put: 

StartFloor= Level1   
EndFloor= Level2   
floorCount= 0

but still doesn't working.. Ofc I've edited Level2 Map and put a Start and End sign.

**Comment by Sataniel98** [comment]
If the floor count is 0, the game will finish when 1 floor is finished as there is no check before entering the first one. If you have two floors and if you do not wish to have any random floors from the list, set it to 2.

**Comment by KevinBaselTheAnalyst** [comment]
Ok I'm understanding more and I've done what you said but still doesn't working.. :(

**Comment by KevinBaselTheAnalyst** [comment]
Here's what I put into _scripts-->dungeons--->MyDungeon.yml_
 
The last floor the players enter. Needs at least start and end signs.
startFloor: Level1
endFloor: Level2
floors:
- Level1
- Level2
floorCount: 2
removeWhenPlayed: false
overrideValues:
  keepInventoryOnEnter: true
defaultValues:
  keepInventoryOnEnter: true
configVersion: 1

And here to _maps-->Level1--->config.yml_
(I've just copy everything from this link because I think it can be usefull)

**https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration**

**Comment by KevinBaselTheAnalyst** [comment]
Just resolve it!!! Read hundred times your post and understood the issue:
So when I create the file name as I wish with .yml, then I have to use that same name into Sign Group to let him work as dungeon and not the name that I used when I did /dxl create, I should look them like floors.
Thanks very much for your help! Amazing Job!!
See you soon!

**Comment by Sataniel98** [comment]
Glad I could help :)
