### ISSUE TITLE
/dxl portal - not work

### ISSUE THREAD

**Issue by WillPowerCraft** [DRE2N/DungeonsXL#224]
/dxl portal - give ure wood sword and chat message - ckick 2 block of portal zone

when click abut block left/right clicks - nothing happens

how that must work?

**Comment by Sataniel98** [comment]
Does it work with the latest dev build?

**Comment by WillPowerCraft** [comment]
hm. i did download plugin from spigot page.
so where i can look list of dev builds?
(usually in developers i can see builds on github on "releases" page, but here 0..

**Comment by Sataniel98** [comment]
Here you go :)

http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/

**Comment by WillPowerCraft** [comment]
thanks i will try that lastest devbuild now  =)))

**Comment by WillPowerCraft** [comment]
/dxl portal work with latest build

but now i have another problem:

1. i create map GG-1
create config with some parametres
dungeons folder is empry

2. in main wold as default player:
/dxl group create 1
/dxl play GG-1

- that gererate random vanilla map world and teleport me here. why?

and every time when i tried launch any varibles dungeons or floors - that generate vanilla map instead load my maps from maps folders (((


help me pls ...

**Comment by WillPowerCraft** [comment]
ok i understand... not all signs in map,,,,, so hard to handle that plugin :3 im stupid)

**Comment by Sataniel98** [comment]
Sounds more like a messed up world cache.
