### ISSUE TITLE
/dxl rewards

### ISSUE THREAD

**Issue by Malfrador** [DRE2N/DungeonsXL#226]
/dxl rewards muss mehrmals genutzt werden, um alle Items zu bekommen. Ich glaube nicht, das das so gedacht ist. Auch erhält man manchmal Rewards doppelt, was doch sehr unpraktisch ist.

**Comment by Sataniel98** [comment]
Wann bekommt man Rewards doppelt?

**Comment by Malfrador** [comment]
Wenn man das Dungeon beendet, geht ein Rewards-Menü auf, in dem ein paar Items sind. Wenn man (wie im Chat steht) dann /dxl rewards nutzt, geht ein neues Menü mit noch ein paar anderen Items auf. Nutzt man es nochmal, kriegt man wieder mehr Items. Also die Items sind erstmal in mehreren Reward-Menüs verteilt. Und aus in meinem Fall dem letzten dieser Menüs habe ich Items doppelt erhalten.
