### ISSUE TITLE
after restart server dxl group signs in main world stop working

### ISSUE THREAD

**Issue by WillPowerCraft** [DRE2N/DungeonsXL#230]
1. create group signs
2. use group signs - to check what they work true
3. save-all
4. restart server
5. group signs in main world not work and looks like default vanilla signs.

0.15.7-SNAPSHOP-08

**Comment by WillPowerCraft** [comment]
i found one more intresting moment
![image](https://cloud.githubusercontent.com/assets/23665302/23824278/8ad78efa-0684-11e7-9eb6-c137c3d532a1.png)

i dont know why is that ? =)

**Comment by WillPowerCraft** [comment]
i found data.yml with protected objects:
that file didnt saved and updated long time - there was wrong portals worng signs. and that was not updated after i saved world from /save-all and i dont know another way to save changes in DXL in main world. about portals and signs...

**Comment by WillPowerCraft** [comment]
now i try to manage data.yml and save and reload plugin / restart server...

**Comment by Sataniel98** [comment]
./save-all has nothing to do with DungeonsXL and will not save any DXL data. The X behind the DungeonsXL version is just there because it's a snapshot. /dxl reload should save the data.

**Comment by WillPowerCraft** [comment]
#233  about /dxl reload - make occuring error

i changed data.yml from text editor and save - that work.
ok that not critical for me if that have some way to work

**Comment by Tiplish** [comment]
Hi, i've already this issue and my DXLportal disapear after restart server. Is it supposed to be fixed? 

Thx :)
