### ISSUE TITLE
Sign Language & breakwhitelist

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#231]
Q: changing sign titles into other languages
Is it possible to change [group], [ready], [leave] sign into other languages? (in my case, it would be korean [그룹], [준비], [떠나기] ) Majority of the players in my servers are low-aged Koreans, and they are not as comfortable to English.

Q: using the 'breakWhiteList' in the new Floor Configuratioin
'breakWhiteList' is not working properly. I tried to use the recently updated Floor Configuration. Whenever I tried to load the plugin it says it is not compatible with the faction plugin (which I don't use in my server). I did not see any other noticable error messages.

**Comment by WillPowerCraft** [comment]
hah) they will d it, i adsked same 1 day ago) and they said - what they add that option to language file

**Comment by WillPowerCraft** [comment]
look #228 issue

**Comment by Ecilpse** [comment]
Oh.. Thanks.
