### ISSUE TITLE
Poor Tutorial Pictures

### ISSUE THREAD

**Issue by InfernalAsh** [DRE2N/DungeonsXL#236]
Hello, I'm not gifted with brilliant eyesight nor is my friend but we are struggling to make any sense of the getting started page on your wiki. The text alone does not tell you how to set lobbies etc or assign portals which has left us at an impass. We would love to implement this plugin but there is very little material showing how.

Little help?

many thanks S

**Comment by Sataniel98** [comment]
Reading the "getting started" page will give you some hints, but this plugin is too complex to be explained in a few sentences. Portals are not "assigned" to anything. You use group and game signs to prepare groups for the dungeon. The signs that lobbies usually contain are listed [here](https://github.com/DRE2N/DungeonsXL/wiki/signs) If you have any specific questions, feel free to ask.

**Comment by InfernalAsh** [comment]
Hello again, 

I think something that would improve the understanding is a better picture if the sign setup. The current angle one makes it hard to see the first few signs. A second picture would help a lot if people I believe. Thanks for your haste in responding.

**Comment by Sataniel98** [comment]
I don't see what's missing there.
