### ISSUE TITLE
respawn in floor

### ISSUE THREAD

**Issue by WillPowerCraft** [DRE2N/DungeonsXL#245]
can ure pls rewrite respawn mechanic in floor to stop that:

1. u teleport to main world spawnpoint - load map
2. u teleport back to start sign in floor - load map

that make long load time and respawn time and if any monster in floor near start sign - ure 100% die again with out do any in game.

only leave server wait time to reconnect and join server help to escape that case.

pls change that tp mechanic...

**Comment by Sataniel98** [comment]
Many plugins override the respawn position. Teleporting one tick after respawning bypasses this.

**Comment by WillPowerCraft** [comment]
=(
have no idea..

**Comment by Sataniel98** [comment]
I still think we should find a solution for this. Give me a few minutes...

**Comment by Sataniel98** [comment]
You can use this if you want: https://github.com/DRE2N/RespawnProtectorXS

**Comment by WillPowerCraft** [comment]
nope didnt help...

thanks for try =)

**Comment by Sataniel98** [comment]
Why though?

**Comment by WillPowerCraft** [comment]
I dl plugin, put in plugin folder, restart server, check plugins list, check folders in plugin folder, view configure with "time:5" try dxl play, die and respawning - that make same load main world and load dxl map - in load time monsters what did kill me dmg me on -18hp ))

that's same case, I just make only 2 mobs near start sign
