### ISSUE TITLE
Images on Wiki Are Missing!

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#249]
Some images on https://github.com/DRE2N/DungeonsXL/wiki/signs are missing which make the wiki page unreadable. It seems that your Dropbox links are all broken.

P.S. could you convert the page into a plain-text format (without images)? Are there any other way that I could get the tutorial from? Perhaps a backup link to a pdf file is better if something going wrong with Wiki.

**Comment by Sataniel98** [comment]
They are not mine, so I'll have to make new ones...

**Comment by godleydemon** [comment]
yeah can't exactly set up a dungeon without the images the first time around lol
