### ISSUE TITLE
Portal Wait-time

### ISSUE THREAD

**Issue by pshadoyan** [DRE2N/DungeonsXL#251]
Hey! I'm completely new to the plugin, but so far it's been fantastic other than this issue with portals. Once you walk into a portal, in order to activate it you've got to walk back and forth, quite annoying; I'd much rather have it so it gets activated right on impact or contact, if that makes any sense. Additionally, I have a question: is it possible to have a 5 second wait time once the portal is activated? So say for instance you activate the portal and then it says : 

You will be teleported in 5 seconds.
You will be teleported in 4 seconds. 

I think you get the point, I'd love if someone could guide me in the right direction if this is already possible, and if it's not, perhaps a suggestion?

Regards, 
Paddy

**Comment by Sataniel98** [comment]
Hi,
it teleports you immediately, but the instance might need a few seconds to be loaded.

**Comment by pshadoyan** [comment]
So besides that, is there any way to add a wait-time?

**Comment by Sataniel98** [comment]
No. Not really sure what this would be good for.

**Comment by pshadoyan** [comment]
Here's a little video depicting what happens : https://youtu.be/bqy7D124aO0

You're only teleported once you walk back, walking into the portal doesn't do anything.

**Comment by Sataniel98** [comment]
I'm aware of some inconsistencies, but I don't think it's possible to improve this.

**Comment by pshadoyan** [comment]
I appreciate the response, much obliged.
