### ISSUE TITLE
/languages/english.yml color editing {issue}

### ISSUE THREAD

**Issue by KevinBaselTheAnalyst** [DRE2N/DungeonsXL#253]
Under this line I wrote:

Player_Death: '&d&lAincard &9&lDungeon &d&l>&9&l>&d&l> **&b&v1** &6died and has **&b&4&v2** &6lives left.'

Every color works great except for the two **bolds**. On chat it appears the PlayerName with colour of darkblue (&1) and for other the LifesLeft in darkred (&4).
I've tried several things because I would like to change those colours differently because players can't read well and I didn't find a solution... What should I do...? :(

Cheers

**Comment by Sataniel98** [comment]
Player names will always have the color of the player's group when he is in a dungeon. You can modify the group colors in the main config.

**Comment by KevinBaselTheAnalyst** [comment]
Ok cool thx. And what about for color code about Number Of Lifes? That's set up red?

**Comment by Sataniel98** [comment]
This should be modifiable in the language file.
