### ISSUE TITLE
FloorCount {issue}

### ISSUE THREAD

**Issue by KevinBaselTheAnalyst** [DRE2N/DungeonsXL#254]
Hello!

I'm trying to make a MFD and this is the set up for 3 Levels right now. I would like that when players finish first level, then they enter the second one and so on. I'm not looking for random tp between level. You told me once that if I have 2 floors in floorCount i need to set to 2 and it worked. I supposed with 3 levels I should set to 3, isn't? Because it's not working....
This is the setting:

The last floor the players enter. Needs at least start and end signs.
startFloor: Level_1
endFloor: Level_3
floors:
- Level_1
- Level_2
- Level_3
floorCount: 3
removeWhenPlayed: false
overrideValues:
  keepInventoryOnEnter: true
defaultValues:
  keepInventoryOnEnter: true
configVersion: 1

Where am I wrong?

**Comment by Sataniel98** [comment]
You don't need the startFloor and the endFloor in the list.

**Comment by KevinBaselTheAnalyst** [comment]
Seems not working. When I try to enter the dungeon says that doesn't exist. I've tried like this:

startFloor:
endFloor:
floors:
- Level_1
- Level_2
- Level_3
floorCount: 3
removeWhenPlayed: false
overrideValues:
  keepInventoryOnEnter: true
defaultValues:
  keepInventoryOnEnter: true
configVersion: 1


And also like this:



floors:
- Level_1
- Level_2
- Level_3
floorCount: 3
removeWhenPlayed: false
overrideValues:
  keepInventoryOnEnter: true
defaultValues:
  keepInventoryOnEnter: true
configVersion: 1

**Comment by KevinBaselTheAnalyst** [comment]
Something really strange happened.... Just figured it out that this error it comes up also if I put the old config....why? It came up only when I tried to change settings as you said.

**Comment by Sataniel98** [comment]
My bad, I meant you should remove the end floor and the start floor from the floor list, otherwise they will be played multiple times. You should also set removeWhenPlayed to true by default.

**Comment by KevinBaselTheAnalyst** [comment]
Ok good, we are almost done. It's working for half now. I copy the settings and explain you what happens:

The last floor the players enter. Needs at least start and end signs.
startFloor: Level_1
endFloor: Level_3
floors:
- Level_2
**floorCount: 0**
removeWhenPlayed: true
overrideValues:
  keepInventoryOnEnter: true
defaultValues:
  keepInventoryOnEnter: true
configVersion: 1

1st Floor I put Lobby, Ready, Start, Floor sign
2nd Floor I put Start and Floor sign
3rd Floor I put Start and End sign

Everytime I finish 1st Floor it teleports me to 2nd and its ok, but everytime I try to go from 2nd to 3rd it teleports me back to 2nd and when I try as second chance it works. I've changed **floorCount** settings into: 1 / 2 / 3 and didn't work, it always happens the same like if it goes random. Why? oO

Thanks for your amazing job

**Comment by KevinBaselTheAnalyst** [comment]
There is any solution or no?
Just to understand what should I do...

**Comment by Sataniel98** [comment]
Not sure what's wrong ATM, I'll have to have a look at it myself.

**Comment by KevinBaselTheAnalyst** [comment]
Ok, I hope you can figure it out asap because I'm ready to open the Dungeon to my server and the players are waiting impatiently for it... xD

Then, when we will be ready 100%, I would like to show you my server and if it's ok for you I would like to make that video tutorial that I told you months ago :)

If you need any kind of help with programming you can ask me, and it will be a pleasure for me to help you.

Cheers

**Comment by KevinBaselTheAnalyst** [comment]
I have waited too much to see if you could resolve this issue but seems you still need more time.
Dunno why it doesn't work, that's a pity because it looks like an awesome plugin.... It's the second bug a found on that plugin about 2 normal settings that should work but they don't. If they really can't work I can't use this plugin into my server, because it seems still on Alpha. If you think you can resolve it shortly let me know and I can take the consideration of using it again. Cheers

**Comment by Sataniel98** [comment]
Hi, I decided to drop this plugin for now. I hope to take it up again in a few months. I think the disclaimer at the resource page sums it up well: "This is Beta software and not ready to be used in a production environment."

**Comment by KevinBaselTheAnalyst** [comment]
It's a pity because it's one of the best plugin that I ever seen!! I'm good at coding, if you are busy now and need help to carry on the codes, I can give you an hand during this month. Let me know whenever you want, or I will wait an answer here when you'll come back and resolve the issue. 
Thx & Cheers

**Comment by Sataniel98** [comment]
Well, PRs with bugfixes are always welcome.

**Comment by Sataniel98** [comment]
Hi,
I'm back and working a lot on DXL. If you are still interested in solving this issue, please let me know and reopen it :)
~ Best regards
