### ISSUE TITLE
Loot wonky

### ISSUE THREAD

**Issue by Flemse12** [DRE2N/DungeonsXL#257]
Me and my friend is making a dungeon and when we looted the dungeon with exact equal amount of loot (20) items we both got 10.

but when we looted it with an unequal amount 21, we both got 21

**Comment by Sataniel98** [comment]
I am almost sure equal or unequal numbers of items make no difference here.

**Comment by Flemse12** [comment]
No we tested on newest dev and last stable.

If equal amount of people in dungeon gotta split unequal amount of loot everyone just get full loot
