### ISSUE TITLE
Maven Install providing Corrupted JARs?

### ISSUE THREAD

**Issue by MarcatoSound** [DRE2N/DungeonsXL#260]
I've recently been trying to do a custom fork for the plugin, to make some adjustments and private bug fixes for a server I'm helping administrate, and have come across an error upon trying to compile the plugin. 

Upon using Maven Install... the following error is returned.

`[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: error reading C:\Users\Matthew\.m2\repository\io\github\dre2n\dungeonsxl-abstract\0.15.7-SNAPSHOT\dungeonsxl-abstract-0.15.7-SNAPSHOT.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Matthew\.m2\repository\io\github\dre2n\dungeonsxl-craftbukkit_1_11_R1\0.15.7-SNAPSHOT\dungeonsxl-craftbukkit_1_11_R1-0.15.7-SNAPSHOT.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Matthew\.m2\repository\io\github\dre2n\dungeonsxl-craftbukkit_1_10_R1\0.15.7-SNAPSHOT\dungeonsxl-craftbukkit_1_10_R1-0.15.7-SNAPSHOT.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Matthew\.m2\repository\io\github\dre2n\dungeonsxl-craftbukkit_1_9_R2\0.15.7-SNAPSHOT\dungeonsxl-craftbukkit_1_9_R2-0.15.7-SNAPSHOT.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Matthew\.m2\repository\io\github\dre2n\dungeonsxl-craftbukkit_1_9_R1\0.15.7-SNAPSHOT\dungeonsxl-craftbukkit_1_9_R1-0.15.7-SNAPSHOT.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Matthew\.m2\repository\net\milkbowl\vault\VaultAPI\1.5\VaultAPI-1.5.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Matthew\.m2\repository\org\bukkit\craftbukkit\1.10-R0.1-SNAPSHOT\craftbukkit-1.10-R0.1-SNAPSHOT.jar; error in opening zip file`

I have tried deleting and re-installing the files listed off several times, but to no avail. Is this a problem with the files Maven is grabbing online? Other JAR files seem to be working fine. (Citizens, commons, etc)

**Comment by Sataniel98** [comment]
Hi,
I cleared my local repo and tried to build it and it worked flawlessly for me, so I'm not sure why this happens. One file that is missing is craftbukkit-1.10-R0.1-SNAPSHOT.jar. You'll have to run BuildTools with --rev 1.10.2 to get it (you'll need all CraftBukkit jars from 1.9.2-1.11.2). Vault should work, the repo is available to me. And the DXL modules, well, aren't fetched online. Did you maybe try to build a module without the others or did you change the order of the repositories?
