### ISSUE TITLE
(Question) Edit without creative

### ISSUE THREAD

**Issue by jonatjano** [DRE2N/DungeonsXL#262]
Hi,
I wanted to know if it is possible to configure the plugin to make editing player in survival mode.
My objectives is to make players created dungeons by the use of their own ressources bought with money they gain/stole in others dungeons.
Is it possible ?
hope you can answer positively 😋 .

**Comment by Sataniel98** [comment]
Well, I never had something like this in mind, so no, I'm sorry. You may let your players build regular maps and import them to DXL with /dxl import, but they won't be able to make DXL signs without edit mode.

**Comment by jonatjano** [comment]
thank you for your reply.
I didn't thought of doing it like that but it's a really good idea, I need to find a way for the signs :p
Anyways for now our priority is to have a stable faction map so it'll take some time before we come to this. if by this time you've done something to solve my problem it would be perfect ^^.
Continue this plugins until the end it is awesome ;)

**Comment by Sataniel98** [comment]
Thank you, I'm busy with university at the moment but really looking forward to take this up again and work through the bug reports soon.
