### ISSUE TITLE
Imported map cannot edit

### ISSUE THREAD

**Issue by EZSeneiko** [DRE2N/DungeonsXL#263]
Downloaded a map into which i put into the dungeonsxl/maps/ and then did /dxl edit and /dxl list it is described as false

**Comment by Sataniel98** [comment]
Sorry... What?

**Comment by EZSeneiko** [comment]
I downloaded a map and placed it into the map folder found in the dungeons xl folder however when i tried to edit it using the /dxl edit command it said no dungeons found however when i do /dxl list it is recognized but it says false

**Comment by EZSeneiko** [comment]
Nvm i found out the issue
