### ISSUE TITLE
Questions regarding plugin :)

### ISSUE THREAD

**Issue by BytedByte** [DRE2N/DungeonsXL#265]
Hi, First off, the plugin looks amazing and also looks like it's the only Dungeon plugin that's up to date. But there's some things im wondering. So if i understood the plugin correctly u create a group, get in a dungeon lobby (where u select gear?) and then from there you join the dungeon through a sign.

What i'm looking for is simply just a way for a /dxt group to walk into portal and get teleported to the dungeon with their current gear and all. No signs or anything. Is that possible or are the signs a must? 
Also, the Lobby sign pic is broken but i saw another issue posted about that :D

**Comment by Sataniel98** [comment]
There are loads of game rules you can change in the respective scripts; one of them is called "keepInventoryOnEnter" and does exactly what you're looking for :) You do not need classes signs, even if you do not use keepInventory you can still let the users play without classes.
