### ISSUE TITLE
Creating a portal?

### ISSUE THREAD

**Issue by BytedByte** [DRE2N/DungeonsXL#266]
Hey, So is anything supposed to happen after selecting two corners after doing /dxl portal ?

I've tried multiple times creating portal but nothing happens. I have a dungeon along with a lobby inside it. But when creating a portal nothing happens. I get the "Portal created" message but there's just no portal there. Starting to get really confused with how this works 🤔

**Comment by Sataniel98** [comment]
Works well for me...

**Comment by BytedByte** [comment]
What are the requirements for a portal? Do i need to have a dungeon map up? Do i need a lobby before i can create it? Or is it supposed to just light up no matter what?
