### ISSUE TITLE
Lack of Clarity on MultiFloor Dungeons

### ISSUE THREAD

**Issue by MarcatoSound** [DRE2N/DungeonsXL#270]
Hey there! Me again.

I'm attempting to create a multifloor dungeon for the first time, and having trouble finding out where to put the "dungeon configuration." According to the wiki and the FAQ, it's:
> as simple as creating a dungeon configuration.

However, I've seen no indicator of where I'm supposed to place that dungeon configuration, nor how it behaves and interacts with maps. Does this mean that maps =/= dungeons, and if so, how does one determine the difference between a dungeon from a map in /dxl list?

Would really appreciate some clarification here. I adore this plugin, and it's not as buggy as you may think, but the documentation is what needs a lot of work still. ^^;;

**Comment by Sataniel98** [comment]
Excuse me, sometimes things seem to be so obvious to me when I design them that I don't realize that some basic information are missing for a user. I've fixed it. Dungeon configs go into their subfolder in "scripts" :)

**Comment by MarcatoSound** [comment]
Okay, thanks so much. x) That cleared it up. 

Also what can I do about dungeon floors showing up in "/dxl list" still while a dungeon script doesn't?

**Comment by Sataniel98** [comment]
/dxl list d shows the dungeons, /dxl list f the floors, /dxl list l all loaded instances and /dxl list defaults to /dxl list f.

**Comment by MarcatoSound** [comment]
Ahh, see I didn't know those sub-commands existed. x) Thanks!
