### ISSUE TITLE
Moving Items Around with 'keepInventoryOnEscape: False' removes them

### ISSUE THREAD

**Issue by MarcatoSound** [DRE2N/DungeonsXL#273]
Hey there! Discovered another problem with the keepInventory rules in dungeon configurations.

I recently discovered while testing out me and my teams latest dungeon that, with the dungeon on 
`keepInventoryOnEscape: true`
That moving items within your inventory and then leaving actually completely removes them from your inventory, even if they weren't acquired in that dungeon. They disappear. 

So, say I have a diamond sword in the first slot of my inventory when I enter a dungeon. When I go into the dungeon, it's still there, but I decide to move it to another slot, let's say slot 2. I realize as I'm playing I don't have time to finish the dungeon, so I use /dxl leave. However upon leaving, the diamond sword is completely gone. 

I'm guessing this has to do with the sword being registered as an item acquired in the dungeon once it gets moved.

**Comment by Sataniel98** [comment]
DXL doesn't register your items as acquired in the dungeon or something, it just saves your inventory when you join the dungeon and replaces it when you leave (if you set it up this way). Just to clarify: Did you use keepInventoryOnEscape: true as described in the text or false as described in the title?

**Comment by MarcatoSound** [comment]
Pardon me, my mistake. Meant to say "false" for both cases. 

But basically if it's set to "false" then when you escape/leave after moving stuff around while in the dungeon, I found items would actually disappear from my real inventory upon returning to the main world.

**Comment by Sataniel98** [comment]
So keepInventoryOnEscape is false and keepInventoryOnEnter is true? Doesn't make much sense to me. Players would be able to take items into the dungeon without risking them. I think DXL doesn't even save the inventory if keepInventoryOnEnter is true.

**Comment by Sataniel98** [comment]
Closed due to changes that have been done to the state reset system.
