### ISSUE TITLE
[Question] Keep durability lost in dungeon

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#274]
Hi,

For my dungeon, i want that player keeps their own stuff but, while loosing durability on their stuff, this have to be saved when they left dungeon. 

The problem is that they have to not keep the stuff that they collect in the dungeon :s 

Any clue on how to do this? 

Thx :)

**Comment by Sataniel98** [comment]
There is currently no way to achieve this :(

**Comment by Tiplish** [comment]
Ok np, thx for your answer :)

**Comment by Tiplish** [comment]
Hi, I think i don't need it anymore. Does it still usefull? Because now we could use the Keep inventory on exit and use the special tag on stuff which have not to be bring outside of the dungeon :p

**Comment by Sataniel98** [comment]
Hi,
I'm also thinking about dropping this feature. It doesn't seem to have many use-cases and is way harder to make than the dungeon item feature. Not tagging the items as personal items itself - but to give the feature a place logically alongside the current keepInventory game rules.
