### ISSUE TITLE
[Bug] Invulnerable in dungeon

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#275]
Hi,

I've a strange issue since i've add config to my dungeon. The mobs can't attack me (External mobs or vanilla). 

I'm OP on my server but i was in the correct mod (Survival or aventurer). The mobs can see me, come to me, hug me but never hit me. 

I use the latest official version of DungeonsXL. 

Maybe i've missed something?

**Comment by Sataniel98** [comment]
Maybe a spawn protection or something? DungeonsXL does not influence anything like this, especially not external mobs.

**Comment by Tiplish** [comment]
Ok thx, i will find a solution.

**Comment by Flashback083** [comment]
Hey ! i have this bug too, do you know how to fix it please @Tiplish ? :/

**Comment by Sataniel98** [comment]
It has nothing to do with DungeonsXL. It might be any other plugin, but I guess in 99% of the cases it's because you didn't set the spawn protection to 0 in the server.properties.

**Comment by Flashback083** [comment]
I make some test and i set 0 for spawn protection and im invulnerable even if i jump in lavaflow i dont take any damage :/ (also i take damage in main world but not in dunjeons)
I only use 
commandsxl-2.1.2
dungeonsxl-0.16-SNAPSHOT-01
Vault-1.4.1
plugins


I test too with spigot 1.11.2 with same plugin

*Edit 1 : I forgot to say but i cant hurt any mob too (everyone is invincible)*
*Edit 2 : I try to import map and the bug is still here*
*Edit 3 : I we create and editing a dungeon but do /gm 0 command, we can take damage and attack, if we save, leave and /dxl play <name> all mob and player are invincible*

**Comment by Flashback083** [comment]
I really need To understand why i have this bug, so if you have any idea :/

**Comment by Tiplish** [comment]
i haven't fix this already :( 

I'm OP on my server and only OP seems to have this problem. My dungeon is far away from spawn to avoid build protection on DXL edit map. 

Some question for you Flashback (we have to found what we have in common to get some clues about our problem :p )

- Are you OP on your server?
- Have you config files for your dungeon? This bug started when i have add this config ( maybe it comes from another thing, i don't know)
- If someone else (not OP) play in your dungeon, he is invincible?

I have leave aside this bug because i don't test dungeon my self (my team does it) and they don't have this problem.

**Comment by Flashback083** [comment]
I test with player non op and the bug is still here :c maybe /dxl play make a bug ?

**Comment by Tiplish** [comment]
Have you try to go in dungeon with group sign?

For my self, i'm the only one who is invulnerable in dungeon (haven't try with another OP player). 

Could you pastbin here your config file? I will compare our both file. 
Do you use a plugin to manage gamemode?

We will try to find in which case this bug appear before asking to Staniel to correct anything x)

**Comment by Flashback083** [comment]
Okok... i have somes few bugs, also i have 2 bugs i want to know if you have too or not : 
- When i die in dungeon, i have this error : https://pastebin.com/JUtEU7dP
- When a player clic on sign to start dungon only him is teleport to start point
Any idea ?
also, i test with my op user and it work but avoid to use portal command and sign group , juste /dxl play <name>

**Comment by Tiplish** [comment]
Maybe you should create new issues for this bugs. I can help you but resolve 3 differents in the same post, we will get mixed up...

For the moment, we are on the previous version of DungeonXL, we will upgrading soon at the next.

**Comment by Flashback083** [comment]
Yeah sorry ! 
Also, i forgot to use sign (in dungeons ) for the invulerability it seem work

**Comment by Tiplish** [comment]
What have you done exactly? Maybe it could solve my problem too :p what is the sign for invulnerability?

**Comment by Flashback083** [comment]
There are no sign, i just but the [start] sign in dungeon and when i click on it, i'm tp at start point and i become vulnerable

**Comment by Tiplish** [comment]
Ok, definitely, it's not the same problem as me :p

**Comment by Tiplish** [comment]
Hi, just to say that, i'm not invulnerable in dungeon anymore. I don't understand how because i haven't test a dungeon my self since many months now. 

So i close this :)

**Comment by Sataniel98** [comment]
Alright, thank you for letting me know.
