### ISSUE TITLE
Setup of Dungeon is incorrect

### ISSUE THREAD

**Issue by DoctorWhoFR** [DRE2N/DungeonsXL#277]
Hello, i want to create a multiple floor dungeon but i can't i have just copy paste the config in github 
but i have this error:
`The setup of dungeon test.yml is incorrect. See https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration for reference.`

My File: [CONVERTED IN TXT FOR UPLOAD]
[test.txt](https://github.com/DRE2N/DungeonsXL/files/1050446/test.txt)

**Comment by Sataniel98** [comment]
The floor count is zero which means zero floors will be played which doesn't make sense.

**Comment by DoctorWhoFR** [comment]
Not that i change this after my bug appear
