### ISSUE TITLE
Reward with Mythicmobs

### ISSUE THREAD

**Issue by iamadcat** [DRE2N/DungeonsXL#279]
Can i give a reward using MythicMobs in loot table?

**Comment by Sataniel98** [comment]
You can give any item and IXL can serialize any item.

**Comment by iamadcat** [comment]
hmm i did and i made a chest.
but it keeps saying like this.

![20170607003115](https://user-images.githubusercontent.com/16010851/26837567-b352be12-4b18-11e7-84b0-f13951ce2528.png)

loot table for test

0:
  # For more information about the Caliburn item serialization format,
  # please have a look at the Caliburn wiki:
  # https://github.com/DRE2N/CaliburnAPI/wiki/Custom-item-script
  item:
    ==: io.github.dre2n.caliburn.item.UniversalItemStack
    type: "CUSTOM_DEFAULT"
    material: "IRON_SWORD"
    durability: 35
    name: "&4CustomName"
    amount: 1
    lores:
     - "&4This is the first line."
     - "&6This is the second line."
    enchantments:
      "PROTECTION_ENVIRONMENTAL": 4
      "THORNS": 1
    attributes:
      name:
        type: "GENERIC_ATTACK_DAMAGE"
        slots:
          - "MAIN_HAND"
          - "HEAD"
        operation: "ADD_NUMBER"
        amount: 8.5
  # The loot chance in percent
  chance: 100.0

1:
  # This is the simple way to store items.
  # Valid input:
  # The first value may be any ID (be it a Vanilla ID or an ID of an ItemsXL item), 
  # the second value is the amount
  # and the third, optional value is the durability value.
  item: "261,1,16"
  chance: 100.0

2:
  # The Caliburn API also supports the usual Bukkit ItemStack deserialization format.
  # If you don't know how to use this and have ItemsXL installed,
  # put the item stack into your main hand and enter the "/ixl serialize" command.
  # You will find a valid, automatically generated YAML representation of your item
  # in the ItemsXL/serialized.yml file.
  item:
    ==: org.bukkit.inventory.ItemStack
    type: IRON_SWORD
    damage: 55
    amount: 1
  chance: 37.5
