### ISSUE TITLE
Races & Classes support/plug

### ISSUE THREAD

**Issue by ZoeticShade** [DRE2N/DungeonsXL#288]
I use a Races system already myself and don't desire to use the internal classes systems the dungeons have, how may I go about shutting it off from Dungeons plugin?

Additional I am having trouble allowing members to bring their own inventory in and out of the dungeons.

Any help on this would be appreciated.

**Comment by Sataniel98** [comment]
It will never be possible to disable the DXL groups, that's just not possible without rewriting major parts of the plugin. The best possibility would be a wrapper to create DXL groups automatically from Heroes, MCMMO, RaC or whatever plugin. But that's nothing I'll be working on in the next few months.

For the second thing, you just need to set the keepInventory game rules to whatever you want, for example keepInventoryOnEnter to true.

**Comment by ZoeticShade** [comment]
I have yet to see where that is sadly, where is that setting located?

**Comment by ZoeticShade** [comment]
Also if I may, where is the class system located in the plugins core folder files/code? If I may.

**Comment by Sataniel98** [comment]
The second is a DXL game rule, so you can set it in the default values section of the main config, in a dungeon config or in a floor config.

io.github.dre2n.player.DGroup

**Comment by ZoeticShade** [comment]
Okay huge thanks for all your help relating to this. It is much appreciated.

**Comment by Sataniel98** [comment]
Feel free to ask if you have further questions.

**Comment by ZoeticShade** [comment]
Okay so when I have looked around the only value I can find relating to
inventories is "OpenInventory" also I do not seem to get a per dungeon
config file to generate. Is there a special command or something to get per
Dungeon configs to appear?

**Comment by ZoeticShade** [comment]
Okay so a %dungeon name here%.yml file is needed in dungeons folder within scripts folder and the config file needs to start with configVersion: 1 as its top line, this much I have figured out.

How does the plugin desire me to enter it exactly for it to understand I desire people to be able to bring their over world inventory into the said dungeon? This is the only thing I have left to figure out and it should work for me perfectly from there.

**Comment by ZoeticShade** [comment]
Never-mind I was able to figure it out, HUGE suggestion is to leave a note on your dungeon config is to check the Floor config first so people aren't fooling with the Dungeon config all day ( like me ) thinking its through that to make these crucial setting changes.

**Comment by Sataniel98** [comment]
Hard to say which one "comes first" because dungeon configs have a section with overriding values and one with subsidiary ones. But yes, I think it should be clarified, especially because game rules aren't explained at the "getting started" page yet.

**Comment by Sataniel98** [comment]
See #91
