### ISSUE TITLE
Citizens Not Working properly

### ISSUE THREAD

**Issue by JennaDiamonds** [DRE2N/DungeonsXL#289]
I'm using citizens with sentinel to create custom enemies.
When using the ExternalMob sign, they spawn in thankfully.. But they keep zero stats and traits from my configs for citizens and sentinel.
When a citizens NPC is spawned, they are just ghosts :(

**Comment by Loivado** [comment]
Hi that's a duplicated issue: #235

**Comment by Sataniel98** [comment]
True. Thanks
