### ISSUE TITLE
1.12 Plan

### ISSUE THREAD

**Issue by iamadcat** [DRE2N/DungeonsXL#290]
do you plan to update your DungeonsXL Plugin to 1.12 version?

if you planned, approximatively, when you update it to 1.12 version? (spigot)

**Comment by Sataniel98** [comment]
Yes, I do. But I will do a good bit of cleanup stuff alongside the update. I plan to start working on it between July and September, depending on how well my new server runs. I've got more than ten original plugins I need to take care of, and then there are legacy plugins like FactionsOne. Especially FactionsXL has a higher priority than DungeonsXL. Besides that, DungeonsXL already works with 1.12.
See #282

**Comment by iamadcat** [comment]
@Sataniel98 Yeah I saw that. but i can't compile the version for 1.12(spigot). can you upload the dungeonsxl for 1.12 spigot?

**Comment by Sataniel98** [comment]
You shouldn't need to recompile anything...
