### ISSUE TITLE
1.12 for spigot

### ISSUE THREAD

**Issue by iamadcat** [DRE2N/DungeonsXL#291]
First of all, Thanks for your quick responding and great work.

As i said before, I can't compile at all because of errors.

Can you build the DungeonsXL version 1.12 for spigot?

I have to make a server with this plugin, but i'm stuck. please help me.

**Comment by Sataniel98** [comment]
As I said... DungeonsXL works with 1.12 without recompiling anything. Just these few things won't work:
- Caliburn API features (should still work with ItemsXL)
- Performance tweaks (async world loading)
- Title / action bar messages will be sent as centered chat messages
- ResourcepackAPI doesn't support 1.12

Recompiling with a recent version of Bukkit will change nothing. There's a pull request with a few things, but it goes a bit past these issues.

**Comment by iamadcat** [comment]
@Sataniel98 

but i have a error with 0.15.5 version.
if i should to use the version in pull request, i can't compile because of errors.
can you compile it?

![20170628111942](https://user-images.githubusercontent.com/16010851/27617851-df8f69f8-5bf3-11e7-8e99-a58e9a3b0b1f.png)

**Comment by Sataniel98** [comment]
Recent dev builds fully support versions up to 1.12.2.
