### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by iamadcat** [DRE2N/DungeonsXL#292]
Thanks for your support.

As you know I'm using DungeonsXL with 1.12.

Can't i use loottable using  the Caliburn item serialization format?

I wrote https://github.com/DRE2N/DungeonsXL/issues/281 this, is this the problem?

I want to give to player a custom items in random chance.

**Comment by Sataniel98** [comment]
DXL has been fully updated to 1.12 in the latest dev builds.
