### ISSUE TITLE
Signs not working!

### ISSUE THREAD

**Issue by S-Patel25** [DRE2N/DungeonsXL#295]
Hey! So, I made a dungeon with every sign that I need, and when I do /dxl test it works perfectly, but when I make a group sign for a GAME (like a play sign, not test), it doesn't work, like the signs don't register! Help please?

**Comment by S-Patel25** [comment]
Nevermind! Fixed the problem, but I have another one, I have a wave trigger (W 1) so that ALL mobs have to be killed, but when I start the dungeon, only about half the signs work? Why is that?

**Comment by DoctorWhoFR** [comment]
Do you have save "/dxl save" ?

Make sure before any test you have save your build with "/dxl save"

**Comment by S-Patel25** [comment]
Yes I did that

**Comment by DoctorWhoFR** [comment]
Make sure the sign is ok.

**Comment by DoctorWhoFR** [comment]
And try restart your server, don't forget that addon is wip

**Comment by S-Patel25** [comment]
The signs are perfect, and I restarted, reinstalled, and still doesn't work

**Comment by Sataniel98** [comment]
Did you start the game with a ready sign?

**Comment by S-Patel25** [comment]
Yes I did, so when I start the thing, it works fine, but only half the signs work, like all the mobs spawn, but when I get to about halfway, the signs are just there, they don't register as a dungeon sign

**Comment by S-Patel25** [comment]
Oh my god! I'm so sorry, I figured it out, but how do I set it so that they don't lost their inventory when they enter?

**Comment by S-Patel25** [comment]
Like a global setting, so that in EVERY map its that so they don't lose their inventory on entering?

**Comment by S-Patel25** [comment]
I also keep getting this in my console:
16.07 02:03:15 [Server] WARN Task #549300 for DungeonsXL v0.15.6 generated an exception
16.07 02:03:15 [Server] INFO java.lang.NullPointerException
16.07 02:03:15 [Server] INFO at io.github.dre2n.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:93) ~[?:?]
16.07 02:03:15 [Server] INFO at io.github.dre2n.dungeonsxl.task.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:66) ~[?:?]
16.07 02:03:15 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:15 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:15 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:15 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:16 [Multicraft] Skipped 59 lines due to rate limit (30/s)

**Comment by Sataniel98** [comment]
You can make settings globally if you add them to the default section in the main config. Concerning the error: Did you reload your server with /reload?

**Comment by S-Patel25** [comment]
Yes I did, and also, when I put that global setting for keep inventory, now when I go in, the dungeon doesn't work, and when I try to do anything now, it just says "internal error has occurred", I've tried restarting, which doesn't fix the problem?

**Comment by S-Patel25** [comment]
16.07 02:03:15 [Server] WARN Task #549300 for DungeonsXL v0.15.6 generated an exception
16.07 02:03:15 [Server] INFO java.lang.NullPointerException
16.07 02:03:15 [Server] INFO at io.github.dre2n.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:93) ~[?:?]
16.07 02:03:15 [Server] INFO at io.github.dre2n.dungeonsxl.task.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:66) ~[?:?]
16.07 02:03:15 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:15 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:15 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:15 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
16.07 02:03:16 [Multicraft] Skipped 59 lines due to rate limit (30/s)
That's the error I keep getting?

**Comment by S-Patel25** [comment]
what about the other error I put up?

**Comment by S-Patel25** [comment]
Also, every single time I put a game rule into the config, the plugin crashes, and I have to reinstall everything!

**Comment by S-Patel25** [comment]
The signs don't even register

**Comment by S-Patel25** [comment]
I'm sorry I keep bothering you, but there is another bug. I have a map called "cave". I wanted to create a new map and so I did /dxl create Castle, and upon doing so, it teleported me into my "cave" map, and whenever I edit the map, it affects it on both the castle and the cave, so when I did /dxl leave, and tried doing it again, the entire plugin crashed!
