### ISSUE TITLE
/dxl save cause a lot of RAM disk usage

### ISSUE THREAD

**Issue by KevinBaselTheAnalyst** [DRE2N/DungeonsXL#296]
Dunno why every time I do /dxl save dunno what happens but somewhere it generates something that occupies MB... Today I just took a look into 5 different maps, didn't add anything, typed /dxl save and when I backuped my server I've noticed that it's 1GB heavier... why that?

**Comment by KevinBaselTheAnalyst** [comment]
I have just notice that there is a backup folder that it's really heavy! Lot of backups are saved from the same map, is that normal? Can I delete all of them or should I keep only the lat one?! How does it work exactly?

**Comment by KevinBaselTheAnalyst** [comment]
The files are saved like this: **Level_1-1500067177018** and I also can't understand which one was the last....

**Comment by KevinBaselTheAnalyst** [comment]
I've solved how to find the oldest one, just tell me If I can delete all backups, or I need to keep all of them, or just need to keep the last one plz

**Comment by Sataniel98** [comment]
If you want backups or not is entirely up to you.
You can configure when DXL makes backups:
ON_DISABLE,
ON_DISABLE_AND_SAVE,
ON_SAVE,
NEVER

**Comment by KevinBaselTheAnalyst** [comment]
If I set to NEVER and the during some changes I run /dxl save, will it save new progress or not?

**Comment by Sataniel98** [comment]
It will still sync your resource world with its edit world instance.

**Comment by KevinBaselTheAnalyst** [comment]
Thx! It's solved for me!
