### ISSUE TITLE
Changing the place where you spawn when ending a dungeon ?

### ISSUE THREAD

**Issue by AdleyBro** [DRE2N/DungeonsXL#300]
Hi,

I want to make dungeons around the world which, when entering their respective entrances, automatically the game will teleport you to the dungeon with the command /dxl play [dungeon].

The problem here is when I end or leave the dungeon, because when leaving it you spawn at the last location you were right before entering. So, because of that, everytime I exit the dungeon I instantly go in again, because I spawn right where I entered (the entrance has a command block which executes the /dxl play when someone is in a radius). Is there a way to change the exit spawn/tp ? If not, would you add it ? Or is there any other solution ?

Thank you.

**Comment by Tiplish** [comment]
Hi, 

Have you try to use group sign? It's a better way, i think, to manage entrance of people in dungeon and limit the number of playing map you could have at the same time.

**Comment by AdleyBro** [comment]
That's not the problem I have. I tried it anyway tho and the problem is still there.

I'll try to explain the problem again: 

The entrance of the dungeon has a command block which executes /dxl play [dungeon], when someone activates that command block standing over a pressure plate, or just by standing within a radius, the player will start playing the dungeon. That's alright, but the issue here is when the player leaves the dungeon (dieing, by using /leave, or by ending the dungeon, no mather what)  because when you leave the dungeon, you spawn at the last location, which in this case is the pressure plate or the radius where you get teleported to the dungeon. That makes someone to be stuck in the dungeon by exiting and entering constantly. 

That's why I need a way to spawn them to a different location when finishing the dungeon, or something like that.

**Comment by Sataniel98** [comment]
Can't you add a short cooldown to your dungeons?

**Comment by AdleyBro** [comment]
If you mean to add the config.yml file to the map, I tried to do it by setting "timeToNextPlay: 1" knowing that 1 is 1 hour.

The file seems to work since the console gives no error and the title and subtitles appear. But the cooldown doesn't work and I still enter the dungeon.

**Comment by AdleyBro** [comment]
Ok, I was testing it the wrong way. The cooldown works. I was testing it as an Admin and not as a regular player, that's why the cooldown didn't work. 

Sry :P

I will use that method then.
