### ISSUE TITLE
Is there a way to restrict players from taking items from item frames ?

### ISSUE THREAD

**Issue by AdleyBro** [DRE2N/DungeonsXL#301]
Hi,

I like to use item frames to indicate certain things, or just for decoration. But I don't want players to be able to take the items that are inside. Is it possible to deny that ?

Thank you.

**Comment by Sataniel98** [comment]
I agree, it should be forbidden if players can't break blocks.

**Comment by AdleyBro** [comment]
Well, the config file is set to not let them break blocks. Yes, they can't break blocks, but they're still able to take the items from the frames.

**Comment by Sataniel98** [comment]
I know. It seems I didn't have them in mind when I programmed the build / destroy game rules. That's definitely something to add. That's what I meant: It should be forbidden to take items from frames when players are not supposed to break / place blocks. But it's not at the moment. Thank you for bringing it to my attention :)

**Comment by Tiplish** [comment]
Is it possible to let player take items from item frame but to not break block? I think 2 differents options could be better when we want to let player take item from frame in adventure mod :p

**Comment by Sataniel98** [comment]
If you're in adventure mode, you don't need the block protections anyway, do you?

**Comment by Tiplish** [comment]
Maybe i haven't understand what you will add. To be clear, i would that when player interract with frame in adventure mod (my default mod for dungeon), i would choose if they could interract with item frame or not (i haven't understand if, when player can't break block, they will not interract with frame too).
