### ISSUE TITLE
Sign doesn't update

### ISSUE THREAD

**Issue by Kidoy** [DRE2N/DungeonsXL#303]
When a player in the dungeon leave the server, the respective sign doesn't update and says that the dungeon is full

**Comment by Sataniel98** [comment]
Do you kick players from the dungeon when they leave the server?

**Comment by Kidoy** [comment]
No. Should it be automatic?

**Comment by Sataniel98** [comment]
No

**Comment by Kidoy** [comment]
How could I solve that?

**Comment by Sataniel98** [comment]
Modify the timeUntilKickOfflinePlayer gamerule. I recommend to do this in the default section of the main config sothat it is set globally.

**Comment by Kidoy** [comment]
I did it but it doesn't work.
This is the general config.yml:
----------------------------
configVersion: 13
language: english
enableEconomy: false
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- WHITE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
announcementInterval: 30.0
sendFloorTitle: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
tweaksEnabled: false
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
  editCommandWhitelist: []
backupMode: ON_DISABLE_AND_SAVE
editPermissions: []
default: {}
timeUntilKickOfflinePlayer: 10
-----------------------------------------
Anyway what the opposite of "keepInventoryOnEnter: true" for when they leave the dungeon...? There isn't in the wiki.

**Comment by Sataniel98** [comment]
It's not inside the default section. The opposite of keepInventoryOnEnter: true is keepInventoryOnEnter: false of course xD

**Comment by Kidoy** [comment]
So what's the default section? Ahahahahah

Yeah of course... but if I want leave items on enter and when they drop something in the dungeon they keep that item when they leave too?

**Comment by Sataniel98** [comment]
The line that says "default: {}" is a map where you can put all game rules. Like
```
default:
    rule: value
```
keepInventoryOnEnter: true
keepInventoryOnEscape: true
keepInventoryOnFinish: true
And optionally
keepInventoryOnDeath: false

It's all in the wiki

**Comment by Kidoy** [comment]
Ok thank you. Last question (I hope). In timeUntilKickOfflinePlayer: 10 ; "10" is seconds?

**Comment by Sataniel98** [comment]
Yes
