### ISSUE TITLE
the portal problem

### ISSUE THREAD

**Issue by rutk2u04** [DRE2N/DungeonsXL#305]
when I use /dxl portal  into dungeon, My inventory Item would be clear, Can't get back.
I have use floor config and dungeon config, it still have this problem, I need help !! pls!!

**Comment by Sataniel98** [comment]
Sorry... what?

**Comment by rutk2u04** [comment]
When I into portal to lobby ,and my item will be clear,I use keep inventory all condition true

**Comment by Sataniel98** [comment]
Then provide some detailed information about your setup and environment, please.

**Comment by rutk2u04** [comment]
Sorry my poor English, when I use /dxl play <dungeon> that player's item will keep , and use  /dxl portal then use portal to <dungeon> ,the player's item disappeared,  I don't know what happened.

**Comment by rutk2u04** [comment]
Sorry, I am solve that by myself, thanks
