### ISSUE TITLE
How do you create a level?

### ISSUE THREAD

**Issue by Stegoleopluradon** [DRE2N/DungeonsXL#306]
I've been trying to find out how to create a level and have tried many different things, but none seem to work. Is a level created using /dxl create?

**Comment by Sataniel98** [comment]
In which context did you read anything about levels?

**Comment by Stegoleopluradon** [comment]
I'm trying to make a MFD

**Comment by Sataniel98** [comment]
Just create each level as a separate instance (/dxl create, /dxl edit) and add a dungeon script to link them together. That's it.

**Comment by Stegoleopluradon** [comment]
How would I add a dungeon script?

**Comment by Sataniel98** [comment]
https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration <- This _is_ basically an MFD
