### ISSUE TITLE
How do I correct use of announcement

### ISSUE THREAD

**Issue by r0last** [DRE2N/DungeonsXL#307]
http://wx4.sinaimg.cn/mw1024/6d4a5b82gy1filwdh3i9fj20c6024745.jpg
http://wx1.sinaimg.cn/mw1024/6d4a5b82gy1filwdhdpxrj20ak07nt8k.jpg

I do not know how to use it correctly...

**Comment by Sataniel98** [comment]
You can use any text for the broadcast message. The GUI is broken in recent Minecraft versions because the player count / group is currently displayed using the item amount and 0 amounts don't work anymore...
