### ISSUE TITLE
were i can found maps for the dungeon?

### ISSUE THREAD

**Issue by FuaHwis** [DRE2N/DungeonsXL#310]
i tried to see in here plugins--->dungeonxl------>maps and i cant see any map...do i have to download any maps?

**Comment by Sataniel98** [comment]
DungeonsXL/maps is the folder where all the raw resource worlds for the instances you built are saved.

**Comment by FuaHwis** [comment]
i mean how i wil load a map in my world?

**Comment by FuaHwis** [comment]
does maps file have maps from its own?

**Comment by FuaHwis** [comment]
or i have to build my own maps?

**Comment by Sataniel98** [comment]
Yes, of course. DungeonsXL is just a tool to instantiate worlds.

**Comment by FuaHwis** [comment]
ok thanks
