### ISSUE TITLE
Spieler können Blöcke abbauen!

### ISSUE THREAD

**Issue by Steiniiii** [DRE2N/DungeonsXL#314]
Guten Abend,

ich bin mir nicht sicher ob, ich hier richtig bin, für Fragen / Probleme, allerdings habe ich nirgends anderswo was gefunden wo ich fragen könnte.

Ich habe folgendes Problem, Spieler können in der Spielsitzung im Dungeon Items abbauen, obwohl in der Config Build auf false steht. Ich habe unten die Config eingefügt.

Das merkwürdige ist, Spieler können abbauen aber nicht platzieren? Was mache ich falsch?

Bitte um Rückmeldung.

Vielen Dank schon jetzt für die Bemühungen.

Gruß und einen schönen Sonntag.

invitedPlayers:
- Steiniiii

# You can force a game type sothat the game type defined by a ready sign gets overriden.
#forcedGameType: DEFAULT

# Time until a player is kicked from a dungeon after going offline (in seconds)
# -1 = never / 0 = immediately
timeUntilKickOfflinePlayer: 120

# If the Lobby is disabled. This applies only to Dungeons that have to be solved alone and where there are no classes to choose from.
isLobbyDisabled: false

# Time until you can play a Dungeon again (in hours)
timeToNextPlay: 20

# Time until a player can get loot for another time
timeToNextLoot: 20

# Time until a new mob waves begins when enough mobs are killed.
#timeToNextWave: 10

# Dungeons can be played with a timer.
# If the group has no time left, the players get kicked.
#timeToFinish: 240

#The game mode, SURVIVAL if nothing
#gameMode: ADVENTURE

# PvP
playerVersusPlayer: false
# Friendly fire refers just to members of the same group
friendlyFire: false

# These commands can be used by all players if they are in the dungeon.
# DXL commands like /dxl leave are included by default.
#gameCommandWhitelist:
#  - version
#  - f list
#  - f show
#  - ch global

# MAKE SURE YOU EDIT THIS PART!
# One of these Dungeons must be finished ("any" for any dungeon). If you do not want any, leave this empty.
#mustFinishOne:
#  - any

# All of these Dungeons must be finished. If you do not want any, leave this empty.
#mustFinishAll:
#  - jumpinjackflash
#  - highwaytohell
#  - wontgetfooledagain

# Max time in hours after the last finish of one of the Dungeons above
#timeLastPlayed: 336

# A list of requirements
#requirements:
#  feeMoney: 7.5
#  feeLevel: 2

# Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: false
# Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: true
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: false
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: false

# If players can build and destroy blocks in this world.
build: false

# Amount of lives a player initially has when he enters a dungeon
initialLives: 12

# Messages also to be created with /dxl msg
message:
  '1': ARRR ich rieche es! Das Gold in dieser Burg! 
  '2': Die Burg ist sicher gut bewacht! Aber was ist schon einfach! Einfach ist was für Landratten! Wir sind Piraten! Erkunde die Burg und töte die Soldaten des Königs!
  '3': Erkunde alles sorgfältig und schaue dich in Ruhe um.
  '4': Klapper Ratsch, Quietsch, das Tor geht auf!
  '5': Soldaten des Königs! Auf Sieeeee! Zum Angriff!
  '6': Puh, die Soldaten sind keine leichten Gegner...
  '7': Verdammt, auch diese Tür ist verschlossen. Suche den Schlüssel!
  '9': Schau dich in den Häusern um, vllt findest du den Schlüssel in einer Truhe
  '10': In dem Hinteren Haus könnte der Schlüssel sein...
  '11': Ja, hier bist du richtig!
  '12': Oh Gott! Oh Gott! Oh Gott! Ein Ungläubiger! Ans Kreuz damit!
  '13': Fertig gerüstet? Dann auf, es ist nicht mehr weit zur Schatzkammer des Königs
  '14': Welche ein Glück, da hat wer den Schlüssel stecken lassen.
  '15': Das Gitter wurde heruntergelassen, finde den Betätigungsschlüssel.
  '16': Finde einen Weg in den Keller!
  '17': RASSSSSSSSEL! Das Gitter geht hoch!
  '18': Attackeee! Töte den König!
  '19': Gruselig und kalt hier unten ...
  '20': Mit einer hervorragenden Schwert Kombo, ringst du den König nieder und besiegst ihn.
  '21': Mit dem Tod des Königs öffnet sich ein Geheimer Gang...

  
# Items you cannot drop or destroy
secureObjects:
- 70
- 69

# Classes to choose from
# Possible enchantment names: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Encha
classes:
  Krieger:
    items:
    - 306,1
    - 307,1
    - 308,1
    - 309,1
    - 267,1
    - 366,1
  Barbar:
    items:
    - 306,1,THORNS/3
    - 311,1
    - 258,1
    - 304,1
    - 364,2
    - 366,1
    - 320,4
  Bogenschütze:
    items:
    - 261,1,ARROW_FIRE/1
    - 262,64
    - 262,64
    - 302,1
    - 303,1
    - 304,1
    - 305,1
    - 320,3
    dog: true
  Assassine:
    items:
    - 267,1,DAMAGE_ALL/5
    - 262,32
    - 261,1,ARROW_KNOCKBACK/2
    - 373/14,2
    - 298,1
    - 299,1
    - 300,1
    - 301,1
  Magier:
    items:
    - 314,1
    - 299,1
    - 300,1
    - 301,1
    - 373/16428,16
    - 373/16421,16
    - 373/16449,2
    - 373/16394,2
    - 373/2,2
    - 364,8
    - 268,1,FIRE_ASPECT/1
mobTypes:
  Gorah:                 
    minecraftType: zombie
    baby: false
    health: 40
    armor:
      hand: 267
  siSchutze: 
    minecraftType: skeleton
    baby: false
    health: 40
    armor:
      hand: 261
  Spifey: 
    minecraftType: spider
    baby: false
    health: 20
  siWache: 
    minecraftType: zombie
    baby: false
    wither: false
    health: 80
    damage: 12
    armor:
      head: 302
      breast: 303
      feet: 305
      legs: 304
      hand: 267
  siKing: 
    minecraftType: skeleton
    baby: false
    wither: true
    health: 120
    damage: 40
    armor:
      head: 314
      breast: 315
      feet: 317
      legs: 316
      hand: 283

**Comment by Sataniel98** [comment]
Versuch am besten nicht die ganze Floorkonfiguration zu kopieren. Ansonsten kopier ich einfach mal, was ich auf meinem Profil geantwortet hab:

"build" ist eine alte Game Rule, die es in den neueren Versionen nicht mehr gibt. Sie wurde durch "breakBlocks" und "placeBlocks" ersetzt. Dazu gibt es noch speziellere Regeln und ein paar mehr sind auch noch angedacht.

**Comment by Steiniiii** [comment]
Guten Morgen,

Okay vielen Dank werde ich ausprobieren.

Gruß

**Comment by Steiniiii** [comment]
Guten Morgen, 

ich habe es nun ausprobiert, allerdings besteht das Problem nachwievor. So sieht nun meine Config aus:

# You can force a game type sothat the game type defined by a ready sign gets overriden.
invitedPlayers:
- Steiniiii
timeUntilKickOfflinePlayer: 120
isLobbyDisabled: false
timeToNextPlay: 20
timeToNextLoot: 20
playerVersusPlayer: false
friendlyFire: false
keepInventoryOnEnter: false
keepInventoryOnDeath: true
keepInventoryOnFinish: false
keepInventoryOnEscape: false
breakBlocks: false
placeBlocks: false
initialLives: 12
message:
  '1': ARRR ich rieche es! Das Gold in dieser Burg!
  '2': Die Burg ist sicher gut bewacht! Aber was ist schon einfach! Einfach ist was für Landratten! Wir sind Piraten! Erkunde die Burg und töte die Soldaten des Königs!
  '3': Erkunde alles sorgfältig und schaue dich in Ruhe um.
  '4': Klapper Ratsch, Quietsch, das Tor geht auf!
  '5': Soldaten des Königs! Auf Sieeeee! Zum Angriff!
  '6': Puh, die Soldaten sind keine leichten Gegner...
  '7': Verdammt, auch diese Tür ist verschlossen. Suche den Schlüssel!
  '9': Schau dich in den Häusern um, vllt findest du den Schlüssel in einer Truhe
  '10': In dem Hinteren Haus könnte der Schlüssel sein...
  '11': Ja, hier bist du richtig!
  '12': Oh Gott! Oh Gott! Oh Gott! Ein Ungläubiger! Ans Kreuz damit!
  '13': Fertig gerüstet? Dann auf, es ist nicht mehr weit zur Schatzkammer des Königs
  '14': Welche ein Glück, da hat wer den Schlüssel stecken lassen.
  '15': Das Gitter wurde heruntergelassen, finde den Betätigungsschlüssel.
  '16': Finde einen Weg in den Keller!
  '17': RASSSSSSSSEL! Das Gitter geht hoch!
  '18': Attackeee! Töte den König!
  '19': Gruselig und kalt hier unten ...
  '20': Mit einer hervorragenden Schwert Kombo, ringst du den König nieder und besiegst ihn.
  '21': Mit dem Tod des Königs öffnet sich ein Geheimer Gang...
secureObjects:
- 70
- 69
classes:
  Krieger:
    items:
    - 306,1
    - 307,1
    - 308,1
    - 309,1
    - 267,1
    - 366,1
  Barbar:
    items:
    - 306,1,THORNS/3
    - 311,1
    - 258,1
    - 304,1
    - 364,2
    - 366,1
    - 320,4
  Bogenschütze:
    items:
    - 261,1,ARROW_FIRE/1
    - 262,64
    - 262,64
    - 302,1
    - 303,1
    - 304,1
    - 305,1
    - 320,3
    dog: true
  Assassine:
    items:
    - 267,1,DAMAGE_ALL/5
    - 262,32
    - 261,1,ARROW_KNOCKBACK/2
    - 373/14,2
    - 298,1
    - 299,1
    - 300,1
    - 301,1
  Magier:
    items:
    - 314,1
    - 299,1
    - 300,1
    - 301,1
    - 373/16428,16
    - 373/16421,16
    - 373/16449,2
    - 373/16394,2
    - 373/2,2
    - 364,8
    - 268,1,FIRE_ASPECT/1
mobTypes:
  Gorah:
    minecraftType: zombie
    baby: false
    health: 40
    armor:
      hand: 267
  siSchutze:
    minecraftType: skeleton
    baby: false
    health: 40
    armor:
      hand: 261
  Spifey:
    minecraftType: spider
    baby: false
    health: 20
  siWache:
    minecraftType: zombie
    baby: false
    wither: false
    health: 80
    damage: 12
    armor:
      head: 302
      breast: 303
      feet: 305
      legs: 304
      hand: 267
  siKing:
    minecraftType: skeleton
    baby: false
    wither: true
    health: 120
    damage: 40
    armor:
      head: 314
      breast: 315
      feet: 317
      legs: 316
      hand: 283

**Comment by Steiniiii** [comment]
Version vom Plugin ist DungeonsXL v0.11.3

**Comment by Sataniel98** [comment]
0.11.3 ist so uralt, ich weiß nicht mal mehr, was dabei überhaupt funktioniert.

**Comment by Steiniiii** [comment]
Gibt es dann bereits neuere Versionen von dem Plugins für die 1.8.8? Oder ist die bei mir geladene Version, die einzigste mögliche Version für die 1.8.8.

Auf jeden Fall schon mal in großes Danke für deine Bemühungen :)

**Comment by Sataniel98** [comment]
Ich konzentriere mich nicht mehr auf 1.8.x- und 1.7.x-Unterstützung. Das heißt, [einige Features fehlen](https://github.com/DRE2N/DungeonsXL/wiki/legacy-support). Aber die Situation war auch damals schon nicht anders. Die neuen Versionen sollten mit 1.8.x nicht schlechter laufen als DXL 0.11.x.
