### ISSUE TITLE
open door

### ISSUE THREAD

**Issue by Tippolo** [DRE2N/DungeonsXL#317]
Hi
is there any other way (es. block sign) to open door?
or only with interact sign?
thank's a lot.
tip

**Comment by Sataniel98** [comment]
Depending on the situation, you can do this with redstone and a trigger until the block closes the current.

**Comment by Tippolo** [comment]
OK...thank's a lot
the block sign is for other purpose i think... 
but in the interact sign, in future version, try to put an item (button or other) so the sign in play mode look like a button but has the same funcion as interact sign...
thank's a lot
