### ISSUE TITLE
classes

### ISSUE THREAD

**Issue by Tippolo** [DRE2N/DungeonsXL#318]
Hello,
I start to put classes in dungeon:
I create a demo.yml file like this:

#Name of the Classes
Demo:
  #Items the Class has on the beginning
  items:
  #Item-Id/data, count, enchantment name/lvl
  - 268,1
  - 276,1
  - 302,1
  - 303,1
  - 304,1
  - 305,1
  - 364,1

and put it in the script/classes directory. Then start the server and in the lobby room I create a classes sign like this:
[Classes]
Demo
save the edit session, leave the edit session and start play.
when I click in the classes sign, nothing happen and in the consolle nothing appear wrong.

Where I'm going wrong?

thank's a lot.
Tip

**Comment by Sataniel98** [comment]
Take care of indents and restart your server
