### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by xRetu** [DRE2N/DungeonsXL#319]
Hi, 
i tried to use tutorial function, but its not working for me and other players. 
I created new world, I added all needed signs and few random with messeges etc. 

it's my config file: 
_tutorial:
    activated: true
    dungeon: tutorial
    startGroup: default
    endgroup: player

Im using Authme plugin, can it have any effect on it? 
I think i did everything well. 
Thanks for your help.

**Comment by Sataniel98** [comment]
There shouldn't be an issue with AuthMe. I've never used it, but I can't imagine why. Did you delete your player data before testing it? Players who already played at the server at least one time will be excluded from the tutorial.
