### ISSUE TITLE
Sign spawning 3 mobs instead of only 1

### ISSUE THREAD

**Issue by AdleyBro** [DRE2N/DungeonsXL#321]
Hi,

I want to make a boss room. For that, a [Redstone] sign will transform into a redstone block when someone is near. That redstone block will trigger some command blocks in order to spawn particles and trigger another sign at the end of the circuit. That last sign is a [Trigger] sign which will trigger an [ExternalMob] sign in the room, spawning the boss.

The problem here is, for some reason, it spawns 3 bosses instead of just 1. The sign is marked this way:
[ExternalMob]
-BossName-
1,1,MM
T 1   --> "1" is the ID

I don't understand why that happens. I have other [ExternalMob] signs which are triggered by Distance and are working perfectly. But it seems that using the "Trigger" trigger makes it work differently ? 

I already checked a lot of times the signs to be sure there isn't any mistake in the writing.

**Comment by Sataniel98** [comment]
I can't say for sure it is not a bug at the moment. I'm currently collecting issues on a to do list for the next release and will definitely have a look at this.

**Comment by AdleyBro** [comment]
Ok, so I just tried to move the sign just one block away and now it spawns only one boss as I wanted ! What a dumb solution lol

I thought of changing the position of the sign because knowing that the plugin creates and saves his own map of the dungeon, and seeing that for some reason, while editing the dungeon, sometimes it would appear to be more than just one "DXL_Edit" world in my server folder, I thought it might be some kind of bug which would mix all those worlds together, making the sign spawn 3 bosses instead of just 1 ??? It might not be that the problem because the other signs triggered by distance in the same dungeon always worked fine. But when I needed to remove all the Mythic Mobs from the dungeon, sometimes there were removed more mobs than it should, because normally there are 9 mob in total but then I removed even 20 in some cases ! 
I always use /dxl save and /dxl leave after every single modification just to be sure nothing breaks up.

Anyway, I resolved the problem. Hope this information can help you for something...

**Comment by Tiplish** [comment]
Another clue, sometimes in keep in memory an old save. Example :  
You put a sign to call 3 mobs. You test. You edit again and replace to get only 1 mob. If you test, you could get 3 mobs... Don't really know why.

So everytime i want to test a change i do this : 
Start a play 
Go to end
Start a play again

Usually, my last change are saved in this last play :)

**Comment by Tiplish** [comment]
Another thing a bit strange :
When i use Mythicmobs, it doesn't spawn 3 mobs instead of 1. It seems appear only with native mobs :s
