### ISSUE TITLE
Loot Tables?

### ISSUE THREAD

**Issue by Eboss34** [DRE2N/DungeonsXL#322]
I have no idea how to work the loot tables or make them work
I have read the page on them about 1000 times and just dont understand it.

Can anyone help?

Thanks in advance,
Eboss34

**Comment by Sataniel98** [comment]
Well what exactly is the thing you don't understand?

**Comment by Eboss34** [comment]
@Sataniel98 
If I use the /ixl serialize command, do I just paste the outcome into a notepad and turn it into a YAML file and put it in the loot table scripts or what? I have tried to copy/paste the example and then change it to my own liking but it still doesn't work. Do you have an example that already has the item set that you can send me, just so I can use something as a better reference?

Thanks

**Comment by Sataniel98** [comment]
[There are examples in the wiki.](https://github.com/DRE2N/DungeonsXL/wiki/scripts#loot-tables)

Make sure to adjust the indents sothat they match the loot table script.

**Comment by Eboss34** [comment]
@Sataniel98 
Ok so this it the yaml file i have made and it says its good and works with the signs and chests but when i finished the dungeon there is nothing to get from the rewards gui
[new 2.txt](https://github.com/DRE2N/DungeonsXL/files/1347730/new.2.txt)

i know it is a text file on here but thats just because it wouldn't let me upload a yaml file

**Comment by Sataniel98** [comment]
Note that TABs are invalid in YAML

**Comment by Eboss34** [comment]
@Sataniel98 
I fixed the tab and still dont get the items when i replaced the file and restarted the server

**Comment by PLHfor3** [comment]
I'm having the same problem. Set up the loot table and then when I went in-game when I click the chest it gives no loot. 
[standard.txt](https://github.com/DRE2N/DungeonsXL/files/1350447/standard.txt)

**Comment by PLHfor3** [comment]
Sataniel, I used the example, and your not hearing him, so hid he. When you click the chest it still doesn't work.

**Comment by Sataniel98** [comment]
Are you using DXL 0.15.x with Minecraft 1.12 or another unsupported version?

**Comment by PLHfor3** [comment]
I am on Minecraft 1.10 (Running Spigot)

**Comment by Eboss34** [comment]
I am on Minecraft 1.12 running your latest version.

**Comment by Eboss34** [comment]
@Sataniel98 I'm not trying to be pushy but was just wondering if you were maybe working on the issue I am having. Just wondering

**Comment by Sataniel98** [comment]
FPlayers.i.get()... You'll need to have a look at the source code. FactionsUUID for example renamed a lot of methods.

**Comment by PLHfor3** [comment]
So what are supposed to do. How bout that answer

**Comment by Eboss34** [comment]
@Sataniel98 So I need to go and check the source code and look for what and change what?

**Comment by Eboss34** [comment]
@Sataniel98 Actually I think I may have an idea on what your taking about. I'll try a few things and then get back to you. Thank you for your help so far.

**Comment by Sataniel98** [comment]
Sorry, that was intended for a different issue. I have no idea why I posted this here.

**Comment by Eboss34** [comment]
Oh haha. Your all good

**Comment by Eboss34** [comment]
So do you have any other ideas why ours aren't working?

**Comment by Sataniel98** [comment]
I've just tried it myself. The loot doesn't appear in the initial loot inventory that opens automatically for me but it's inside the /dxl rewards inventory. I have just coded a util for inventories with multiple pages for another project of mine a few months ago, I'll use it to rewrite this.

**Comment by Eboss34** [comment]
Ok cool. Thank you so much. Do you think you could send me the script you used? And then just let me know when you are finished using the other code stuff? That would be great.

Thanks again

**Comment by Sataniel98** [comment]
Well, I used the ones the two of you sent me ^^ I just fixed the TABs. If you have problems understanding the syntax of YAML, you can use an online parser like http://www.yamllint.com/ that tells you when you do something wrong. It can't figure out DXL specific stuff of course, so feel free to ask again. But it shouldn't be too hard anyway if you use IXL to serialize and take care of the indents.

**Comment by Eboss34** [comment]
Ok cool. Thanks

**Comment by Sataniel98** [comment]
Loot inventories are recoded as of DungeonsXL 0.16 build no. 5, so please test if it works well for you. /dxl rewards has been removed because it's of no use anymore.

**Comment by PLHfor3** [comment]
@Sataniel98 I have a totally different problem. When I click a Chest in the dungeon it does nothing. It doesn’t add anything to my reward inventory. And then at the end the rewards is also empty and I even do the dxl rewards command and nothing is there to. I think the main problem is that the chests aren’t giving the loot either.

**Comment by Sataniel98** [comment]
That must be because of erroneous scripts or maybe because of external influences, which is not likely to be the case.

**Comment by PLHfor3** [comment]
Could you possibly take a look at my loot table above. I included it in a previous post. I’m using DXL 0.15.6

**Comment by Eboss34** [comment]
@Sataniel98 so I have tryed to put the 0.16 version into a java file and it hasn't worked. Am I supposed to download it from somewhere else or could you do that or what? Sorry

**Comment by Sataniel98** [comment]
Pre-compiled dev builds are available here: http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/ You can build them yourself by downloading the source and running the build.bat file if you have Apache Maven installed.

@PHLovesCU I did and it works fine for me since I fixed the TABs.

![](http://fs5.directupload.net/images/171006/wbzv4rsx.png)

**Comment by PLHfor3** [comment]
I pasted it into a yaml checker and it said ok. Where do I fix the tabs?

**Comment by Eboss34** [comment]
@PHLovesCU 
did you get the new version?

**Comment by PLHfor3** [comment]
No I’m using 0.15.6.

**Comment by Sataniel98** [comment]
What exactly happens if you open the chest? Does it open an inventory or does it just nothing? Do level and money rewards work for you?

**Comment by PLHfor3** [comment]
I click the chest and it just says in chat “have been added to your reward inventory”. It doesn’t open an inventory it just doesn’t add anything. The levels and money work correctly.

**Comment by Sataniel98** [comment]
Could you post a screenshot of how the chest and sign look like?

**Comment by PLHfor3** [comment]
![7ab250f5-3447-4f1a-8c3b-3eddca73d467](https://user-images.githubusercontent.com/32468763/31310474-a2ffddbe-ab5e-11e7-85ea-ab1ea1bd25bc.jpeg)

**Comment by Sataniel98** [comment]
I don't see anything wrong there to be honest, maybe try to replace the sign to make sure the data is saved correctly.
