### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by DogiWF** [DRE2N/DungeonsXL#323]
I want to make a function like this:
When a player places the block at the [Place] sign, console writes some certain commands.
For example, player places the stone and then console writes "//pos1 500,5,500 and //pos2 501,5,501 and finally //set 0" so blocks at those coordinates disappear and comes back when dungeon ends. Is it possible? If it is, how can I do it?

Or should I use command blocks? Like the block will be a pressure plate and there will be command blocks underneath which will write those commands. But if I do it, when the dungeon ends those blocks wont come, right?

**Comment by Sataniel98** [comment]
You can use a command sign with CommandsXL to do this, but a command block would of course be possible as well.

**Comment by DogiWF** [comment]
So the map can reset after the game ends?

**Comment by Sataniel98** [comment]
The map is always at the state that you saved, then copied and instantiated.

**Comment by DogiWF** [comment]
Got it, thank you.
