### ISSUE TITLE
dungeonsxl custom config error

### ISSUE THREAD

**Issue by georgegxb** [DRE2N/DungeonsXL#325]
everytime that i make a config file for my dungeon on the dungeon folder im using for example on the config Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true etc i reload the plugin and everything stops working so i need to delete the plugin and folder and install it again so the plugin can work. i dont know what im doing wrong ?

**Comment by Sataniel98** [comment]
There are several possibilities:
- You're using /reload or a plugin that reloads plugins dynamically which is not supported
- Your config is erroneous
- Other plugins cause problems with DXL
...and a few more. Anyway, it would be helpful if you could show me your whole config files and tell me where exactly you put them.

**Comment by georgegxb** [comment]
dungeonsxl/maps/mydungeon im using the /dxl reload and for a reason it can save my server i get a error for a season.lock

**Comment by georgegxb** [comment]
im using the /dxl reload and for a reason it can save my server i get a error for a season.lock

**Comment by Sataniel98** [comment]
And the content?

**Comment by georgegxb** [comment]
what you mean ?

**Comment by Sataniel98** [comment]
What you wrote into the file

**Comment by georgegxb** [comment]
Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true

**Comment by Sataniel98** [comment]
Can you upload the file as a whole or put the exact content into a `code box` sothat I can check the formatting?

**Comment by georgegxb** [comment]
do you want me to upload the config file that i made here so you can see it ???

**Comment by Sataniel98** [comment]
Exactly

**Comment by georgegxb** [comment]
[file.zip](https://github.com/DRE2N/DungeonsXL/files/1381063/file.zip)
i just made a externalmob sign with citizens and for a reason all the signs are not working when i click the sign to join a group im trying to leave it by clicking the other sign that i made [dxl] leave but is not working

**Comment by georgegxb** [comment]
its because im using 15.2 ? and not the 0.16  ?

**Comment by Sataniel98** [comment]
Even though it doesn't make much sense to me to change just one keepInventory game rule, this looks technically correct. Updating to the latest version is of course recommended. Do you get any errors? Are the signs set up correctly with the correct permissions or by an OP? Did you include all necessary lobby signs?
