### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by Lucatortuga9** [DRE2N/DungeonsXL#332]
im new with this plugin , and i cant create a dungeon, the wiki is not useful, can i have a step by step guide?

**Comment by Sataniel98** [comment]
That would be the wiki?

**Comment by Lucatortuga9** [comment]
yes but it's very difficult, the start  and checkpoints are not working, i have a start point and 4 checkpoints but when the dungeon starts they are teleported to the last checkpoint

**Comment by Sataniel98** [comment]
You probably didn't include a trigger in the last line of the sign or one that triggers automatically. Try to add a distance trigger like "D 5" in the last line.

**Comment by Lucatortuga9** [comment]
yeah thanks, and how can i make multiple dungeons?, the portal is the same right? how can i let them choose which dungeon?

**Comment by Sataniel98** [comment]
Add a group sign.

https://github.com/DRE2N/DungeonsXL/wiki/signs#global-signs
