### ISSUE TITLE
Get rid of deprecated methods to make DXL ready for 1.13

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#333]
Get rid of:
- [x] Old Material enum values
- [x] Block data values
  - [x] LockedDoor
  - [x] TeamFlag
  - [ ] PlaceableBlock
  - [x] RedstoneTrigger
  - [ ] BlockSign
  - [ ] DEditPlayer
  - [ ] DPortal
  - [ ] GameSign
  - [x] GroupSign
- [x] Entity#fromName() etc.
  - MobSpawnTask
  - DMob
- [ ] Old SkeletonType
  - DMobType
  - MobSpawnTask
- [x] LivingEntity#getMaxHealth(); LivingEntity#setMaxHealth(double health)
  - DGamePlayer
  - DGlobalPlayer
  - DInstancePlayer
  - DPlayerData
  - DMobType

1.8 compatibility:
- EntityEquipmanet/HumanEntity#getItemInHand(); EntityEquipmanet/HumanEntity#setItemInHand(ItemStack item); ... 
  - DGamePlayer
  - PortalCommand
  - GlobalProtectionListener
  - DMobType
  - DMob
  - MobSpawnTask
- Magic value dye
  - DColor#getWoolData()
  - TeamFlag
DVs:
- [x] Numeric material IDs
  - PlaceableBlock
  - HologramSign
  - BlockSign
  - DMobType
- [ ] Remove /dxl deleteportal command (-> /dxl break)
- [ ] Remove MythicMobs signs (-> ExternalMob)
- [x] Remove support for 1.7.x and 1.8.x (-> 1.9+ :P)

Do **not** get rid of:
- Bukkit#getOfflinePlayer(String name) - No replacement available; not likely to get remove
- Internal deprecated methods - That's to be done later

**Comment by Tiplish** [comment]
Hi,

Is it the all list that you have identified as main incompatibility with the next Minecraft update and DXL? Or there could be a lot of unidentified incompatibility due to the 1.13?

**Comment by Sataniel98** [comment]
I did this in November; about two months before the first API preview was published. Thus, it's completely speculative. I'm almost sure that's everything though, and even if it's not, further breakages wouldn't increase the work load significantly. To be honest, testing the affected things with all of the versions it's supposed to work with is likely to be more of a hassle than the actual programming. The update may be huge for Spigot and Minecraft from a technical point of view, but it really isn't much trouble for DXL. Spigot will provide some legacy support, so DXL might work fine without any adjustments at all. But even then, I'll clean the code up a bit.

**Comment by Tiplish** [comment]
Great news, thanks for information :) i'm developper too and i've seen a lot of technical chance/add in the 1.13 vers but i wasn't able to figure how it will impacte development and so, the delay before a release of our favorite plugin whith 1.13 support. 

Have a nice day o/

**Comment by Sataniel98** [comment]
This commit resolves a good bit. However, I still need to do something in regard to usage of block DVs.
