### ISSUE TITLE
Players cannot leave if being ridden by an entity

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#336]
I have this slime made with MM which mounts its target until somebody doesn't kill it. Our players noticed that if you try to leave while being ridden, it says you that you left, yet you remain stuck inside the dungeon and if you die, you lose the whole inventory, no matter what floor/dungeon configuration you have regarding inventories. 

A solution could be a simple check: IF ridden by an entity THEN don't execute the command :)

**Comment by Sataniel98** [comment]
Fixed in DRECommons 4.2 (DXL 0.16).
