### ISSUE TITLE
Rewards occasionally do not trigger upon completion of a dungeon

### ISSUE THREAD

**Issue by MarcatoSound** [DRE2N/DungeonsXL#337]
Title says it all, 

Many of my players have been discovering that completing a dungeon, half the time the rewards screen does not pop up, and other times it has a long delay before doing so, making it so players are completing dungeons and getting locked out of them via cooldown, but not getting the rewards.

**Comment by Sataniel98** [comment]
I'm afraid but that's not enough information to reproduce the problem. The reward inventory doesn't have any kind of delay; it opens when the player moves. This ensures for example that the inventory doesn't open while he is inside a portal.

**Comment by MarcatoSound** [comment]
Oh I had no idea that's what made it pop up. Does it cancel if the player stays still for too long?

**Comment by Sataniel98** [comment]
No, that shouldn't make a difference.
