### ISSUE TITLE
DXL Commands aren't working

### ISSUE THREAD

**Issue by TPG0908** [DRE2N/DungeonsXL#338]
For a couple days now the dxl on mine and my friends server has stopped working, whenever we type commands nothing comes up at all, we are running 1.8.8 and the plugins we have are AsyncWorlgInjector, ItemEditor, WorldEdit, CrazyEnchantments, TimTheEnchanter, HealthBar, Essentials, BattleTracker, GroupManager, ClearLag, SimpleRename, PlotSquared, Broadcaster, XPMultiplier, Votifier, Marriage, Multiverse-Core, Worldguard, AdvancedPortals, AsyncWorldEdit, SuperTrails, Shopkeepers, ChestRestock, MythicMobs, EssentialsProtect, EssentialsChat, TimeIsMoney, EchoPet, EssentialsAntiBuild, PlayerVaults, GAListener, DailyRewards, EssentialsSpawn, BloodInMinecraft, PlayerMarkers, KitsCreator, LagspikeDetect, CombatTagPlus, HolographicDisplays, CratesPlus, DungeonsXL
I have tried fixing it by removing some plugins we got after DXL but this has been a hassle since I've been having trouble accessing the server files recently, any help is appreciated. Thanks.

**Comment by Sataniel98** [comment]
Any errors when the server starts?

**Comment by TPG0908** [comment]
Not that me or the owner are aware of, no.

**Comment by Sataniel98** [comment]
If nothing comes up at all, that usually means the plugin didn't load properly. Perhaps because of bad error handling with some corrupted data. But I can't help you without any hint at all what happened. Maybe you can have a look at a startup log again. The plugin might also be marked red if you run /plugins.

**Comment by TPG0908** [comment]
It does appear green but ill ask the owner to look into seeing if there's any problems with the plugin loading.

**Comment by TPG0908** [comment]
When we checked the console we found out this
[22:06:47 ERROR]: Error occurred while disabling DungeonsXL v0.15.6 (Is it up to date?)
java.lang.NullPointerException
It wasn't set to be disabled then we looked and found the server doing this
[22:06:47 INFO]: [DungeonsXL] Disabling DungeonsXL v0.15.6

**Comment by TPG0908** [comment]
Found a fix... owner got the most recent version instead of a 1.8 version, this is what i have to deal with. xD Thanks for the help. :)
