### ISSUE TITLE
ExternalMobs not working

### ISSUE THREAD

**Issue by TPG0908** [DRE2N/DungeonsXL#339]
Okay since we got the right version whenever I try to make an external mob spawn it has failed with no message like it's not a dungeon sign and I'm not sure what to do? Any help?

**Comment by Sataniel98** [comment]
It'd help if we knew what exactly fails.

The first thing would be if the sign is registered correctly. Do you have the necessary permissions to place DXL signs (dxl.sign.mob)? Does it disappear when you test the dungeon? Is the external mob provider registered properly or one of the default ones (Citizens, CustomMobs, MythicMobs)? And then: Does the sign turn into air when the ready sign is triggered? Or does it turn into a sign with an error message? Is the ExternalMob sign triggered properly, e.g. with a distance trigger? Is there a message from DXL or the provider plugin in the log?

**Comment by TPG0908** [comment]
Yeah I have permissions to place dungeon signs but when i type everything in it doesn't register as an actual dxl sign, when I test it stays there as a normal sign, I get no error message it just acts like the command doesn't exist, I'm going to try get more recent versions of dxl to see if its because it wasn't added in the version we have.

**Comment by Sataniel98** [comment]
What exactly did you type?

**Comment by TPG0908** [comment]
[ExternalMob]
SkeletalScout
5,15,MM
D 15

**Comment by TPG0908** [comment]
Fixed the problem i finally got files access i just needed a more recent version.
