### ISSUE TITLE
Group requirements bug

### ISSUE THREAD

**Issue by Kuriji** [DRE2N/DungeonsXL#34]
The [classes] sign doesn't expand to the right as stated before. This is a bug. (PS I figured out how to use the classes in the map config, but that should be stated in the wiki.

Edit: Also When I put keepInventoryOnDeath: true it still drops items.

Edit: ALSO when I put up the XML Group signs, Everyone but me cannot use it. "You do not meet the requirements to join this group." Even though I have no requirements set. 

If any of this is unclear, please let me know in the comments. I won't get offended

This post went from requesting permissions. (Found after a little digging.) To 'why aren't signs working?'

**Comment by Sataniel98** [comment]
I didn't write the article about signs - I have no idea why it says they'll expand. It has never been like that. Your issue with the group signs is most times a result of trouble with the must finish sections. I'll try to reproduce the second issue.

**Comment by Kuriji** [comment]
I haven't set any must-finish requirements, that's the problem.

Also my build is 0.11 SNAPSHOT.

**Comment by Kuriji** [comment]
So I've set myself to the default and not operator. I cannot find anything that says it requires anything. Here is my config.yml inside /plugins/dungeonsxl
http://pastebin.com/AsNduufH

here is the config.yml inside dungeonsxl/maps/DungeonofDoom

http://pastebin.com/E8bMCf06

Just dropping some additional info to see if we can fix this.

**Comment by Sataniel98** [comment]
Okay, I fixed the keepInventoryOnDeath bug (dev build will be out soon), but I can't reproduce the group bug :(

**Comment by Kuriji** [comment]
Would there be anything in the config.yml that would cause it?

Just to clarify:
When we use the sign [xml] group Dungeon x,x,+ it says that the requirements aren't met for the dungeon. I don't see any way for there to be requirements.

EDIT: If I'm an operator, it allows me to do so.

**Comment by Kuriji** [comment]
Any updates on this problem? Should I try using a different version?

**Comment by Sataniel98** [comment]
Didn't even turn on my computer since last week because of exams :C
