### ISSUE TITLE
Cant find where to create loot tables

### ISSUE THREAD

**Issue by TPG0908** [DRE2N/DungeonsXL#340]
I'm trying to set up a loot table for my dungeon and when i look for where to create them I cant find the scripts folder, so I'm not sure where to actually put the loot table.
The folders i do have are dungeons, languages, maps but not scripts?

**Comment by Sataniel98** [comment]
No idea why. The scripts folder is created just like the others when the plugin starts.

**Comment by TPG0908** [comment]
Should I create it manually then? I didn't want to initially in case I broke everything.
