### ISSUE TITLE
[Suggestion/Question] Monster arena with only 1 boss

### ISSUE THREAD

**Issue by maxlehot1234** [DRE2N/DungeonsXL#342]
Hi, I just want to know if it was possible, inside an arena to put ONE mythicmobs OR ONE https://www.spigotmc.org/resources/%E2%98%9B-boss-unbelievable-custom-monsters.46497/ boss.

Players can simply enter the arena or do any command to join it and fight against the boss. The boss will be different each time the arena start to add a difficulty thing in it :P 

Let me know how I can do this if it was possible ;)

Thank you so much

**Comment by Sataniel98** [comment]
All custom mob plugins that have a spawn command with X, Y, Z and world parameters are supported. You can of course spawn just one mob. Maybe link it to the end sign with a mob trigger. The randomization can be achieved for example with redstone. So yes, I think it should be possible.

**Comment by maxlehot1234** [comment]
Achieved with redstone? How?




lundi 18 décembre 2017 08:21 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by Sataniel98** [comment]
I'm not an expert if it comes to redstone. There are YT tutorials though. You can trigger signs with redstone using a redstone trigger (R).

**Comment by Tiplish** [comment]
You could use redstone to active a command_block which summon thanks to a command inside :)

**Comment by Sataniel98** [comment]
@Tiplish That's possible, too, but mobs spawned by a command block instead of a dungeon sign will not be recognized as DXL mobs. This might cause mob triggers etc. not to work as expected.

**Comment by Tiplish** [comment]
Yes but he doesn't specified anything about triggering the boss with DXL o/ That's why i suggest it.

Isn't it possible for dxl to trigger a Mythimob spawned with /mm mobs spawn instead of only DXL sign? Just a question, i know that it's not a common feature :p

**Comment by Sataniel98** [comment]
Well technically, an external mobs sign does nothing but running a spawn command with the respective parameters and checking the area where it was spawned for the mob to track it. You can of course do the same but without the area check with a command block.

**Comment by Tiplish** [comment]
Where is specified the area? Is it possible to be outside of this area if we moved the boss from his spawn point? (I'm a bit curious :p)

**Comment by Sataniel98** [comment]
The area is specified by the position of the sign. One sole check is done in the same tick when the mob is spawned to fetch it. The mob is then registered as a "DMob" by DXL and can for example be used by mob triggers.
