### ISSUE TITLE
Mob Trigger issue

### ISSUE THREAD

**Issue by Phoenixmrn** [DRE2N/DungeonsXL#343]
Im sorry for opening 2 at the same time but though this issue leads to the next, i dont believe its a direct cause.

I use Block signs to make barrier blocks that turn to air so players cannot continue until they have completed the objectives.
I have noticed that, when using the Wave trigger or Mob trigger, if the killing blow is dealt by a non-player the trigger doesnt count the death.

**Comment by Sataniel98** [comment]
Thank you for your reports.

**Comment by Phoenixmrn** [comment]
Sorry, for clarity i tried wave first, then switching to just Skeleton, then finding the best success with mythic mobs FireSkeleton. However using a single named mob as the trigger still showed the issue, if a skeleton shot it last the mob death wouldn't register.

**Comment by Sataniel98** [comment]
See #343
