### ISSUE TITLE
[Question] How to lock the ice melt

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#348]
Hello,

When my team build some dungeon, the ice melt destroy some build (example: an ice cavern o/).

Is it possible during an edit to lock the ice melt?

Any clue? 

Thanks :)

**Comment by Sataniel98** [comment]
Not yet. I mean, you could use a plugin to change the biome.

**Comment by Tiplish** [comment]
There is a biome where, when you put a light, a ice block will not melt? Sorry, we just facing this problem :(

**Comment by Sataniel98** [comment]
Wouldn't it stay ice if it is in a Cold Taiga biome or something similarly cold?

**Comment by Tiplish** [comment]
Not if there is a light :( but we have found a solution. 

We use a special scripte in denizen which is able to perform a command as a player/server/op. 

Everytime a player spawn, he triggs a serie of command block thanks to a pressure plate which change game rules, times AND worldguard flag (like Ice-melt DENY). When you change de Ice-melt flag, you could stop de melt of the ice when there is light. 

It's not the best way but it works, even if the map is alwas different. o/

**Comment by Sataniel98** [comment]
Wow, I actually didn't know that. Glad to hear you found a solution.

**Comment by Tiplish** [comment]
Maybe i could close this issue? Because, honestly, i think it's not a priority feature and if you have to choose to develop something, it could be a compatibility with worldguard which is more global than just solve the ice melt problem :p 

As you want. And also, thanks for your fast reply as alwas ;)

**Comment by Sataniel98** [comment]
Keeping it open shouldn't hurt though even if the issue won't be adressed in the forseeable future.
