### ISSUE TITLE
[Feature] Put a tag/lore to prevent get out the dungeon with specific item

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#351]
Hi,

I'm not sure that is not already possible but an idea was to implement a lore on the item that the player have lore "Dungeon item". 

The goal is, when the player leave the dungeon, every item which is tagged with "Dungeon item" will be removed from his inventory. 

With this feature, it is possible to go in the dungeon with our inventory and then leave with an used stuff (no infinite potion for example and you have to repair your armor after).

**Comment by Sataniel98** [comment]
I really like the suggestion.

**Comment by Sataniel98** [comment]
Done. This feature will be included in DXL 0.17.
