### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sowelipililimute** [DRE2N/DungeonsXL#353]
This is probably really simple, but I searched through the entire Wiki, the entire configs, and much more. How do I set a cooldown?

**Comment by Sataniel98** [comment]
Like, a cooldown to make it so that players can only play a dungeon once every X hours? That would be the "timeToNextPlay" game rule. This for example will set a cooldown of six hours:

```
timeToNextPlay: 6
```

Read more [here](https://github.com/DRE2N/DungeonsXL/wiki/game-rules).
