### ISSUE TITLE
setting up a custom configuration for a SFD.

### ISSUE THREAD

**Issue by kuohsuanlo** [DRE2N/DungeonsXL#354]
As title, I've tried many possibilities to create a simple config file but still can't get it done.
My path of the config file is right. My dungeon name is world_dragon
in file 
plugins\DungeonsXL\scripts\dungeons\world_dragon.yml
`
keepInventoryOnEnter: true`
`configVersion: 1
`
Only two lines.

But the plugin output an error with 
`[18:33:55 INFO]: The setup of dungeon world_dragon.yml is incorrect. See https:/
/github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration for reference.`

But the file is for multi-floor dungeon. Could you provide an SFD config file for us?

I've found the same issue track on https://github.com/DRE2N/DungeonsXL/issues/325
but is it not informative enough in the thread, so I post again. Thanks.

**Comment by Sataniel98** [comment]
Single floor dungeons don't require a dungeon config, they are created automatically at runtime per map. Try to add your game rules to the respective floor config instead.

**Comment by kuohsuanlo** [comment]
respective floor config means 
`plugins\DungeonsXL\maps\world_dragon\config.yml` right?
 I made it work. But it's not mentioned in the wiki, instead one of your in the issue track response.

**Comment by Sataniel98** [comment]
That's correct. It says so in the example floor config in the wiki: "# Floor configuration of DungeonsXL (config.yml in DungeonsXL/map/%mapName% folder)".
