### ISSUE TITLE
[Question] Set /dxl leave as a "end" possibility

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#355]
Hi,

There is a way to set the command /dxl leave as if the player end the dungeon? For example proc the timer before do the dungeon again? 

Thx :)

**Comment by Sataniel98** [comment]
If I understood it correctly, no. /dxl leave always makes the player quit the game without finishing the dungeon. An alternative might be to add more end signs or to have one with a use item trigger triggered by an item the player always has.

**Comment by Tiplish** [comment]
You understood correctly :) so if we want that the player, when he left the dungeon, wait the next play time (24hours for example specified in the config of the dungeon), he has to trigger a end sign and we have to block the /dxl leave command that's right?

**Comment by Sataniel98** [comment]
Yeah. You might want to set timeUntilKickOfflinePlayer to -1 sothat players don't bypass it by leaving the server.

**Comment by Tiplish** [comment]
Mmmh ok. Could it be a feature option that if someone use /dxl leave, it starts the playtime timer?

/dxl leave is very usefull if someone is stuck but player could use it to do the dungeon again

**Comment by Sataniel98** [comment]
I understand your point, but couldn't you just use keepInventoryOnEscape: false to fix this?

**Comment by Tiplish** [comment]
The problem was not the inventory but the timer :p 

We have a dungeon which give path choice. If the player could use /dxl leave and go back again in the dungeon, he could try many path in one day. I want that he has to assume a choice :)
