### ISSUE TITLE
Config Datei wird nicht erstellt. Map wird nicht als Dungeon angezeigt

### ISSUE THREAD

**Issue by DuPleXFD** [DRE2N/DungeonsXL#36]
Hallo^^

Probiere grade das Plugin aus. Es funktioniert auch soweit gut dennoch kann ich keine einstellungen an der config vornehmen die zb erlaubt das spieler mit eigenen inventar das dungeon betreten. auch weiss ich nicht wie ich mehrere ebenen erstellen kann ;/ . zu guter letzt wird der dungeon nicht als solcher angezeigt wenn ich bspw den befehl /dxl help eingebe. 

meine spigotversion: 1.9 aktuellstes build
alle derzeitigen plugins:

AdvanceAchivments
AuctionChest
AutoMessage
citizens-2.0.17-SNAPSHOT
commandsxl-2.1.2
dungeonsxl-0.11-SNAPSHOT-23
dynmap-2.3-alpha-1
Essentials-2.x-SNAPSHOT
EssentialsChat-2.x-SNAPSHOT
EssentialsSpawn-2.x-SNAPSHOT
HolographicDisplays
iConomy
LogBlock
LWC
MoneyThief
Multiverse-Core-2.5
Multiverse-Inventories-2.5
Multiverse-Portals-2.5
PermissionsEx-1.23.4
PVPLogoutEqualsDeath-0.7
PvpTitles
RegionForSale_2.6
ScoreboardStats
ServerSigns
Shopkeepers
Vault
WorldBorder
worldedit-bukkit-6.1
worldguard

**Comment by Sataniel98** [comment]
Es sollen eigentlich nur die Config-Dateien erstellt werden, die zwingend benötigt werden. Da man für Floors normalerweise nicht unbedingt etwas konfigurieren muss (vor allem bei kleinen Projekten) und die Daten dann einfach aus dem Default-Part der globalen config.yml genommen werden können, wird auch nicht automatisch eine Ebenenkonfiguration erstellt. Die kannst Du allerdings selbst anhand des Beispiels im Wiki einfügen. Ebenen werden über Config-Dateien im DungeonsXL/dungeons-Ordner hinzugefügt (mehr dazu im Wiki).

**Comment by DuPleXFD** [comment]
bei mir steht in der config datei nichts. nur ganz oben config version: 1
was mir auch aufgefallen ist, ich als spieler sehe im chat keine updates für event. zb [DBX]zombie greift an etc. also ich habe mich lange durch dein wiki gekämpft xD . es ist schon sebsterklärend aber am anfang nicht ganz ersichtlich wie es funktioniert. und wie erstelle ich nun floors ? :D

**Comment by Sataniel98** [comment]
Ich weiß, die Dokumentation ist etwas dürftig :/ Es ist aber eigentlich nicht so schwer:
1. Du erstellst eine Dungeon-Datei unter DungeonsXL/dungeons. Der Name der Datei ist der Name des Dungeons, die Endung .yml.
2. Du fügst die Maps hinzu, die der Dungeon beinhalten soll. Beispiel: https://github.com/DRE2N/DungeonsXL/wiki/dungeonkonfiguration
3. Das war's. Gelistet werden Dungeons unter /dxl list d. Betreten kann man die Dungeons mit /dxl play d [Dungeon] oder per Group-Schild, wobei die Zeile mit der Anzahl der Gruppen und Spieler noch ein ",+" erhält.

Aber ja, das mit der leeren Haupt-Config ist ein Fehler. Danke für die Meldung :)
