### ISSUE TITLE
Is it possible to make dungeon under nether or the_end environments?

### ISSUE THREAD

**Issue by kuohsuanlo** [DRE2N/DungeonsXL#362]
As title, is it possible to make dungeon under nether or the_end environments?

**Comment by Sataniel98** [comment]
Sure, you can use any world. Just copy it into the maps folder or use /dxl import.

**Comment by kuohsuanlo** [comment]
What I mean is not the map region file. I mean the environment is 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.Environment.html
, which will affect the sky, dragon AI, time setting, compass etc.

Because I have a ender dragon dungeon, however the dragon AI seems broken in overworld (known minecraft bug). Dragon would only stay in a place with END environment.

**Comment by Sataniel98** [comment]
I didn't realize this isn't saved in the world itself ^^"

**Comment by Sataniel98** [comment]
This should fix it. As of .16 build 11, there's a new setting for floor configs to set a custom world environment.
