### ISSUE TITLE
Out of the dungeon, What items I got became airHow can I keep What items I got?

### ISSUE THREAD

**Issue by qingshufan** [DRE2N/DungeonsXL#363]
The question is similar to the title!
For example,
Before I entered the dungeon, there was an iron sword.
Then I went into the dungeon and got a pork.
Then leave the dungeon and the pork becomes air, but the iron sword exists.

**Comment by Sataniel98** [comment]
This is because your keepInventory game rules are set up wrongly, or rather paradoxically. If you set keepInventoryOnEnter to true, it makes no sense to set keepInventoryOnFinish to false.
```
# Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true
# Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: false
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: true
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: true
```

**Comment by qingshufan** [comment]
Oh Thank you for Sataniel98.The question solved

**Comment by Sataniel98** [comment]
Glad I could help
