### ISSUE TITLE
Sound sign

### ISSUE THREAD

**Issue by koca2000** [DRE2N/DungeonsXL#366]
Hi,
is there a sign for playing sound? I found SoundMsg sign in documentation, but there is no usage.

**Comment by Sataniel98** [comment]
Yes, that does indeed exist. To be honest, I kind of forgot about this. It used to be a [Spoutcraft](https://dev.bukkit.org/projects/spoutcraft-plugin) only feature but could easily be done with Vanilla Minecraft nowadays. I'll add recoding it to my to do list.

**Comment by Sataniel98** [comment]
Sound signs have been readded in build 595. The wiki is updated :)
