### ISSUE TITLE
Map Requirements not being met but are still able to go through

### ISSUE THREAD

**Issue by arnhav** [DRE2N/DungeonsXL#367]
Apologies for being a bother again, however I was testing the latest snapshot of the plugin and came across a peculiar issue. I am using the `feeMoney` requirement for entrance into a dungeon and when the player has the money it deducts the amount from the player and allows them through, however even without having the money required the ready sign allows the player through. Additionally, it seems that the `timeToNextPlay` is not working either. I have it set to 2 (2 hours) and it allows the player back in almost immediately. Thank you for your time!

**Comment by Sataniel98** [comment]
I'd like to clarify that timeToNextPlay only stops the player from entering the dungeon when he finished it. If he leaves for example with /dxl leave, he can play again immediately. Is it possible that permissions allow the player to bypass the requirement?

**Comment by arnhav** [comment]
Ah I see, the player was leaving before finishing the dungeon. Is it possible to change that requirement so that the timer begins as soon as you leave a dungeon regardless of whether or not you finished the dungeon?

**Comment by Sataniel98** [comment]
You are not the first one who asked that and it does make sense to me to prevent the players from having infinite tries to finish the dungeon without delay. But I'd like to keep a setting that allows delays only if the dungeon is finished correctly. I'd add a new game rule that allows delays after fails, but something like that is not a high priority task at the moment.

**Comment by arnhav** [comment]
Alrighty, thank you. As for the `feeMoney` requirement? Any idea as to why that allows you through even though you don't have the money?

**Comment by Sataniel98** [comment]
Not sure ATM. I'll try to reproduce and fix that within the next 24-36 hours.

**Comment by Sataniel98** [comment]
I was indeed able to reproduce a few issues with requirements:
* The level requirement doesn't work well with keepInventoryOnEnter
* The permission node dxl.ignorerequirements allows players to start the game even if they don't fulfill the requirements. However, they are still demanded, which is confusing.

Is it possible that you tested this with the dxl.ignorerequirements permission node?

**Comment by arnhav** [comment]
Ah yea, that was probably the case.... I didn't realize that I had the permission node. And I probably got confused by the messages in chat. Thank you.

**Comment by Sataniel98** [comment]
@arnhav11 
> Ah I see, the player was leaving before finishing the dungeon. Is it possible to change that requirement so that the timer begins as soon as you leave a dungeon regardless of whether or not you finished the dungeon?

Has been added in build 598 now!
