### ISSUE TITLE
can have multiple dungeons on 1 single MC map.

### ISSUE THREAD

**Issue by mexbotdude** [DRE2N/DungeonsXL#369]
Hi, I've just download the plugin and read the getting started and I really like it, I just wanna know if I can have multiple dungeons on 1 single map.
and if a group is playing a dungeon, are other people to play the dungeon as well (at the same time) by their own group or are they required to wait until the previous group finish the dungeon?

**Comment by Sataniel98** [comment]
DungeonsXL is a system for dynamic world instantiation. It is by design impossible to have multiple dungeons in one map. Because of that, groups of course do not need to wait until others are finished. They just get their own instance.

**Comment by mexbotdude** [comment]
ok, in that case if there are 10 dungeons being played at the same time, isnt that very laggy. Tecnically they are running 10 worls + the main one

**Comment by Sataniel98** [comment]
Not in my experience. I'm running a huge 16k * 10k* main map, so there are few to no chunks that are permanently loaded anyway. Performance-wise, I don't see a difference between teleporting to an unloaded place in the main world or teleporting into a dungeon instance. If you don't wish to have an unlimited amount of dungeons loaded, you can set the maxInstances setting to something that suits your setup.

**Comment by mexbotdude** [comment]
so for a specific dungeon I should only import the specific chunks for each world?

**Comment by Sataniel98** [comment]
No, why? The chunks that are far away from a player shouldn't be loaded. It might decrease the time to copy the map, though, but as long as the resource world isn't a giant file, that will probably make no difference.
