### ISSUE TITLE
Mob sign spawns unlimited mobs if not triggered on new wave start.

### ISSUE THREAD

**Issue by koca2000** [DRE2N/DungeonsXL#370]
When I have Mob sign disabled using triggers and finish wave and then activate them, they will start spawning mobs infinitely.

**Comment by koca2000** [comment]
I also noticed that trigger stops spawning, but mobs that should be spawned if sign would be triggered are counted to wave.

**Comment by Sataniel98** [comment]
What sign setup exactly does this refer to?

**Comment by Sataniel98** [comment]
Possibly a duplicate of #321

**Comment by koca2000** [comment]
I don't thing so. The problem there is that mob sign will start spawning unlimited number of mobs when restone trigger was disabled and now become enabled.

**Comment by Sataniel98** [comment]
Why do you think that the trigger is important for the amount of mobs spawned?

**Comment by koca2000** [comment]
When I don't use it, it works fine. When I use that trigger, it starts spawning mobs and never stops.

**Comment by Sataniel98** [comment]
OK and what exactly are you doing? How do your signs look like?

**Comment by koca2000** [comment]
Mob sign:
[Mob]
Zombie
5,1
R

Wave sign:
[Wave]
1.5
false
W 1

**Comment by koca2000** [comment]
I have more mob signs there, two are enabled at start, three are disabled. After two waves I enable those disabled signs using redstone and they start spawning mobs infinitely

**Comment by Sataniel98** [comment]
I assume this is a duplicate of #475
