### ISSUE TITLE
Turning off classes/not changing inventories when entering dungeon

### ISSUE THREAD

**Issue by Gelox1209** [DRE2N/DungeonsXL#371]
Is there a way to turn off classes and not have to choose one, and keep their inventories when entering dungeons? If not can you add a way to?

**Comment by Sataniel98** [comment]
Does this help you? https://github.com/DRE2N/DungeonsXL/wiki/faq#how-can-i-make-it-so-that-players-play-dungeons-with-their-own-items

**Comment by Gelox1209** [comment]
Yes thank you very much!
