### ISSUE TITLE
Group/Leave signs not working as intended.

### ISSUE THREAD

**Issue by bsickinger** [DRE2N/DungeonsXL#372]
A player is able to click a second group sign while already in a group.  Sometimes after clicking a group sign it says you are not in a group and forces you to use another while your name stays on the first sign.

After exiting a dungeon, the group sign a party occupied does not always revert back to a join group sign. instead says dungeon in progress still.

![2018-04-22_02 41 16](https://user-images.githubusercontent.com/38603605/39092584-d14d76c8-45d6-11e8-8591-cb5e4617ca2c.png)

**Comment by bsickinger** [comment]
This is on spigot 1.12.2 I've tried on both version 0.15.6 and dev build 0.16 with the same results.

**Comment by Sataniel98** [comment]
That's true. Global signs need a major rewrite. That won't happen in the near future though (at least not by me) :(

**Comment by bsickinger** [comment]
What is the recommended way to set this up then? just have players use /commands and no signs?

**Comment by Sataniel98** [comment]
There's no recommended way. I'm still using signs.

**Comment by bsickinger** [comment]
Gotcha. Thats too bad. I'd really like to be able to use this plugin in production but can't justify it without the signs working properly. I'm definitely going to be checking in for updates. Keep up the work!

**Comment by Sataniel98** [comment]
Group signs have been reworked in build 627. Note that the game and group sign syntax has slightly changed. If you still notice issues, please let me know.
