### ISSUE TITLE
Finishing the dungeon

### ISSUE THREAD

**Issue by Gelox1209** [DRE2N/DungeonsXL#377]
How many ways are there to finish a dungeon aside from clicking the finish sign?

**Comment by Sataniel98** [comment]
A dungeon is always finished with an end sign (or a floor sign that actually does the same if it is in the last floor of a multi floor dungeon). But you don't need to _click_ the end sign, you can use whatever you want to trigger it. If you use for example a distance trigger, the game finishs when a certain place is reached. If you use a mob trigger, the game ends when a mob is killed. There are as many possibilities as there are triggers.

**Comment by Gelox1209** [comment]
Got it thanks.
