### ISSUE TITLE
Bug in der config?

### ISSUE THREAD

**Issue by DuPleXFD** [DRE2N/DungeonsXL#38]
spieler können trotz einer sperre den dungeon erneut betreten. ich habe eingestellt das sie 24 std warten müssen bis sie den dungeon betreten dürfen. sie können aber trotzdem rein :/ . ausserdem setzen sich beim server neustart die portale zurück und werden normale netherportale

**Comment by Sataniel98** [comment]
Tritt der Fehler im neusten Build (v0.11-SNAPSHOT-28) auf?

**Comment by DuPleXFD** [comment]
hoppla, ich habe die 27. werde das gleich mal checken

**Comment by DuPleXFD** [comment]
öhm, also die neuste die ich runterladen kann ist die v0.11-SNAPSHOT-27

**Comment by Sataniel98** [comment]
Huh? ^^
![Build 28](http://fs5.directupload.net/images/160328/ddlksxut.png)

**Comment by Sataniel98** [comment]
Jedenfalls ist Build 28 vom [protections-and-players](https://github.com/DRE2N/DungeonsXL/tree/protections-and-players)-Branch kompiliert, der, wie der Name schon sagt, das neugeschriebene Protection-System enthält. Dazu wurde auch das Persistenzsystem teilweise neugeschrieben und obwohl es gestern erst bis auf weiteres fertig wurde, waren meine Tests mit mehrmaligen Reloads / Restarts immer positiv.

**Comment by DuPleXFD** [comment]
ja jetzt sehe ich es auch auf dem schirm. ich melde mich wenn mir etwas auffällt. ^^ danke für deine schnellen antworten

**Comment by Sataniel98** [comment]
Ich freu mich über jedes Feedback :)

**Comment by Sataniel98** [comment]
#44
