### ISSUE TITLE
World edit wont work with the dungeon plugin, is that right?

### ISSUE THREAD

**Issue by Darkgaming2020** [DRE2N/DungeonsXL#380]
Sorry if this isnt your issue or if im asking a stupid question. Anyway so im wanting to use world edit to build inside the dungeons because ya know its easier but whenever i try it does this.

29.04 22:16:38 [Server] ERROR An unexpected error while handling a WorldEdit command
29.04 22:16:38 [Server] INFO java.lang.reflect.InvocationTargetException: null
29.04 22:16:38 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
29.04 22:16:38 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
29.04 22:16:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
29.04 22:16:38 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:205) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:248) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]
29.04 22:16:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
29.04 22:16:38 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1466) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1271) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
29.04 22:16:38 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
29.04 22:16:38 [Server] INFO Caused by: java.lang.NullPointerException: The world was unloaded and the reference is unavailable
29.04 22:16:38 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[PaperSpigot-1.12.2-b1248.jar:git-Paper-1248]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitWorld.getWorld(BukkitWorld.java:131) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitWorld.equals(BukkitWorld.java:351) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.LocalSession.getSelection(LocalSession.java:408) ~[worldedit-bukkit-6.1.7.3.jar:?]
29.04 22:16:38 [Server] INFO at com.sk89q.worldedit.internal.command.WorldEditBinding.getSelection(WorldEditBinding.java:87) ~[worldedit-bukkit-6.1.7.3.jar:?]

**Comment by Sataniel98** [comment]
That's not on my side.
