### ISSUE TITLE
Command signs in dungeons.

### ISSUE THREAD

**Issue by Gelox1209** [DRE2N/DungeonsXL#381]
It seems like when I'm using command signs and use D 5 as the trigger, it will execute the command when within 5 blocks + whatever I set the delay to( For example I set it to 5, when the player is within 5 blocks it will execute the command every 5 seconds) Is that intended? If so how do I disable it?

**Comment by Sataniel98** [comment]
I'll do some tests. Might take a bit of time (at least until the weekend).

**Comment by Sataniel98** [comment]
I close this one because it's connected to #452.
