### ISSUE TITLE
Link mob signs with wave signs.

### ISSUE THREAD

**Issue by koca2000** [DRE2N/DungeonsXL#382]
There will be 2 (or more) wave signs in dungeon. Each wave sign will have their mob spawn signs, which they will trigger and count their mobs.

It can be used for multiple connected rooms in one dungeon with different spawns.

**Comment by Sataniel98** [comment]
Oh... Okay? And what is the issue?

**Comment by koca2000** [comment]
Not issue, feature request.

**Comment by Sataniel98** [comment]
See #383
