### ISSUE TITLE
Negative Lives in dungeons

### ISSUE THREAD

**Issue by bsickinger** [DRE2N/DungeonsXL#384]
I have a dungeon set up with a limit of 1 life and 1 group life.  If player 1 dies, he will respawn with -1 if player 2 is still alive.  he can then continue the dungeon. if he leaves, it acts as a fail not an escape.

**Comment by Sataniel98** [comment]
OK, I'll have a look at it. Player and group lives are not really intended to be used together. What behavior exactly do you expect?

**Comment by Sataniel98** [comment]
I was only able to reproduce that group lives still counted down after 0. The killed player didn't respawn inside the dungeon anymore. Not sure what exactly I did differently.

**Comment by Sataniel98** [comment]
I'll mark this as a minor bug and leave it as it is for now, because group lives and per player lives are logically not usable simultaneously anyway.

**Comment by Sataniel98** [comment]
Fixed
