### ISSUE TITLE
timeToNextPlay and timeToNextPlayAfterStart not working

### ISSUE THREAD

**Issue by arnhav** [DRE2N/DungeonsXL#386]
### Expected behavior
With both of these set in the config, a player should be let back into the dungeon if their cooldown has ended.

### Actual behavior
The cooldown never ends. Restarting the server has no effect.

### Steps to reproduce
Simply set timeToNextPlay and timeToNextPlayAfterStart in your config for a dungeon.

Version Info: Using the latest build

**Comment by Sataniel98** [comment]
Damn. Fixed it. Thanks for the report :)
