### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by sumdream** [DRE2N/DungeonsXL#389]
when I Edit an dungeon,I try to set an lobby,but the sign does not have setted.Console show this:```` An error occurred while accessing the handler class of the sign Lobby: ````

**Comment by Sataniel98** [comment]
I need the whole stacktrace, this says about nothing ^^

**Comment by sumdream** [comment]
The console does not print any stacktrace, only 1 line.Its therer any to turn on DEBUG mode?

**Comment by Sataniel98** [comment]
No. Which build do you use?

**Comment by sumdream** [comment]
Build Num: #612
Server Core: spigot 1.12.2

**Comment by Tiplish** [comment]
Hello, it's the same as #398 No ? :p

**Comment by Sataniel98** [comment]
Yes.
