### ISSUE TITLE
apocalypse question

### ISSUE THREAD

**Issue by Gelox1209** [DRE2N/DungeonsXL#391]
Can someone explain how apocalypse works and how I should set it up?

**Comment by Sataniel98** [comment]
Like any game type, with a ready sign. Apocalypse allows both PvE and PvP.

**Comment by Gelox1209** [comment]
and how do you use the wave system?
How do you start the first wave and how should I set the spawnpoints of mobs?

I have the trigger set to W 1 but it's not working as the mobs won't spawn, so is there anything I need to add to start the first wave? or...

**Comment by Sataniel98** [comment]
https://github.com/DRE2N/DungeonsXL/wiki/signs#wave

https://github.com/DRE2N/DungeonsXL/wiki/signs#mon

**Comment by Sataniel98** [comment]
See also #383
