### ISSUE TITLE
[bug] Only OP player could use group sign

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#393]
Hi,

I'm using dungeonsxl-0.16-SNAPSHOT-611.

Only OP player could interact with group sign, no player could :s is there a permission that i have to add to players?

**Comment by Sataniel98** [comment]
I'm not aware of any recent changes done to that. Could be though that I forgot something, it has been quite a bit since the last release build... Is it possible that it's because of the Vanilla spawn protection or a protection plugin? Does it work in a clean environment?

**Comment by Tiplish** [comment]
I've found the bug : it's the worldguard lock. 

Before (in 15.7 DXL version) the players could interact with locked DXL sign, not now :( 

Have you change anything in this behaviour? :p

**Comment by Sataniel98** [comment]
Might be an event priority thing then, could possibly have happened when I refactorized the listeners `¯\_(ツ)_/¯` Should be fixed soon

**Comment by Sataniel98** [comment]
I just tested it (build 620) and it seemed to work at least with the default flags. Which ones do you use? I also couldn't find anything in the source code, the listener is registered with ignoreCancelled true and HIGHEST priority. Is there maybe another protection plugin or the Vanilla spawn protection involved?

**Comment by Tiplish** [comment]
I will test it. I've just upload the build 620 on my serv :)

**Comment by Sataniel98** [comment]
Any news on this? ^^

**Comment by Tiplish** [comment]
Alwas here :(
