### ISSUE TITLE
Players spawn into random area on overworld rather than dungeon.

### ISSUE THREAD

**Issue by bsickinger** [DRE2N/DungeonsXL#396]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Players should spawn into the dungeon lobby

### Actual behavior
Players are being teleported to a random location in their current world

### Steps to reproduce
Seems to happen when a player dies in a dungeon. Something happens which respawns them in the dungeon despite only having one life. it considers them not in a group at that point since they are out of lives. Anyone else who tries to use the dungeon after that gets teleported to a random location.

**Comment by bsickinger** [comment]
sounds a lot like issue 344. Sorry if its a duplicate

**Comment by Sataniel98** [comment]
Yes, seems to be. Thank you for the report though, I'll keep this open.

**Comment by Sataniel98** [comment]
May I see your game rules (floor config, dungeon config if you use one, main config)?

**Comment by Sataniel98** [comment]
I'm positive this should be fixed now, if you still get the problem, please let me know...
