### ISSUE TITLE
[Question] Dev build

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#402]
Hello, 

You have solve some problems/bugs but there is no dev build since the 3.5.18. Is it possible to upload a new dev build ?

Thanks :)

**Comment by Sataniel98** [comment]
New dev builds will be uploaded when all severe issues are fixed. There is no benefit from uploading a DXL build of the project's current state.

**Comment by Tiplish** [comment]
Ok thanks for the information :)
