### ISSUE TITLE
[Bug] Ready sign doesn't work correctly

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#403]
Hello, with the last dev build, i have many problems. When i try to click on start sign, i have this problem : 

https://pastebin.com/wNa2n8t1

And nothing else happends :( 

On some other dungeon i have another behaviour : when i click on ready sign, i'm not tp to the start sign but on the spawn of the map :( 

Any clue? Thanks :)

**Comment by Sataniel98** [comment]
Fixed, thanks.
