### ISSUE TITLE
[Bug/miss] Ready Sign doesn't work

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#404]
Hi, i'm on dev build 625. One of my dungeon doesn't work when i click on ready sign. 

What happends if i have forgot one of the main signs? (Start/lobby/end/ready) or if i have put more than one of each? Is there a way to debug this?

I'm not sure that the problem comes from DXL because other dungeon works fine.

One this buggy dungeon, i could break blocks too :s

**Comment by Sataniel98** [comment]
If you don't use a lobby or start sign, the spawn location of the world should just be used instead. Forgetting the end sign will not influence the ready sign or lobby behavior. Multiple start signs will create different start positions per group. How exactly does it fail? Does nothing happen at all?

**Comment by Tiplish** [comment]
I have a start, a lobby, a end and a ready sign. When i click on ready sign in play mod, nothing happends at all (nothing appear in the console :( ).

**Comment by Sataniel98** [comment]
I really don't know :/ Could you maybe send me the dungeon and all game rule sources that might influence it (dungeon and global config)?

**Comment by Tiplish** [comment]
I haven't set any config for the dungeon and i've try another map without config and it works :s 
I will spend some time tonight to find something usefull. 

If i don't find anything i will send you it.

**Comment by Sataniel98** [comment]
You could try removing the DXLData.data file inside the maps/{your map} folder and to replace the signs - after making a backup of course. Maybe there's junk data that causes problems.

**Comment by Sataniel98** [comment]
Or is there maybe a classes sign somewhere? The ready sign won't be usable before a class is selected if it's possible to choose one.

**Comment by Tiplish** [comment]
I don't use class from dxl ^^" I'm not at home this week-end so i will test next week.
