### ISSUE TITLE
Player death drop exp/level

### ISSUE THREAD

**Issue by AaronHzy** [DRE2N/DungeonsXL#408]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
set “keepInventoryOnDeath” in map config.yml

### Actual behavior
Player death level to 0

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
I'm sorry, but I really don't understand what your issue is.

**Comment by Sataniel98** [comment]
keepInventoryOnDeath by design does not do anything but making the players keep their inventory on death.

**Comment by AaronHzy** [comment]
Well, I mean player death will lose xp
