### ISSUE TITLE
Disable mob griefing

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#409]
> However, right now when I'm in the dungeon, ghasts and creepers can destroy the map.
> Is there any way to turn the mob griefing off?
> -@Schwanzz

Mob griefing should be handled just like any kind of block breaking and can be disabled with the breakBlocks game rule.

**Comment by Schwanzz** [comment]
Tried that and now the server is crashing...

This is the error report:
https://pastebin.com/A4eXy5D9

**Comment by Schwanzz** [comment]
Nevermind, I fixed it.

Thanks anyways

**Comment by Sataniel98** [comment]
I'll definitely have a look at the error you just posted though. It looks like it occurs because a world from which a player joined a dungeon isn't loaded anymore. See #410
