### ISSUE TITLE
"timeToFinish" not work

### ISSUE THREAD

**Issue by AaronHzy** [DRE2N/DungeonsXL#413]
"timeToFinish" not work in map config.yml

in config
`timeToFinish: 10`

Player is not kicked out in 10 seconds

**Comment by Sataniel98** [comment]
It works perfectly fine for me, please provide more information about your environment sothat I can help you...

**Comment by AaronHzy** [comment]
PaperSpigot-1.12.2-b1409
Linux Centos 7

**Comment by Sataniel98** [comment]
The game did start? Did you include and trigger a ready sign?

**Comment by Sataniel98** [comment]
I can only assume that the game did not start, or that the game rule was overriden. Closing this for now.
