### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by architetto14** [DRE2N/DungeonsXL#416]
Hello!

I translated the language file in Italian. I uploaded it here: [http://www.mediafire.com/file/9o888m282hw4pyf/italian.yml](url)
I had a little problem, tho.
I translated the file, used a parser to correct all errors, then created a new file called italian.yml.
The fact is: when I restarted the server DungeonsXL generated a new language file, called italian_old.yml.
This happened even though I set the language in the config file on italian.
I thought "Not a big deal" and pasted the text of italian.yml in italian_old.yml. I restarted the server and it worked out just fine: it's all translated.
But now I got two identical files. Is this something supposed to happen?

Thanks!

**Comment by Sataniel98** [comment]
Hi,
thank you for sharing this, I'll add it as soon as possible :) The "_old" files are supposed to be backups that should be created when the language file has been changed. This mechanic indeed seems to be slightly broken.

**Comment by architetto14** [comment]
So that's how it is. Ok, thanks for the fast answer! It's not a big deal in the end, you just need to edit both files and the translation works fine.

Have a good day!
