### ISSUE TITLE
Dynmap support

### ISSUE THREAD

**Issue by koca2000** [DRE2N/DungeonsXL#420]
Hi.

Please add ability to hide all new maps your plugin create on dynmap.
https://github.com/webbukkit/dynmap/issues/2225

**Comment by Sataniel98** [comment]
I had the same issues, but never really bothered to add an integration because you can just disable them manually.

```
- name: DXL_Edit_1
  enabled: false
- name: DXL_Edit_2
  enabled: false
...
```

**Comment by koca2000** [comment]
Yeah but I noticed that you do not look for lowest number when you create a new map, so when you are making lots of test of map you may have even number 25.

**Comment by Sataniel98** [comment]
Theoretically, yes. But I never had a problem with it. I'm not saying DungeonsXL won't get a proper integration for Dynmap, but I don't see that on my to do list for the forseeable future.
