### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by architetto14** [DRE2N/DungeonsXL#421]
Hello, here I am again.

Reading through the wiki I believed there was a command to obtain the rewards from the Dungeon I completed whenever I want. But today I noticed that that command (/dxl reward) doesn't exist. Or at least it doesn't work.

In case it doesn't exist I would kindly ask you to add a command that permits to obtain the rewards in every moment after I completed the dungeon.

In case it doesn't work, well, now you know it.

Thanks for your hard work!

**Comment by Sataniel98** [comment]
Hi,
where did you find this in the wiki? The /dxl rewards command has been removed some time ago. It became redundant because the reward screen got unlimited pages and can show all rewards.

**Comment by architetto14** [comment]
At the moment I don't remember, I found that command some time ago. As soon as I find I will report it here
