### ISSUE TITLE
Sign change error

### ISSUE THREAD

**Issue by DrOreo002** [DRE2N/DungeonsXL#423]
### Steps to reproduce
I'm not sure

Here's the full error log. I believe the problem is on casting block state into some block interface. I'm not really sure, but well you can take a look at it [here](https://pastebin.com/L6EZsAY7)

**Comment by Sataniel98** [comment]
Hi,
the problem turned out to be an incompatibility with a different plugin. It will be fixed.

**Comment by DrOreo002** [comment]
Okay, ty for the help
