### ISSUE TITLE
cant break group signs

### ISSUE THREAD

**Issue by GGNoPotato** [DRE2N/DungeonsXL#424]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Sign should break

### Actual behavior
Sign doesnt break

### Steps to reproduce
Place a [DXL] sign and they wont break in regular world 
- Tried to replace with world edit and it still would not delete the signs

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
Did you even use /dxl break?
