### ISSUE TITLE
Feature Request: dynamic amount of mob spawns based on game play

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#426]
Can we have different / customized amount of mobs spawned based on:
* how many players are playing - e.g. mobs amount could be doubled or tripled when there are more plays join a dungeon.
* infinite times, there are always fixed amount of mobs alive - force players to push through a mob wave in certain map areas.
* when there is no more player nearby, halt the mobs spawning (improve server performance)

This might be a good or bad thing. It just come up my mind when I was submitting #407 .

**Comment by Sataniel98** [comment]
See also #383

**Comment by Sataniel98** [comment]
I also think there is room for improvement if it comes to mob spawning.
