### ISSUE TITLE
Suggestion: Invisible Interaction Signs

### ISSUE THREAD

**Issue by frost-sparks** [DRE2N/DungeonsXL#427]
I'm wanting to make dungeons and dragons esc dungeons, and one of the features of that game is the ability to do a "spot check" when you do this you check your surroundings for something suspicious in the wall, with a mob, etc. while attempting to recreate this in a dungeon i was able to get pretty close, but the sign in big, bright letters sort of gives away where to look.

The solution: have a way to make the interaction signs invisible! this way, the player would have to check for a piece of andesite in a pile of stone to click, rather than a bright colorful sign. it isn't perfect, but a big improvement.

**Comment by Sataniel98** [comment]
Interesting suggestion, I might come back to it.
