### ISSUE TITLE
Lots of errors on console

### ISSUE THREAD

**Issue by Krauzzer** [DRE2N/DungeonsXL#428]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Tried to install and run the plugin but it didn't work

### Actual behavior
The plugin was somewhat enabled but can't use its command `/dungeonsxl` and got a lot of errors from console

### Steps to reproduce
*First time run!* 
I don't see a list of any incompatibilities. But I do have **EWG** and **Multiverse**, are they incompatible for some reason? Those are the only I can think that might affect DungeonsXL

### First Error log - Before players connecting to the server:
[HastePaste](https://hastepaste.com/view/bOodKTt)

### Subsequent errors - After a player connects:
*This one keeps going on and on...*
[HastePaste](https://hastepaste.com/view/fCBcspm)

**Comment by Sataniel98** [comment]
The second stacktrace is most likely a result of the startup error. The first one is caused by unexpected behavior of Citizens. May I know which build and addons of Citizens you are running?

**Comment by Krauzzer** [comment]
I am running latest dev build, also some weird things are happening after I removed the plugin, like my spawn area appearing in other worlds and it would only disappear after a player got close so then the chunks would update/ as well as my survival world appearing in my spawn area and it causes so much lag to update those chunks

**Comment by Sataniel98** [comment]
DungeonsXL has no influence on your main worlds, especially not after being removed. I can't imagine why it would be incompatible with EWG and know that it is definitely not incompatible with Multiverse. It seems like DXL tries to hook into Citizens before it is enabled, however this usually does not happen. I cannot reproduce it in a clean environment.

**Comment by Sataniel98** [comment]
See #430
