### ISSUE TITLE
[Feature] Compatibility with SkillAPI

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#431]
Hi,

I use a plugin named SkillAPI which have a level system. Is it possible to add a condition for entrance in dungeon, the level of the player?

**Comment by Sataniel98** [comment]
Duplicate of #25. This is the second oldest unresolved issue of this project, opened in 2015 ^^"

**Comment by Tiplish** [comment]
Arg i've miss it :'(
