### ISSUE TITLE
[ Question ] : End sign wont showed on dungeon map.

### ISSUE THREAD

**Issue by DrOreo002** [DRE2N/DungeonsXL#432]
This prob a dump question, because I'm prob doing something wrong :/

So I have a dungeon with game type of Adventure, and then I placed the class sign, lobby, mob, start and the END sign

( My end sign format )
[End]

P 0/1 (last line)

but when I test the dungeon, the end sign is not there. Its gone somehow, so I decided to kill all of the mobs on the dungeon (because I think that the end sign will created if I killed all the mob inside the dungeon), but its still not working.

Help?

**Comment by Sataniel98** [comment]
It will not be created because you added a trigger to it. Leaving the last line empty makes some signs (ready, classes, end, floor) use an interact trigger by default. Adding a custom trigger overrides the default one. It probably doesn't end the game because you didn't add a wave sign.

**Comment by DrOreo002** [comment]
Alright, ty for the help ;). I'm going to close all of my issue now
