### ISSUE TITLE
[ Question ] Hologram is not created

### ISSUE THREAD

**Issue by DrOreo002** [DRE2N/DungeonsXL#433]
So I have this hologram script 

0:
  - "[Hologram]"
  - "&fBunuh semua mob"
  - "&funtuk lanjut ke wave selanjutnya dan memenangkan dungeon ini!"
  - 5.0

5.0 will make the hologram go up or go down?, because I've tried 2.0 height but the hologram go down for no reason, And also the third line is not created. Idk why
help?

**Comment by Sataniel98** [comment]
It doesn't go down. It's just normally spawned to the bottom. The third line (not the fourth) may contain a height adjustment to the top.

**Comment by DrOreo002** [comment]
Okay, I'll try it now. Ty for your help !

EDIT : Its working now, ty!
