### ISSUE TITLE
[ Question ]

### ISSUE THREAD

**Issue by DrOreo002** [DRE2N/DungeonsXL#434]
How to disable dungeon?. So player cannot join into the dungeon?

Sorry If I'm asking too much question this week lol. I'm really confused on making this dungeon things :/

* Btw, can you add some basic tutorials?

**Comment by Sataniel98** [comment]
Just don't add an entrance or adjust the requirements? ^^ The wiki is supposed to contain examples here and there. If anything isn't clear, you may ask questions, refer to the entries you don't understand and I'll see if I can improve them. If you're talking about videos, then no, I'm afraid but I'm not going to make one in the forseeable future.

**Comment by DrOreo002** [comment]
xD, its okay if you don't want to. Ty for your kind help ;)
