### ISSUE TITLE
[ Question ] Wave is not triggered

### ISSUE THREAD

**Issue by DrOreo002** [DRE2N/DungeonsXL#436]
So I have a wave sign like this
[Wave]
1.5
true
W 1

And I also have a mob sign like this

[Mob]
Zombie
1,5
P 0/0

When I start the game the mob spawning is working fine, but the wave sign is not triggered when I killed all of the mobs. Is there's something that I do wrong or its a bug?

**Comment by Sataniel98** [comment]
P 0/0 would trigger if the 0th wave is finished. Since there is no 0th wave, it does not trigger. Set it to 0/1 (and maybe read #383).

**Comment by DrOreo002** [comment]
Well if I put P 0/1, there will be no mobs spawned when I started the game :/

**Comment by Sataniel98** [comment]
Yes of course not, because they need to be triggered. If you don't need the mobs to be spawned at a specific wave at all, don't use a progress trigger to spawn them.

**Comment by DrOreo002** [comment]
Hmmm, alright. I'll do it

Btw, why is it not going to the next wave when I killed all of the mobs?

**Comment by Sataniel98** [comment]
Do you use a wave sign with a wave trigger?

**Comment by DrOreo002** [comment]
Yes

[Wave]
1.5
true
W 1 

Btw if I put one it will triggered when all of the mobs is killed right?.

**Comment by Sataniel98** [comment]
Oh, I see, sorry ^^" That's correct. What does /dxl game say if you slay all mobs?

**Comment by DrOreo002** [comment]
https://imgur.com/a/CM4M6hi

I uploaded the gif file there.

**Comment by DrOreo002** [comment]
Sooo, any good news?

**Comment by DrOreo002** [comment]
Ummmm. Hello?

**Comment by Sataniel98** [comment]
Sorry, no ideas so far.

**Comment by DrOreo002** [comment]
Soo, is it working on your side?. 

If so, what version r u running?

**Comment by Sataniel98** [comment]
I haven't tested it yet. July (/ February) is probably the worst month in the whole semester for a university student to care for Minecraft, sorry for that ^^" I'll let you know when I get to test it.

**Comment by DrOreo002** [comment]
Mmmk, ty for da help!

**Comment by DrOreo002** [comment]
Sooo, any good news?

**Comment by DrOreo002** [comment]
Hello?

**Comment by DrOreo002** [comment]
Are you still online?

**Comment by Sataniel98** [comment]
I didn't forget you. I'm working on it.

**Comment by DrOreo002** [comment]
xD. Glad to hear that!

**Comment by Sataniel98** [comment]
Update on this: It worked fine for me without the P0/0 trigger that hardly makes sense. Did you try it with no trigger at all?

Major changes to the wave system, possibly even a rewrite from scratch to make it more powerful, reliable and intuitive is scheduled for the next major update. If you'd like to contribute any ideas to improve this, feel free to let me know. #383

**Comment by DrOreo002** [comment]
So what trigger did you use?. Btw I'm going to explain the problem from the start now

So I've created an dungeon that has Wave sign like above, and it also has a mob sign that has the trigger of P 0/0, so it would spawn when I started the game. But when I killed those mobs, it didn't change to the next wave, the sign that has P 0/1 trigger does not triggered.. And I don't know why

I want to make the mob will spawn once, and automatically.. Can this be done?

**Comment by Sataniel98** [comment]
I used no trigger at all.

**Comment by DrOreo002** [comment]
Well, okay. Prob I'm going to change on how my dungeon will works.

Btw, can we go into the topic now?. I need to know why is the next wave is not triggered when I killed a mob that is spawned using the P 0/0 trigger?

**Comment by Sataniel98** [comment]
I'm not sure. Is this mob sign the one and only mob sign in the dungeon? Does the amount of mobs that are actually spawned match the amount specified on the sign?

**Comment by DrOreo002** [comment]
1. No, there's other mob sign too, with the P 0/1 trigger
2. Yes

**Comment by DrOreo002** [comment]
I changed the first sign to use the I trigger, but it seems like when I killed all of the mobs. It didn't go to the next wave.., I can send you the map if you want to

**Comment by Sataniel98** [comment]
That would probably make it a lot easier, thank you

**Comment by DrOreo002** [comment]
I'll upload it ASAP. I'm busy rn

**Comment by DrOreo002** [comment]
Here : http://www.mediafire.com/file/63n6k7miubk6fu7/TestMap.zip/file

please take a look ;)

**Comment by Sataniel98** [comment]
It seems the other mob signs prevent the new wave from being triggered, like, that all mobs are required for it to be slain, even those that can't be spawned yet because they _require_ that wave to be finished. I know that doesn't look too well-engineered, I'm afraid, but that's how it is for now.

**Comment by DrOreo002** [comment]
Ugh, so I need to wait the new wave system to come out?. If so, its fine tho. I'm going to cancel my dungeon project on my server then

**Comment by DrOreo002** [comment]
Hey, any good news so far?

**Comment by Sataniel98** [comment]
You can follow the progress of development in the commit history, the changelog wiki page or the 0.17 milestone issue list.

**Comment by DrOreo002** [comment]
Hey, it has been a really long time now.. I hope that I heard some good news from ya, so is it completed?

**Comment by Sataniel98** [comment]
It's still more or less the same state.

**Comment by Sataniel98** [comment]
See #383
