### ISSUE TITLE
[Question] Is there a way to ban certain items in dungeons?

### ISSUE THREAD

**Issue by FTOtter** [DRE2N/DungeonsXL#437]
Sorry if this is covered in the wiki, I did look but couldn't find anything. I may have missed it, though, that wiki is pretty big :)

Is there a way to allow users to take their inventory into a dungeon, but disallow certain items? As in, they can use their weapons and armor, take food or potions, but they can't take things like enderpearls? 

If this is not already a feature, could it possibly be added? 

Thank you!

**Comment by Sataniel98** [comment]
Hi,
there's currently no such feature. But I'll keep this open and take it into consideration for the time after the next major update (0.16).

**Comment by FTOtter** [comment]
I would really love it if this could be added! Things like enderpearls, chorus fruit, and elytra can allow people to totally cheat a dungeon. I know you can make it so people can't bring anything in, but that just doesn't work for the type of server I'm working on. Thank you!
