### ISSUE TITLE
How to disable default mob spawning?

### ISSUE THREAD

**Issue by JesterOwl** [DRE2N/DungeonsXL#439]
Hello, sorry to bother but I just haven't been able to figure this out. 

Is there a possible way to disable mob spawning in DXL dungeons besides the sign spawning?

For example I've setup a dungeon where players go through and clear mythic mobs but they're interrupted by normal mobs such as creepers etc, is there a way to stop that? (Sorry if it's obvious, I've been looking over the github wiki and can't seem to find it.)

**Comment by Sataniel98** [comment]
Hi, natural mob spawning should be disabled in instances. Do you have the worlds DXL_Game_1 etc. registered by a world manager like Multiverse?

**Comment by JesterOwl** [comment]
Yes, but it is unloaded. Initially, it was a world managed by Multiverse and I imported it.

https://imgur.com/a/IsgsKS7

**Comment by Sataniel98** [comment]
Anything else that might influence mob spawning? A performance plugin, maybe?

**Comment by JesterOwl** [comment]
Oh, yea. Thanks for the help and sorry for wasting your time, I didn't know that mob spawning was disabled by default and that something else was causing it...

I use the plugin "ExtraHardMode" which increases mob spawning (which was enabled in all worlds) setting it up to only be enabled in the worlds we use on multiverse, fixed the issue.

Thanks again!
