### ISSUE TITLE
Sperre bei betreten eines dungeon

### ISSUE THREAD

**Issue by DuPleXFD** [DRE2N/DungeonsXL#44]
also ich muss als erstes sagen: echt super das du hier die bugfixes raushaust wie warme semmel ^^ . dafür mal ein fettes dankeschön.

eines ist mir dennoch aufgefallen und zwar das diese sperre die man einstellen kann leider noch nicht funktioniert. 24 std habe ich eingestellt, der user kann den dungeon dennoch betreten

**Comment by Sataniel98** [comment]
Ich kann es mit "timeToNextPlay: 1" nicht reproduzieren :/

**Comment by Sataniel98** [comment]
Könntest Du es eventuell noch einmal Schritt für Schritt darstellen?
- Welches Ergebnis hast Du erwartet?
- Was genau hast Du Schritt für Schritt gemacht, um es zu erreichen?
- Was genau ist das Ergebnis / was tun Spieler, bevor sie den Dungeon erneut spielen?

**Comment by DuPleXFD** [comment]
- Spieler sollen nach beendigung des Dungeons [nur einem Floor] oder nach dem clearen aller Floors den Dungeons für die Zeit X den dungeon nicht betreten dürfen. 
- Wenn ich die Frage richtig verstanden habe: Der Spieler joint der Gruppe über das Globale Schild neben dem Portal. Spieler starten in der Lobby und bestätigen mit [Ready] die Bereitschaft. Normaler Spielablauf. Mobs töten, Kisten öffnen und looten. Muss dazu sagen das es noch eine Bedingung gibt den Dungeon erfolgreich zu verlassen. Der Spieler muss keinen Boss töten, er läuft durch und beendet das Spiel über das Ausgangsschild. Spieler steht wieder vor dem Portal vor dem Portal.
- Der Spieler bedient sich über das Lootfenster. Er steht vor dem Portal klickt wieder auf das Schild und betritt den Dungeon erneut.

Kleine Anmerkung: In einer Vorgängerversion kam es vereinzelt vor das der User sein Inventar nicht mitnehmen konnte. Er startete mit leeren Inventar. glaube ab #30 war das vorbei. 

Gibt es sowas wie einen Debugmodus? Würde dir die Logs schicken, schraube fast jeden TAg an den Dungeons
