### ISSUE TITLE
[Bugs] SoundMsg doesn't work, Mobs sign spawns wrong number of mobs.

### ISSUE THREAD

**Issue by FTOtter** [DRE2N/DungeonsXL#441]
### Expected behavior
I exactly copied the sign from the wiki page with the wolf howl sound effect, wanting to have a wolf howl noise. 

### Actual behavior
It didn't make any noise.

### Steps to reproduce
Try to make the sign as in the wiki. (Also, I can't figure out where I would get a list of other sounds that could be used. The page linked in the wiki just goes in loops as far as I can tell.)

**Comment by Sataniel98** [comment]
Moved the second and third issue to #442 and #443, please create one issue per actual issue.

**Comment by FTOtter** [comment]
Ah, sorry, I was trying not to post too much. Will do in the future!

**Comment by Sataniel98** [comment]
No problem ^^

"The page linked in the wiki just goes in loops as far as I can tell." - What page linked in the wiki? Just use the same sounds as the ones you would use for /playsound, including custom ones. These are version specific. [This](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/CraftSound.java) probably shows it well.

**Comment by FTOtter** [comment]
In the wiki, if you go to signs, then to sound message, there is a link called "sound category" which links to [this page](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/SoundCategory.html). I assumed that page was supposed to have a list of the sound names in correct syntax, like the link you just posted above. But when you click a category under Enum Constants, it just takes you down the page to a link that brings you right back up to the list of categories. It may be my own misunderstanding, I clicked the link in the wiki expecting something like what you just posted, so I was confused by how that page was laid out.

**Comment by Sataniel98** [comment]
This is the official java doc of the sound categories, not the sounds. It defines the way the sound is played, which is supposed to be used in the second sign data line:

MASTER,10.5,1.0

**Comment by FTOtter** [comment]
Ah, okay, so that was my misunderstanding then, sorry!

**Comment by Sataniel98** [comment]
I just tested and confirmed that the sound message sign and entity.wolf.howl definitely do work in 1.12.2. What I used was:

[SoundMSG]

entity.wolf.howl

MASTER,10.5,1.0

U Test
