### ISSUE TITLE
Script sign not working as expected

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#443]
Also having an issue with a script sign. Using it to try to make a puzzle where you have to flip certain levers, too many to fit on a sign, to open a door. 

I made a yml file named "door.yml" and put it in the "signs" folder within the "scripts" folder.

The file looks like this:

0:
  - "[Door]"
  - 
  - 
  - "T 1, T 2, T 3, T 4, T 5, T 6, T 7, T 8"

I placed a sign with the following:

[Script]
door

But it did not work to open the door when the levers were flipped. I know all the signs attached to the levers are working correctly. I thought maybe the 0 was the issue, so I changed that to a 1 and reloaded the file and stopped/started the server. 

After that, I got the following console error:

`ERROR Error occurred while enabling DungeonsXL v0.16-RC-02 (Is it up to date?)
09.07 02:39:45 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
09.07 02:39:45 [Server] INFO at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661) ~[?:1.8.0_144]
09.07 02:39:45 [Server] INFO at java.util.ArrayList.add(ArrayList.java:473) ~[?:1.8.0_144]
09.07 02:39:45 [Server] INFO at de.erethon.dungeonsxl.sign.SignScript.<init>(SignScript.java:60) ~[?:?]
09.07 02:39:45 [Server] INFO at de.erethon.dungeonsxl.sign.SignScript.<init>(SignScript.java:43) ~[?:?]
09.07 02:39:45 [Server] INFO at de.erethon.dungeonsxl.sign.SignScriptCache.<init>(SignScriptCache.java:36) ~[?:?]
09.07 02:39:45 [Server] INFO at de.erethon.dungeonsxl.DungeonsXL.loadSignScripts(DungeonsXL.java:513) ~[?:?]
09.07 02:39:45 [Server] INFO at de.erethon.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:238) ~[?:?]
09.07 02:39:45 [Server] INFO at de.erethon.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:128) ~[?:?]
09.07 02:39:45 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot131.jar:git-Spigot-7754231-94b0980]
09.07 02:39:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by Sataniel98** [comment]
@FTOtter Java array / list indexes start at 0, 1 is not expected here. That doesn't explain why it doesn't work though. Can you say for sure whether it is caused by the script sign? Does it work if you use a door sign directly and include as many of the triggers as possible?

**Comment by FTOtter** [comment]
Yes, it worked fine with the triggers, we actually accomplished what we wanted by essentially using trigger signs in a ladder logic array, to bypass the need for the script sign. We also have multiple more simply triggered door signs that work perfectly. 

When it was set to 0, as I initially tried it, it did not work. Bizarrely, it also made my Ready sign not work, even though that is on the opposite side of the map and they shouldn't be related in any way. Nothing else seemed to be affected.

**Comment by Sataniel98** [comment]
@FTOtter I tested it and it did work for me. I copied your door.yml script, added 8 trigger signs with distance triggers, one block sign as an indicator for each to see if it is triggered and a door with a [script] / door sign. As soon as all triggers had been triggered, the door opened. Could you maybe try to do the same, like, add actions triggered by the 8 triggers to make sure that all of them are fired correctly?
