### ISSUE TITLE
Players are teleported in the Nether when they stay in the dungeon's portal

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#444]
Hi,

When a player end a dungeon, he is usually in the dungeon's portal. The problem is, they are TP in the nether. Is it possible to desactivate this behaviour? For the moment, we have put invisibles blocks in the nether to prevent any death there :p

**Comment by Sataniel98** [comment]
DungeonsXL cancels teleportations into the nether through its portals. Do you have any other portal plugins that might interfere?

**Comment by Tiplish** [comment]
We use MultiWorld
