### ISSUE TITLE
Minimum group size doesn't work

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#445]
### Expected behavior
When i specified the minimum group size to 2, it requires two players to trigger the Ready Sign

### Actual behavior
One player alone could trigger the Ready sign

### Steps to reproduce
1) Create a dungeon with the minimum group size to 2
2) Go alone in the dungeon
3) Hit the ready sign of the dungeon

I'm using dungeonsxl-0.16-RC-02

**Comment by Sataniel98** [comment]
Just tested it and I believe you made exactly the same mistake as I did... Testing with an account that is OP / has dxl.ignorerequirements. It works fine for me without that permission.
