### ISSUE TITLE
Problems with /DXL reload

### ISSUE THREAD

**Issue by architetto14** [DRE2N/DungeonsXL#447]
### Expected behavior
I use /dxl reload and everything goes fine

### Actual behavior
I use /dxl reload and often Group signs and Portals stop working. The signs and the portals do not disappear, but they do not work at all. If I recreate the signs and the Portals they work until the next /dxl reload

### Steps to reproduce
Just use /dxl reload

I do not get any error.

**Comment by Sataniel98** [comment]
Hi,
can you tell if the lost global protections are saved in the data.yml? Does the data loss include old signs & portals or are just those registered since the last server start affected? I'll definitely have a look at this, I just can't promise it'll be within the very next days or weeks due to exams.

**Comment by architetto14** [comment]
I'll check the data.yml next time and I will tell you if the global protections are there.

The data loss affects all the signs, not just the new ones. It doesn't affect the ones inside the dungeons.

I'd like to report another bug: it is possible to take the heads and the glass in the bottom corners, the ones used to change page, of the loot window when you finish a Dungeon.

Thank you for the hard work and take your time: I have exams too in this period

**Comment by Sataniel98** [comment]
Under which circumstances does this happen? I've never seen this.

**Comment by architetto14** [comment]
A player reported this to me with a video. It happened only once and it wasn't due to lag because he placed the heads that he took from the gui. If more reports will follow I'll try to add more info.

**Comment by FaMa91** [comment]
This issue happen at every reload of dxl or restart of the server. Some times it breaks some signs but everytime the portals need to be redone

**Comment by Sataniel98** [comment]
Still cannot reproduce this. My signs and portals persist in a clean environment.

**Comment by Tiplish** [comment]
What version of DXL you used? Because with the old versions, i've had this problems too.
