### ISSUE TITLE
Mobs becoming invisible and impossible to hit when player respawn

### ISSUE THREAD

**Issue by Eredian2000** [DRE2N/DungeonsXL#448]
In a solo dungeon, when the player respawn, every living mobs become invisible and impossible to hit, but continue to use skills, make sound and hit the player.
It does not seem to happen every single time, but still pretty often.
From what I tested, it seems that the bug affects vanilla mobs (tested with pigmen) and Mythicmobs monsters alike.
It happens in both editor worlds and instance worlds, but not in "true" minecraft worlds.

**Comment by Sataniel98** [comment]
Which version are you running?

**Comment by Eredian2000** [comment]
Version 0.16 of dungeonsxl (the latest version, but I encountered the same bug with 0.16 RC#4), along with the latest version of spigot 1.12 .

**Comment by Tiplish** [comment]
It's occure sometimes in our server too, but only on client side (others players could see mobs). A Deco/reco solves this.

**Comment by Sataniel98** [comment]
Maybe there's a packet or something I can send to work around this. I don't believe this bug is caused by DXL though.

**Comment by Sataniel98** [comment]
Closed since it can now be avoided with the deathScreen game rule.
