### ISSUE TITLE
Mob attribute system

### ISSUE THREAD

**Issue by DuPleXFD** [DRE2N/DungeonsXL#45]
es wäre noch super wenn man nicht nur die maximale gesundheit der mobs, sondern auch die geschwindigkeit und die kraft konfigurierbar wäre. ich weiss das das mythikmobs macht, aber das plugin kriegen wir erst nächste woche :/

**Comment by Sataniel98** [comment]
Langfristig vielleicht schon. In Bukkit kann man Attribute erst seit 1.9 benutzen und ich will im Moment noch 1.8.x voll unterstützen. Deswegen haben abwärtskompatible Features erstmal Priorität für die nächsten Meilensteine...

**Comment by DuPleXFD** [comment]
ach das wäre so genial :( , es macht einfach keinen sinn das die mobs mehr hp haben wenn sie nicht viel stärker oder schneller sind. wenn man sich noch hinsetzt und stellt mit commandblock stärkere waffen her ist der dungeon ohne diese nicht schaffbar. das würde dem eine sehr spezielle note geben

**Comment by Sataniel98** [comment]
Note: I will create a new API to (de-) serialize items and mobs. This will take some time.

**Comment by Sataniel98** [comment]
See #383
