### ISSUE TITLE
[Question] Tutorial functionality

### ISSUE THREAD

**Issue by ParadiddlePride** [DRE2N/DungeonsXL#450]
Hello, I am currently in the process of learning this plugin, and can't seem to find any information about how the Tutorial dungeons actually work.
- Is the player forced into a tutorial upon joining the world/server?
- Is the player asked to perform a command?

I'm just unsure how this works, as we want to have a one-time-only dungeon due to use of quests, storytelling, etc. If the tutorial offers a way to not allow players to return to the dungeon once completed, that'd be great, but I genuinely don't know how to accomplish this.

**Comment by Sataniel98** [comment]
Hi,
new players are forced into the tutorial dungeon. Thus, it doesn't require a command or portal. The player spawns in its lobby and plays it alone. I'll update the documentation on this. If the dungeon can be played again is up to you - just don't make a portal for it.
