### ISSUE TITLE
Serious bug about skillapi

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#458]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

In the skillapi I am using the skill bar.

I am using the skillapi pro plugin

Disconnecting in the dungeon will make the skills of the skillapi all brush out and become available, just like in the video.

This BUG is very serious and hopes to solve it quickly.

BUG video
http://www.mediafire.com/file/239otavvdkkg2f6/bug.mp4/file

**Comment by Sataniel98** [comment]
Hi, I don't know if you can do anything about that or not by adjusting the keepInventory game rules since I don't know what exactly SkillAPI does. I am however not going to add an integration for premium plugins. They can do that as good as I, probably better, in their plugin, and are, unlike I, paid for it. Have a nice day.

**Comment by Niinnee** [comment]
This is not a problem with SKILLAPI, but a question of your support for the overlapping number of backpack items. I hate your decision. Although I like your plugin very much, I can't find another plugin instead of this plugin. Because this bug is too serious, I can't guarantee that the player will not drop the line and disconnect the link.

The skillapi plugin is great for RPG. I think there should be a lot of people using it, and you are a dungeon plugin. It will definitely be used in the same way as I do, so they will also encounter this situation. , then you must not give up using this plugin.

Plugin link: https://www.spigotmc.org/resources/skillapi-premium.28029/

**Comment by Niinnee** [comment]
@Sataniel98

**Comment by Sataniel98** [comment]
Still, it definitely is a problem with SkillAPI just as much as it is a problem with DungeonsXL. DXL does nothing that is not to be expected here. I believe it's likely that your keepInventory settings could be adjusted to get along with SkillAPI, but to be honest, that video doesn't show me at all which kind of behavior is expected. If there's a backpack feature that shouldn't be accessible in or outside of dungeons, then that's something they could handle as good as or easier than DXL can.

**Comment by Niinnee** [comment]
I tried to solve it. I can only set the player to drop the line without leaving the dungeon to avoid this problem. But not a long-term solution
