### ISSUE TITLE
Cannot place a torch in the dungeon

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#460]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

This is the parameter I wrote in config.yml, and I also typed /dxl reload, but I still can't place the torch. I don't know what caused it.

Game types: default

breakPlacedBlocks: true
breakWhitelist:
  Torch: []
placeBlocks: true
placeWhitelist:
  - Torch
gameMode: SURVIVAL

video
http://www.mediafire.com/file/z11nnucwc8nz04o/20180817_011142.mp4/file

**Comment by Niinnee** [comment]
AND [Title] Using M XXXXXX will become invalid
I used to have an effect to update the plugin, it didn't work, and I didn't make any changes.

**Comment by Sataniel98** [comment]
I don't understand what you mean by the second post, but the first one is because a game type overrides config values, and "DEFAULT" doesn't allow to place blocks. "CUSTOM" is what you're looking for. I'm sorry for the missing / outdated documentation.

**Comment by Niinnee** [comment]
Trigger use [M (MythicMobs mob) ] Some things will be invalid
For example: [Title], [CMD]
