### ISSUE TITLE
The ExternalMob [CustomMobs, CM] sign doesn´t work

### ISSUE THREAD

**Issue by Sckarlex** [DRE2N/DungeonsXL#462]
I created an externalmob sign on my dungeon using the CustomMobs plugin, but, when i test the map the mobs don´t spawn. In my server console appear the commands like this:

INFO: [- CustomMobs -] 96.5 should be a number!
INFO: [- CustomMobs -] /ccmob spawn <name> <worldname> <x> <y> <z> [amount] - Console and CommandBlock spawn command

(That message repeat 20 times)

But the Mobs dont summon. I don´t know if the sign is wrong or if I need to create a command in the config.yml. PLEASE HELP ME :C.

My sign Format:
[ExternalMob]
Zombie = The name of my customMob
1,20,CM
D 10

Sorry for my bad english :(

**Comment by Sataniel98** [comment]
I'm afraid but that's a bug. It seems CustomMobs doesn't like decimals in its spawn command arguments. I'll fix that next Thursday when I'm back home.

**Comment by Sckarlex** [comment]
how can I put numbers without decimal?

**Comment by Sataniel98** [comment]
You can't.

**Comment by Sataniel98** [comment]
Which version of DungeonsXL are you using? Sounds like an awfully outdated one, probably 0.15.6 or lower. This bug is a duplicate of #204 and has been fixed 1 1/2 years ago.
