### ISSUE TITLE
Signs show outside of Test mode

### ISSUE THREAD

**Issue by Dynamikr** [DRE2N/DungeonsXL#463]
### Expected behavior
The dungeon would work the same as in /dxl test

### Actual behavior
Certain signs show up physically and don't work such as end,leave,teleport,externalmob, and sound message

### Steps to reproduce

Create any dungeon with any  of the previous signs

**Comment by Sataniel98** [comment]
/dxl test starts a game, but you need a ready sign to start one in a game instance.
