### ISSUE TITLE
Enter the dungeon Server crash

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#467]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)
Server crashes after entering the dungeon with the portal
[latest.log](https://github.com/DRE2N/DungeonsXL/files/2365293/latest.log)

**Comment by Sataniel98** [comment]
Hi, can you load the world without DungeonsXL?

**Comment by Niinnee** [comment]
yep

**Comment by Niinnee** [comment]
yes，can load

2018年9月10日星期一，Daniel Saukel <notifications@github.com> 写道：

**Comment by Sataniel98** [comment]
Sorry for the long wait. May I see your configs, including the main config and every config that contains the rules "gamePermissions" (most likely the floor config)?

**Comment by Sataniel98** [comment]
Doesn't seem to be related to DungeonsXL but Bukkit and the permission plugin.
