### ISSUE TITLE
Death when leaving dungeon 1.8.8

### ISSUE THREAD

**Issue by GerwinVerkerk** [DRE2N/DungeonsXL#468]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
I expect not to die when I leave a dungeon using /dxl leave or the leave sign.

### Actual behavior
Dieing when leaving a dungeon on minecraft 1.8.8, using the newest dungeonsxl 0.16.3

### Steps to reproduce
1. Join a dungeon
2. Leave the dungeon
DEATH

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
May I see the user file while you are in the dungeon?

**Comment by Sataniel98** [comment]
Fixed, thank you for your report!

**Comment by GerwinVerkerk** [comment]
Wow, you are fast dude! I will check it out and try to update to the newest release!

**Comment by Sataniel98** [comment]
There's no new release so far, but you can already check this bugfix and the latest features by using the latest dev build: http://erethon.de/repo/de/erethon/dungeonsxl/. I expect to have a new Beta release ready soon though.
