### ISSUE TITLE
Mythicmobs not working!

### ISSUE THREAD

**Issue by neox91120** [DRE2N/DungeonsXL#469]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Steps to reproduce  :: i don't know

Overall, i placed a sign : 
[Mob]       
Custommobname
1,1
D 10

And it says the sign was created but the mob doesnt spawn.

i tried replacing [Mob] with [MM] juste in case and that doesnt event create a sign

In dungeon world of course

Thanks for the response

PS: I don't speak english sorry for the errors

**Comment by Sataniel98** [comment]
Hi, did you create and trigger a ready sign? Is there a message in the console when the mob should have spawned?

**Comment by neox91120** [comment]
the trigger is D 10
and yeah there is a ready sign.
Other mobs spawn normaly (well not normally there always like 4x more mobs that spawn xD)
there is no message in the console when mobs spawn
maybe i didnt activate it?

**Comment by neox91120** [comment]
I also have another problem.
I placed a [DXL] sign in my spawn and cant delete it, it just wont break, i used wordedit and now the blocks that the signs were attached to cant break either.
Sorry but i need help for 2 problems now :(

**Comment by Sataniel98** [comment]
Use /dxl break. I'll try to reproduce your problem with MythicMobs.

**Comment by neox91120** [comment]
ok thanks in advance

**Comment by neox91120** [comment]
Um so?

**Comment by neox91120** [comment]
I guess this forum isnt very useful ....

**Comment by Sataniel98** [comment]
It has barely been a week, have some patience...

**Comment by neox91120** [comment]
oh okay sorry then, its because you responded so quick the first time.
And i cant really advance if i dont get a solution :/

**Comment by Sataniel98** [comment]
Tested, MythicMobs works perfectly fine. Make sure to include the correct provider ID at the sign (MM) and to trigger the ready and mob sign.

**Comment by lyimu** [comment]
Example:

[Mob]
Custommobname
1,1,MM
D 10

**Comment by neox91120** [comment]
yes that works thanks!!
It isnt properly explained on the wiki

**Comment by Sataniel98** [comment]
It is, under wiki/signs#mob:

<table>
  <tr>
    <td>1</td><th>[Mob]</th><td></td>
  </tr>
  <tr>
    <td>2</td><th>Type</th><td>The type of the Mob. You can use custom mobs from the floor config.
  <tr>
  <td>3</td><th>delay,amount(,provider)</th><td>The delay determines how many seconds it takes for the next mob to spawn and the amount how many mobs are spawned altogether. The third, optional parameter specifies which external mob provider will be used.</td>
  </tr>
  <td>4</td><th>Trigger</th><td></td>
  </tr>
</table>

DungeonsXL provides built-in support for InsaneMobs, MythicMobs, CustomMobs and Citizens.

<table>
  <tr>
    <th>Plugin</th>
    <th>External mob provider tag</th>
  </tr>
  <tr>
    <td>Citizens</td>
    <td>CI</td>
  </tr>
  <tr>
    <td>CustomMobs</td>
    <td>CM</td>
  </tr>
  <tr>
    <td>InsaneMobs</td>
    <td>IM</td>
  </tr>
  <tr>
    <td>MythicMobs</td>
    <td>MM</td>
  </tr>
</table>

You can also add other custom mob plugins if they provide a spawn command with a mob identifier and a location (world name and coordinates) in the [main configuration](main-configuration).

Anyway, I'm glad to hear it works.
