### ISSUE TITLE
Portals

### ISSUE THREAD

**Issue by Poweringg** [DRE2N/DungeonsXL#47]
hi, i have small problem, i dont know it is my bad or not, but i created a portal. Then i ran two MC clients, i went with these clients into portal, and portal teleported only one player or none.

**Comment by Sataniel98** [comment]
Yes, it's sometimes a bit wayward, but it works sooner or later. It seems to be an issue of the PlayerPortalEvent itself. This will be fixed when I switch to the PlayerMoveEvent which is necessary anyways for supporting custom portal types like e.g. water.

See #9.
