### ISSUE TITLE
How to procedurally generated dungeons?

### ISSUE THREAD

**Issue by AdleyBro** [DRE2N/DungeonsXL#470]
Hi,

I want to make procedurally generated dungeons and I don't know if there's a way to do it without using command blocks. I would like to know if there is a way you can do that with this plugin or if there's any other that can. Maybe with the combination of various plugins.  

Thank you for reading.

**Comment by Sataniel98** [comment]
Could you explain in detail what you need to happen?

**Comment by AdleyBro** [comment]
A rogue-like dungeon. You build, for example, 4 different rooms and create (somehow) a system which places those 4 rooms randomly, creating a randomized dungeon. So, everytime you enter to one, it will never be the same as before, because the rooms are placed differently. You could build more than only 4 rooms and even make the "system" to choose randomly only a few of all those rooms you've created. That's what I need, a "system" which connects randomly buildings/rooms I have created. I don't know if DXL does that or if there is any plugin that can do it without the need of command-blocks.

**Comment by Sataniel98** [comment]
DXL does this in [multi floor dungeons](https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration).

**Comment by AdleyBro** [comment]
Thank you, I will try it.
