### ISSUE TITLE
Signs and Portals break on a server reset or /dxl reload.

### ISSUE THREAD

**Issue by lyimu** [DRE2N/DungeonsXL#471]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Signs should allow  4 players in when a sign contains

> [dxl]
> Group
> Dungeon
> 4,TestGroup01

### Actual behavior
When server is restarted or plugin is reloaded. All signs that usually accept 4 people now only accept 1 person, or they may break entirely.

### Steps to reproduce
Make a sign with a max cap of players 2+
Reload Plugin
Try clicking on a sign that allows 2+ players
Once the first player joins it says full

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
I'll have a look at this, thank you for the report.

**Comment by FaMa91** [comment]
Same Issue here: https://github.com/DRE2N/DungeonsXL/issues/447
Since 12 July, we really need a fix to this.

**Comment by Sataniel98** [comment]
> Same Issue here: #447
> Since 12 July, we really need a fix to this.

That issue has nothing to do with problems saving the amount of maximum elements per sign though. This one is a separate problem that has probably been introduced with the recent rewrite in v0.17.
