### ISSUE TITLE
This turned out to actually be an issue

### ISSUE THREAD

**Issue by neox91120** [DRE2N/DungeonsXL#473]
This is not an issue just some help needed xD

How do you put up a reward when you finish a dungeon. 
I created a dungeon and all but when i click end sign no rewards are offered. I would like to know how to set them up please :/

**Comment by Sataniel98** [comment]
No problem, in fact, questions help me enhancing the documentation, so please feel free to ask whenever you're stuck.

Just let your players trigger a chest sign (by opening a reward chest). The rewards are saved and given to the players once they move after leaving the dungeon. Note that rewards are not given if the game type is either one of the PVP types or the test game type that is used if you entered through /dxl test. This is to prevent abuse with multi accounts and collusion, and in the case of /dxl test sothat builders who take part of the game as regular players can test their dungeons without the need to wait for a time cooldown.

**Comment by Sataniel98** [comment]
I'm sorry for this. Just realized there's is an error with a missing dependency in the latest version that causes them not to open. I'm working on it!

**Comment by neox91120** [comment]
ok thx
