### ISSUE TITLE
Players bringing their outside world gear into dungeons.

### ISSUE THREAD

**Issue by lyimu** [DRE2N/DungeonsXL#476]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

Im looking to allow players to bring their own gear into dungeons rather than using classes, however I cant find any settings like this in the configs. How would I go about doing this?

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
https://github.com/DRE2N/DungeonsXL/wiki/faq#how-can-i-make-it-so-that-players-play-dungeons-with-their-own-items

**Comment by lyimu** [comment]
Thank you!
