### ISSUE TITLE
Fortune triggers not working as expected with reward chests

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#477]
> I have another question:
> How do you use the fortune sign?
> when i place this sign on a chest i put
> 
> [Chest]
> 2000,15
> 
> F 50
> 
> (i tried ''F 0.5'' and ''0,5'' still same problem)
> 
> This is the correct usage i suppose.
> 
> But what happens is that, when a player opens it he can see the loot, he then closes the chest, and in chat the loot was added to team and that is good.
> BUT, then he can reopen the chest, and do the same thing, so he can get infinite loot in the end of game. This is so cheat.
> And the Fortune doesnt even work because he can always 100% open it
> 
> PS: I placed the Sign on the chest
> 
> thanks in advance :)
> ~ @neox91120

Usage indeed seems to be correct. I assume the unexpected behavior is specific to reward chests as they are handled separately from all regular triggers. I'll have a look at this, thank you for the report. Is there an error message in the console?

**Comment by neox91120** [comment]
no there isn't

**Comment by neox91120** [comment]
I just realized something,
The chest rewards work well now. I have no idea why.
But the fortune triggers are useless. i tried every type none work, always get a 100% chance of getting loot.
And still nothing in console

**Comment by Sataniel98** [comment]
See #452
