### ISSUE TITLE
Bug: Ability to take loot chest menu items

### ISSUE THREAD

**Issue by FixTheAdmin** [DRE2N/DungeonsXL#478]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Menu items should stay

### Actual behavior
You can take menu items

### Steps to reproduce
End a dungeon with loot table reward. Once out you can keep the "Next page" and glass pane items.
https://i.imgur.com/xckoaxf.jpg
DXL version 0.17.1

In addition I did not get the loot table items but it might be a configuration issue on my end.
Here is the loot table: https://hastebin.com/oxahidayov.makefile

**Comment by Sataniel98** [comment]
Can't reproduce this, interaction is cancelled properly.

The loot table script is correct, but it seems there was a bug with items without modifiers having no amount specified. Fixed :)

**Comment by Sataniel98** [comment]
As this is most likely a problem chained to another one that has hopefully been fixed, please let me know if it happens again.
