### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by neox91120** [DRE2N/DungeonsXL#479]
This isn't an issue.
I just wanted to know how to put cooldowns to the use of certain dungeons?

For example a player cant play the same dungeon 2 in 24h?

I'm aware that i need to use ''timeToNextPlayAfterFinish'' and a value in a config file

But i cant find any config files for any of my dungeon maps
Only the main config of everything i can find.

If there should be a config file in my map folder of my dungeon then how do i get it?
(there is only :  DXLdata.data       /       session.lock       /        level.data_old   files   and not config )
There is also a region file but i dont think it is necessary here.

PLease help its my last step to releasing a dungeon :/

**Comment by Sataniel98** [comment]
You get the floor configuration by creating it. A floor configuration is optional and therefore not generated automatically.

PS: The issue function is supposed to be used for questions as well as bug reports or feature requests, you don't need to label every question with "not an issue" ^^
