### ISSUE TITLE
Just need help :/

### ISSUE THREAD

**Issue by neox91120** [DRE2N/DungeonsXL#480]
This isnt an issue i just dont know where to ask.
How can i put a cooldown so that players cant do more than one dungeon a day?

I know its something to do with the config file in the map of the dungeon but there is no config file in tha map file.
Once i have the config i can do the rest.
How do i get the config file which doesnt appear on its own?

**Comment by Sataniel98** [comment]
Isn't this exactly what you asked in #479?

**Comment by neox91120** [comment]
it is sorry i thauoght i already asked but wasnt sure and didnt find it open because it was closed xD very sorry.

**Comment by Sataniel98** [comment]
No problem ^^
