### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by neox91120** [DRE2N/DungeonsXL#482]
How do i create a dungeon floor.
This may seem simple i'm sorry if i missed it in the wiki :/

I would like to change some settings of a certain dungeon (like the cooldown before being able to play it) 

You've already told me to create a floor so that it generates a file that i can modify but how do i create it?
A command in game? Or do i do it manually and name it however?

Thanks

**Comment by Sataniel98** [comment]
A dungeon floor can be any map in the maps folder. A map can be used in multiple contexts simultaneously - multi floor dungeons do not own floors. If you want to set settings for a dungeon, use the dungeon config to do so, if you'd like to set it to the floor, set it to the floor. This article explains the inheritence: https://github.com/DRE2N/DungeonsXL/wiki/game-rules

**Comment by neox91120** [comment]
Yes that's what i need, but the issue is that i can't seem to find any config file for a specific dungeon.
Inside my map folder  in the dungeons plugin  i only have 4 files  DXLdata/level.dat/session/ and a folder region.
No map config there.
The only configurable file i have is the main config of the plugin

**Comment by Sataniel98** [comment]
Not trying to be mean, but I am not sure what else I can say to clarify this, because this is exactly what you asked for in #479 and #480...

My reply from #479:
> You get the floor configuration by creating it. A floor configuration is optional and therefore not generated automatically.

Wiki (https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration):
> In case you’re confused because you do not find a config.yml file in your map folder: This is intended because a map does not necessarily need a config file. The values can also be fetched from the dungeon configuration, which is more convenient if a dungeon has multiple floors with the same rules, or from the main configuration, which might be more convenient if the game is very simple or for testing / building purposes.

**Comment by neox91120** [comment]
No i m just dumb.
When you said that i needed to create it i just didnt understand that ''I'' needed to create it.
I thoght there was some kind of ingame command to do but i just have to create i file and name it however xD
and then put in the settings
U have every right to be mean (to me xD).
You have been so helpful !
This plugin is great and that is why i keep insisting on getting help.
If there is anyway for me to help you i would not refuse !
Thanks a lot for your HELP !

**Comment by Sataniel98** [comment]
I'm glad it's clear now :)
