### ISSUE TITLE
Plugin does not start on 1.13.2

### ISSUE THREAD

**Issue by FixTheAdmin** [DRE2N/DungeonsXL#483]
### Expected behavior
Plugin should be enabled

### Actual behavior
Plugin is disabled on server start. Error message: https://hastebin.com/cafitahuna.css

### Steps to reproduce
Install dungeonesxl v0.17.1
Run papermc version git-paper-403 (MC:1.13.2)

**Comment by Sataniel98** [comment]
DXL 0.17.1 simply does not support 1.13.2. I'll update it this weekend.

**Comment by FixTheAdmin** [comment]
Thank you very much

**Comment by Sataniel98** [comment]
Fixed. A new build will be released this day.
