### ISSUE TITLE
[Question] how to allow interacting with armor stand without breaking blocks?

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#486]
Hi !

### Expected behavior
Players could take items on an armor stand and can't break any blocks

### Actual behavior
Players can't take items on armor stand and can't break any blocks

I'm using DXL version 17.1

I suppose that it's something in the config but i can't figure out where it is :(

**Comment by Sataniel98** [comment]
Does this help? :)
```
breakBlocks: false
# A list of all entity types 
# If this is left out AND if breakBlocks is false, armor stands
# and item frames will be protected by default.
# If this is left out and if breakBlocks is true, nothing will be protected by default.
interactionProtectedEntities:
- ARMOR_STAND
- ...
```
Note that leaving an option out and setting it to an empty list is not the same. Without having it tested, this should work:

```
breakBlocks: false
interactionProtectedEntities: []
```

**Comment by Tiplish** [comment]
I think that this new options are not in my dungeon config, i will fix it. Thanks :)
