### ISSUE TITLE
DXL 17.2

### ISSUE THREAD

**Issue by bambinidk** [DRE2N/DungeonsXL#487]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

DXL after server restart.
 Spigot 12.2

 When server has been restartet the plugin should worked before restart
 but it don't, it doesn't function at all. when i write /dxl edit [the worldname] it do nothing can't even use /dxl test or other dxl commands, looked at the log file no errors nothing with dxl appears.
 Can it be bossbar2.0.0 that corce the problem because thats the only plugin i have put in after i have made the dungeon and before reset the server.

And another thing how do players get their own items with them in the dungeon rather than an empty inventory.

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
If the commands don't respond, they are either overriden by another plugin or DungeonsXL isn't loaded correctly. This might be because of a YAML syntax error. Make sure to read the FAQ: https://github.com/DRE2N/DungeonsXL/wiki/faq

**Comment by bambinidk** [comment]
Thx i will look at it for the error

Hilsen kent

________________________________
Fra: Daniel Saukel <notifications@github.com>
Sendt: onsdag, oktober 31, 2018 00:08
Til: DRE2N/DungeonsXL
Cc: bambinidk; Author
Emne: Re: [DRE2N/DungeonsXL] DXL 17.2 (#487)


If the commands don't respond, they are either overriden by another plugin or DungeonsXL isn't loaded correctly. This might be because of a YAML syntax error.
