### ISSUE TITLE
Citizens lag.Is it compatibility?

### ISSUE THREAD

**Issue by nozuo** [DRE2N/DungeonsXL#488]
[timings2.txt](https://github.com/DRE2N/DungeonsXL/files/2543212/timings2.txt)
The timings of 8M will be running for 10 seconds.
Citizens lag.Is it compatibility?
I use sentinel. 
DungeonsXL uninstall NPC after unloading the world？

![image](https://user-images.githubusercontent.com/8280703/47926884-c307e700-defc-11e8-904a-e9c62cffff9e.png)

**Comment by Sataniel98** [comment]
I have also noticed that there's more upkeep than expected. I'm collecting data and working on it.

**Comment by nozuo** [comment]
> I have also noticed that there's more upkeep than expected. I'm collecting data and working on it.

![image](https://user-images.githubusercontent.com/8280703/47947746-3e00ea00-df5d-11e8-9096-a1fd33d0661e.png)
![image](https://user-images.githubusercontent.com/8280703/47947754-5cff7c00-df5d-11e8-9cc4-f23bc7899f27.png)

hello,After server running for some time, can not join the new game.can't test too.

**Comment by Sataniel98** [comment]
Should be fixed
