### ISSUE TITLE
[Question]Can I set the delay time to end dungeon？

### ISSUE THREAD

**Issue by ProperSAMA** [DRE2N/DungeonsXL#489]
Leave the dungeon after kill mobs is easy.(kill mob→leave dungeon at once)
But then I don't have enough time to pick up mob drop item...
Can I set the delay time to end dungeon？(kill mob→delay 10 seconds→leave dungeon)

**Comment by Sataniel98** [comment]
Why don't you just add for example an additional distance trigger sothat players have as much time as they need?

**Comment by ProperSAMA** [comment]
Sounds good!
But..How should I do it?
I placed one sign with “[End]” "M Zombie,D 8" and try to achieve this idea
But that has not been the case.I just got close and didn't kill the Zombie.The dungeon is over.
I saw wiki about Multiple Triggers.But this picture looks different from the text.

**Comment by Sataniel98** [comment]
#452
