### ISSUE TITLE
User verlieren Items nach beendigung des Dungeons

### ISSUE THREAD

**Issue by DuPleXFD** [DRE2N/DungeonsXL#49]
Hallo^^
Nach dem ich mehrmals alle Dungeons durchgetestet habe viel mir auf das die User ihre Items verlieren wenn sie 3 Leben verbraucht haben. Die Einstellung die das verhindern soll ist bei mir auf true. Leider kann ich dir keine Fehlermeldung geben :/ . ich benutze die neuste Spigot version und Java ist up to Date.

**Comment by Sataniel98** [comment]
Es sollte also so aussehen:
keepInventoryOnEnter: true
keepInventoryOnEscape: true
keepInventoryOnFinish: true

Ist das richtig?

**Comment by DuPleXFD** [comment]
ja alles steht auf true. habe es auch getestet: user gewinnt dungeon, kein prob [auch die lootverteilung funktioniert]. User beendet durch /dxl leave auch ok. user stirbt und spawnt im dungeon ebenso... nur wenn ich im dungeon meine leben aufgebraucht habe sind die sachen weg.

**Comment by Sataniel98** [comment]
keepInventory nervt ^^ Ich dachte, seit #19 würde es vorläufig funktionieren. Dann muss ich da wohl nochmal im Detail drangehen. Weiteres bitte in den ursprünglichen Issue :)
