### ISSUE TITLE
[Bug] Can't interact with armor stand

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#490]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior

Can take armor from an armor stand

### Actual behavior

Can't interact with an armor stand in a lobby

### Steps to reproduce

Create a dungeon, put an armor stand in, with stuff on it. Play the dungeon and... cry :(

i've used this config : 
https://pastebin.com/Wf2CMLGg

New clue: You have to hit the ready sign and you could interact with armor... not before. Strange no? :s

**Comment by Sataniel98** [comment]
Sorry for not getting back to you about this, but armor stands and item frames are by default protected from interaction. However if breakBlocks is true and nothing is specified, they are not protected.
