### ISSUE TITLE
BUG: Player stays in adventure mode after leaving dungeon 1.8.8!

### ISSUE THREAD

**Issue by GerwinVerkerk** [DRE2N/DungeonsXL#491]
When you start a dungeon and then leave using /dxl leave or click a leave sign, the gamemode you had in the dungeon will stay on you in the normal world. This goes for 1.8.8 and I don't know about newer versions. 

Example: 
When I join a dungeon that has adventure mode as gamemode I will keep adventure mode when I leave while I was survival mode in the original world!

**Comment by Sataniel98** [comment]
Fixed, thank you for the report!
