### ISSUE TITLE
Question: Where to find all possible config.yml options and custom values

### ISSUE THREAD

**Issue by GerwinVerkerk** [DRE2N/DungeonsXL#492]
Dear Daniel,

Where can I find all possible option and default values top put in the config.yml? 
Lines like these were very hard to find:

keepInventoryOnEnter: true
initialLives: 1
keepInventoryOnDeath: false
keepInventoryOnEscape: false

Is there a page on which I can find all of the possible customizations? I would also like to know how to make a dungeonspecific configuration. Maybe some update on the wiki can help with this?

Thank you for all of your great work thus far!

**Comment by Sataniel98** [comment]
Hi,
I'm sorry for the late reply. These values can be found at the game rules page of the wiki, and if something's missing, it's here.
https://github.com/DRE2N/DungeonsXL/blob/master/src/main/java/de/erethon/dungeonsxl/game/GameRuleProvider.java#L43
