### ISSUE TITLE
About Multiple Triggers

### ISSUE THREAD

**Issue by ProperSAMA** [DRE2N/DungeonsXL#494]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
1. play dungeon
2. kill mob
3. back to spawnpoint
4. end the dungeon

### Actual behavior
1. play dungeon
2. kill mob
3. end the dungeon
The two trigger only satisfies one.Sign active.
But wiki says "Only if all Triggers are triggered, the sign becomes active."
### Steps to reproduce
1. place a sign in point 1 with "[Mob]" "ssb" "0,1,MM" "D 10"
2. place a sign in point 2 with "[End]"(First Line) "M ssb,D 8"(Last Line)
3. place a sign in point 3 with "[Start]".point 3 is near the point2
4. The distance between the two points is far enough.

**Comment by tabels** [comment]
I have the exact same issue. I put W1,D3 on the last line and the game ends only when a player enters the radius of the sign. The wave is ignored. When I put D 3,W1 you just needed to kill all mobs, the radius was ignored. I tried every combination but none worked as expected.

**Comment by Sataniel98** [comment]
Hi,
this is a duplicate of #383. Thank you anyway for the report.
