### ISSUE TITLE
Group sign not working

### ISSUE THREAD

**Issue by Endothelium** [DRE2N/DungeonsXL#495]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Join a group when clicking on a group sign

### Actual behavior
Nothings happen
No logs
The sign remain the same

![image](https://user-images.githubusercontent.com/11161697/48808640-d0f1a080-ed21-11e8-8cb7-932372e3e062.png)

### Steps to reproduce
Import a map with /dxl import
Edit the map and add lobby and leave sign into the map
Create a group sign in the main world

[DXL]
Group
instance_name
2,2

or 

[DXL]
Group
instance_name
2,test

I am using spigot 1.13.2 

![image](https://user-images.githubusercontent.com/11161697/48808681-f41c5000-ed21-11e8-950d-9a25b5205227.png)

Thanks

EDIT: it doesn't seem like a compatibility problem with my others plugin. I just test on another spigot 1.13.2 with only dungeonXL loaded. It's the same, can't click the sign.

**Comment by Endothelium** [comment]
Ok it works in 1.13.1, so its 1.13.2 related

**Comment by Sataniel98** [comment]
Thank you for the report. This is the same as #497 and #498. The issue has been resolved in v0.17.4.

**Comment by FixTheAdmin** [comment]
Thank you!
