### ISSUE TITLE
Lives Config

### ISSUE THREAD

**Issue by GGNoPotato** [DRE2N/DungeonsXL#496]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Set lives in dungeon to any number besides unlimited

### Actual behavior
Everyone gets unlimited lives...

### Steps to reproduce
Tried putting config values for default and the script folder as well but nothing seems to change it.

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
Do you have another game rule source overriding the rules? I can't tell without having a look at your configs.
