### ISSUE TITLE
Floor configuration: Shall players play the dungeon with their own items

### ISSUE THREAD

**Issue by sn0wcl0ud** [DRE2N/DungeonsXL#499]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

Deutsch/German

### Expected behavior

Die Spieler sollen mit ihren eigenen Items spielen.

### Actual behavior

Ich weiß nicht, wie ich es konfigurieren soll.

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Explanation of the requested feature

Ich brauche eine Schritt für Schritt erklärung wie ich die config Datei einfügen soll. Ich verstehe diese Hilfe nicht: https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
Versuch die hier: https://github.com/DRE2N/DungeonsXL/wiki/simple-dungeon#settings
