### ISSUE TITLE
Map saving

### ISSUE THREAD

**Issue by Poweringg** [DRE2N/DungeonsXL#50]
Hi, i built dungeon, then i type /dxl save and /dxl leave and then i stopped the server. And next day i ran server again, and map look like this
![bez nazvu](https://cloud.githubusercontent.com/assets/15527318/14225677/49e48f3c-f8cb-11e5-846f-b20811cd02e1.png)

i'm running on - spigot 1.9.2
DXL version - dungeonsxl-0.11-SNAPSHOT-32

**Comment by Sataniel98** [comment]
I have no idea what could cause this :(

**Comment by Sataniel98** [comment]
It is (hopefully) an unrepeatable thing, I close this unless it happens again...
