### ISSUE TITLE
Bug with placing group signs

### ISSUE THREAD

**Issue by TrixRabbit21** [DRE2N/DungeonsXL#501]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Making a group sign with a max size of 4 should place the "new group" sign with another sign under it.

### Actual behavior
When placing it facing North or West, the second sign doesn't place directly under it.
![2018-12-21_22 05 03](https://user-images.githubusercontent.com/46063329/50371332-712f2500-056d-11e9-8c0a-dce101c27fe5.png)
![2018-12-21_22 04 54](https://user-images.githubusercontent.com/46063329/50371335-77bd9c80-056d-11e9-97db-0112c8ad7349.png)

### Steps to reproduce
Make a group sign with a max size of 4 while facing North or West.

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
Thank you for the report, it's fixed!
