### ISSUE TITLE
［suggest］add sign config

### ISSUE THREAD

**Issue by Sithme-Chu** [DRE2N/DungeonsXL#502]
I'm a player from China.
I want to customize the content of all the sign.
(Does not affect its original function）
Because not all Chinese players can read English so well. (for example, I'm not good at English)
maybe you can add a copy of config about sign？
( Why don't you fall into discord?）

**Comment by Sataniel98** [comment]
You can change the lines of signs in the language file just like all messages.

**Comment by Sithme-Chu** [comment]
but such as “pve limited “ I can't change it....

**Comment by Sataniel98** [comment]
Well yes, that should be the only case though and the default trigger signs for ready, classes and end signs are just shortcuts for convenience anyway. If you mind, you can use a trigger sign with custom text and have the ready sign triggered by that. It might be worth making sign scripts that include both the ready and trigger sign; you could use these as replacements for ready signs with the same amount of work to create them in dungeons.

**Comment by Sithme-Chu** [comment]
ok thanks！
