### ISSUE TITLE
Fortune Trigger not working with chest reward

### ISSUE THREAD

**Issue by Endothelium** [DRE2N/DungeonsXL#504]
### Expected behavior
Fortune trigger apply a loot chance on chest reward

### Actual behavior
Whatever fortune value i put, it seems there is a 100% chance for the chest reward

### Steps to reproduce
Create a sign

[Chest]
1000,15

F 0.1

With a chest near

**Comment by Sataniel98** [comment]
Duplicate of #477. Thank you anyway for the report :)
