### ISSUE TITLE
I can't put signs on door

### ISSUE THREAD

**Issue by FunkyJamma** [DRE2N/DungeonsXL#505]
ok, guys, I have an issue, I am trying to put a sign on a door so I can trigger it. But when i attempt to place the sign the door opens and it wont place. the only door i am able to place a sign on is the steel door. and the open door trigger like in the wiki example doesnt seem to work with steel doors. 

Is there a way to use the sign with a steel door? maybe i can use the sign to trigger the lever?

**Comment by Sataniel98** [comment]
Hi,
try sneaking while placing the sign.

**Comment by FunkyJamma** [comment]
awesome this worked
