### ISSUE TITLE
Copy deletion problem

### ISSUE THREAD

**Issue by xiaoguo233** [DRE2N/DungeonsXL#506]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)
Why did I create more than 8,000 copies of the map and about 200 of them were not automatically deleted?

**Comment by Sataniel98** [comment]
I am aware of this. Screenshots I have seen show sizes of only a few bytes for these folders, so I don't think they are still loaded but mostly deleted. Not sure what exactly makes them stay, I'll have a look at it.

**Comment by Sataniel98** [comment]
OK this doesn't seem to be true: The region files are still loaded and some reference keeps them alive.
