### ISSUE TITLE
/Play not working correctly [1.13.2]

### ISSUE THREAD

**Issue by andfoster** [DRE2N/DungeonsXL#507]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
/dxl play {World name} would let me play the dungeon I made in the {world name}

### Actual behavior
Teleports me to the world without any signs rendered

### Steps to reproduce
do /dxl play

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
Hi,
this is intended. /dxl play does not start games - ready signs do. Few signs are instantiated before the game starts.

**Comment by andfoster** [comment]
I want to have an item where when users right click it it runs a command. I was hoping that there's a way to put players in the dungeon without them clicking a sign? Signs are a little old-fashioned

**Comment by Sataniel98** [comment]
You can use any trigger for ready signs, like item triggers, instead of the default sign interaction trigger.
