### ISSUE TITLE
My Loot Table isn't working correctly. (Not A bug I just need help!)

### ISSUE THREAD

**Issue by andfoster** [DRE2N/DungeonsXL#508]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

Here's my "commonChest.yml" file inside of loottables
https://gyazo.com/afe1844f0687f4df9fa8291bb2d694d5

Here's my chest
https://gyazo.com/e8915526c53c74fd2ff9d0cb48e9e8eb

When in game it shows up as
"Please ask an admin to fix" (Something along those lines)

Thanks! Happy new year!

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
A happy new year to you, too! Chest signs transform the signs in near by them into reward chests. Place one next to the sign.

**Comment by andfoster** [comment]
Any way to put physical items in a chest randomly? Something like how most hunger games work

(Sorry for all the questions)
