### ISSUE TITLE
Any way to put physical items in a chest randomly? Something like how most hunger games work

### ISSUE THREAD

**Issue by andfoster** [DRE2N/DungeonsXL#509]
Any way to put physical items in a chest randomly? Something like how most hunger games work

(Sorry for all the questions)

_Originally posted by @andfoster in https://github.com/DRE2N/DungeonsXL/issues/508#issuecomment-450738990_

**Comment by Sataniel98** [comment]
A feature like this doesn't exist yet, but I like the idea and it shouldn't be hard to realize as it's practically the same as a chest sign but the items are put into the chest instead of the loot inventory.
