### ISSUE TITLE
A bug with Trigger `WAVE`

### ISSUE THREAD

**Issue by MikuSnow** [DRE2N/DungeonsXL#515]
I have set 30 mob signs
```
[Mob]
MM_Mob
1,1,MM

```
But I have kill all the mob, the count is 28.
And I test many times. Sometimes mob counts is 30.
And the problem is : Sometimes the mob spawn then they disappear immediately.

**Comment by Sataniel98** [comment]
Mobs disappearing for no reason is an issue with the respective mob provider plugin, please report it to them as a mob spawned through a console command in a custom world.
