### ISSUE TITLE
Loot tables bug

### ISSUE THREAD

**Issue by KreLLeR564** [DRE2N/DungeonsXL#517]
Trying to get the loottables to work.

I tried to put the example text in wiki into http://www.yamllint.com and then put it into a yaml file and put it into loottables folder and it's not working.

I've been working on trying to get the loottables to work for all evening and nothing is working.

Hope for some help.

**Comment by Sataniel98** [comment]
Well, I'm sorry about that, but I can't do more than being sorry about it if you don't follow the issue template.

### Expected behavior
What did you do and what did you expect DungeonsXL to do?

### Actual behavior
What exactly happened instead and how does it not match your expectations?

### Steps to reproduce
Including information about your setup.

**Comment by KreLLeR564** [comment]
This is the file im using with that is a yaml file named: loottest
--- 
0: 
  chance: 75.0
  item: 
    ==: de.erethon.caliburn.item.ExItem
    amount: 3
    attributes: 
      nameOfFirstAttribute: 
        amount: 8.5
        operation: ADD_NUMBER
        slots: 
          - MAIN_HAND
          - OFF_HAND
          - HEAD
          - TORSO
          - LEGS
          - FEET
        type: GENERIC_ATTACK_DAMAGE
      nameOfSecondAttribute: 
        amount: 8.5
        operation: ADD_NUMBER
        slots: 
          - OFF_HAND
        type: GENERIC_MOVEMENT_SPEED
    enchantments: 
      PROTECTION_ENVIRONMENTAL: 4
      THORNS: 1
    itemFlags: 
      - HIDE_ATTRIBUTES
      - HIDE_ENCHANTS
    lores: 
      - "&4This is the first line."
      - "&6This is the second line."
    material: STICK
    name: "&4CustomName"
    type: DEFAULT
1: 
  chance: 100.0
  item: "261,1,16"
2: 
  chance: 37.5
  item: 
    ==: org.bukkit.inventory.ItemStack
    amount: 1
    damage: 55
    type: IRON_SWORD

**Comment by KreLLeR564** [comment]
the reward still gives xp and money but doesnt give items, just shows: have been added to your loot inventory.

**Comment by Sataniel98** [comment]
This still doesn't follow the template. I can't tell what you have done with and how you have used this script. If you are still having trouble, please open a new issue that follows the template.
