### ISSUE TITLE
How to implement the plugin "Boss"

### ISSUE THREAD

**Issue by Zedryx** [DRE2N/DungeonsXL#526]
I dont understand the wiki when it comes to the externalMobProviders in the main config. 

my spawn command for bosses is "/boss spawn world x y z bossname"

How do i implement it into the config? What are the exact lines? Ive tried so much already but nothing works

**Comment by Sataniel98** [comment]
Hi, that would be for example:

```
externalMobProviders:
    BS: boss spawn %world% %x% %y% %z% %mob%
```

Regards
