### ISSUE TITLE
[Bug] Block Signs are broken

### ISSUE THREAD

**Issue by arnhav** [DRE2N/DungeonsXL#528]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Working block signs

### Actual behavior
Every block sign does not work in a dungeon.

### Steps to reproduce
Latest release version. 
Load up a dungeon with block signs

I believe this was due to the updates to the Caliburn API

**Comment by Sataniel98** [comment]
Which Minecraft version do you use?

**Comment by arnhav** [comment]
1.13.2

**Comment by arnhav** [comment]
Any update on this issue?

**Comment by Sataniel98** [comment]
I'm working on different bugs at the moment and will review this one once that is done.

**Comment by Sataniel98** [comment]
Just tested them and they work without issues. Are you running the latest version (0.17.4 or a 0.17.5 snapshot)? What exactly happens?

**Comment by arnhav** [comment]
We were working with 0.17.4 and the block sign upon playing a dungeon would simply have an error message. I am currently trying out the latest snapshot to see if it fixes the issue.

**Comment by Sataniel98** [comment]
The console log should in that case show information about what exactly is wrong with the signs.

**Comment by arnhav** [comment]
Here is the error:
https://pastebin.com/DTqsbJKw

**Comment by Sataniel98** [comment]
Are you running ItemsXL?

**Comment by arnhav** [comment]
Yes I am

**Comment by Sataniel98** [comment]
Which version?

**Comment by arnhav** [comment]
0.5.3

**Comment by Sataniel98** [comment]
IXL 0.5.3 doesn't support 1.13.2. Updating to 0.5.4 should resolve the problem.

**Comment by arnhav** [comment]
I updated to 0.5.4 but I'm still getting the same error

**Comment by Sataniel98** [comment]
I have tested it with the master of DungeonsXL and ItemsXL 0.5.4. It works well.

**Comment by arnhav** [comment]
Yea, it required a restart. Thanks for the help!
