### ISSUE TITLE
Error with Group sign

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#530]
**_English (approx)_**
Hi , 

I have problem with sign , it's work but when i restart my server any of sign seems doesn't work... i don't know why ? maybe the location ? I have any Error in my console

I see in my data.yml. half of my sign have disappear but in my world he is always present.
there is a game capture for sign location.
[image](https://i.imgur.com/CVc2lfo.png)

ps: when i rewrite the file when the server is offline , it's seems to be work but i don't knwo why and for how much time ...

Thanks for help

**_FR_**
Salut, 

J'ai un problème avec le plugin, ça fonctionne impeccable jusqu'a ce que je redémarre le serveur. Les panneaux sont toujours la mais la moitier seulement fonctionne encore. Dans le fichier data.yml, j'ai pu voir que certain de mes tableaux n'y était plus. Alors que les panneaux dans le monde sont bien présent mais comme plus présent dans le fichier, on ne peux plus intéragir avec eux. 

Voici une capture d'écran des panneaux et seulement ceux non surligné fonctionne. 
[image](https://i.imgur.com/CVc2lfo.png)

Ps: en modifiant le fichier data.yml une fois le serveur hors ligne les panneaux semblent de nouveau fonctionner mais pour combien de temps ? 

Merci pour l'aide

**Comment by Sataniel98** [comment]
Hello,

I believe your issue is a duplicate of #447 and #513, which have already been addressed in the latest builds. Thank you anyway for the report. If I am mistaken and if the problems persist in the latest dev build, please let me know.

~ Regards, Sataniel

(PS: Even if I reply in English, writing issues in French is fine.)

**Comment by skyfyx** [comment]
Re, the problem persist i'm in 0.17.4 and when i restart my server half of my sign group didn't work. ( even DXL Leave group sign).

Re, le problème persiste je suis en 0.17.4 et quand je restart mon serveur la moitié de mes panneaux ne fonctionne plus. (Même les panneaux Dxl Leave sont affecté)

Encore merci pour tout tes efforts !
Thanks for all your work !

**Comment by Sataniel98** [comment]
I was referring to the latest dev builds. https://erethon.de/repo/de/erethon/dungeonsxl/

**Comment by skyfyx** [comment]
Oh ok :) , i'm looking forward to it !

**Comment by Sataniel98** [comment]
Please let me know if it works! The dev build server will be up again soon.

**Comment by skyfyx** [comment]
you have resolved this problem in the latest ? i'm gonna try i tell you soon. ( URL not found )

**Comment by Sataniel98** [comment]
Yes, and the build server will as I said be fixed soon.

**Comment by Sataniel98** [comment]
@skyfyx It is fixed and as of now builds are uploaded again.
