### ISSUE TITLE
Gamerules

### ISSUE THREAD

**Issue by Nim54321** [DRE2N/DungeonsXL#531]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
add gamerules to the config.yml not working

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Explanation of the requested feature
Just need help figuring out how to add gamerules to my congfig.yml si they enable in game.

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
Hi,
please use either the wiki or follow the template to ask questions.
