### ISSUE TITLE
Setting lives/cooldown [Question]

### ISSUE THREAD

**Issue by Scabista** [DRE2N/DungeonsXL#532]
Just sort of curious how to go about setting the lives a player has per dungeon run, and the cooldown between running a dungeon. I've looked at the "game rules" page, but that doesn't really give me the information I need.

**Comment by Scabista** [comment]
#q

**Comment by Sataniel98** [comment]
Does the simple dungeon tutorial help you? https://github.com/DRE2N/DungeonsXL/wiki/simple-dungeon Setting cooldown & lives works just like that. See the floor configuration page for a visual example how each game rule looks set through a YAML config: https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration

**Comment by Scabista** [comment]
Thank you so much. I guess I was just confused a bit, the way you worded everything here helped clear things up for me. :)
