### ISSUE TITLE
Block command in Dungeon ? 

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#533]
Hello , 

I don't knwo where i can ask question .. so i create this post because i don't find any answer. 
it's possible to block permission in dungeon ? like fly ? please

Thank you very much

**Comment by Sataniel98** [comment]
Hi,
your permission plugin should allow you to limit permissions to worlds.

**Comment by skyfyx** [comment]
yes but it's a virtual world created by dxl ? so if i go in dxl edit i can't add perm on this world ?

**Comment by Sataniel98** [comment]
You can _add_ permissions through the editPermissions section in the main config. But _blocking_ them is something that should be realized by simply not granting them for every world in your permissions plugin.

**Comment by skyfyx** [comment]
Re, yes but i have problem when a player have fly command in world and he is enter in donjon he's keep fly.
I don' t know if t's understandable

**Comment by Tiplish** [comment]
I don't know if it could help you but : if you add a "negative permission" like -essential.fly , it disables the permission, even if the player has the permission when he enters in the dungeon or inherited from a grade.

**Comment by skyfyx** [comment]
i'm gonna try Tiplish thanks ;) 

ps: i can't because i've not the name of the world for make that , because it's a generated world by dungeonXL( sorry if it is understandable)

ps2: i've try with name of dungeon it's doesn't work. if i fly before i can fly in dungeon

**Comment by Sataniel98** [comment]
As I said, you should do it the other way around... Forbid the permission in general. Allow it specifically in the worlds where it should be allowed.

**Comment by Tiplish** [comment]
What permission plugin do you use skyfyx?

**Comment by skyfyx** [comment]
I use Luckperms Tiplish.

I can't Sataniel because when he's type the command in world , he's keep in other world.

En fr, quand il utilise la commande dans le monde général, il l'a garde quand il rentre dans le donjon. ça reset pas les commandes ;) .Du coup il faudrait que j'enléve le fly pour le skyblock, c'est pas cool ..

**Comment by Tiplish** [comment]
https://www.reddit.com/r/admincraft/comments/76hi8n/luckperms_user_worldspecific_perms/

Je ne sais pas comment tu as géré tes grades/permissions. Mais en gros si tu précises les permissions par monde au lieu de global, quand il va aller dans un donjon, il n'aura plus ces permissions :) 

I don't know how you have managed your permissions. But if you define your permissions per world and not globaly, when the player enter in a dungeon, i will not have the per world permissions :)

**Comment by skyfyx** [comment]
Tiplish c'est déjà fait mais j'ai essayé avec le nom du monde et en faite ça désactive pas le fly de base. Je ne parle pas de la commande. Il faudrait un truc qui force un unfly mais ça existe pas.

yes Tiplish I've already done it but I tried with the name of the world and the 'fly' is not deactivated. I wasn't talking about the command. I'd need something that can trigger an 'unfly' but it doesn't exist.

**Comment by Sataniel98** [comment]
OK, that should be handled by DXL. I've added an issue (#535) for the improvement and will tag you @skyfyx when a dev build that contains the fix is available. I'll close this one in favor of it.
