### ISSUE TITLE
Dev Builds Year

### ISSUE THREAD

**Issue by Segysmundo** [DRE2N/DungeonsXL#534]
It's 2018 all over again! 😮

![image](https://user-images.githubusercontent.com/19178945/52355395-8a633680-2a32-11e9-83eb-57be7ab4e2b4.png)

**Comment by Tiplish** [comment]
It's a rollback i think o/

**Comment by Sataniel98** [comment]
Thanks for making me aware ^^ I'll fix this at the next opportunity.

![](https://media.giphy.com/media/1iOFuymd9jB2o/giphy.gif)
