### ISSUE TITLE
Lava bucket and Water bucket

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#536]
Hi , 

Again me .. sorry if i spam or anything else , i wanted to help.
I have find an another problem ... Player can use lava bucket and water bucket in Dungeon.
And i can't blocked this ( like fly ).

Thanks for your plugin!

**Comment by Sataniel98** [comment]
Hi again!

Please don't hesitate to ask, you're welcome to do so, that's what this issue tracker is for. Have you configured anything concerning breaking and placing blocks in the game rules (/ the map config file)?

**Comment by skyfyx** [comment]
Hi , i don't find any configuration for rules in config files on wiki. Even for command it's not possible to add any command, because if i add a commande in edit mode it's doesn't work in play mode. Because the world created have an antoher name :)

**Comment by Sataniel98** [comment]
I mean this: https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration

For commands in games, see the gameCommandWhitelist section.

**Comment by skyfyx** [comment]
Omg! you are the best it's exactly what i'm looking for !for command! 
But for lava_bucket and water_bucket it's doesn't work the only choice is forbidden this item for now , because kill a mob or boss with lava it's to easy :)
