### ISSUE TITLE
Wave Limit ?

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#540]
Hello , 

How i can set the limit of wave ? exemple after Wave 5 the player will be teleported and the wave stop to spawn mob ? ( i don't know if it's really english)

Comment je peux faire en sorte de limiter à 5 Vagues et ensuite téléporter le joueur et aussi stopper que les mobs ne spawn ?

Merci , Thank you ;)

**Comment by Sataniel98** [comment]
See [here](https://github.com/DRE2N/DungeonsXL/wiki/signs#progress) and also #383.

**Comment by skyfyx** [comment]
i found i'm in shame ... because now i've an another question? i can post here and we closed the issue ? or you have just a discord name ? more simple for just one question

my discord name if you want : SkyFyx#2775

ps : because i've a lot of question , simple i think but i'm understanding.

**Comment by Sataniel98** [comment]
I usually don't support through Discord, but you may open as many issues as you want. Please create one per question.
