### ISSUE TITLE
Order of signs for floors and waves

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#541]
Hello ,

I have a question for orders of sign. What is the exactly way ? 

Lobby -> ready -> start -> Waves -> end(trigger P 0/1) and for set to floor 1 is end ( for next floor trigger P 1/1) ? Or starting sign of the next floor ? ( maybe start sign, with floor specified?)
Sorry if is not understandable.

J'ai une question , quel est le sens dans lequel on doit mettre les panneaux ? 
Lobby -> ready -> start -> Waves -> end(trigger P 0/1)  et comment faire en sorte que le floor soit terminé ( pour le prochain Trigger P 1/1) ? Ou comment définir le prochain étage ? ( peut étre le panneau start avec l'étage spécifié ?)

for now i'm here but i don't understand why the end teleport the player out of the dungeon.
[Image](https://ibb.co/mBTcWWv)
and in the next room ( floor ) , i have make a sign with [Floor] in the first line and floor_02 for the second line ( name of the floor )

Thank you again :)

**Comment by Sataniel98** [comment]
P x/y is triggered when x floors and y waves are finished. So P 0/2 is triggered in any floor after 2 waves are finished. It probably doesn't send you to a floor because you started the game by specifying the name of the map instead of the name of the multi floor dungeon script to join the floor: https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration

**Comment by skyfyx** [comment]
I test the donjon with /dxl test, but i've make the config floor in config.yml , i need to create an another config file with the name of dungeon ?  

But the configuration of the signs seems to be correct ?

**Comment by Sataniel98** [comment]
/dxl test automatically tests the single floor dungeon that is generated automatically for each created map. A dungeon config is necessary to link floors in separate maps together.

**Comment by skyfyx** [comment]
i have made the floor on the same map.... i don't undesrtand i need to rename my config.yml for a name of
dungeon ? or just i need to make test with dxl play ?

**Comment by Sataniel98** [comment]
If everything that shall be played is in one map, use a teleport sign instead of an end sign.

**Comment by skyfyx** [comment]
ok i'm gonna try but I don't know how to precise the trigger of a specific wave .. because in my dungeon I want to have 10 different waves. that's why I want to use the floor system.

**Comment by Sataniel98** [comment]
Just like you did it, P0/1 is the first wave, P0/2 the second one and so on.

**Comment by skyfyx** [comment]
yes ok it's work fine :) , thank you sometimes i'm very slow ... but maybe one day i'm gonna understand the principe of floor :p

**Comment by skyfyx** [comment]
Oh ok but the next wave continue to spawn after i have teleported the player .. a way to stop this ?

**Comment by skyfyx** [comment]
ok another problem i can't create more than 1 sign with wave because it's deactivate all Wave signs.

Ps: its' not really like that , i think it's an internal probleme because when i remove the sign , it's doesn't work again.... when i remove all Wave sign and i replace just one it's does'nt work ...

Ps2: it's work when i remove all Mobs sign in other room, because the wave try to trigger the other sign in other room but he can't because it's not what i  need. And because i've set a Distance trigger very low ...

**Comment by Sataniel98** [comment]
It surely is an internal problem. I am aware that wave signs being dungeon-wide without the possibility to group mobs together makes them pretty useless, and that the inconsistent trigger mechanics don't make it better. Both are more or less the biggest unfinished features in DungeonsXL.

See #383 and #452.

**Comment by skyfyx** [comment]
oh ok thanks man :) , if you need some help tell me :) 
bon courage !

**Comment by Sataniel98** [comment]
If you feel like it, you can comment your ideas and thoughts about better systems in the respective issue :)

**Comment by skyfyx** [comment]
it's not possible to trigger a mob with a P 0/3 for exemple, because the wave doesn't work too ...
