### ISSUE TITLE
Chat prefixes

### ISSUE THREAD

**Issue by Gandalf-Le-Dev** [DRE2N/DungeonsXL#543]
Hello, it seems that the chat prefixes aren't working at all, i have disabled every chat modifier (essentials, deluxechat etc...)

**Comment by Sataniel98** [comment]
Hello @ArKeid0s,
I can't reproduce this.
![2019-03-01_19 13 02](https://user-images.githubusercontent.com/8921300/53657411-63290f00-3c56-11e9-9453-2e2ae11219c2.png)
![2019-03-01_19 13 33](https://user-images.githubusercontent.com/8921300/53657421-6623ff80-3c56-11e9-9fbb-54a8595f9d7e.png)
![2019-03-01_19 14 05](https://user-images.githubusercontent.com/8921300/53657422-67edc300-3c56-11e9-84ce-195662404c41.png)

Please make sure to use the issue template where possible. I can't help you without knowing what exactly you are expecting to happen / trying to achieve and what you are doing to get it to work.

From what you've written, it looks like there is either some plugin you missed that overrides chat events, or that the players didn't even enter the "/dxl chat" channels.

~Best regards, Sataniel

**Comment by Gandalf-Le-Dev** [comment]
Sorry my bad I didn't knew that I should enter the dungeon chat is their a way to automatically enter the dungeon chat when I join a game ? And is there a way to display the group name even outside of the dungeon for example with deluxe chat ?
Thanks for your fast answer btw.

**Comment by Sataniel98** [comment]
You can use a command sign for this: https://github.com/DRE2N/DungeonsXL/wiki/signs#command

Other chat channels aren't modified by DungeonsXL.

**Comment by Gandalf-Le-Dev** [comment]
Just one more question what are the incompatibilities with Towny ?

**Comment by Sataniel98** [comment]
See this post and the following messages: https://www.spigotmc.org/threads/dungeonsxl.78142/page-66#post-3295057

**Comment by Gandalf-Le-Dev** [comment]
Thanks 
Just for you to know for the moment I have no problem with both plugins just one bug sometimes after a restart my sign placed in a town doesn’t work anymore they are no more considered as dxl blocks
