### ISSUE TITLE
[Cmd]Error

### ISSUE THREAD

**Issue by inrh** [DRE2N/DungeonsXL#544]
Sorry, my English is not good, I use Google Translate
**Description**

[//]: # (A clear and concise description of what the bug is.)

Error
When...（look image）
![qq 20190302144213](https://user-images.githubusercontent.com/39998280/53678400-77721800-3cf9-11e9-8b33-f636c327cd88.png)
![qq 20190302113849](https://user-images.githubusercontent.com/39998280/53678403-7e008f80-3cf9-11e9-9376-881134992a46.png)

**Comment by Sataniel98** [comment]
Hello and thank you for the report. I'll fix it as soon as possible.

**Comment by Sataniel98** [comment]
Anyway, you need to specify an executor, for example the console.
