### ISSUE TITLE
bug with gamerules

### ISSUE THREAD

**Issue by Gandalf-Le-Dev** [DRE2N/DungeonsXL#547]
**Description**

I have followed your guide on simple dungeons but even with the created confine.yml file into my map folder the game rules does not apply. One more thing pitman are spawning true portals with a nether texture :/

**Reproduce**

used /dxl create Name then I put a lobby sign, a ready sign a start sign and a leave sign in the map
in the big world I have created a group sign a ready one and a portal

**Expected behavior**

keep the inventory of the player when he enter, die and leave the dungeon

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
default :
  keepInventoryOnEnter: true
  keepInventoryOnFinish: true
  keepInventoryOnDeath : true

```

**Comment by Sataniel98** [comment]
It's supposed to be called config.yml, not confine.yml. The configurations you provided are a default section of the main config.yml at plugins/DungeonsXL/config.yml. A floor configuration (plugins/DungeonsXL/maps/{map name}/config.yml) does not have the values nested into any section.

**Comment by Gandalf-Le-Dev** [comment]
That is the part that I have not understood on the wiki, how do I create multiple floors ? Do I have to create on map for eache floors ? Or can I just put multiple start sign and end signs ?

**Comment by Gandalf-Le-Dev** [comment]
I have deleted my config.yml file in my map folder and I have done that 
```
configVersion: 16
language: french
enableEconomy: true
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
default:
  isLobbyDisabled : true
  keepInventoryOnEnter : true
  keepInventoryOnDeath : true
  keepInventoryOnFinish : true
  keepInventoryOnEscape : true
```

I have no dungeon script just a map because I want this dungeon to be a single floor dungeon but can you explain me how to do multiple floors as I said before I havent understood your wiki

**Comment by Sataniel98** [comment]
Yes, linking together floors is the point of multi floor dungeons. Multiple starts signs simply set different start points for different groups. Creating a dungeon script is creating an MFD, nothing else is needed. Just use the name of the script where you'd usually use the floor name.

**Comment by Gandalf-Le-Dev** [comment]
So how do I define the start point of each floors ? 
And is my code right in the config file because I does not work :/

**Comment by Sataniel98** [comment]
With a start sign. The first floor needs a lobby like any dungeon. And yes, your config looks correct, but isLobbyDisabled only applies to single player dungeons.

**Comment by Gandalf-Le-Dev** [comment]
My default setting precise above in the main config file does not work when I enter the dungeon my inventory is cleared

**Comment by Sataniel98** [comment]
Can't reproduce this, inventories are kept as they should.

**Comment by Gandalf-Le-Dev** [comment]
I found a way to keep my inventories but now I can't create MFD ...
