### ISSUE TITLE
Can't delete portals

### ISSUE THREAD

**Issue by BeeKii** [DRE2N/DungeonsXL#548]
I can't seem to figure out how to delete portals. Anyway that I can do this?

**Comment by Sataniel98** [comment]
Use /dxl break.

**Comment by BeeKii** [comment]
I've done that, the portal still persists.

**Comment by Sataniel98** [comment]
Break it?

**Comment by BeeKii** [comment]
I did, it vanishes. But still tells me to be in a group when I pass through it. And the portal fully rematerializes when I restart the server.
