### ISSUE TITLE
Mob names

### ISSUE THREAD

**Issue by Aeyori** [DRE2N/DungeonsXL#552]
**The feature you'd like to know more about**
[//]: # (e.g. game rules)
How to spawn mobs

**Link to the wiki article (in case it exists)**
None I believe
**What did you already try?**
I tried typing Wither Skeleton, wither_skeleton and witherskeleton but none of them spawn it, as well as Evoker and Vindicator. I'm not sure what I'm typing wrong or if I need more prefixes or something. Zombies, husks, strays, silverfish, and skeletons are spawning for me (they're the ones I've tried atl)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
WITHER_SKELETON, EVOKER and VINDICATOR should work fine. Make sure you're running the latest version of DungeonsXL and ItemsXL in case you're using it.

**Comment by Aeyori** [comment]
Okay I just checked and everything is working now! I was using Wither skeleton before and now I added in the line, and for the Evoker and Vindicator I had the wrong trigger number! Thank you (:
