### ISSUE TITLE
Any command are not blocked in dungeon

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#553]
Hi, 

I have question / Trouble , all player can have access to just 1 command in dungeon (/shop).
And this command is not fair because, i've sell in this shop "ender pearl" and in this config file i block them.

So my question is it's possible to make a blacklist command ? ( for block /shop command)

There is my config.yml
[https://pastebin.com/RRF0Gp70](https://pastebin.com/RRF0Gp70)

Thanks ;)

**Comment by Sataniel98** [comment]
All commands are normally blocked unless players have the dxl.bypass permission node, so a blacklist shouldn't really be needed. Which plugin do you use for the shop? If other commands are correctly forbidden, "shop" must either be whitelisted somewhere else like in the main config or handled by its plugin in an unorthodox way that DXL doesn't recognize.

**Comment by skyfyx** [comment]
i'm use shopGuiPlus for shop . And it's my main config file from DungeonXL:

[https://pastebin.com/CBJwJtbv](https://pastebin.com/CBJwJtbv)

Thanks for you help , again :)

**Comment by skyfyx** [comment]
i have found this line in config from shopGuiPlus : 
`disableShopsInWorlds: []`
but i have no name of world because the world is generated with dungeonXL and have a specific name like "DXL_GAME_1" so i can't block the shop on a specific world

**Comment by skyfyx** [comment]
Any idea Sataniel ? :)

**Comment by Sataniel98** [comment]
No, I'm afraid I don't know why the shop command behaves differently in this case. It's hard to tell if they are doing anything different since ShopGUIPlus is proprietary.
