### ISSUE TITLE
Problems with deleting maps and reloading

### ISSUE THREAD

**Issue by Lunki51** [DRE2N/DungeonsXL#554]
**Description**

Hi, by using you're plugin , i came across two major problems.First, the files doesn't seem to delete themself even after a player left the dungeon.The only way i found to remove them automoticaly is by using /reload or /dxl reload.But this cause an another problem, when entering a dungeon after a reload, the plugin send you into a empty flatt world instead of the desired dungeon.The only way i found to fix that problem is by entering the edition of the dungeon and then leaving it.Dungeons seem to work correctly only when them been edited before.

**Reproduce**

This bug seem to appear only on my server on linux.I tried on a local windows server with the sames plugins but i can't manage to have the same bug.
On local server, the local files does not delete themself on reload but only on server restart

**Screenshots / GIFs / videos**

Sadly, there is no error catch in the console
Here is a video that i made to illustrate the bug.Sometimes, it take me one or two try to encounter a flat map :

https://youtu.be/Fz0h1uevD2E

I'm ading a list of all my installed plugins : 
[Plugins.txt](https://github.com/DRE2N/DungeonsXL/files/3015219/Plugins.txt)

I hope you will find a solution.
Continue your work, your plugin is very good.

PS : Sorry for the spelling mistakes, english is not my native language

**Comment by Sataniel98** [comment]
Hello and thank you for the report. Game instances not being deleted correctly is a known issue (#506), but the problem with empty flat worlds after reloads is a different topic. Are DXL_Game_* worlds registered in Multiverse and have entries in its worlds.yml file?

**Comment by Lunki51** [comment]
I did not registered the DXL_Game_* worlds in Multiverse and there are not in the worlds.yml file.Should I ?

**Comment by Sataniel98** [comment]
No, you should not.

**Comment by Sataniel98** [comment]
The error that the worlds aren't removed is fixed. I still can't reproduce the flat world issue, but it looks very similar to one I once had with Towny and DungeonsXL. Could you tell me if the issue still occurs in a clean environment without any plugins but DungeonsXL?

**Comment by Lunki51** [comment]
The issue don't seem to occur anymore with this new version.
Maybe the issue was the old instances who were creating interferences.
Thanks for the support, great plugin.
