### ISSUE TITLE
Title not use trigger

### ISSUE THREAD

**Issue by 0Lamplight0** [DRE2N/DungeonsXL#555]
[https://proxy.spigotmc.org/199e710dfed5b05db6b2a5fc65183f3a9c66c3ec?url=https%3A%2F%2Fcontent.screencast.com%2Fusers%2Faa9412%2Ffolders%2FDefault%2Fmedia%2Fed3dd38f-fade-4847-a5e0-70d9427f1d08%2F321.png](url)

[https://proxy.spigotmc.org/199e710dfed5b05db6b2a5fc65183f3a9c66c3ec?url=https%3A%2F%2Fcontent.screencast.com%2Fusers%2Faa9412%2Ffolders%2FDefault%2Fmedia%2Fed3dd38f-fade-4847-a5e0-70d9427f1d08%2F321.png](url)

Not  work

**Comment by 0Lamplight0** [comment]
![QQ截图20190328012534](https://user-images.githubusercontent.com/49027172/55163200-4d9afc80-51a4-11e9-8c5d-3aba69b67eee.png)
Not work age. pls help me

**Comment by Sataniel98** [comment]
Duplicate of #452
