### ISSUE TITLE
Loot Tables

### ISSUE THREAD

**Issue by fatmanjumprope** [DRE2N/DungeonsXL#557]
I need some help figuring out what I'm doing wrong in my loottable config. I'm trying to set up some loot the players can only obtain and use while in the dungeon. When I open the chests in the dungeon however, they are empty. 

I've tried looking through all the issues related and looked through the spigot forum page but still couldn't find much help. I've tried to replicate other configs I've found but that doesn't seem to make anything happen.

Below is what my loottable.yml looks like at the moment.
```
0:
  # This is the simple way to store items.
  # Valid input:
  # The first value may be any ID (be it a Vanilla ID or an ID of an ItemsXL item), 
  # the second value is the amount
  # and the third, optional value is the durability value.
  item: "261,1,16"
  chance: 100.0
```

**Comment by Sataniel98** [comment]
I don't see any mistakes. Please follow the issue template for questions and explain in detail how you're using the loot table.

**Comment by fatmanjumprope** [comment]
I apologize, I thought I was using the correct format. 

explain in detail how you're using the loot table:
I've created a loottable named gear1.yml and placed it into the scripts/loottable section of Dungeonsxl. the loot table I posted in my original post is what's inside gear1.yml. I've only added the one single item for testing purposes. Inside my dungeon I have a sign on a chest that says [Dungeonchest] on the top line 2nd line is blank and the 3rd line is set to gear1. I have nothing placed inside the chest. I intend these items to be only items a player can collect and use inside the dungeon. Once I launch my dungeon for testing however, no items appear in the chest with the sign on it.

https://github.com/DRE2N/DungeonsXL/wiki/scripts#loot-tables

**Comment by Sataniel98** [comment]
> Once I launch my dungeon for testing however, no items appear in the chest with the sign on it.

This seems to be the issue. If I understood this correctly and the sign still appears next to the chest, then the sign has not been initialized at that point. Note that most signs aren't initialized before the game starts, which is done through a [ready] sign. Ready signs automatically become clickable if no trigger is specified.

**Comment by fatmanjumprope** [comment]
Ahh, I apologize again. I'm having some trouble putting into words what my issue is. I have clicked the ready sign and started the dungeon before opening the chest. The sign is invisible and it's just a chest inside the dungeon. Once I attempt to open said chest however, the bow from the loottable isn't inside. The chest is just empty.

**Comment by fatmanjumprope** [comment]
I apologize for wasting your time here. After I restarted my server the bow displayed in the chest. I believe it was an issue with me reloading the plugin maybe.
