### ISSUE TITLE
bugged chunks in dxl world spawn

### ISSUE THREAD

**Issue by HauserGrim** [DRE2N/DungeonsXL#558]
My english is very bad and i create video demonstration
Config: default
Plugin ver: latest
Server ver: latest paper 1.13.2 build
Video:
https://youtu.be/YqsYli0T_vU

**Comment by Sataniel98** [comment]
Not on DXL's side. Stop the server, remove the plugins/DungeonsXL/maps/.raw folder and restart.

**Comment by HauserGrim** [comment]
I stopped server, deleting this folder, start server, create new map, and nothing has changed

**Comment by HauserGrim** [comment]
I created a clean spigot server with dxl and everything works fine, I will run a couple of tests and try to find the cause.
(And also, basically, I use Google translator, so sometimes I may not be clear. Ask again if something is not clear)

**Comment by HauserGrim** [comment]
This incompatibility with Paper ...

**Comment by HauserGrim** [comment]
Fixed in 0.18
