### ISSUE TITLE
How to configure identifiers?

### ISSUE THREAD

**Issue by StreamJerker** [DRE2N/DungeonsXL#559]
How do I set Identifiers for things like classes and mobs?

https://github.com/DRE2N/DungeonsXL/wiki/scripts

I tried renaming the entire .yml file as the name of the class or mob I wanted; that didn't work so I added a line to the top of the config settings for the class/mob I wanted and I did something like Fighter: to encapsulate all the config parameters under that of "Fighter"

What is the proper way to set the identifier, following the example scripts you have posted on the GitHub

**Comment by Sataniel98** [comment]
The file name is the class name. Make sure to reload the plugin if you create or edit it while the server is running.

**Comment by StreamJerker** [comment]
Is it the same way with mobs? Ironically I got the classes to work not long after opening the ticket. I must've not reloaded the plugin last time I had edited them.

**Comment by Sataniel98** [comment]
Yes, it is.

**Comment by Sataniel98** [comment]
Yes, it is.

**Comment by StreamJerker** [comment]
Thank you very much for the help, it's been bugging me for days. 😄

**Comment by Sataniel98** [comment]
No problem, feel free to ask if you have further questions!
