### ISSUE TITLE
Built In Custom Mobs not working

### ISSUE THREAD

**Issue by techboy04** [DRE2N/DungeonsXL#560]
**Description**

[//]: # Mob Boss Sign not working when used correctly

**Reproduce**

[//]: # Added the Mob Signs as specified and used the mob name as the custom one specified in the mobs folder (without the .yml)

**Expected behavior**

[//]: # A boss spawning in for players to battle. Within the specified radius

**Screenshots / GIFs / videos**

[//]: # 
[2019-04-18_12 24 04](https://user-images.githubusercontent.com/26682382/56376149-251b8680-61d5-11e9-8496-8d02c35ba07f.png)

**Relevant configuration files**

[//]: # Boss.yml

```
type: Skeleton
maxHealth: 100
itemHelmet: 310
itemChestplate: 310
itemLeggings: 310
itemBoots: 310
itemHand: 310
isWitherSkeleton: true
```

**Comment by Sataniel98** [comment]
Did you reload the plugin?

**Comment by techboy04** [comment]
Yes I did.
I saved the map then did /dxl reload

**Comment by Sataniel98** [comment]
Doesn't look wrong, I'd have to test this, which I can't at the moment. I'll let you know.

**Comment by Sataniel98** [comment]
Feature will be replaced with the next mob library update
