### ISSUE TITLE
Using script sign to generate a hologram

### ISSUE THREAD

**Issue by wwyjason** [DRE2N/DungeonsXL#563]
Hello. I am a user from Hong Kong and I am trying to using script sign to generate a hologram. However, it didn't work.

I put a sign like this in my dungeon and it told me that I have successfully created a dungeon sign.
![image](https://user-images.githubusercontent.com/50078766/56946669-585aff80-6b5d-11e9-8e9b-f88a97c4c4d6.png)

On the other hand, I have also created a script as below.
![image](https://user-images.githubusercontent.com/50078766/56946772-ac65e400-6b5d-11e9-81b2-2c9995e4585c.png)

I would like to ask if there is any problem in my setting? Thank you.

**Comment by Sataniel98** [comment]
Hi,
it doesn't look wrong. What exactly doesn't work? Note that script signs are only initialized when the game starts, so they won't work in a lobby.

**Comment by wwyjason** [comment]
ok, thanks a lot for your help

**Comment by wwyjason** [comment]
Hi. I would like to ask another question.
This time I would like to generate a hologram by using script sign and here is my config:
![image](https://user-images.githubusercontent.com/50078766/57179494-07c30980-6eb1-11e9-8728-81221b0e01c1.png)

However, there was an error in my console once I have pressed the ready sign of my dungeon.
![image](https://user-images.githubusercontent.com/50078766/57179526-4eb0ff00-6eb1-11e9-92a4-8a839dda69b7.png)
![image](https://user-images.githubusercontent.com/50078766/57179528-5670a380-6eb1-11e9-9a08-08bed82e18e8.png)

It is sure that the name of my script config and the one on my script sign is the same.
I would like to ask if there is any problem in my setting? Thank you.

**Comment by Sataniel98** [comment]
This script lacks the fourth line of the sign. I'll fix the bad error handling. Also, please open a new issue for each issue and use the template.
