### ISSUE TITLE
Multiple game sessions for 1 dungeon. Is it possible?

### ISSUE THREAD

**Issue by HauserGrim** [DRE2N/DungeonsXL#565]
My English is bad, so I will describe with an example.
How it works:
1. Creating dungeon map and sign
2. Group owner clicked on sign
3. Map copied to server folder with DXL_Game_0 name and group joined to dungeon
Other groups need to wait for the game to end

What I want:
1. Group 1 owner clicked on sign
2. Map copied to server folder with DXL_Game_0 name, group 1 start game
3. Group 2 clicked on sign
4. Map copied with DXL_Game_1 name and group 2 start game
etc.

Is it possible to do this?

**Comment by Sataniel98** [comment]
Just add multiple group signs.

**Comment by HauserGrim** [comment]
But it takes quite a lot of space. You did not think to make it possible to do it with one sign?

**Comment by Sataniel98** [comment]
I didn't, and I don't think there l'd be any benefits for the kind of server this plugin targets.
