### ISSUE TITLE
command sign doesn't work

### ISSUE THREAD

**Issue by wwyjason** [DRE2N/DungeonsXL#567]
I got a question about the command sign for the dungeon.

This is what I want to do:
I would like to run a command for my players once they have killed the boss and interact with a sign and that's how I set them.
![image](https://user-images.githubusercontent.com/50078766/57453032-e63e9500-7297-11e9-9cca-e018850c378d.png)

![image](https://user-images.githubusercontent.com/50078766/57453043-eb034900-7297-11e9-960e-f5ea9a70e0da.png)

I have given my player the permission "test.asop", but it still somehow gave me this message:
![image](https://user-images.githubusercontent.com/50078766/57455276-60bde380-729d-11e9-84ba-da7a264761de.png)

Am I setting anything wrong?

**Comment by Sataniel98** [comment]
Console commands require ".asconsole", not ".asop", and this suffix is added automatically, so if you specify it as "test.asop", the node needed to perform the command would in your case be "test.asop.asconsole".

**Comment by wwyjason** [comment]
Well, I still cannot run the command for my player and here is my change:

![image](https://user-images.githubusercontent.com/50078766/57518577-eac48580-734b-11e9-88ad-fd6be263cc2d.png)
![image](https://user-images.githubusercontent.com/50078766/57518630-0760bd80-734c-11e9-9ab3-4c51b2868330.png)

I have checked if my player have the permission or not and it seemed that he had that permission node.
![image](https://user-images.githubusercontent.com/50078766/57518691-3119e480-734c-11e9-9a9e-78469e782cf1.png)

I am wondering if I understand anything wrong for the plugin? 
( I am using 1.13.2, but the plugin is only for 1.7.9-1.12, I don't know will this break the plugin)

**Comment by TFGKuro** [comment]
hi, i have one problem, the sign of the groups dont work, when I create the sign as the guide says nothing happens and it stays like a normal sign and it does not let me enter the world in groups help!

**Comment by Sataniel98** [comment]
> hi, i have one problem, the sign of the groups dont work, when I create the sign as the guide says nothing happens and it stays like a normal sign and it does not let me enter the world in groups help!

Open a new issue and use the template (**ALL** listed points).

**Comment by Sataniel98** [comment]
Feature will be replaced in the next update
