### ISSUE TITLE
question about starting the dungeon

### ISSUE THREAD

**Issue by wwyjason** [DRE2N/DungeonsXL#569]
When my players of the same group started a dungeon by going into the lobby and clicking the 'ready' sign, they could not see each other once they entered the dungeon. This bug(or should I say  problem?) didn't happened everytime.

I would like to ask if this is the problem of the plugin or my own server?

**Comment by Sataniel98** [comment]
See #448 (players are also entities). It's not caused by DXL but adding a workaround may be possible and it is on my to do list.
