### ISSUE TITLE
Having issue with editing Dungeons

### ISSUE THREAD

**Issue by Tkiljoy** [DRE2N/DungeonsXL#571]
We have created 2 dungeons however we cannot work on the dungeons. When we try to use /dxl edit [name] is gives us an error saying that there is too maps instantiated

**Reproduce**

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
```
# The maximum amount of games that may run at once.
# Useful to prevent overloading.
maxInstances: 10
```
You have reached the maximum amount of instances you allowed in your main configuration. If your server can handle more, think about increasing it.
