### ISSUE TITLE
MAKE a discord 

### ISSUE THREAD

**Issue by report101** [DRE2N/DungeonsXL#577]
So most plugin has a discord server its simple and does not need a github account 
also all players using the plugin can help each other out , also allows a faster respond

**Comment by Sataniel98** [comment]
Feel free to make one as long as you don't call it official, but I am strongly against sharing my private contact information with the public and am not going to join. Plus, as much as it speeds things up for users, it slows things down for me. GitHub issues is much more organized and it offfers a template to fill out, that, if it is used, reduces the need to ask more questions on my part.
