### ISSUE TITLE
Player can place lava and lose xp

### ISSUE THREAD

**Issue by Daxxas** [DRE2N/DungeonsXL#579]
**Description**

[//]: # Players can place lava and water in instances even when the placeblocks rules are set to deny 
Players also lose xp when they die in the dungeons even with the keepinventory rules set to true

**Reproduce**

[//]: # make a dungeon where you deny place blocks and set all the keepinventory rules to true, enter the dungeon as a player with a lava bucket and xp. Try to place lava with the bucket and die to check if you lose xp

**Expected behavior**

[//]: # Players shouldn't lose xp or be able to place lava

**Screenshots / GIFs / videos**

[//]: # I can do one if needed
**Relevant configuration files**

[//]: # I will add them tomorrow if you are seeing this then it probably means I'm asleep

```

```

**Comment by Sataniel98** [comment]
Using buckets is interaction, not block placing, and thus not covered by rules for placing and breaking blocks. As for the EXP, I will have a look at it. Thank you for the reports!
