### ISSUE TITLE
Portal linking to dungeon?

### ISSUE THREAD

**Issue by t0xic1** [DRE2N/DungeonsXL#58]
I didn't find any command which links the portal to specified dungeon anywhere?

**Comment by Sataniel98** [comment]
Portals are not linked to dungeons, the group and / or game signs contain this information :) A player who clicks such a sign could use any DXL portal.

**Comment by t0xic1** [comment]
Aww i though it would work like that :(

So there is no way to create portals directly to dungeons only signs?

**Comment by Sataniel98** [comment]
Unfortunately not. A dungeon game setup needs a bit more user input to define:
- The group membership,
- The size of the group,
- Shall the game use a multi floor system or not?
- Which dungeon / map shall the user choose?
  And so on. It would be hard to guess all of that if the only information was that the user uses a specific portal.
