### ISSUE TITLE
/dxl create not working/ Doesn't tp me to flat world

### ISSUE THREAD

**Issue by QuazArxx** [DRE2N/DungeonsXL#580]
Mind you I'm in 1.14 even though I read the API is the same. When I do 

/dxl create skeleton_tomb

I get "An internal error occurred while attempting to perform this command". It still makes the world though as I see in the FTP file access. It also doesn't bring me to the flat world so i'm still sitting in my world.

On top of that if I do 

/dxl delete skeleton_tomb

It says "Do you wish to delete all saved backups as well?" to which there's no command anywhere to respond to it and you can't click on it. I would love to get this plugin working for my server but nothing seems to be working.

**Comment by Sataniel98** [comment]
The plugin doesn't support 1.14.

**Comment by bijanmahdavi** [comment]
@Sataniel98 do you plan on adding 1.14 support in the future?

**Comment by Sataniel98** [comment]
Yes, ETA is between 8th and 16th June.

**Comment by bijanmahdavi** [comment]
@Sataniel98 thank you for the quick reply! I look forward to it

**Comment by Sataniel98** [comment]
Fixed.
