### ISSUE TITLE
Redstone does not update

### ISSUE THREAD

**Issue by nickpauwels1988** [DRE2N/DungeonsXL#581]
Created a redstone cirquit with item frames. Based on the position of the item frame a redstone signal passes through to a comparator and a redstone repeater. redstone signal does not seem to update after the user changes the position of the item in the itemframe in the live version of the dungeon. (To change the position of the item in the itemframe we use mythicalmobs)

**Comment by Sataniel98** [comment]
If this doesn't use any DXL features then it's not related to DXL. Also, please use the predefined template.
