### ISSUE TITLE
Plugin is not using my config.yml inside my dungeon map folder.

### ISSUE THREAD

**Issue by wells218** [DRE2N/DungeonsXL#582]
I have tried creating a config.yml in DungeonsXL/maps/%Mapname% folder. but it seems that it wont use the actual config. I have reloaded and restarted the server.

**Comment by wells218** [comment]
It is also not executing the keep inventory rule in the main
 config

**Comment by Sataniel98** [comment]
Hello,
please use the issue template. This saves us all a lot of time.
