### ISSUE TITLE
Interact sign not work

### ISSUE THREAD

**Issue by Deywark** [DRE2N/DungeonsXL#583]
**Description**

Interact signs not work

**Reproduce**

I have simply put these 2 signs and when I give the interaction on the right the door does not open.

**Expected behavior**

If I understood correctly, I should open the door.

**Screenshots / GIFs / videos**

![2019-05-28_20 17 31](https://user-images.githubusercontent.com/38083744/58502101-25b91c80-8186-11e9-9745-e2cbcf5066bb.png)

If they finally help me correct this error, could I put buttons instead of posters?
This was just a test, the "sign" would be much further
Thank you and I hope your answer

"The plugin does not give any error in the console"

**Comment by Sataniel98** [comment]
Hi,
the trigger on the door says "1" instead of "I1". You can use redstone triggers to use redstone mechanics, but wireless redstone isn't supported.
