### ISSUE TITLE
I want to finish the dungeon when the monster dies.

### ISSUE THREAD

**Issue by geumu** [DRE2N/DungeonsXL#584]
**Monster Death** -> **Dungeon Clear** -> **Message output: The item will be paid 10 seconds later. Please empty the inventory.** -> **Item reward**

I want to make a dungeon like this. What should I do?

**Comment by Sataniel98** [comment]
Using the predefined issue template would be a good way to get started. An overview about the signs and triggers is available here: https://github.com/DRE2N/DungeonsXL/wiki/signs

**Comment by geumu** [comment]
Thanks for the quick answer. I read the wiki twice, but I do not know yet. I also saw the video. https://www.youtube.com/watch?v=YpqIbg_acwE

I do not know how to pay an item to the user 10 seconds after the monster dies and the dungeon finishes.

**Comment by Sataniel98** [comment]
The items are given to the player as soon as he moves out of the dungeon portal.
