### ISSUE TITLE
Global protections  don't get removed correctly

### ISSUE THREAD

**Issue by Poweringg** [DRE2N/DungeonsXL#59]
Hi, i destroy portal by command "Dxl break" portal dissapears, but when i restarted the server, portal was back(see image). I can't destroy him by hand, but i can destroy it again by command "Dxl break". Then i restarted server again, and it's again back.  I removed the portal through config.
![000](https://cloud.githubusercontent.com/assets/15527318/14935736/8f8b284a-0edb-11e6-99fc-d10f3ee8e6fa.png)

**Comment by Sataniel98** [comment]
Was able to reproduce it. I'll fix it as soon as possible :)

**Comment by Sataniel98** [comment]
Fixed it in Build 56. The data format changed a bit, though:

```
protections:
    gameSigns:
    groupSigns:
    leaveSigns:
    portals:
```

You'll probably have to move some entries.
