### ISSUE TITLE
0.18 snapshot perfomance on 1.13.2

### ISSUE THREAD

**Issue by HauserGrim** [DRE2N/DungeonsXL#591]
I realized that there could be problems with 1.14, but I did not understand, the new snapshot will work better with 1.13 than 0.17? On 1.13 there will be no new bugs or performance deterioration?

**Comment by Sataniel98** [comment]
v0.18 will definitely work better with 1.13 than v0.17.

Performance with 0.18 with MC1.13 > 0.17 with MC1.13 > 0.18 with MC1.14.

The snapshot however is a snapshot. That means, it represents nothing but an interim stage in development. The disclaimer from the dev build server applies:

> Please note that development builds are provided only for the purpose to allow users to contribute bug reports and feedback. You may use them to prepare for upcoming new features and changes, but avoid to use them in a production environment. Make sure to create backups of your maps, data and configuration.

There are no more guarantees than what has been said in the update notes. Of course, efforts are made sothat no new bugs are introduced. But DungeonsXL is after all published as a project in development, not as a finished product, and it is up to you to decide if you're fine with using it in a production environment or not.
