### ISSUE TITLE
MythicMobs invalid world

### ISSUE THREAD

**Issue by Kvosty** [DRE2N/DungeonsXL#596]
Hi Sataniel,

I have a little problem with spawning mobs by using MythicMobs plugin. I have this format on sign.

[Mob]
Ragdul
1,1,MM
D 30

Problem is, when i trigger the sign this error shows me up in console
"[MythicMobs] Invalid location specified for spawning a mob: world does not exist."

Funny thing is, it was working 2 days ago? Without problem. I tried to break it, and create new mob sign, but it didnt work.

**Comment by Sataniel98** [comment]
OK I'll test it, but MythicMobs' console spawn command (/mm mobs spawn [mob_name]:<level> <amount> <world,x,y,z>) didn't change and performing it automatically is about what DungeonsXL does. There's not that much that could break, so most of the possible problems with spawning custom mobs are on their side.

**Comment by Kvosty** [comment]
My config looks like this


configVersion: 16
language: english
enableEconomy: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders:
    # providerTag: spawn command
    # "%%"indicate placeholders
MM: mm m spawn %mob% %world% %x% %y% %z%
resourcePacks: {}
maxInstances: 10
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
default: {}

**Comment by Sataniel98** [comment]
"MM: mm m spawn %mob% %world% %x% %y% %z%"
This is wrong. You don't need to add anything there for MythicMobs, it's supported natively. And the command doesn't work like this, MythicMobs uses commas between the world and coordinate parameters, and I don't know if it works without an amount parameter. Just remove this part.

**Comment by Kvosty** [comment]
Thank you, i just deleted this line and its working now
