### ISSUE TITLE
I want to finish the dungeon automatically when I get all the monsters. What should I do?

### ISSUE THREAD

**Issue by geumu** [DRE2N/DungeonsXL#597]
bukkit: paperspigot 1.12.2

I tried PvE LMS with ready sign. If a monster dies, it does not get out of the dungeon. How can you clear the dungeon when i kill the monster?

**Comment by Sataniel98** [comment]
The easiest way at the moment is a wave trigger.

**Comment by geumu** [comment]
> The easiest way at the moment is a wave trigger.

thanks you
