### ISSUE TITLE
Have players leave the dungeon somewhere else

### ISSUE THREAD

**Issue by fenix12585** [DRE2N/DungeonsXL#598]
Currently when players leave the dungeon they are brought back to the portal. I am using dxl in an unorthodox way where players complete quests to get access and do not want players able to replay the dungeon without doing the quest again. Is it possible to change the location they return to after doing /dxl leave or using a leave sign?

Thank you!

**Comment by Sataniel98** [comment]
Hi,
I'll mark it as a suggestion as no such feature currently exists.
