### ISSUE TITLE
Running this plugin on 1.14.3 Paper

### ISSUE THREAD

**Issue by pkhodadi** [DRE2N/DungeonsXL#599]
**The feature you'd like to know more about**
1.14.3 Paper Compatibility
[//]: # (e.g. game rules)

**Link to the wiki article (in case it exists)**
None
**What did you already try?**
Using the most recent stable version (0.17.7)
**Relevant configuration files**
None
[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
Well, I'll just quote the update notes from the latest snapshot:

> The build is forward compatible to 1.14.3. bStats says about 15% of you guys are already running DXL with Minecraft 1.14.x, so I'd like to stress once more that this is a bad idea, at least for production environments. I'm not putting disclaimers here to protect myself against complaints but because my test results proved that it simply doesn't work well enough.
>
> These were admittedly made with by now outdated Spigot builds, but that's still the current state.
>
> [...]
>
> **Update policy**
> This build is a development build. That means that it is not only not as stable as release builds but also that its features are always subject to change. Features in development builds might be removed or changed without automatical data converters in a following build. The builds posted here [on SpigotMC.org] are only builds from the master branch.
> 
> The reason why the old branch (0.17) wasn't updated is that the changes made to the project setup in order to support Minecraft 1.14 are rather far reaching, and they coincidenced with the API updates for 0.18. 0.18 is supposed to become a major feature update once it's ready that was and is developed independently of Minecraft updates - that means even if there is this early dev build, it will still take a while until it is finished.
> 
> **Support for Minecraft 1.14**
> The current development builds come with technical support for Minecraft 1.14.x. This means technical inclusion and consideration of 1.14.x features are present, but the current performance of Spigot 1.14.x (regardless if it's Spigot's or Mojang's problem) if it comes to world loading and crash bugs make it impossible to guarantee the same quality as with 1.13.x in practice.
> 
> If you'd like to try it out, please let me know how your experience with performance in 1.14 is and if there are any issues and how frequent they are.

Note that Spigot itself also doesn't have any stable builds out at the moment. Paper isn't targeted, but in my experience, its plugin support not only theoretically includes everything supported by Spigot. I use it for my own server (1.13.2) without issues

0.17.7 was released as a semi stable build and it does not have long term support. DungeonsXL is Beta software, a stable build doesn't exist yet. At least one severe bug present in 0.17.7 has been fixed since then.
