### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by DeathFCKing** [DRE2N/DungeonsXL#600]
Hello author i want to ask you some question of dxl portal, when i created the portal at which time the player still had items but when going through the portal the player was gone and when leave was left, the item would automatically point back. sr my english very bad

**Comment by Sataniel98** [comment]
Hello,
I'm not trying to be nitpicking but it would save us a lot of time if you opened a new issue and followed the issue template. I don't understand what your problem is. If that helps, you may write in French or German.
Best regards.
