### ISSUE TITLE
Some command sign triggers not work

### ISSUE THREAD

**Issue by ShallowAi** [DRE2N/DungeonsXL#601]
**Description**

Command sign triggers not work except [D]istance trigger when the mob not spawn at first

**Reproduce**
-> Other triggers will not work
Place a [Mob] Sign, set second line as "mob1", third line "1,3,MM", fifth line "D 24"
Place a [Mob] Sign, set second line as "mob2", third line "1,1,MM", fifth line "M mob1,D 24"
Place a [CMD] sign, set second line as "samplecommand", third line "0,OP" ,set trigger as "M mob2,D24"
-> Other triggers will work
Place a [Mob] Sign, set second line as "mob1", third line "1,1,MM", fifth line "D 24"
Place a [Mob] Sign, set second line as "mob2", third line "1,1,MM", fifth line "M mob1,D 24"
Place a [CMD] sign, set second line as "samplecommand", third line "0,OP" ,set trigger as "M mob2,D24"

**Expected behavior**

Command will be repeat again and again even if you not killed mob2. Just like triggers not work except [D]istance.

**Comment by Sataniel98** [comment]
Thank you for the report.

**Comment by Sataniel98** [comment]
The command sign function will be recoded from scratch.
