### ISSUE TITLE
The [Block] sign only works when it is placed on the ground

### ISSUE THREAD

**Issue by nudetiger** [DRE2N/DungeonsXL#604]
**Description**

When you place a [block] sign on another sign, the [block] sign will not work
When you place a [block] sign on the wall, the [block] sign will not work either

My [block sign]
                                          [Block]
                                      Sandstone,2
                                            Air
                                       M mymob

**Screenshots / GIFs / videos**

I dont have the screenshots yet, but if you want them, just tell me

```
Also, I have a request, could you please add something that to wait a specific time before the sign being trigger cause I want my players to kill the boss and wait for ten seconds before the door being open
```

**Comment by Sataniel98** [comment]
Fixed :)
