### ISSUE TITLE
DXL Worlds are not suppressed

### ISSUE THREAD

**Issue by MrKrj** [DRE2N/DungeonsXL#606]
**Description**

[//]:  At the end of a dungeon, the world that was created do not get deleted. The first world "DXL_Game_0" is created then each new dungeon the plugin generates a "DXL_Game_1", "DXL_Game_2" etc.
This error message appears when creating the following world :
> [DungeonsXL] Warning: An unrecognized junk instance (DXL_Game_0) has been found, but could not be deleted.
May Multiverse cause that effect ?

**Expected behavior**

[//]:  Worlds should be deleted

**Comment by Sataniel98** [comment]
True, however a duplicate of #506.
