### ISSUE TITLE
Crash and Chunk errors

### ISSUE THREAD

**Issue by Saelman** [DRE2N/DungeonsXL#607]
**Description**
So after generating a new world or editing a existing one (not exactly sure if this happens on editing a existing one) everything works fine until i or one of my other coworkers leave the world. at this point the server will stop responding. apon reentering the world there will be several chunk errors. Im currently using minecraft 1.14.2 on spigot. 18 gig ram
https://pastebin.com/MpWeQQ0d  <---- Crash as seen from console
**Reproduce**
Generate a world, then leave, after a second the server will stop responding and the following errors in the pastebin are lunched in console and the server crashes, the world apon reload can or will have chunk errors in it.

**Expected behavior**
Normal exit of the DXL dungeon world without the server stopping or any chunk errors.

**Screenshots / GIFs / videos**
https://pasteboard.co/In3ejWI.png
https://pasteboard.co/In3eygC.png

**Relevant configuration files**
https://pastebin.com/tTUBPTtP

**Comment by Sataniel98** [comment]
Hello @Saelman,
thank you for your feedback. However besides 18 GB RAM being dramatically much too much for a Minecraft server, Minecraft 1.14.2 is not supported by DungeonsXL.

Please make sure to read the update notes:

> Just like the latest one, this build includes a fix of a severe bug and updating is highly recommended.
>
> The build is forward compatible to 1.14.3. bStats says about 15% of you guys are already running DXL with Minecraft 1.14.x, so I'd like to stress once more that this is a bad idea, at least for production environments. I'm not putting disclaimers here to protect myself against complaints but because my test results proved that it simply doesn't work well enough.
>
> These were admittedly made with by now outdated Spigot builds, but that's still the current state.
[...]
**Support for Minecraft 1.14**
The current development builds come with technical support for Minecraft 1.14.x. This means technical inclusion and consideration of 1.14.x features are present, but the current performance of Spigot 1.14.x (regardless if it's Spigot's or Mojang's problem) if it comes to world loading and crash bugs make it impossible to guarantee the same quality as with 1.13.x in practice.

https://www.spigotmc.org/resources/dungeonsxl.9488/update?update=284726

**Comment by Saelman** [comment]
oh! my apologizes! the 18 gigs of ram is just cause i can for development lol, thanks for the quick support!
