### ISSUE TITLE
Crash server when 2 instances

### ISSUE THREAD

**Issue by Flashback083** [DRE2N/DungeonsXL#609]
**Description**
When i leave the 2nd instance, the server crash

**Reproduce**
Create 2 groups
Join the dungeon with the first group
Join the second with the second group
Reach the END sign or do /dxl leave with the second group
Crash server

**Expected behavior**
End the dungeon for both groups

**Logs**
https://gist.github.com/Flashback083/fc6c954396d3c850d4d5a590f8891ce7

Thanks for your help !

**Comment by Sataniel98** [comment]
Hey,
which version is this? Looks like it is using MCP (Forge) mappings.

**Comment by Flashback083** [comment]
Version of the server ?
1.12.2 - But yeah with Forge and Plugins

**Comment by Sataniel98** [comment]
I don't know which software you're using for that but as long as this isn't reproducable with supported Spigot builds it isn't likely to be a bug on DXL's side.
