### ISSUE TITLE
Sign trigger when the instance is unloaded

### ISSUE THREAD

**Issue by Daxxas** [DRE2N/DungeonsXL#612]
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...];)

I'm having an issue where an error could be spammed when an instance is unloaded, having a feature like this would let me fix my problem easily

[//]: # (A clear and concise description of what you want to happen.)

The sign would trigger when an instance is unloaded because there is no live left, or every players left the instance

[//]: # (A clear and concise description of any alternative solutions or features you've considered.)
There is nothing else that I can think of to do what I want than this way at the moment  :(

**Comment by Sataniel98** [comment]
I'll keep it in mind but close it in favor of #452.
