### ISSUE TITLE
Problem with Floor dungeon.

### ISSUE THREAD

**Issue by AioBahn** [DRE2N/DungeonsXL#613]
Hi, im using DungeonsXL for 1.14.3 Server

I create MFD and i already create the config, but when im trying to test the dungeon and kill all the mobs, its not going to the next floor and dungeons is finished.
Any help?

**Comment by Sataniel98** [comment]
Sounds like you're starting the single floor dungeon of the first floor instead of the multi floor dungeon, make sure to specify the name of the dungeon config instead.
