### ISSUE TITLE
DXL_EDIT worlds throwing "raids.dat" errors in the console

### ISSUE THREAD

**Issue by TheRedMajora** [DRE2N/DungeonsXL#614]
**Description**
Seems 1.14.3 is trying to do something with a raid file in the edit worlds (maybe the game world aswell, haven't tested), but something is keeping it...

**Reproduce**
Updated my server to 1.14, (before even starting the 1.14 server) downloaded the latest DungeonsXL and this error spams my console every few minutes.

**Expected behavior**
Well, nothing really seems to be bad. Game works fine, it's just annoying to have red text all over the console :P

**Screenshots / GIFs / videos**
![image](https://user-images.githubusercontent.com/8898217/61382146-7eff1b80-a8ac-11e9-9664-163300a5f903.png)

```

```

**Comment by Sataniel98** [comment]
Thanks, I'll have a look at it!

**Comment by Sataniel98** [comment]
Should be fixed. Please report again if it still occurs.
