### ISSUE TITLE
Item Loot Tables

### ISSUE THREAD

**Issue by CelicGames** [DRE2N/DungeonsXL#617]
So, I made my first dungeon. Its a pretty little thing and most of players on my server enjoy playing it. I also have an itemedit plugin on my server. I created many items this way and I'd love to create more you can obtain in the dungeon. 

This is where my problem comes in I guess.

The loot tables are giving me a headache. I can't seem to make them function. I've been trying to use the ItemsXL serialize ability to generate the items I want to put in the table, but it just never works. Whenever I play the dungeon with the loot table reward chest and open it, it shows that I got reward but it doesn't say what it is, nor does it appear when I complete the dungeon.

The file I'm attaching is almost a test of the loottable, the two items I imputed are the servers currency item and a mystery key for our mystery box plugin. I even tried it though with things like an iron sword or a flower and it still seems not to work.

Any ideas? 
[loottable1.txt](https://github.com/DRE2N/DungeonsXL/files/3415141/loottable1.txt)

**Comment by Sataniel98** [comment]
The "serialized" key isn't part of the serialized data, it isn't supposed to be put there. And the slots, the keys you called "loottableitemX", aren't numeric.

**Comment by CelicGames** [comment]
Okay, I fixed what I think you were telling me to fix. It still doesn't work though. I had no idea there had to be numeric IDs


0:
  ==: org.bukkit.inventory.ItemStack
  type: GOLD_INGOT
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §6§lGold Bricks
  chance: 97.0
1:
  ==: org.bukkit.inventory.ItemStack
  type: GOLD_NUGGET
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §6§lGold Coins
  chance: 23.0
2:
  ==: org.bukkit.inventory.ItemStack
  type: BLAZE_ROD
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §5§lMystery Box Key
    internal: H4sIAAAAAAAAAONiYOBg4HD393GJ93aNZGBJSi0uYQAAnR/6jBUAAAA=
  chance: 20.0

**Comment by Sataniel98** [comment]
There's still no "item:" section in the slot sections. You can use this for reference:
https://github.com/DRE2N/DungeonsXL/wiki/scripts#loot-tables

**Comment by CelicGames** [comment]
Heres what I'm testing and it still doesn't work. 

0:
  item:
    ==: org.bukkit.inventory.ItemStack
    type: GOLD_INGOT
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §6§lGold Bricks
  chance: 100.0

**Comment by CelicGames** [comment]
Okay! I fixed it! I just had to restart my server with that! Thank you so much for the help!
