### ISSUE TITLE
Any way to disable silverfish infesting blocks

### ISSUE THREAD

**Issue by snowy6409** [DRE2N/DungeonsXL#618]
**Silverfish Infested Blocks**
Is there any way to disable silverfish infesting blocks, I am using silver fish as sewer rats but they end up destroying blocks when they try to infest them.

**Comment by HauserGrim** [comment]
If you use MythicMobs you can use PreventBlockInfection option for silerfish

**Comment by snowy6409** [comment]
@HauserGrim You are correct the is an option in mythical mobs for that. I will just use that but this is still a good enhancement for DXL to gain standalone.
