### ISSUE TITLE
MythicMobs 4.7.0 (dev builds) support?

### ISSUE THREAD

**Issue by HauserGrim** [DRE2N/DungeonsXL#619]
Going to purchase a premium version of MythicMobs for use on the server (1.14.4) with DXL
I wanted to ask before this if dev builds of MythicMobs 4.7.0 are supported?

The free version of MM works, but causes strong lags (in 1.14.x), so I decided to buy a premium.

In changelog i seeing only this: https://mythicmobs.net/manual/doku.php/changelog#api
And in theory, it should work fine.
But just in case I decided to ask.

**Comment by Sataniel98** [comment]
I don't guarantee anything but DungeonsXL doesn't use the MythicMobs API, so it is very unlikely to break.
