### ISSUE TITLE
Can't leave the dungeon

### ISSUE THREAD

**Issue by jeannen** [DRE2N/DungeonsXL#620]
**Description**

My players are stuck on the dungon, they can't use the [End] sign. I can use it with OP rights. It was working well before (I don't know since when the bug is present)

# (A clear and concise description of what the bug is.)

**Reproduce**

- Create an [End] sign
 # (List steps to reproduce)

**Expected behavior**

he player is supposed to leave the dungeon/]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

https://pastebin.com/Y2PvBqW]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
I can't view the pastebin entry.

**Comment by jeannen** [comment]
Whoops, my bad: https://pastebin.com/kWmm6Ek3

**Comment by Sataniel98** [comment]
Sorry for the late reply.

This looks like a player in the game somehow left the game world where the game takes place... This must not happen - you can prevent it with the secure mode (main config).
