### ISSUE TITLE
DXL_Game_X cannot be deleted and more and more

### ISSUE THREAD

**Issue by BearLeonLight** [DRE2N/DungeonsXL#622]
I use [/mv import DXL_Game_0 normal] to load, then 1.[/mv delete DXL_Game_0]2.[/mvconfirm] can delete the map normally.
Can you add Multiverse-Core support to remove the dungeon map.

**Comment by Sataniel98** [comment]
No, DXL instances aren't supposed to be imported into Multiverse, and that they aren't removed isn't intended design but a duplicate of #506

**Comment by BearLeonLight** [comment]
So what should I do?
