### ISSUE TITLE
BossShopPro not enabled

### ISSUE THREAD

**Issue by keyute** [DRE2N/DungeonsXL#624]
**Description**

[//]: # (A clear and concise description of what the bug is.)
DungeonsXL fails to recognise bossshop is enabled on 1.14
**Reproduce**
Make a boss shop sign and play the map
[//]: # (List steps to reproduce)

**Expected behavior**
Boss shop should be recognized 
[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
The Pro version isn't supported at the moment, but it will be, soon.
