### ISSUE TITLE
+How do I remove dxl portal?

### ISSUE THREAD

**Issue by Aeyori** [DRE2N/DungeonsXL#628]
**The feature you'd like to know more about**
dxl portal
[//]: # (e.g. game rules)

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/getting-started#entering-the-dungeon
**What did you already try?**
/dxl remove portal
**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
Use /dxl break.
