### ISSUE TITLE
Add Permission to join Portal into the game

### ISSUE THREAD

**Issue by nhoc2player** [DRE2N/DungeonsXL#630]
**Please describe the use case or the problem your request is related to.**

[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...];)
DungeonXL dont have Permission Portal/Join

**Describe the solution you'd like**

Add Permission go into the Name of Portal/Join

Ex: If you have permission dungeonxl.portal.name << ( name portal or id here ) you can not go into the portal to join the game

**Describe alternatives you've considered**

Nope

**Comment by Sataniel98** [comment]
I don't understand what you are trying to say.

**Comment by nhoc2player** [comment]
Sorry about my english so bad
The Question is could you add Portal Permission? Like manage some people have High level can join the game?
Ex: dungeon.portal.[name of 
 the portal] so, if you have this permission, you could join the portal

**Comment by Sataniel98** [comment]
But portals aren't even tied to dungeons - player groups are. You can just use the requirement system for this.
```
requirements:
  permission:
    - my.custom.node
```
