### ISSUE TITLE
checkpoints not working

### ISSUE THREAD

**Issue by keyute** [DRE2N/DungeonsXL#634]
**Description**

[//]: # (A clear and concise description of what the bug is.)
player does not spawn at checkpoints
**Reproduce**
use sign

[Checkpoint]

D 5

teleport players to the sign via command block
kill yourself
[//]: # (List steps to reproduce)

**Expected behavior**
player spawns at checkpoint sign
[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**
minecraft 1.14
[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
Just confirmed it works fine. Perhaps it didn't work with the old builds from last year, but at least today it seems to work fine.
