### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#635]
**Description**

[//]: # (A clear and concise description of what the bug is.)

Players click on the [leave] sign and the server crashes suddenly.

[//]: # (List steps to reproduce)

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**
[2019-08-02-2.log](https://github.com/DRE2N/DungeonsXL/files/3461176/2019-08-02-2.log)

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
DungeonsXL does not appear in the log. Something seems to have gone wrong related to Citizens' custom skins, maybe the connection to the Mojang servers timed out. Since this is triggered by chunk loading I'd try it without Paper first.
