### ISSUE TITLE
WAVE function

### ISSUE THREAD

**Issue by YuuMilkToasT** [DRE2N/DungeonsXL#637]
The wave function

[Mob]
WolfBoss
1,1,MM
W 0.04

I set 4 little wolf in the dungeon and after kill all the 4 wolf then the WolfBoss will be spawn. But it cannot work in this latest version of dxl, last time i use the old version it works.

**Comment by Sataniel98** [comment]
As the wiki says, the feature isn't supported anymore since waves are rewritten from scratch in 0.18.
