### ISSUE TITLE
Group signs not functioning well after restart or /dxl reload

### ISSUE THREAD

**Issue by CreeperHang** [DRE2N/DungeonsXL#638]
**Description**

Everytime when I restart the server or /dxl reload, the group signs won't be functioning well as the startIfElementsAtLeast won't be working anymore that players won't teleport to the dungeon automatically.

**Reproduce**

I have checked the other bug reports as well and even tried installing different versions of the plugin (from latest to 0.17.7 and 0.17.5). But it still doesn't work.
Server Version: Paper version git-Paper-629 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Multiverse Version: Multiverse-Core Version: 3.0.0-SNAPSHOT-b760

**Screenshots / GIFs / videos**

https://ibb.co/R0zrttj

```

**Comment by devingDev** [comment]
We have this problem too that after sometime the signs for group don't start once it's full. Not sure what triggers this behaviour. Maybe it was /dxl reload too.
This is on a 1.14.4 Spigot server
