### ISSUE TITLE
I need your help. 

### ISSUE THREAD

**Issue by Fi1zz** [DRE2N/DungeonsXL#641]
Why does the configuration file I set for my replica world not take effect?

GameMode: ADVENTURE and initialLives: 2 have no effect
Examples:

message:
  '1': wda
secureObjects: []
invitedPlayers: []
timeToFinish: 1248
gameMode: ADVENTURE
initialLives: 2

**Comment by Sataniel98** [comment]
I don't know, perhaps another config or the game type overrides it.
