### ISSUE TITLE
Feature Review - Videos or Example Maps?

### ISSUE THREAD

**Issue by JaHollTV** [DRE2N/DungeonsXL#644]
**The feature you'd like to know more about**

[//]: # (e.g. game rules)

**Link to the wiki article (in case it exists)**

**What did you already try?**

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
Nope, see the FAQ.
