### ISSUE TITLE
Bugging around while the Dungeons is about to end.

### ISSUE THREAD

**Issue by SushiBarIV** [DRE2N/DungeonsXL#645]
**Description**

Since I killed the last Mob / Boss I'm getting stuck and I can't do anything, except
leaving the Server to join again. Im falling throught the map and when I try
to type sth. in the Chat, sth. like this will show up: **You can't message**.

**Reproduce**

Already descriped in the Description

**Expected behavior**

Normaly, the Dungeon needs to be ended, since the boss gets killed.

**Error code/s**

*https://pastebin.com/iK8FRBwQ*

**Comment by Sataniel98** [comment]
Does this occur with Spigot 1.13.2?

**Comment by SushiBarIV** [comment]
No in 1.14.4

**Comment by Sataniel98** [comment]
Yeah but does it also occur in 1.13.2?

**Comment by SushiBarIV** [comment]
I don't know, I don't use 1.13.2. But I may can try that

**Comment by SushiBarIV** [comment]
And somehow, DXL will always reset my language file
