### ISSUE TITLE
How would i block off rooms and make a player clear it before continue

### ISSUE THREAD

**Issue by Ratthew** [DRE2N/DungeonsXL#649]
Hi I was wondering if it would be possible to encase the entrances of a dugeon room and force players to kill all the mobs in the area before proceeding to the next location, plz help

**Comment by UnendingNight** [comment]
Combine a [Mob death](https://github.com/DRE2N/DungeonsXL/wiki/signs#mob-death) trigger with an [open door](https://github.com/DRE2N/DungeonsXL/wiki/signs#open-door) trigger.
