### ISSUE TITLE
Despawning Mobs and invisible Mobs.

### ISSUE THREAD

**Issue by UnendingNight** [DRE2N/DungeonsXL#650]
**Description**

My dungeon seems to be having an issue with despawning/disappearing. During the final boss battle when a player respawns they seem to randomly become unable to see the boss, nor can they swing at it. However the boss is still there as other players are still able to interact/fight the boss. During solo play something very similar happens. After dying to the boss and respawning the boss and the other minions despawn completely. This one isn't to chance and happens every time without fail. 

**Screenshots / GIFs / videos**

https://youtu.be/jx8tp__yqBM

**Comment by Sataniel98** [comment]
That's a bug of Minecraft itself. #448
