### ISSUE TITLE
command sign dosen't work on mob killing

### ISSUE THREAD

**Issue by SKYRIMx6023** [DRE2N/DungeonsXL#654]
Here is the sign(Already installed CXL)

[CMD]
fb1end1
1,op
M WolfKing

but when i killed the WolfKing,it dosen't happen anything
other sign still work like:

[end]

M WolfKing

whatever way i used (Trigger or something), still can't let the command sign active after killed some mob

help please! 
verison 0.18

**Comment by Sataniel98** [comment]
Feature will be replaced in the next release.
