### ISSUE TITLE
About mob arena , teleport...etc

### ISSUE THREAD

**Issue by LemonSolar** [DRE2N/DungeonsXL#655]
Hi , there are some questions i wanna ask:
1.Is it possible to set "a specified mob(s) spawn when a specified mob(s) died"? just like mob arena.
2.How can i set "a group / a people is teleported to another place (in same dungeon) when they killed some mobs ?
3.How can i set "a player finished the dungeon and automatically leave when he killed the boss of a dungeon"?
thx for help.

**Comment by Sataniel98** [comment]
Hi,
just add a mob triggier to your mob / teleport / end sign that specifies the mob to kill.

**Comment by LemonSolar** [comment]
Sorry, but i only know how to set "a trigger of single mob"
LIke: I kill 1 mob and tp to another place
but i don't know how to set:I kill 5 mobs completely and tp to another place
Can you give me an example please?

**Comment by Sataniel98** [comment]
Yes, that's how the trigger works. You'll need to find a way with redstone or command blocks if you need something more complicated. See #383.

**Comment by LemonSolar** [comment]
Sorry, can you give me some tips/examples to let me understand how can I set it please?
I tried hard to use redstone to set it, but still doesn't work....
