### ISSUE TITLE
Importing old dungeon worlds.

### ISSUE THREAD

**Issue by Gelox1209** [DRE2N/DungeonsXL#656]
Is there a specified way to import old dungeon maps from older dungeonsxl (specifically version 0.16.3) to the current one?

I have tried just copy and pasting the maps from the old DungeonsXL folder to the new one, and so far, it's giving me this error whenever I try to edit it: https://pastebin.com/N9V5n0hN

**Comment by Sataniel98** [comment]
It is your health scale that is causing errors, not the update or map.
