### ISSUE TITLE
Loot Tables not loading into chests

### ISSUE THREAD

**Issue by hsghgs** [DRE2N/DungeonsXL#659]
**Description**

I have created a loot table using the example and created a reward chest in my dungeon but the loot does not load, even with 100%, I tried using all 3 examples and none of them work.

**Reproduce**

Create Loot Table, Create Rewards chest sign.

**Expected behavior**

Loot to load into chest

**Screenshots / GIFs / videos**

None Applicable

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
[Dungeon1.zip](https://github.com/DRE2N/DungeonsXL/files/3628454/Dungeon1.zip)

```

**Comment by hsghgs** [comment]
I hope you can help me with this, Sorry if this is in the wrong category, also I apologize if this is a simple mistake...

**Comment by Sataniel98** [comment]
The file is called *.yaml instead of *.yml. DXL only recognizes *.yml since *.yaml is almost never used in the context of Bukkit servers.

**Comment by hsghgs** [comment]
Yikes, I feel stupid, didnt even think about that, but new problem, whenever anyone plays the dungeon the signs don't load as chests. They do in test mode but not when they play.

**Comment by Sataniel98** [comment]
Players must trigger a ready sign before the game starts.

**Comment by hsghgs** [comment]
Awesome, that makes sense, now how do players finish the dungeon, is it using the leave sign or is it something else, cause money,levels and items are not being added after using the leave sign.

**Comment by hsghgs** [comment]
NVM, I figured it out using the end sign, thank you so much for your help.

**Comment by hsghgs** [comment]
I do have one more question, how can I add items from custom enchants into the loot table, is this possible?

**Comment by Sataniel98** [comment]
It depends on how your plugin recognizes the items as custom items. If it for example just checks for lore lines, all you have to do is add that lore in the loot table file. If it uses custom NBT data, things are a little more complicated. Most plugins don't use the new API for custom item data, and thus, they aren't represented in Bukkit's item stack serialization system. As far as I know, these item stacks can still be saved without losses, but they use some kind of unreadable hash, so you can't easily modify with notepad.

**Comment by hsghgs** [comment]
Well im using the crazy enchants plugin, I dont know how to check what its using so maybe you know?

**Comment by Sataniel98** [comment]
They use lore lines.
