### ISSUE TITLE
Mythic Mobs Inteegration

### ISSUE THREAD

**Issue by Talon0513** [DRE2N/DungeonsXL#660]
**The feature you'd like to know more about**
DungeonsXL Signs for [Mob] not spawning Mythic mobs

[//]: # (e.g. game rules)

**Link to the wiki article (in case it exists)**
None

**What did you already try?**
Used Dungeon Sign copied from the wiki
[mob]
SkeletalKnight
1,4,MM
D 12

But this does not spawn a skeletal knight

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
Works fine for me.

**Comment by Talon0513** [comment]
Was the setup I sent you correct?


Sent from Mail for Windows 10

**Comment by Sataniel98** [comment]
I didn't receive anything.

**Comment by Sataniel98** [comment]
@Talon0513 Do you still have issues with this?
