### ISSUE TITLE
MythicMobs despawn on death.

### ISSUE THREAD

**Issue by Eutherin** [DRE2N/DungeonsXL#665]
**Description**

If I die while a mythicmob is active it disappears and is not there when I respawn.

**Reproduce**

place MM sign for skeletalknight/minions, die

**Expected behavior**

Mobs should stay alive when you die.

**Screenshots / GIFs / videos**

See zip below.

**Relevant configuration files**

https://www.mediafire.com/file/twejtea5gdt83lh/SwampLair.zip/file

**Comment by RogerPlaysMC** [comment]
That’s MythicMobs. Set Despawn: false on the mob.

**Comment by Sataniel98** [comment]
DungeonsXL doesn't handle external mobs in any way different from when a player runs commands to spawn them. If there are bugs, please report them to MythicMobs.
