### ISSUE TITLE
Chest

### ISSUE THREAD

**Issue by LolGecko30** [DRE2N/DungeonsXL#67]
Players can just walk through dungeons without hitting mobs and get the loot and leave, how do I stop that?

**Comment by Sataniel98** [comment]
You could add mob, wave or progress triggers to your dungeon signs. They make it so that the things get triggered just if the enemies are defeated. You can connect them with other triggers, for example distance triggers, if you want.

https://github.com/DRE2N/DungeonsXL/wiki/signs#triggers
