### ISSUE TITLE
/dxl rewards command didnt work

### ISSUE THREAD

**Issue by micahkun** [DRE2N/DungeonsXL#672]
the command didnt work, it didnt show anything.
(of course im completing the dungeon first)

**Comment by Sataniel98** [comment]
Such a command doesn't exist.

**Comment by micahkun** [comment]
ah, i guess  im watching some old tutorial.
So, how to open rewads chest/inventory if i accidentally close it before i take all the rewards?

**Comment by Sataniel98** [comment]
It should drop everything in the inventory.
