### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#675]
**The feature you'd like to know more about**

Classes

**What did you already try?**

I tried to go into the 'classes' folder already but it is empty.

**Comment by Sataniel98** [comment]
Please read the wiki before asking questions.

**Comment by TheWackersKian** [comment]
Ahh yes I have found it now, but I'm very new to this stuff. Where do I add 
"keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true"
to. Sorry for bothering you, haha. And would that allow people to bring items from the main world into the game, or just instead bring items from the game back into main world.
