### ISSUE TITLE
Dungeon not starting automatically after restart / reload plugin

### ISSUE THREAD

**Issue by HauserGrim** [DRE2N/DungeonsXL#683]
**Description**

Amount of groups to start dungeon automatically removed after restart server from Game sign.

**Reproduce**

Create Game sign with "1,1" on 4 line
Game should begin when the group joins.
Restart / stop server / reload DXL to save data.yml
When join group game no longer automatically run.
Check data,yml, even though there is a line in file responsible for the automatic start, it disappears at the next restart.

**Expected behavior**

This should not happen with normal behavior.

**Screenshots / GIFs / videos**

https://youtu.be/DJX_a28QkSE

**Relevant configuration files**

Default

**Comment by Sataniel98** [comment]
Video is private

**Comment by HauserGrim** [comment]
Strange, I set access by link. Same link.

**Comment by Sataniel98** [comment]
Fixed!
