### ISSUE TITLE
Server crashes often in the middle of the dungeon.

### ISSUE THREAD

**Issue by jpotyka** [DRE2N/DungeonsXL#684]
**Description**
[//]: # (A clear and concise description of what the bug is.)
Server crashes in the middle of the dungeon.
Most of the time some mobs have been spawned and fought.
Towny is disabled for new worlds (using the feature from towny).
Spigot:1.14.4-R0.1
DXL: v0.18-SNAPSHOT-771
java-8-openjdk

Used Mobs:
Some Illager
Villager
Zombies

**Reproduce**
[//]: # (List steps to reproduce)
Restart the server and try to do the dungeon a few times.

**Expected behavior**
[//]: # (A clear and concise description of what you expected to happen.)
Let me finish the dungeon.

**crash-report**
as file
[crash-2019-11-11_22.42.41-server.txt](https://github.com/DRE2N/DungeonsXL/files/3853873/crash-2019-11-11_22.42.41-server.txt)

**Comment by Sataniel98** [comment]
As the log says, an NPE is thrown ticking an entity. This is internal stuff that has nothing to do with a Bukkit plugin.
