### ISSUE TITLE
RewardChest Sign not working correctly

### ISSUE THREAD

**Issue by Dartanboy** [DRE2N/DungeonsXL#685]
**Description**

When I create a dungeon and use a [RewardChest] sign, it does not work. When someone enters the Dungeon, it does create a chest, however it does not reward any money or XP. I do have Vault installed.

**Reproduce**

Place a sign in a dungeon (in edit mode) with the following lines:
1 - [RewardChest]
2 - 150,2
3 - *Blank*
4 - *Blank*

**Expected behavior**

I expect for this chest to add $150 to the player's balance on completion of the dungeon. This a) does not happen nor b) shows any signs of this attempting to happen. No console errors, no in-game messages, etc.

**Media**

No available media.

**Comment by Sataniel98** [comment]
Is economyEnabled set to true in the main config?
