### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by mamilicalmir** [DRE2N/DungeonsXL#686]
**Description**
When entering the dungeons multiples times crashes the server
[//]: # (A clear and concise description of what the bug is.)

**Reproduce**

[//]: # (List steps to reproduce)

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)
https://pastebin.com/PbNuukCw
**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
This is a server bug.
