### ISSUE TITLE
Players are keeping Inventory from old Runs.

### ISSUE THREAD

**Issue by JJ003333** [DRE2N/DungeonsXL#687]
**Description**

Some but not all of my players keep there old inventory from one DXL map to the next. # (A clear and concise description of what the bug is.)

**Reproduce**

When Musty_Song goes in to any DXL map. He Still have items from the last time he was in a DXL map

**Expected behavior**

They should have nothing when they join the Lobby of a DXL map.
They should NOT drop items and keep them after death.
I should not be forced to log out after winning, just to rejoin the main world.

I just want to know how i Fix it for my Players. They love this. I just don't know what i might have set up wrong. 

Unrelated but also a problem.
Players keep there inventory after death and drop them. 
I'm using the Bedwars config unedited / unchanged.
Just added the Sample map and ran with it.

**Relevant configuration files**

[Config.txt](https://github.com/DRE2N/DungeonsXL/files/3881966/Config.txt)

[//]:  (If applicable, add screenshots to help explain your problem.)

![image](https://user-images.githubusercontent.com/47468570/69469330-337ae380-0d5e-11ea-9316-db9e86403e77.png)
![image](https://user-images.githubusercontent.com/47468570/69469215-a6d02580-0d5d-11ea-845f-c7c53a9058b9.png)
![image](https://user-images.githubusercontent.com/47468570/69469233-c23b3080-0d5d-11ea-924c-2a0f4724b16f.png)
![image](https://user-images.githubusercontent.com/47468570/69469241-ccf5c580-0d5d-11ea-94f1-de9ff5c9a1ab.png)
![image](https://user-images.githubusercontent.com/47468570/69469321-24943100-0d5e-11ea-8594-c526857465ff.png)

After all that. When i Win. I get stuck. I cant use any chat Functions. no commands or talking. 
The map vanish and i just bounces like I'm having bad rubber banding.

![image](https://user-images.githubusercontent.com/47468570/69469695-2d860200-0d60-11ea-8a02-4f9f81aaec27.png)

**Comment by JJ003333** [comment]
My main problem is that they buy good stuff in bedwars and take it in to the Hard Dungeons.
they should be wiped of all items and then need to pick a class. but they keep their items. using them to cheat

**Comment by JJ003333** [comment]
![image](https://user-images.githubusercontent.com/47468570/69485200-1865ad80-0e0a-11ea-9c97-3efec4a64ee1.png)

**Comment by JJ003333** [comment]
This is the Admin group
![image](https://user-images.githubusercontent.com/47468570/69485204-36331280-0e0a-11ea-9871-52314f336ab2.png)

**Comment by JJ003333** [comment]
I dont know why this group # keeps going up
![image](https://user-images.githubusercontent.com/47468570/69485228-87430680-0e0a-11ea-9217-6919ed0c4ca3.png)

**Comment by Sataniel98** [comment]
The group ID is a static counter; this behavior is intended. Think of it as an ID number like in Discord. If you don't want it, give the groups unique names through group signs. DungeonsXL does not support Multiverse-Inventories. Make sure to disable it for the DXL worlds.
