### ISSUE TITLE
API question. Check if player in dungeon.

### ISSUE THREAD

**Issue by HauserGrim** [DRE2N/DungeonsXL#688]
How can I check if a player in game (dungeon)? Or get list of players in the all games?

**Comment by Sataniel98** [comment]
You can check if the world startsWith("DXL_Game_") or just get the DGlobalPlayer representation and check if it is instanceof DGamePlayer. DungeonsXL#getDPlayerCache().getByPlayer(Player).

**Comment by HauserGrim** [comment]
Thanks
