### ISSUE TITLE
Phatloots support 

### ISSUE THREAD

**Issue by Markiie** [DRE2N/DungeonsXL#690]
**Please describe the use case or the problem your request is related to.**

[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...];)
I can't seem to use the plugin phatloots. It's what I use everywhere else on my server and it would be fantastic if I was able to set them in my dungeons too. however, when I do so and test the dungeon it just appears as a normal chest.
**Describe the solution you'd like**
If at all possible add support for Phatloots allowing me to add loot chests in dungeons 
[//]: # (A clear and concise description of what you want to happen.)

**Describe alternatives you've considered**
I haven't really considered any I'm afraid. I have considered crying in a corner but that's about it. 
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)
N/a

**Comment by Sataniel98** [comment]
Not sure about this, it looks like DXL's reward chests do the important things of it out of the box.

**Comment by Markiie** [comment]
Yes I agree, however, DXL doesn't allow you to add items custom you made by hand as far as I'm aware. It's also nice to keep one plugin controlling everything to do with the said feature. For example, I cant use DXL reward chests anywhere else other than dungeons. I could, however, use phatloots wherever I like. I can setup one chest and set certain chances and certain loot-tables and use them all over the world. It's just so much more easy to organize and keep up with!
