### ISSUE TITLE
Massive lag after the server has ben running dungeons for some time

### ISSUE THREAD

**Issue by ffjdksl** [DRE2N/DungeonsXL#692]
**Description**

I recently introduced 3 new dungeons to my server, making them far more popular. Now that my players have been using dungeons a lot more, at times the server starts lagging and doesn't stop until a reload is done. 

**Reproduce**

Have one or 2, even 3 dungeons.
Let your players do their thing
The server slowly, from one moment to another starts lagging bad.

**Expected behavior**

The server doesn't lag.

**Screenshots / GIFs / videos**

I'll paste some logs the server generates once the lag starts.
https://www.dropbox.com/s/turhvbd3izjp8bv/2019-12-21-9.log?dl=0
https://www.dropbox.com/s/turhvbd3izjp8bv/2019-12-21-9.log?dl=0

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
Don't know which configuration file could be wrong here.
```

**Comment by Sataniel98** [comment]
This isn't really expressive, please provide timings for lag reports.

**Comment by ffjdksl** [comment]
Oh, forgot I had this open. Noticed the issue was the server ram getting
full, sorry!
