### ISSUE TITLE
Error when trying to join Dungeon

### ISSUE THREAD

**Issue by project-play** [DRE2N/DungeonsXL#693]
**Description**

I become an java.io.FileNotFoundException: plugins/DungeonsXL/maps/test/DXLData.data (No such file or directory) Error

**Reproduce**

Edit map and configure all settings Save it leave the edit mode and try it with firends or alone

**Expected behavior**

java.io.FileNotFoundException: plugins/DungeonsXL/maps/test/DXLData.data (No such file or directory)

**Screenshots / GIFs / videos**
https://imgur.com/a/QUa9N8K

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
Seltsam, eigentlich sollte es keine Möglichkeit geben, dass eine Map ohne die DXLData-Datei geladen wird. Gab es vorher noch andere Fehler?

**Comment by project-play** [comment]
Da sind zur zeit zeit Zwei Fehler in den Logs
https://imgur.com/a/AePFVxj
https://imgur.com/a/9DvvRKy Das sind die Fehler

**Comment by Sataniel98** [comment]
Dann hast Du ein Server-Setup-Problem. DungeonsXL bzw. Bukkit braucht die Permissions, an der Stelle Dateien erstellen zu können.
