### ISSUE TITLE
Citizens' NPCRightClickEvent does not fire for Citizens made by DXL Dungeon Signs

### ISSUE THREAD

**Issue by Dartanboy** [DRE2N/DungeonsXL#696]
Description

If a sign makes a Citizen in a DXL dungeon, the NPCRightClickEvent does not fire when they are right-clicked.

Reproduce

Create a dungeon, create a [Mob] sign creating an NPC, use the NPCRightClickEvent.

**Comment by Sataniel98** [comment]
This is probably because Citizens mobs created by DXL are transient and not stored in Citizens' registry. It might be possible to fire the events manually, but better use the respective Entity events in the meantime.

**Comment by Sataniel98** [comment]
You can now use the game rule "useNativeCitizensRegistry: true" to avoid this issue. Note that this rule is not supported.
