### ISSUE TITLE
Infinite void after finishing a dungeon

### ISSUE THREAD

**Issue by Dartanboy** [DRE2N/DungeonsXL#697]
**Description**

After finishing a dungeon, sometimes the player in the dungeon gets stuck in an endless void. Player is unable to chat, move, or do anything. They are also invisible to all commands (for example, I did /kick <player> in an attempt to get them out, but Essentials told me there was no player with that name). They are, however, in the TAB list.

**Reproduce**

You finish a dungeon, I guess. The [End] sign had a Mob Death trigger of a mob from MythicMobs.

**Expected behavior**

You finish a dungeon and get teleported back to where you entered.

**Screenshots / GIFs / videos**

I have a screenshot from my friend who was in the dungeon. I was saying random crap in the console beforehand so you can see that in his chatbox. He sent it to me on Discord you can see it here:

https://cdn.discordapp.com/attachments/655910918709837845/662850665256583199/2020-01-03_20.50.44.png

I also managed to get the Console Error.
https://pastebin.com/EWkgBTXG

**Comment by Dartanboy** [comment]
Got the entire error today, as opposed to the partial one from above:

https://pastebin.com/xrphQzJk

**Comment by Dartanboy** [comment]
**Successful Workaround**

Detect mob death with a [Redstone] sign with a small delay that powers the [End] sign so it does not occur on the same tick.

**Comment by Sataniel98** [comment]
Couldn't reproduce this with Vanilla or the default MythicMobs. Please confirm it still occurs in the latest build and, if it does, provide the mob you used.
