### ISSUE TITLE
startIfElementsAtLeast get deleted after a restart

### ISSUE THREAD

**Issue by SparkGNRK** [DRE2N/DungeonsXL#700]
When the server restart or when I reload the plugin, the line on data.yml "startIfElementsAtLeast" get deleted and dungeons can't start when groups click the game sign.

**Reproduce**

Set a "game" sign with an "amount of groups to start the dungeon automatically" and reload the plugin or restart the server.

**Expected behavior**

The line "startIfElementsAtLeast" shouldn't be deleted.

DXL v0.18 771
Spigot 1.12.2

**Comment by Sataniel98** [comment]
Thank you for the report :)
I'll review this for the next release.

**Comment by SparkGNRK** [comment]
Thanks ! :)

**Comment by Sataniel98** [comment]
Fixed.

**Comment by SparkGNRK** [comment]
Thanks ! 👍
