### ISSUE TITLE
keep inventory on death bug

### ISSUE THREAD

**Issue by NotHattori** [DRE2N/DungeonsXL#702]
even if the flag is set to be true, the inventory is cleared when the guy respawns and has more then one life, also, the items disappears, they don't drop in ground, they just disappear
i don't know if it's a bug caused because i'm using 1.8.8 minecraft or if i'm doing anything wrong.
thx 4reading
( without pre-kit set )

**Comment by Sataniel98** [comment]
Duplicate. Already resolved
