### ISSUE TITLE
CustomMob collaboration support

### ISSUE THREAD

**Issue by MusicIsForLosers** [DRE2N/DungeonsXL#71]
Hi,
I need help regarding using the CustomMob plugin with your Dungeons plugin. I don't know how to add the mobs into your dungeons

**Comment by Sataniel98** [comment]
Try to use an ExternalMob sign :)

https://github.com/DRE2N/DungeonsXL/wiki/signs#externalmob

The mob provider ID of CustomMobs is CM.
