### ISSUE TITLE
How do you control which direction the nether portal blocks faces?

### ISSUE THREAD

**Issue by ValleVonMemester** [DRE2N/DungeonsXL#710]
You wrote somewhere that it depends on what direction the player is facing. If I want them to go from east to west, what direction should I face and when does the direction I face matter (is it when you execute the command or when you mark the corners of the portal with the wooden sword?)

**Comment by ValleVonMemester** [comment]
edit: fixed with worldedit

//replace minecraft:nether_portal minecraft:nether_portal[axis=z]

**Comment by Sataniel98** [comment]
Duplicate of #668
