### ISSUE TITLE
Players taking gears in

### ISSUE THREAD

**Issue by JustinHa95** [DRE2N/DungeonsXL#712]
Hello, I would like to enable players from taking there own equipments to the dungeon, however its clearing the inventory and no one has there equipments when entering the dungeon. Any suggestions? Thanks.

**Comment by Sataniel98** [comment]
Please read the wiki. This is explained in detail.

**Comment by JustinHa95** [comment]
I have added this into the rightful folder but its still not working for me... I have tried to create multiple dungeons with /dxl create Test, Test_02, and Test_03.  This is the config for the Test.yml


![Untitled](https://user-images.githubusercontent.com/61490221/75421159-4245d900-58ff-11ea-9094-c34e5a8ede8f.png)

I also checked console and I keep getting this error...

>.... [02:12:10 INFO]: [DungeonsXL] The setup of dungeon Test.yml is incorrect. See https://github.com/DRE2N/DungeonsXL/wiki/dungeon-configuration for reference.

**Comment by Sataniel98** [comment]
There's a map called Test and the dungeon is called Test.yml. This creates two dungeons called "Test" (the multi floor dungeon with Test, Test_02 and Test_03 and the single floor dungeon of the map) which doesn't work, they need to be unique.
