### ISSUE TITLE
Include reloading loot tables in /dxl reload

### ISSUE THREAD

**Issue by johnelder** [DRE2N/DungeonsXL#713]
It seems that when we do /dxl reload, the loot tables are not reloaded.  If I'm missing something, please let me know.

Otherwise, can we get a call to caliburn to reload the loot tables at the same time?
Or, a command to reload loot tables manually?

Thank you

**Comment by Byte-Oracle** [comment]
Using /dxl reload also allows for the ui buttons to be taken off of the rewards screen into player inventories.
