### ISSUE TITLE
RewardsChest

### ISSUE THREAD

**Issue by Ikodeiix** [DRE2N/DungeonsXL#716]
Bonjour, 

J'utilise votre plugin afin de faire des dungeons et me retrouve bloqué à l'ajout des "rewardChest"
J'ai installé votre fichier exemple .yaml que j'ai renommé loot dans le dossier script/lootable.
Quand j’installe le panneau, le message "You have succesfully created a dungeons sign"

voici quelques photo de mes tests
![2020-03-06_20 57 07](https://user-images.githubusercontent.com/60135852/76118144-8fa40380-5fed-11ea-8e26-593166429ba5.png)

Le enableEconomy est bien mit sur "true"

**Comment by Ikodeiix** [comment]
Le problème étant évidemment que les panneaux restent visibles au lancement du dungeons et que rien est présent dans les coffre

**Comment by Sataniel98** [comment]
Bonjour, 
vous avez un panneau [ready] pour commencer le jeu?

**Comment by Ikodeiix** [comment]
Le panneau réady est bien installé et fonctionne parfaitement au lancement du dungeons 
![2020-03-07_08 13 02](https://user-images.githubusercontent.com/60135852/76138900-8b0e3800-604b-11ea-8256-41c7edd2cd69.png)

**Comment by Sataniel98** [comment]
Il y a des erreurs ou méssages dans la console ? Est-ce que le panneau marche sans "loot" ? Le fichier s'appelle "loot.yml" (pas ".yaml") ?

**Comment by Ikodeiix** [comment]
Au lancement du dungeons, aucune erreur est présente dans la console : 
![Capture](https://user-images.githubusercontent.com/60135852/76160405-6fc62a00-612a-11ea-9b84-ab50b4ea2cac.PNG)

Le panneau ne fonctionne pas en laissant juste la money et l'xp gagné : (le dungeons est ici bien lancé)
![2020-03-08_10 51 40](https://user-images.githubusercontent.com/60135852/76160474-d5b2b180-612a-11ea-9465-e67fccd2307c.png)

Vue  que je n'ai pas bien compris en lisant le wiki, j'ai mit le même fiché avec les deux extensions différentes : 
![bbb](https://user-images.githubusercontent.com/60135852/76160530-39d57580-612b-11ea-902a-02922b66e721.PNG)

Voici mon config.yml si cela peu aidé :/ 
![aaa](https://user-images.githubusercontent.com/60135852/76160538-4eb20900-612b-11ea-9aae-88ddab524fe9.PNG)

Je te remercie du temps que tu passe à m'aider ! 👍

**Comment by Sataniel98** [comment]
De rien. Le panneau droit est trop loin du coffre. Les panneaus avec un loot table marchent sans coffre, mais les autres ont besoin d'un coffre à côté pour les items.

**Comment by Ikodeiix** [comment]
Donc si je comprends bien, les panneaux utilisant une loottable nécessite aucun coffre ? Et les panneaux sans doive être coller sur le block à coté, à la même hauteur ?

**Comment by Sataniel98** [comment]
Les panneaux utilisent les items du coffre à côté (un bloc, la diréction n'est pas importante) et ajoutent les items de la loottable. S'il n y a pas de loottable et pas de coffre non plus, le panneau ne marchera, mais s'il y a une loottable mais pas de coffre, un coffre généré remplace le panneau.

**Comment by Ikodeiix** [comment]
![2020-03-09_20 23 54](https://user-images.githubusercontent.com/60135852/76249730-426d9f00-6244-11ea-87dd-bb7727385067.png)

(Le panneau reste comme cela quand je start le dungeons)

:/ je n'arrive toujours pas à le faire fonctionner, bizarre étant donné que toutes les autres fonctionnalitées fonctionnent parfaitement …

Tampis, je vais essayer de trouver un autre moyen d'ajouter une récompense à la fin
