### ISSUE TITLE
keepInventoryOnEnter not working ?

### ISSUE THREAD

**Issue by Cornak00** [DRE2N/DungeonsXL#718]
Hello, it's making a long time that I am trying to make players play dongeon with their own inventory. I did everything described in the wiki (in config.yml of the map or directly the config.yml of the plugin). But nothing worked... I don't understand why. Can you help me please ? :/
I'm in spigot 1.15.2

**Comment by Cornak00** [comment]
Thank you for your help

**Comment by Sataniel98** [comment]
Other plugins like Multiverse-Inventories might interfere. If that's not the case, please show me how exactly you set your configs up and what exactly you are doing ingame, step by step.

**Comment by Cornak00** [comment]
Hello, ok thanks to your answer I tried to remoe Multiverse-Inventories and it worked. Thanks you so much, I’ll try another way to set différents inventories between my world. Thanks you very much that was very helpfull ! Just in case, do you know any plugin like Mv-Invetories which not interfere with DXL please ?  De : Daniel SaukelEnvoyé le :lundi 9 mars 2020 12:33À : DRE2N/DungeonsXLCc : Cornak00; AuthorObjet :Re: [DRE2N/DungeonsXL] keepInventoryOnEnter not working ? (#718) Other plugins like Multiverse-Inventories might interfere. If that's not the case, please show me how exactly you set your configs up and what exactly you are doing ingame, step by step.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Sataniel98** [comment]
I don't know - it should be possible to limit MV-Inventories to worlds where you need them, or to exclude the dungeon worlds (DXL_Game_*, DXL_Edit_*) from it.
