### ISSUE TITLE
Class bug

### ISSUE THREAD

**Issue by goldenkuky209** [DRE2N/DungeonsXL#719]
I made a dungeon step by step and it all works if i have OP enabled.
But if i set my rank to default and no OP it tells me "You dont fulfill the requirements for this dungeon. Choose your class first." I dont want to have any classes so i let players with their own items.
```
# A list of requirements
# Note that requirements will be ignored if the player has the
# dxl.ignorerequirements permission node.
requirements:
  feeMoney: 2500
  feeLevel: 10
  # If the group has too many or not enough members, the players will not be allowed to use the ready sign.
  groupSize:
    minimum: 1
    maximum: 1
  # Players must have these permission nodes to enter the dungeon:
  permission:
    - dungeon.mine
  # Items that may not be taken into the dungeon
  forbiddenItems:
    - ELYTRA
    - ENDERPEARL
    - CHORUS_FRUIT
```

**Comment by Sataniel98** [comment]
There are other requirements as well that aren't realized through the requirements API and thus not in this section, like timeToNextPlay, mustFinish etc. If they are fulfilled, the message won't be sent.

**Comment by goldenkuky209** [comment]
The message still appears even after i fulfilled timeToNextPlay, mustFinish
etc.

lun., 9 mar. 2020, 13:35 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
It doesn't send the message if all requirements are met.

**Comment by goldenkuky209** [comment]
It sends me the "chose a class" message. And i do not know how to disable
classes.

lun., 9 mar. 2020, 19:38 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
The class message is wrong, but it's only sent if the requirements aren't met.

**Comment by goldenkuky209** [comment]
I deleted everything in the maps config and added everything again from the
Floor configuration, i edited some of them to match the server (like the
entry fee, time etc.) and the class message still appears.
Do i need to add something else besides the Floor config?


lun., 9 mar. 2020, 19:43 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
You don't need anything other than the dungeon map created with /dxl create or /dxl import. If you'd like to override some config values that are dungeon or map specific, you need a floor config. The default values (the ones used if nothing is configured) are in most cases sufficient. It is recommended to add only the settings you'd like to override and leave the other ones out.

**Comment by goldenkuky209** [comment]
#########################
# MAP SPECIFIC SETTINGS #
#########################

# Defines the map environment, as this is not saved in the map itself.
# May be set to either THE_END, NETHER or NORMAL.
# If this setting is left out (or if no floor config is used at all),
NORMAL will be used.
worldEnvironment: NORMAL

# Players who can edit the dungeon (/dxl invite)
# You my add both UUIDs and names.
invitedPlayers:
- goldenkuky209

##############
# GAME RULES #
##############
# If the Lobby is disabled. This applies only to Dungeons that have to be
solved
# alone and where there are no classes to choose from.
isLobbyDisabled: false

# Time until a player is kicked from this dungeon after going offline (in
seconds)
# -1 = never / 0 = immediately
timeUntilKickOfflinePlayer: 600

# Time in hours until a player can play this dungeon again
# This prevents players from playing the dungeon again if they started the
dungeon,
# no matter if they finished, left it or got kicked.
timeToNextPlayAfterStart: 6

# This only prevents players from playing the dungeon again if they
finished it correctly.
# If they leave it or get kicked, players can always retry a dungeon.
timeToNextPlayAfterFinish: 12

# Time until a player can get loot for another time
timeToNextLoot: 12

# Time until a new mob waves begins when enough mobs are killed.
timeToNextWave: 10

# Dungeons can be played with a timer.
# If the group has no time left, the players get kicked.
timeToFinish: 900

# The game mode, SURVIVAL if nothing
gameMode: ADVENTURE

# If players may fly.
fly: false

# PvP
playerVersusPlayer: true
# Friendly fire refers just to members of the same group
friendlyFire: false

# These commands can be used by all players if they are in the dungeon.
# DXL commands like /dxl leave are included by default.
gameCommandWhitelist:
  - version
  - f list
  - f show
  - ch global

# MAKE SURE YOU EDIT THIS PART!
# One of these Dungeons must be finished ("any" for any dungeon).
# If you do not want any, leave this empty.
mustFinishOne:
  - any

# All of these Dungeons must be finished. If you do not want any, leave
this empty.
mustFinishAll:
  - jumpinjackflash
  - highwaytohell
  - wontgetfooledagain

# Max time in hours after the last finish of one of the Dungeons above
timeLastPlayed: 336

# A list of requirements
# Note that requirements will be ignored if the player has the
# dxl.ignorerequirements permission node.
requirements:
  feeMoney: 2500
  feeLevel: 10
  # If the group has too many or not enough members, the players will not
be allowed to use the ready sign.
  groupSize:
    minimum: 1
    maximum: 1
  # Players must have these permission nodes to enter the dungeon:
  permission:
    - dungeon.mine
  # Items that may not be taken into the dungeon
  forbiddenItems:
    -
    -
  # Items the player must have to play the dungeon
  keyItems:
    -
    -

# Shall players play the dungeon with their own items or do you want to use
classes?
keepInventoryOnEnter: true
# Shall players lose their items when they die (do not mix up this with
"onEscape"!)?
keepInventoryOnDeath: true
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: true
# Shall players keep their inventory when they leave the dungeon without
succeeding?
keepInventoryOnEscape: true

# If players can build and destroy blocks in this world.
breakBlocks: false
# If players may destroy blocks they placed themselves.
breakPlacedBlocks: false
# A whitelist of breakable blocks.
# breakBlocks is supposed to be set to "true" if this should be used.
breakWhitelist:
  # A material value and a list of all tools that can destroy this block
  SPONGE: ["IRON_PICKAXE", "STICK"]
  # Dirt blocks can be destroyed with any tool
  DIRT: []

# A list of all entity types that shall be protected from damage.
# If this is left out AND if breakBlocks is false, armor stands, paintings
# and item frames will be protected by default.
# If this is left out and if breakBlocks is true, nothing will be protected
by default.
damageProtectedEntities:
- SLIME
- PAINTING
# A list of all entity types
# If this is left out AND if breakBlocks is false, armor stands
# and item frames will be protected by default.
# If this is left out and if breakBlocks is true, nothing will be protected
by default.
interactionProtectedEntities:
- ARMOR_STAND

placeBlocks: true
# A whitelist of placeable blocks.
# placeBlocks is supposed to be set to "true" if this should be used.
placeWhitelist:
  - SPONGE

# Amount of lives a player initially has when he enters a dungeon
initialLives: 3
# Alternatively, you can use group lives.
initialGroupLives: 3

# Messages also to be created with /dxl msg
message:
  '1': Welcome to this dungeon!
  '2': Another message

# Items you cannot drop or destroy
secureObjects:
- 69

# A list of permissions players get while they play the game.
# The permissions get removed as soon as the player leaves the game.
# Requires Vault and a permissions plugin like PermissionsEx.
gamePermissions:
  - dxl.reload
  - another.node

# Use this to replace the default ready / new floor message.
# This is fully compatible with the override system.
# If titles are deactivated in the main config, this is not going to work.
title:
  title: "&6&lThe Mine"
  subtitle: "&aEasy"
  actionBar: "&aA C T I O N B A R"
  chat: "&bCentered chat message"
  # How long shall the title be visible (seconds)?
  # The title works without these three options.
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0

# If it should rain permanently in the dungeon
# true = permanent rain
# false = permanent sun
# leaving this out = random weather like in vanilla Minecraft
rain: false

# Same principle as above but for thunderstorms
thunder: false

# The time ticks (to be used like in the vanilla /time command)
time: 20000



This is my config rn. I dont know whats wrong with it, the class message
still appears.

lun., 9 mar. 2020, 20:03 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
This is almost an exact copy of the list of possible game rules in the wiki. It is not intended to be copied. If this is used, a player may use the ready sign if he either has the dxl.bypass permission or:
- Hasn't started the dungeon for at least six hours.
- Hasn't finished the dungeon for at least twelve hours.
- Has already finished at least one dungeon.
- Has finished the dungeons named "jumpinjackflash", "highwaytohell" and "wontgetfooledagain" in the last 336 hours.
- Has at least 2500 of the Vault main currency.
- 10 experience levels.
- Is in a dungeon group with exactly one member.
- Has the permission node "dungeon.mine".
And I don't know if the keyItems and forbiddenItems sections are syntactically valid like this.

The player also gets the permission to reload the DungeonsXL plugin (and kick the whole server out of their dungeon games).

You should consider removing the whole config. The keepInventory rules are the only thing in it I can certainly tell are intended to be there, but in my experience, most users who want them enabled use them in all dungeons, so adding them to the default section of the main configuration should be preferable. Let DungeonsXL handle the rest itself and include and the respective rule in a config  if you notice something doesn't work like you want it to.

**Comment by goldenkuky209** [comment]
Thank you!
It works now.
One last question, how can i add a custom item (for ex: and item from
MMOItems) to KeyItems?

lun., 9 mar. 2020, 20:54 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
You can register the item in ItemsXL. Using items from other plugins by their own respective internal identifiers isn't supported.

**Comment by goldenkuky209** [comment]
Ok ty.
Your plugin is awesome lol

lun., 9 mar. 2020, 21:39 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
Thank you ^^ Glad I could help
