### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#72]
To start with, thank you for the amazing plugin DungeonsXL! My whole server is currently based on it, and I hope you will enhance it in the future.

However, because of the incomplete wiki, I have two questions for you:
1. How do you "convert" a Map to a Dungeon? Wiki suggests to put the maps to DungeonsXL/maps, but they get recognised as a map, not a Dungeon. I somehow need to "convert" them to Dungeons, because I need to edit the Dungeons config.
2. The Group signs provide entering a group with a predefined Dungeon to play. Is it also possible to create a group and select the dungeon with commands, and if yes, how?

Thank you for the time you put into this, I really appreciate this, and hopefully your plugin will have a bright future!

**Comment by Sataniel98** [comment]
A map can always be used as a single floor dungeon. If you want to include it in a multi floor dungeon, just create a dungeon config and the plugin will handle the rest :)
The /dxl play command allows players to join a dungeon and groups can be set up without a sign with /dxl group. In 0.12 dev builds, there is a semi-working announcer for games similar to the one in ZArena.

**Comment by Sataniel98** [comment]
Du bist laut Profil Österreicher? Du kannst auch gern auf Deutsch schreiben :)

**Comment by ghost** [comment]
Deine erste Antwort betreffend, müsste ich also nur die Vorlage in der Wiki in DungeonsXL/maps als config.yml abspeichern, oder braucht die den Namen der Map? Falls nichts von den beiden zutrifft, könntest du mir dann bitte eine genaue Anleitung liefern.

(Edit: In einer Map wurde bereits eine config.yml automatisch erstellt, der Code lautet wie folgend:
`message:
  // Messages des Dungeons
secureObjects: []
invitedPlayers: []
`
Ich habe den Code mal hier rein kopiert.)

Die zweite Antwort hat mir hingegen sehr geholfen, danke für deine Hilfe und Bereitschaft.

**Comment by ghost** [comment]
Danke für die Hilfe, die Config funktioniert. Viel Glück mit diesem wundervollen Plugin, und ich hoffe auf weitere Updates.
