### ISSUE TITLE
Make a trigger based on the number of monsters killed

### ISSUE THREAD

**Issue by Misolation** [DRE2N/DungeonsXL#721]
Hi plugin author
I successfully registered on GitHub to use Issues Tracker
As the title says,
Make a trigger based on the number of monsters killed
can this be achieved in the future?
Looking forward to your reply.

If bother you
I'm very sorry

**Comment by Sataniel98** [comment]
I agree that better mob waves and triggers is an important new feature for DungeonsXL. However, while it is easy to implement a trigger that simply counts killed mobs of a type, this still doesn't allow complex setups. I have plans to add ways to group mob signs together into one trigger and for a new mob wave system, but this can unfortunately not be done in the next major update (v0.18). The relevant issues for these topics are #452 and #383.
