### ISSUE TITLE
How to create a custom item?

### ISSUE THREAD

**Issue by goldenkuky209** [DRE2N/DungeonsXL#724]
Hello, i would like to know how to create a custom item and where should i put it?(main config,floor config, etc).
I want to create a custom key item that allows players to enter a dungeon, and the custom key item gets to get removed after entering the dungeon.

**Comment by Sataniel98** [comment]
We use ItemsXL for this: https://github.com/DRE2N/CaliburnAPI/wiki However, this will change a bit in the next version.

**Comment by goldenkuky209** [comment]
I have installed ItemsXL and tried to create a custom item but every time i
create a file for it it tells me
"An internal error occured while attempting to perform this command"

vin., 20 mar. 2020, 00:52 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
Probably a syntax error in the script.

**Comment by goldenkuky209** [comment]
Ok.
Do you know what name the item file needs to have?
I tried KEY.yml but it gave me that error.

vin., 20 mar. 2020, 14:22 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
The name isn't important, but the contents of the file.

**Comment by goldenkuky209** [comment]
Do i copy the file from the CaliburnAPI wiki?

**Comment by goldenkuky209** [comment]
Hello, what do i put in the custom item file and how do i name it?
I just paste the stuff from the CaliburnAPI wiki?

vin., 20 mar. 2020, 15:01 goldenkuky <goldenkuky209@gmail.com> a scris:

> Do i copy the file from the CaliburnAPI wiki?
>

**Comment by Sataniel98** [comment]
It's all explained there. I can't tell you anything other than what it says there.
