### ISSUE TITLE
Leaving dungeons freezes server sometimes

### ISSUE THREAD

**Issue by Eutherin** [DRE2N/DungeonsXL#731]
See title

[//]: # (A clear and concise description of what the bug is.)

**Reproduce**

Enter and leave a dungeon a few times.

**Expected behavior**
leave dungeon without locking up and requiring a force kill on the server.

**Comment by Sataniel98** [comment]
Are there any errors in the console?

**Comment by Eutherin** [comment]
I'll let the server run to figure it out when it crashes again, but it took >15 minutes to shut down last time.

**Comment by apc274003** [comment]
Hello, was this issue fixed? because i am having something very similar

**Comment by Sataniel98** [comment]
I hope this is fixed now. See https://github.com/PaperMC/Paper/issues/3063
