### ISSUE TITLE
Keep Inventory Bug

### ISSUE THREAD

**Issue by apc274003** [DRE2N/DungeonsXL#737]
**Description**

KeepInventoryonFinish, and KeepInventoryonEnter is enabled

**Reproduce**

When players remove armor from inventory, and is put into inventory, than dies, armor disappears, or even if the armo is put back on

**Expected behavior**

Armor is still in inventory

**Screenshots / GIFs / videos**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

configVersion: 16
language: english
enableEconomy: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: false
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
default: {initialLives: 1, initialGroupLives: 1, keepInventoryOnEnter: true, keepInventoryOnFinish: true}

**Comment by Sataniel98** [comment]
Both rules don't change anything about inventory behavior on death, that would be keepInventoryOnDeath.

**Comment by apc274003** [comment]
Problem still occuring even when keepInventoryOnDeath is true, I'm guessing Armor slots aren't registered as inventory when entering a dungeon? Has been tested on a server with no plugins besides dungeonXL, and bug is still there
