### ISSUE TITLE
Dungeons crashing my server?

### ISSUE THREAD

**Issue by apc274003** [DRE2N/DungeonsXL#742]
This is not the same as before, here is my log

https://gyazo.com/5b2820cbe6a4ff8c029f95c0c5fe033f

**Comment by Sataniel98** [comment]
This doesn't look like the full error, is there more?

**Comment by apc274003** [comment]
After a while the server will always crash because of dungeons, it's gotten to the point where I have to disable dungeons, but I don't want too because it's a really good plugin and a big part of my server, and I put a lot of time into it, it just crashes my server too much

Any redstone interactions also give me this error
https://gyazo.com/18c5d138d57ec52deed69c72822a9a67


Crash Log:
[crash-2020-04-02_02.30.04-server.txt](https://github.com/DRE2N/DungeonsXL/files/4423033/crash-2020-04-02_02.30.04-server.txt)

**Comment by Sataniel98** [comment]
You're out of memory, you need more RAM. As for the other issues I'll have a look at them.
