### ISSUE TITLE
KeepInventoryOnFinish: True doesnt keep inventory

### ISSUE THREAD

**Issue by Eutherin** [DRE2N/DungeonsXL#743]
**Description**

[//]: players cant keep their inventory when leaving a dungeon.

**Reproduce**

[//]:put KeepInventoryOnFinish: True in the config.

**Expected behavior**

[//]: players keep their inventory when leaving the dungeon

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]:
"
gameCommandWhitelist:
  - class
  - player
  - skills
  - rpginv
  - rpginventory
  - c
  - p
  - profile

mustFinishOne:
  - tutorial

KeepInventoryOnFinish: true

timeUntilKickOfflinePlayer: 300

title:
  title: "&BThe Jailbreak"
  subtitle: "&4Story Introduction"
  
timeToNextLoot: 12000
"

**Comment by Sataniel98** [comment]
Can't reproduce this after merging gamerules has been fixed. Probably a side effect of it.
