### ISSUE TITLE
How to make Staged Waves?, i.e. Adds more [Mob] Signs to the Wave System.

### ISSUE THREAD

**Issue by TheRealTamama** [DRE2N/DungeonsXL#748]
**Current Issue:**
Waves dont progress until all the other [Mob] Signs are triggered.
Even if Wave was triggered manually, the other [Mob] Signs just spawn infinitely.

**Solutions I'm Looking for:**
I want to make a Horde Dungeon, which will increase the amount of [Mob] Signs for each stage they unclock. Just think of Call of Duty Zombies, its basically that. So now I need a solution of excluding [Mob] Signs from the [Wave] Signs and vise versa via a trigger, from what I have been reading on the forums, it works on a Global effect and it takes in consider for all the [Mob] Signs on the map.

Thank you for reading and taking time to consider my questions. Please do also post any updates on the rewriting of the Wave Feature which I heard from a past post saying its estimated to be done around 2019.

**Comment by Sataniel98** [comment]
Thank you for your feedback! Something like this is planned. It will be possible to add a "mob group" ID to the mob on the mob sign, and waves will be handled per mob group. There is no ETA though, I'm currently working on v0.18 which will include the changes listed [here](https://github.com/DRE2N/DungeonsXL/wiki/changelog#018) and more bug fixes. A rewrite of the trigger and mob wave systems is scheduled for v0.19. I can't promise it will be released in 2020, but it will definitely happen sooner or later.

See #383.
