### ISSUE TITLE
Spawning infinite mobs with MythicMobs

### ISSUE THREAD

**Issue by Al0ris** [DRE2N/DungeonsXL#749]
**Description**

Whenever I use the [mob] sign and spawn a custom mob with mythic mobs, it spawns an infinite amount of the custom mobs vanilla counterpart (A skeleton boss from Mythic Mobs would spawn a vanilla Skeleton) 

**Reproduce**

1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/SkeletonKing/1,1,MM/I 1sign
3. Create interact sign with Id 1
4. Test with /dxl play
5. Trigger ready sign and right click interact sign

**Expected behavior**

I just wanted the Mythic Mob custom boss to spawn one time

**Relevant configuration files**

I didnt change dungeon config

**Comment by Al0ris** [comment]
[Recording.zip](https://github.com/DRE2N/DungeonsXL/files/4435249/Recording.zip)

**Comment by Sataniel98** [comment]
Does this still happen with build 893?
