### ISSUE TITLE
Drop Plugin not working correctly.

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#75]
I use an external Plugin for creating specific items that have a customised drop rate with mobs, which has been working perfectly.
However, when playing in a Dungeon created with your plugin, these items do not drop on mob death. Maybe the drop method gets overwritten by DXL? Is there an option to turn it off?

**Comment by Sataniel98** [comment]
Yes, DungeonsXL currently overrides all drops.

**Comment by Sataniel98** [comment]
The drop system will be improved alongside the new mob and item system I'm working on.
