### ISSUE TITLE
Problem to get back our stuff after a dungeon

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#76]
I have try the actual version for Spigot and your snapshot 0.12 build #15 to compare, problems are the same. 

When someone left a Dungeon, the inventory of the player is empty even if he is in game mode 1. In game mode 0, all players loose there stuff. 
I've look inside the playerSave.yml file and all the save are good. We could see the stuff of the player before he goes through the portal in playerSave.yml . Despite, it's impossible to get it back :s 

I've done some tests to understand what happend.

On my main world 1, the keep inventory is enable and it's where i've seen the problem. User looses there stuff after a dungeon. 

On my main world 2, keep inventory is disable for players. I've try with a friend who is not OP and the problem is already there.

**Comment by Sataniel98** [comment]
Could you provide:
- A list of your plugins
- Your exact keepInventoryOnFinish and OnEscape setup
- The error log if it exists
- The savePlayer.yml, the inventory before joining the dungeon and while playing it
- The leave reason (a leave sign, no lives left, /dxl leave, an end sign, offline time,...)

**Comment by Tiplish** [comment]
I could provide some information : 

**1)Leave Reason**
- If the leave reason is that you select the leave sign in dungeon, you get back your stuff.
- If the leave reason is that you end the dungeon, you loose your stuff
- If the player was in game mode 1, he kept his stuff after leaving the dungeon.

**2)savePlayer.yml**
This file contain the right stuff that the player has before enter in the dungeon. It is what you want to know?

I have a plugin named "GameModeInventory" which could be in conflict... I'm looking for more precision and i come back to you :)

That's all that i can give to you for the moment. I will try some test to provide what you require.
