### ISSUE TITLE
When clicking on an end sign in a multi floored dungeon it teleports you to the next floor for 1 second and immediately teleports you back to the worldspawn

### ISSUE THREAD

**Issue by SpaW2145** [DRE2N/DungeonsXL#763]
I've created A multi floored dungeon, I used the plugin before so I know  how to use it, I was surprised to see that the dungeon is unplayable.
Here is a screenshot of the error message on the console

![Capture](https://user-images.githubusercontent.com/50777078/79304447-a7767d80-7ef1-11ea-9d1d-cf6f61cf6ffd.PNG)

**Comment by Sataniel98** [comment]
Can't reproduce anymore in the latest build, it should be resolved.
