### ISSUE TITLE
Putting this plugin into my server crashes it

### ISSUE THREAD

**Issue by apc274003** [DRE2N/DungeonsXL#765]
Snapshot 911, I don't even know the cause, all I know is the second I put this plugin into my server and restart my server it automatically shuts back down.

Crash Log:

---- Minecraft Crash Report ----
// There are four lights!

Time: 4/16/20 12:46 AM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:910)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:954)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:405)
	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325)
	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270)
	at net.minecraft.server.v1_15_R1.MinecraftServer.loadSpawn(MinecraftServer.java:623)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:469)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:890)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.destroystokyo.paper.io.chunk.ChunkTaskManager.raiseTaskPriority(ChunkTaskManager.java:446)
	at com.destroystokyo.paper.io.chunk.ChunkTaskManager.raisePriority(ChunkTaskManager.java:433)
	at net.minecraft.server.v1_15_R1.PlayerChunk.markChunkUrgent(PlayerChunk.java:104)
	at net.minecraft.server.v1_15_R1.PlayerChunk.onNeighborRequest(PlayerChunk.java:56)
	at net.minecraft.server.v1_15_R1.PlayerChunk.markChunkUrgent(PlayerChunk.java:143)
	at net.minecraft.server.v1_15_R1.PlayerChunk.onNeighborRequest(PlayerChunk.java:56)
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:345)
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.b(PlayerChunkMap.java:822)
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$a$16(PlayerChunkMap.java:737)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.9.0-12-amd64
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 240888272 bytes (229 MB) / 519110656 bytes (495 MB) up to 2075918336 bytes (1979 MB)
	CPUs: 1
	JVM Flags: 2 total; -Xmx2048M -Xms512M
	CraftBukkit Information: 
   Running: Paper version git-Paper-171 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) true
   Plugins: { LuckPerms v5.0.72 me.lucko.luckperms.bukkit.LPBukkitBootstrap [Luck], WorldEdit v7.1.0;8e55131 com.sk89q.worldedit.bukkit.WorldEditPlugin [], ColoredSigns v3.0* com.SirBlobman.colored.signs.ColoredSigns [SirBlobman], WildTP vRelease-2.4.3* us.creepermc.wtp.Core [], XRayDetector v1.0* me.signatured.xraydetector.XRayDetector [], WorldBorder v1.8.7* com.wimbli.WorldBorder.WorldBorder [Brettflan], BuycraftX v12.0.6 net.buycraft.plugin.bukkit.BuycraftPlugin [Buycraft], Broadcaster v2.1.0* de.axelrindle.broadcaster.Broadcaster [Axel Rindle (lalo5)], Votifier v2.6.0-SNAPSHOT com.vexsoftware.votifier.NuVotifierBukkit [Ichbinjoe, blakeman8192, Kramer, tuxed], ProtocolLib v4.5.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], WorldGuard v7.0.2-SNAPSHOT;bf2593e com.sk89q.worldguard.bukkit.WorldGuardPlugin [], MVdWPlaceholderAPI v3.0.1* be.maximvdw.placeholderapi.PlaceholderAPI [Maximvdw], AntiVPN v5.11.37 me.egg82.antivpn.BukkitBootstrap [egg82], CustomItems v2.15.7 com.jojodmo.customitems.Main [jojodmo], FeatherBoard v4.25.0* be.maximvdw.featherboard.FeatherBoard [Maximvdw], mcMMO v2.1.113 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy, kashike], Vault v1.7.2-b107 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], MobHeads v2.3 com.cyber.mobheads.Main [CyberDrain], ColoredAnvils v1.08* me.flamingkatana.coloredanvils.ColoredAnvils [], MyCommand v5.5.1 it.mri.mycommand.Main [emmerrei a.k.a Ivanpro], Essentials v2.17.2.0 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685], HolographicDisplays v2.4.1 com.gmail.filoghost.holographicdisplays.HolographicDisplays [], CommandSigns v2.2.0 be.nokorbis.spigot.commandsigns.CommandSignsPlugin [Nokorbis], SilkSpawners v6.0.0-SNAPSHOT-b${BUILD_NUMBER} de.dustplanet.silkspawners.SilkSpawners [xGhOsTkiLLeRx, mushroomhostage], Citizens v2.0.26-SNAPSHOT (build 1865) net.citizensnpcs.Citizens [fullwall], Shopkeepers v2.8.1 com.nisovin.shopkeepers.SKShopkeepersPlugin [nisovin, blablubbabc], MythicMobs v4.9.0-3255 io.lumine.xikage.mythicmobs.MythicMobs [Xikage AKA Ashijin], CrazyAuctions v1.2.12-RELEASE me.badbones69.crazyauctions.Main [BadBones69], EssentialsChat v2.17.2.0 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], TAB v2.6.5 me.neznamy.tab.platforms.bukkit.Main [NEZNAMY], SuperbVote v0.5.4 io.minimum.minecraft.superbvote.SuperbVote [tuxed], PlayerVaults v4.1.6 com.drtshock.playervaults.PlayerVaults [drtshock, kashike, CmdrKittens], GriefPrevention v16.13.0 me.ryanhamshire.GriefPrevention.GriefPrevention [], EssentialsSpawn v2.17.2.0 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], CratesPlus v4.5.3 plus.crates.CratesPlus [Connor Linfoot], ShopGUIPlus v1.28.0 net.brcdev.shopgui.ShopGuiPlugin [brc], Guilds v3.5.4.4 me.glaremasters.guilds.Guilds [Glare], DungeonsXL v0.18-SNAPSHOT-911 de.erethon.dungeonsxl.DungeonsXL [Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel], LeaderHeadsRevamped v4.0.5 tech.panoply.leaderheads.LeaderHeads [Panoply Tech], ShopGUIPlusSilkSpawnersBridge v1.1.1 net.brcdev.shopgui.bridge.silkspawners.ShopGuiBridgeSilkSpawnersPlugin [brc], CitizensCMD v2.4 me.mattstudios.citizenscmd.CitizensCMD [Mateus Moreira],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING WorldEdit Session Manager: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING luckperms-scheduler: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING luckperms-scheduler-worker-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Server-Worker-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], TIMED_WAITING Paper Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:148)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1610), org.bukkit.craftbukkit.v1_15_R1.CraftCrashReport.call(CraftCrashReport.java:33), net.minecraft.server.v1_15_R1.CrashReportSystemDetails.a(SourceFile:79), net.minecraft.server.v1_15_R1.CrashReport.i(CrashReport.java:71), net.minecraft.server.v1_15_R1.CrashReport.<init>(CrashReport.java:35), net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:965), java.lang.Thread.run(Thread.java:748)], RUNNABLE Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1: [java.lang.ClassLoader.defineClass1(Native Method), java.lang.ClassLoader.defineClass(ClassLoader.java:757), java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142), java.net.URLClassLoader.defineClass(URLClassLoader.java:468), java.net.URLClassLoader.access$100(URLClassLoader.java:74), java.net.URLClassLoader$1.run(URLClassLoader.java:369), java.net.URLClassLoader$1.run(URLClassLoader.java:363), java.security.AccessController.doPrivileged(Native Method), java.net.URLClassLoader.findClass(URLClassLoader.java:362), java.lang.ClassLoader.loadClass(ClassLoader.java:419), sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352), java.lang.ClassLoader.loadClass(ClassLoader.java:352), org.apache.logging.log4j.core.async.RingBufferLogEvent.getThrownProxy(RingBufferLogEvent.java:330), org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61), org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38), org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:455), org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232), org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217), org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161), org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:218), org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156), org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129), org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120), org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84), org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448), org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433), org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417), org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79), org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337), org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161), org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45), org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29), com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168), com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING luckperms-scheduler-worker-0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Keep-Alive-SocketCleaner: [java.lang.Object.wait(Native Method), sun.net.www.http.KeepAliveStreamCleaner.run(KeepAliveStreamCleaner.java:101), java.lang.Thread.run(Thread.java:748)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING mysql-cj-abandoned-connection-cleanup: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:80), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Server console handler: [java.io.FileInputStream.read0(Native Method), java.io.FileInputStream.read(FileInputStream.java:207), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), net.minecraft.server.v1_15_R1.DedicatedServer$2.run(DedicatedServer.java:90)], TIMED_WAITING ForkJoinPool-2-worker-25: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], TIMED_WAITING luckperms-scheduler-worker-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], WAITING ForkJoinPool-2-worker-18: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], RUNNABLE Thread-12: [sun.nio.fs.LinuxWatchService.poll(Native Method), sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47), sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314), java.lang.Thread.run(Thread.java:748)], WAITING Paper RegionFile IO Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING mysql-cj-abandoned-connection-cleanup: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:85), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Signal Dispatcher: [], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING Paper Async Task Handler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_15_R1.DedicatedServer$1.run(DedicatedServer.java:72)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)], TIMED_WAITING MVStore background writer nio:/home/minecraft/servers/mine273019/plugins/LuckPerms/luckperms-h2.mv.db: [java.lang.Object.wait(Native Method), org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3116)], WAITING Server-Worker-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165), sun.java2d.Disposer.run(Disposer.java:148), java.lang.Thread.run(Thread.java:748)],}
   
   Force Loaded Chunks: { world: {}, world_nether: {}, world_the_end: {},}
	Player Count: 0 / 50; []
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)

**Comment by Sataniel98** [comment]
Closing this since changes have been made to the world loading / unloading system. If it still occurs with build 951+, please tell me.
