### ISSUE TITLE
Damage Bug

### ISSUE THREAD

**Issue by apc274003** [DRE2N/DungeonsXL#766]
Whenever getting damaged in a dungeon, this error shows up in the console.

https://gyazo.com/1f7286edb3f2c4a2f5f0ed0f9271017a

**Comment by Sataniel98** [comment]
Should be fixed, however I could only reproduce this when players die if death screens are disabled. The stacktrace also clearly involves a player who died ("onDeath"). If you are sure that you also have problems when players are damaged without dying, please create a new issue for this as it is probably not related to the problem when players die.
