### ISSUE TITLE
Group sign bug

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#77]
When i create a group sign when i set the number of group could play, the others signs which is created with this source sign are bugged. If i try to join a group and leave it, my name is still on the sign for exemple.

**Comment by Sataniel98** [comment]
This bug is known but I'm not yet working on it. Try to create one sign per column :)

**Comment by Tiplish** [comment]
I do and it works. I've seen that we could do it like this but i just would like to let you know the issue :)

**Comment by Tiplish** [comment]
Hello Sataniel, i've found another bug about sign.

When you put a group sign on a wall and after, just in the upper side of the first sign, you put a second group sign (linked to the same dungeon), the first sign is erased. 

I know that when you make a group sign which include more than 4-5 players, another sign appear just in the bottom side of the first one . 

So could it be a normal feature? :p

**Comment by Sataniel98** [comment]
Fixed. Or rather, broken feature removed.
