### ISSUE TITLE
Trigger signs not working

### ISSUE THREAD

**Issue by Eutherin** [DRE2N/DungeonsXL#770]
Trigger signs set to redtsone don't trigger when provided with power.

**Description**

When provided power, redstone trigger signs aren't firing. I don't see an error in the console.

**Reproduce**
see pictures.

**Expected behavior**
When block sign is on is provided power it should activate the trigger.

**Screenshots / GIFs / videos**

https://imgur.com/a/pXzd4ce

**Relevant configuration files**

**Comment by Tiplish** [comment]
@Sataniel98 Maybe reliable with #771 . He uses [Trigger] signs too.

**Comment by Sataniel98** [comment]
Can confirm it's the trigger sign (or the t trigger?) that is broken - the redstone trigger worked fine in my tests.

**Comment by Eutherin** [comment]
Did you change how these signs work? Do you want a map pack and a video of it not working? It's still not working as of snapshot 958
Redstone trigger that should be activated:
![image](https://user-images.githubusercontent.com/25861695/81627435-0628fd00-93b3-11ea-8fdc-c2f4046ffba7.png)
![image](https://user-images.githubusercontent.com/25861695/81627531-3cff1300-93b3-11ea-9109-8acb52e3aa74.png)
![image](https://user-images.githubusercontent.com/25861695/81627551-48523e80-93b3-11ea-83a9-53f77c8beaca.png)


Doors that are still closed
![image](https://user-images.githubusercontent.com/25861695/81627465-13de8280-93b3-11ea-86a7-bd1716cc0d0e.png)

Mob signs that do not spawn:
![image](https://user-images.githubusercontent.com/25861695/81627660-864f6280-93b3-11ea-9434-00ba0e5a868d.png)
Signs for those mobs that don't fire when given signal
![image](https://user-images.githubusercontent.com/25861695/81627673-90716100-93b3-11ea-815b-1a4a7e7a53ad.png)

Both of these maps worked on a previous edition.

**Comment by Eutherin** [comment]
The only alternative I see to these signs is to either make a different mob disguised as a button teleported to and locked at a location, which is a bad idea for entity count, given that command blocks don't work very well in dungeons.

**Comment by Eutherin** [comment]
https://www.mediafire.com/file/00s17tyvifs4lod/Minecraft__1.15.2_-_Multiplayer_%25283rd-party%2529_2020-05-11_18-20-43.mp4/file

**Comment by Eutherin** [comment]
I'm not getting any console errors to give more info with.
![image](https://user-images.githubusercontent.com/25861695/81628104-a0d60b80-93b4-11ea-9466-e84d7f6c1a82.png)

**Comment by Sataniel98** [comment]
See #792

**Comment by Eutherin** [comment]
I don't see a discord message to Tiplish, I tried reaching out in discord but I don't think you saw it.

**Comment by Eutherin** [comment]
I'm still having the problem on build#962

**Comment by Sataniel98** [comment]
Apparently the fix didn't work. I don't know what's wrong ATM

**Comment by Sataniel98** [comment]
Correction: It worked fine in my own tests. Will publish a new build soon.
