### ISSUE TITLE
Trigger M SkeletalKnight

### ISSUE THREAD

**Issue by nicolasecm** [DRE2N/DungeonsXL#773]
Hello, I am trying to use the Mob death trigger with the MithycsMobs plugin, but it doesn't work for me on a bukkit server of version 1.13.2, I don't know if it is doing it wrong, could you give me an example of how to use it please .

**Comment by Sataniel98** [comment]
If you're on 1.13.2, you can use the latest stable Beta version: https://www.spigotmc.org/resources/dungeonsxl.9488/download?version=265570

I'm currently rewriting parts of the whole sign system and things might not work 100%.

**Comment by nicolasecm** [comment]
Yes, that version worked correctly for me, thank you :D, very good project

**Comment by Sataniel98** [comment]
The mob death trigger works fine for me with the latest build. I used the default SkeletalKnight to test it.
