### ISSUE TITLE
Null (Doesn't Even Start)

### ISSUE THREAD

**Issue by JTGgamer** [DRE2N/DungeonsXL#784]
When I try to run the plugin it doesn't work (it is disabled). I don't know why and have tried reinstalling and enabling it with plugman but nothing works. I am on the latest dev version
(0.18 | #958 | SNAPSHOT) and on 1.14.4 paper spigot.

Reproduce: All I did was install it.
Expected Behaviour: Plugin loads and works.

Error:
https://pastebin.com/qrU6tAdA

**Comment by Sataniel98** [comment]
Please post the startup error.

**Comment by JTGgamer** [comment]
is this it?

https://pastebin.com/qrU6tAdA

**Comment by JTGgamer** [comment]
Updated to the latest version and this just happened

**Comment by JTGgamer** [comment]
Not sure if this is a separate issue or the same one.
Got this randomly, I don't really know what happened 
https://pastebin.com/rbPXUmTa
Go this when trying to test a dungeon
https://pastebin.com/GZGGPx6P
