### ISSUE TITLE
PlayerInteractEvent NPE

### ISSUE THREAD

**Issue by HauserGrim** [DRE2N/DungeonsXL#789]
DungeonsXL v0.18-SNAPSHOT-962
Paper 1.15.2 b264
I was not able to reproduce the error, but it seems to occur when some blocks are destroyed.
DXL configs are default. There are no dungeons, the plugin is installed, but not used.
https://pastebin.com/vprxPj2L

**Comment by Sataniel98** [comment]
Thanks, fixed.
