### ISSUE TITLE
Subtitles aren't working at all

### ISSUE THREAD

**Issue by OmarZiadeh** [DRE2N/DungeonsXL#790]
Using title signs, subtitles do not work period (using message IDs and using them as numerals).

**Reproduce**

1. edit a dungeon or create a dungeon
2. modify config to add messages, we'll use 0: "test" for now
3. Place a title sign with [Title], 0, 0, D 5
4. This can be replaced with any trigger
5. test the dungeon after saving config and reloading/restarting server
6. Notice that there is no subtitle

You expect for any subtitle to happen, "test" in this case, yet nothing appears on the screen, yet the normal title does.

**Comment by Sataniel98** [comment]
Turns out the documentation was wrong. Title sign syntax is

[Title]

titleId,subtitleId

_empty_

_trigger_
