### ISSUE TITLE
[Bug] Redstone sign isn't triggered when they are close to a block powered

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#792]
**Description**

Hi, 
I'm using redstone trigger to open some doors. 
But in the build 962, the redstone have to feed the sign. I can't just put my sign on a block which is powered by redstone (like in build 819). It's has broke some of my dungeon and it's more hard to hide redstone system. 

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [BLOCK] sign, [Block]/1//R sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger block sign with a lever on a block close or by a redstone signal directly on the sign

**Comment by Sataniel98** [comment]
Fixed, see the Discord message I sent you.
