### ISSUE TITLE
[Bug] Trigger sign can't be put and break and put again 

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#793]
**Description**

Hi,
When i try to change a trigger, for example the number 2, if i break it and try to put it again, the plugin throw me an ingame error that i've wrong syntax on my sign.

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [Trigger] sign, [Trigger]/1//R sign
3. Break the sign
4. Place again [Trigger] sign, [Trigger]/1//R sign
5. See the error message

**Expected behavior**

Place the sign everytime i need when i've previously break the sign

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Does this happen with other IDs that are not 1 too?

**Comment by Tiplish** [comment]
Any ID :s

**Comment by Sataniel98** [comment]
Works fine for me, other than for number 1. IDs seem to erroneously start at 2 but the replacing works.
