### ISSUE TITLE
Map bug after restart

### ISSUE THREAD

**Issue by icyvector** [DRE2N/DungeonsXL#795]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
After a server restart, trying to edit a map brings me to an old version of the map. After a while and a few reloads, it will finally load the right map

**Reproduce**
1. Restart server
2. /dxl edit [map]
3. Old version spawns
(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/pig/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the pig spawn sign)

**Expected behavior**
Loading saved map versions

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Thank you for the report, I'm sorry for the late reply. I can't reproduce this. It might be caused by bugs / confusion with the delays after a map is saved. This has since May been improved quite a bit and will continue to be improved. If it still occurs with recent builds, please make a new issue.
