### ISSUE TITLE
papi group_members bug

### ISSUE THREAD

**Issue by keyute** [DRE2N/DungeonsXL#796]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
using %dxl_group_members% would return a list of names joined with a comma, and the last player's name cut off.  
(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

**Reproduce**
1. have 1 or more players in your group
2. use %dxl_group_members%
(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/pig/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the pig spawn sign)

**Expected behavior**
lets say mary and bobby is in the group, i expect
mary,bobby instead of mary,bobb
(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Fixed.
