### ISSUE TITLE
Players cannot rotate item frames

### ISSUE THREAD

**Issue by AevumDecessus** [DRE2N/DungeonsXL#798]
**Description**
With interactionProtectedEntities set to an empty array, and damageProtectedEntities set to a null array, or an array with just ARMOR_STAND in them, players still cannot rotate item frames placed in a dungeon

**Version**
* dungeonsxl-dist-0.18-SNAPSHOT-962.jar
* Spigot 1.15.2

**Reproduce**
1. Create a new dungeon with /dxl create alpha
2. Place [ready] sign and an item frame with an item in it
3. dxl save, then edit plugins/DunegonsXL/maps/alpha/config.yml to clear out interactionProtectedEntities and damageProtectedEntities

**Expected behavior**
Players will be able to right click and rotate the item frame to change the output of an attached redstone comparator 

**Relevant configuration files**
```gameMode: SURVIVAL
groupSize:
  minimum: 1
  maximum: 1
interactionProtectedEntities:
damageProtectedEntities:
title:
  title: "&4Escape the Castle"
  subtitle: "&6By Aevum & Luthien"
rain: false
thunder: false
time: 6000
```
ALSO fails
```gameMode: SURVIVAL
groupSize:
  minimum: 1
  maximum: 1
interactionProtectedEntities:
- ARMOR_STAND
damageProtectedEntities:
- ARMOR STAND
title:
  title: "&4Escape the Castle"
  subtitle: "&6By Aevum & Luthien"
rain: false
thunder: false
time: 6000
```

**Comment by Sataniel98** [comment]
I will review this. It is intended that if blocks are protected, several block-like entities are by default protected, too.

**Comment by UltramarEdoras** [comment]
I think this bug persists and it's not only related with item frames. Trying to enable the possibility to interact with armor stands the same happened to me. It will be nice if you could fix it in order to add adventure maps which use this feature.

Here is my config.yml:

```
--- 
breakBlocks: true
breakPlacedBlocks: true
damageProtectedEntities: []
interactionProtectedEntities: []
placeBlocks: true
```

I hope it gets fixed soon. Thanks for your work, @Sataniel98

**Comment by Sataniel98** [comment]
I'll work on it as soon as I have time. It might take a few weeks though since I'm taking an internship atm.
