### ISSUE TITLE
Dungeon kann nicht abgeschlossen werden wenn Spieler afk geht

### ISSUE THREAD

**Issue by Sn0wStorm** [DRE2N/DungeonsXL#80]
Wenn eine Gruppe einen Dungeon spielt und einer afk geht dann bleibt er im Dungeon wie zu erwarten. Nur drückt der afk Spieler ja nicht auf das Ende Schild.

Wenn alle anderen schon auf Ende gedrückt haben kann man den afk Spieler zwar kicken oder "/sudo Spieler dxl leave" machen, aber trotzdem beendet sich das Dungeon nicht. Das liegt glaube ich daran, dass sich das Ende Schild nur updated wenn ein Spieler es anklickt, der das Dungeon noch nicht beendet hat.

Kurz: Afk Spieler autokick? Wenn Spieler leaved wenn alle anderen schon Ende gedrückt haben beendet sich das Dungeon nicht

**Comment by Sataniel98** [comment]
Das zu verbessern wäre wichtig.

**Comment by Sataniel98** [comment]
Ich finde es ausreichend oder sogar besser, wenn der Captain der Party mit /dxl group kick den jeweiligen Spieler manuell rauswerfen kann. Zu Fixen ist aber, dass nicht getestet wird, ob die verbleibenden Spieler fertig sind.

**Comment by Sataniel98** [comment]
Das solte funktionieren.
a50b0e279cd1768ed9bfd3a412cb4577dd9ef058
