### ISSUE TITLE
bungee support?

### ISSUE THREAD

**Issue by lostINParadies** [DRE2N/DungeonsXL#800]
Hey, Ist dein Plugin Bungeecord kompatibel? Wir arbeiten an einem story server mit cloudnet. Würde gerne dein Plugin für die dungeons missionen benutzen.

würde das funktionieren?

**Comment by Sataniel98** [comment]
Es gibt keinen Bungee-Support. Viel dürfte der aber nicht tun müssen. Nur Rewards & Requirements und von einem Server aus direkt in einen Dungeon auf dem anderen zu kommen ist schwierig.

**Comment by lostINParadies** [comment]
Hab mich noch nicht ganz auseinandergesetz mit dem Plugin. Muss ein Startbefehl ausgeführt werden, um das dungeon zu starten?

**Comment by lostINParadies** [comment]
Geht mir nur darum, dass kein weiterer Spieler wärend ein Spieler das dungeon spielt, rein kommt. und so auf einen neuen Server gehen muss

**Comment by Sataniel98** [comment]
Das Starten funktioniert mit einem Schild und Portal. Grundsätzlich können Spieler nicht in laufende Dungeons, in denen schon andere Spieler spielen.
