### ISSUE TITLE
Portals Don't Teleport on Entry

### ISSUE THREAD

**Issue by Yippu** [DRE2N/DungeonsXL#802]
**Description**

When entering a portal created using "/dxl portal", the portal does not immediately teleport the user to the dungeon. Rather, the user has to step into the portal then move outside the portal, or to either side inside the portal frame to activate the teleportation.

**Reproduce**

1) Create dungeon or use existing dungeon
2) Right click a global Group sign to join a group
3) Walk into the dungeon portal (created using "/dxl portal")
4) Now you will notice there is no teleportation, even from standing still after a period of time

**Expected behavior**

Upon walking into the portal, it should instantly teleport the user into the dungeon lobby.

**Screenshots / GIFs / videos**

https://youtu.be/htcztHtG0IQ

**Relevant configuration files**

n/a

**Comment by Sataniel98** [comment]
I don't think I can do much about this. I want to do as few lookups for portals as possible as they need to be made on move events, so they are only checked when the player's block location is changed and there's always a chance that the event isn't fired.
