### ISSUE TITLE
MMOCore Integration

### ISSUE THREAD

**Issue by qckcat** [DRE2N/DungeonsXL#804]
**Please describe the use case or the problem your request is related to.**

It seems like there is a stalemate between both you guys and MMOCore when it comes to adding integration due to you both offering API support. I spoke with the MMOCore developers/community manager and they have offered to give you the plugin for free to add integration with yours..

![image](https://user-images.githubusercontent.com/3664124/82055373-014f9c00-9686-11ea-8398-26bb1449703f.png)

I have also considered building my own bridge but it doesn't seem like it's entirely possible using their API and I am still in contact with the developers about this.

**Comment by Sataniel98** [comment]
I'm sure their plugin and API do their purpose well, but I won't add support for it.

1. Linking GPL and proprietary software is legally questionable. Linking DungeonsXL's Lesser GPL _API module_ and proprietary software is fine, though, so a separate bridge plugin or an implementation in MMOCore does not have this issue.
2. They're selling their plugin for 17.90 EUR per copy while DXL is free. It's only fair that they do the work that could be realized in both plugins.
3. Implementing DXL's group adapter API is child's play. I've done that for Parties and will gladly do it for other plugins as long as they're free and open source, so there's an example to base it on. Even though I haven't fully tested everything of this new API yet in regards to if the behavior it assumes is desired is actually desired, the implementation should be doable as it is.
