### ISSUE TITLE
How to create floors

### ISSUE THREAD

**Issue by Amph1dian** [DRE2N/DungeonsXL#806]
**The feature you'd like to know more about**

How to create floors

**Link to the wiki article (in case it exists)**

https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration
BUT THIS DOSINT TELL ME ANYTHING
**What did you already try?**

idk what to try no clear way to do it
and your mob areana link dosint work plus pvp areana and more

**Comment by Sataniel98** [comment]
Just create a map with /dxl create. That can be used as a floor in a dungeon script without any further setup.

The mob arena etc. links are just examples I intend to add. They don't explain anything in addition to the rest of the wiki, they just visualize it better.
