### ISSUE TITLE
/dxl test Funktioniert nicht, oder unerwartet

### ISSUE THREAD

**Issue by Sn0wStorm** [DRE2N/DungeonsXL#81]
Wenn man wie früher /dxl test name macht kommt nur die Hilfe Meldung.  
/dxl play name funktioniert wie erwartet.

Aus dem code kann ich entnehmen dass man schon mit einer Gruppe in einer Lobby sein muss? Warum ist der test Befehl dann so anders als der play Befehl?

Wurde immer genutzt als schnelle Möglichkeit Änderungen im Dungeon zu testen, ohne Belohnungen etc.
Es wäre sonst auch ne gute Idee so etwas einzubauen, dass man aus der Editworld heraus sofort einen test starten könnte, also dass sich einfach alle Schilder sofort verwandeln etc.

**Comment by Sataniel98** [comment]
Das liegt daran, dass ich Befehle hinzugefügt habe, um Dungeons ohne Portal (in Gruppen) zu spielen. Damit war der Befehl /dxl test praktisch überflüssig. Der neue Befehl löst in der Lobby, in die man unter anderem durch /dxl play kommt, sozusagen ein Ready-Schild aus und startet ein Game mit dem GameType TEST.
