### ISSUE TITLE
Mobs Disappearing

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#810]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

When playing Dungeons if you die there is a possible chance that when you respawn, all mobs in the dungeon have vanished and can't be seen.

**Reproduce**

1. Join a Dungeon
2. Make sure the Dungeon has multiple lives set in the config
3. Die and you will have a chance that when you respawn that all dungeon mobs cannot be seen anymore, but they can still attack you.

**Expected behavior**

Mobs shouldn't disappear and just remain visible.

**Screenshots / GIFs / videos**

It's hard to screenshot invisible things.

**Relevant configuration files**

N/A. Not related to config.

**Comment by Sataniel98** [comment]
Possible duplicate of #448.

If not, if you use MythicMobs, make sure despawn is set to false.

**Comment by RocketManKian** [comment]
Are there any plans to fix this rather than turning on immediate respawn?

**Comment by RocketManKian** [comment]
Update - Just tested this with that gamerule enabled. Mobs still vanish after death

**Comment by Sataniel98** [comment]
Does this happen in Minecraft 1.15.2?

**Comment by RocketManKian** [comment]
Hi there I just re-installed the plugin and it seems the issue isn't occuring anymore. Although now the Title signs aren't working for some reason...

**Comment by RocketManKian** [comment]
This problem still persists. It happens after dying, the game rule change didn't work. It's a 50/50 chance for it to happen. You can't see the mobs, but they can hurt you and still make noises.

**Comment by Sataniel98** [comment]
Could you please confirm that it happens with Spigot 1.15.2 without client mods?

**Comment by RocketManKian** [comment]
Yes sure. What would you like a picture of?

**Comment by RocketManKian** [comment]
To prove it

**Comment by Sataniel98** [comment]
I'll believe you without it, just want to make sure it still happens in 1.15.2 and with a Vanilla client

**Comment by RocketManKian** [comment]
Hi there! I tested twice on vanilla 1.15.2 (no optifine) and then with optifine and it seems like that is the issue. Do you know if this is on Optifines end or do you need to enable compatibility with it? Thanks for the quick reply!
