### ISSUE TITLE
Dungeons Signs

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#812]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

When updating to the latest version of Dungeons XL my [Title] and [End] sign no longer work and in game appear as "##Error## Please contact an Admin!"

**Reproduce**

(List steps to reproduce, e.g.:
1. Update to the latest version of Dungeons XL
2. The [Title] and [End] signs don't work when updating to the latest version, I believe as they were placed in a previous version. I have also tried replacing the sign, but it still doesn't work.

**Expected behavior**

The Title and End sign to work correctly.

**Screenshots / GIFs / videos**

![2020-06-10_15 34 34](https://user-images.githubusercontent.com/47107486/84281071-09d5ae00-ab30-11ea-8e1f-38a2b628c254.png)
![2020-06-10_15 35 05](https://user-images.githubusercontent.com/47107486/84281077-0c380800-ab30-11ea-84aa-78144f9cb0ff.png)

**Relevant configuration files**

N/A

**Comment by Sataniel98** [comment]
Title signs don't allow for direct text input anymore. You have to write the text in the messages game rule in the config and put their numeric ID on the sign as explained in the wiki. How do the end signs not work?

**Comment by RocketManKian** [comment]
Hi there! Just wanted to let you know. End sign now works, I believe it wasn't working initially. One question please. I now have 2 messages on my Title sign. Is it possible to have the title display on 2 lines in game if you know what I mean? Since right now both messages display on one line and don't fit on screen

**Comment by Sataniel98** [comment]
The Minecraft client doesn't allow for line breaks in titles so there's nothing we can do.
