### ISSUE TITLE
End Sign

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#814]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Hi there! When completing a dungeon and clicking the [End] sign at the end, the following message appears in chat "You successfully finished the dungeon" although it doesn't teleport the player, the only way to then leave the dungeon is '/dxl leave'. It seems like this only happens for default players since as an OP it works fine for me.

**Reproduce**

(List steps to reproduce, e.g.:
1. Create dungeon
2. Place [End] sign
3. Play through dungeon
4. Click the end sign
5. Then you are stuck in the dungeon and the end sign won't teleport you out

**Expected behavior**

When clicking the End sign it should teleport you out

**Screenshots / GIFs / videos**

![2020-06-12_21 54 49](https://user-images.githubusercontent.com/47107486/84545696-95e60200-acf7-11ea-82b7-fac9f82989c2.png)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents so that others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Have the other players in the group not finished the game?

**Comment by RocketManKian** [comment]
It was a one man group, we tested both in a group and solo. When we played in a group, I could click the end sign fine but then he couldn't. In a solo game he couldn't click the end sign either. In my solo game I could.

**Comment by Sataniel98** [comment]
Is there an error in the console?

**Comment by RocketManKian** [comment]
Hi there, there is no issues in console. This is now happening to me, and I am an op. When I initially start the dungeon though I get this in console "Server thread/WARN Failed to check session lock for world located at ./DXL_Game_4, aborting. Stop the server and delete the session.lock in this world to prevent further issues."

**Comment by Sataniel98** [comment]
Could reproduce this for MFDs

**Comment by quentinlegot** [comment]
Hello, I have the same problem, but my end sign is different:

![image](https://user-images.githubusercontent.com/26069031/85005202-c0e9af00-b158-11ea-8325-c252a84418be.png)
It marked M 8 in game not M 0, just somes pixels not appear ^^


When i finish the game, I have the success message but somes of chunk I on despawn, I fall in the void to infinity, and I not teleported.

That display this error every tick until I log out:

![image](https://user-images.githubusercontent.com/26069031/85005104-a44d7700-b158-11ea-90af-8a9fdb528f60.png)

**Comment by RocketManKian** [comment]
Sataniel98 just wanted to let you know that I believe the thing that is causing the End Sign issue is when you rename a dungeon. My dungeon name was initially 'D1' then I renamed it to 'Forsaken Temple' with a space in it and then the bug came back. So I think it's something to do with spaces in names?
