### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#818]
**The feature you'd like to know more about**

Mob Spawning

**Question**

Hi there! Was just wondering if there's an option to disable mobs spawning with armor and enchanted weapons? Or is that just reliant on minecraft it self? Thanks!

**Comment by Sataniel98** [comment]
This happens randomly but a custom mob of the type should not have any.

**Comment by RocketManKian** [comment]
Thanks! How would I add a custom mob of the type?

**Comment by Sataniel98** [comment]
You can add it in IXL or use the internal legacy mob script system.
