### ISSUE TITLE
Restore Health and food before start a dungeon

### ISSUE THREAD

**Issue by quentinlegot** [DRE2N/DungeonsXL#824]
**Please describe the use case or the problem your request is related to.**

If players haven't his entire life when enter the dungeon, he can begin with a disadvantage

**Describe the solution you'd like**

set Health and food level to the player max 

**Describe alternatives you've considered**

currently command sign with a distance trigger can help solving the problem

**Comment by Sataniel98** [comment]
Players are already healed and fed automatically if keepInventoryOnEnter is false, but it doesn't make sense to me to do that if they keep their own inventory, stats and so on. As you already mentioned, there's a solution that works fine for keepInventoryOnEnter: true.
