### ISSUE TITLE
[Bug] Dungeons in the End dimension get corrupted

### ISSUE THREAD

**Issue by arnhav** [DRE2N/DungeonsXL#828]
**Description**

In build 0.18-771 we had a dungeon that was in the End dimension. Since updating to any version beyond 771 this dungeon will load up as a corrupted overworld.

**Reproduce**

1. Create a dungeon in the End dimension in build 771 or below
2. Load said dungeon in build 771+

**Expected behavior**

The dungeon should load up in the end dimension with the build still being present.

**Screenshots / GIFs / videos**

https://imgur.com/a/RXA3uKq

**Extra Info**

This warning did pop up when loading the world for the first time after updating. It should be noted that the DXLData.data file was removed prior to updating the plugin (during downtime between server restarts)

https://hastebin.com/cabizatolo.md

**Comment by arnhav** [comment]
After browsing through the issues I believe issue #805 is similar to this

**Comment by arnhav** [comment]
Any update on this?

**Comment by Sataniel98** [comment]
Can't work on it before October.

**Comment by arnhav** [comment]
Ah ok, no worries then
