### ISSUE TITLE
Players Cannot Access Certain Dungeons

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#829]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

In my server I have a total of 4 dungeons: Tutorial, Dungeon1, Dungeon2 and Dungeon3. Players can access Tutorial and Dungeon 1, but when clicking the group join sign for Dungeon 2 and 3 when they go into the portal it won't teleport them - for some strange reason. This problem however does not occur for myself as I am op, but it seems like it doesn't work for unopped players. In the Dungeon 2 and 3 sign there also seems to be a regular bug where you can spam click the sign and then it spams the chat saying you joined the group, then the leave sign doesn't make you leave the group either.

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a few dungeons
2. Create a Group join sign for the dungeons
3. De-op yourself and some of the dungeons won't pull you into the world
4. (Rare bug) you to be stuck in a group and have the opportunity to join multiple groups without leaving.

**Expected behavior**

The portal and sign to work proactively together and then pull the player into the dungeon. Group signs to stop you from joining multiple groups before leaving one.

**Screenshots / GIFs / videos**

![2020-06-20_19 50 02](https://user-images.githubusercontent.com/47107486/85212801-54380580-b34e-11ea-8658-762d9b784c7e.png)

**Relevant configuration files**

N/A

**Comment by Sataniel98** [comment]
Why did you close this?

**Comment by RocketManKian** [comment]
I realise this was due to me not realising that something changed with the "mustFinishOne" variable in config.yml and it was causing issues as it was set to 'mustFinishAll' so I changed it to 'one' and it fixed.
