### ISSUE TITLE
"Chest Has Already Been Opened" Bug

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#835]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

When completing dungeons there is a 50/50 chance for the reward chest at the end to work and not display the following message "Chest has already been opened", if this message pops up players will not receive the loot gained within the chest when ending the dungeon.

**Reproduce**

(List steps to reproduce, e.g.:
1. Play Dungeons
2. Open Reward Chest within the dungeon
3. It should pop up with the following message "Chest Has Already Been Opened"
4. When ending dungeon you don't receive rewards

**Expected behavior**

When clicking the Reward Chest within a dungeon it to successfully work and grant the player items when ending the dungeon.

**Screenshots / GIFs / videos**

![V5hg8kc](https://user-images.githubusercontent.com/47107486/85903610-9eadfc00-b7fe-11ea-869c-929f3dc76959.png)

**Relevant configuration files**

N/A

**Comment by Sataniel98** [comment]
Can't reproduce this. If a chest has already been opened, it can't be opened anymore. If it hasn't been opened, I can open it without issues. Note that only the players in the group of the player who opened it get rewards from the chest.
