### ISSUE TITLE
Dungeon signs not creating

### ISSUE THREAD

**Issue by Verious1030** [DRE2N/DungeonsXL#836]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)
When I place a sign and follow what I found on the wiki, the signs don't successfully create. I would test the dungeon but it says I don't have a start sign when I do. 
**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/pig/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the pig spawn sign)

**Expected behavior**
I wanted the signs to work and start the game, but alas, it does not. It just places a normal sign. 
(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)
https://pastebin.com/pYQprjCg
**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Plugins isn't enabled for whatever reason, so it won't work.
