### ISSUE TITLE
Support essentials.keep.inventory

### ISSUE THREAD

**Issue by Bricec6** [DRE2N/DungeonsXL#837]
**Describe the solution you'd like**

Hello, is it possible to add support to essentials keep.inventory? If I give my player a general permission to keep.inventory, when he goes into the dungeon he will still lose his stuff.

I would like to give permission to keep.inventory also according to the dungeon world for example:
/lp user <player> permission set essentials.keep.inventory world=dungeon

so he can keep his stuff, but the other players who don't have permission lose their stuff.

**Comment by Sataniel98** [comment]
No, just use the DXL game rule.

**Comment by Bricec6** [comment]
The DXL rule makes sure you either lose your stuff or you don't, and doesn't manage a permission system, if not make one... 
dungeonxl.lostinventory.bypass , so you don't lose your stuff, if I enable keepInventoryOnDeath: false

it allows us to have a large choice, I would like some players to lose their inventory, others not, before solving the bug: https://github.com/DRE2N/DungeonsXL/issues/838

**Comment by Sataniel98** [comment]
Decided against this because I don't see this being used by many people.
