### ISSUE TITLE
Weitere Funktionen

### ISSUE THREAD

**Issue by Sn0wStorm** [DRE2N/DungeonsXL#84]
Ich hab ein paar Funktionen in branches eingebaut. Zu finden hier https://github.com/Sn0wStorm/DungeonsXL/branches

MaxDungeons fügt eine Config option hinzu um die Anzahl gleichzeitig laufernder Dungeons zu begrenzen, damit der Server nicht out of memory läuft.

Teleport Sign ist ein Schild zum Teleportieren. 1. Zeile [teleport]
Dann wird man beim Auslösen des Schildes zu diesem hin teleportiert. Am einfachsten in Verbindung mit einem Interact Sign, dass dan das Teleport sign auslöst.
Alternativ kann man in eine Zeile die Koordinaten (mit , getrennt) und / oder eine Zeile mit Himmelsrichtung angeben. Ist Release-fertig

MultiServer sind die normalen Belohnungskisten auskommentiert und werden mit XServer an einen im Moment statisch festgelegten Server geschickt auf dem das DungeonReward läuft. Das gibt dann das Belohnungskisten Menü aus oder im Falle von Tutorial ersetzt das Inventar mit dem Dungeon Inventar.
Bräuchte noch übersetzung, config optionen und noch einiges mehr.

Die Branches basieren auf dem Master. Soll ich einen Pull request erstellen und wenn ja in welchen branch?

**Comment by Sataniel98** [comment]
Danke erstmal dafür, es hört sich wirklich gut an :) Für den PR wäre mir der 0.12-Branch am liebsten. Für MultiServer würde ich lieber bei einem eigenen bleiben, solange es noch nicht ganz fertig ist.
