### ISSUE TITLE
Plugin Completely Unusable

### ISSUE THREAD

**Issue by cat-boop** [DRE2N/DungeonsXL#843]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
Attempting to ./dxl edit <dungeon name> results in following error:
![image](https://user-images.githubusercontent.com/45737435/86199616-6a448380-bb0f-11ea-850a-91611ddaf6f3.png)

Dungeon portals are also completely unusable.

Cannot access the dungeon I have created in any way. Definitely not a problem of having too many worlds loaded; I only have 3 worlds on my server at the moment. Been using the plugin for quite a while with little to no problem. All of a sudden today it stopped working as intended. I updated the plugin and the same issue occured.

**Reproduce**
1. Create dungeon.
2. Setup basic dungeon.
3. Save/leave dungeon.
4. Attempt to return to edit mode via /dxl edit 
5. :/
**Expected behavior**
Should move me right into edit mode just like every time in the past 3 weeks that I've been using the plugin.

**Screenshots / GIFs / videos**
![image](https://user-images.githubusercontent.com/45737435/86199690-9c55e580-bb0f-11ea-9af1-fdc66f894498.png)

**Comment by Sataniel98** [comment]
I'll need information about your setup and stacktraces if there are any.
