### ISSUE TITLE
Missing world uuid message spam in config and crash

### ISSUE THREAD

**Issue by Neocky** [DRE2N/DungeonsXL#846]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

When i join a dungeon and leave it, my console gets spammed every 5 minutes with a error that a world uuid isn't found. 
When i enter it again, a new uuid is added and now twice the amount of errors are put into the console.
It gets so bad that eventually the server crashes.

It could be a not compatible plugin, but i tested some and did not yet find any. The Dungeons works but then the missing world uuid message appears.

I would appreciate you help!

**Reproduce**
1. Start Server
2. Get into a Dungeon
3. Leave Dungeon
4. After max. 5 mins the errors start to come

**Expected behavior**

(A clear and concise description of what you expected to happen, e.g.:
Not get spammed about missing world uuids, and don't crash.

**Relevant configuration files**
I didn't change anything in the configs.
Dungeon is working and i can enter and exit the edit mode.

```

```

**Comment by Sataniel98** [comment]
No idea about this. Does it occur with every world?

**Comment by Neocky** [comment]
Yeah it does. 
I just created a new testworld with the /dxl create command then saved it then left and the errors still came. With a new world uuid but...yeah.

**Comment by Neocky** [comment]
Hey, 
so I tested every Plugin with it and it is a issue with the Plugin: Custom Items.
I contacted the author about it and he said that he will find a fix for it. 
Thank you for your time!
