### ISSUE TITLE
Spigot bug report about teleporting NPE

### ISSUE THREAD

**Issue by TTNO1** [DRE2N/DungeonsXL#847]
Hello, I know this is unrelated to the plugin but I saw your spigot bug report about NPE when teleporting a player and I am having the exact same problem. I saw a comment that says you fixed the problem, do you mind explaining how you fixed it?

Bug report: https://hub.spigotmc.org/jira/browse/SPIGOT-5631

**Comment by Sataniel98** [comment]
I've kept a reference to a World object even when the World was unloaded. What you can do is to either keep a reference to the world's UID or name instead, wrap it in a WeakReference or to listen to WorldUnloadEvent and set the reference to null.
