### ISSUE TITLE
Public Chat

### ISSUE THREAD

**Issue by Exvinem** [DRE2N/DungeonsXL#848]
I have a question.....
How can i connect all the chat in the server?
i mean, i want those who is inside the dungeon can chat to the public too so they dont need to do /dxl chat... is there anything i can do?

**Comment by Sataniel98** [comment]
DungeonsXL doesn't do anything about the chat unless you use /dxl chat.

**Comment by Exvinem** [comment]
but when the players is inside the dungeon, they cant see the chat from global
is there any way?

**Comment by Sataniel98** [comment]
Players in dungeons can read the normal Vanilla public chat.

**Comment by Exvinem** [comment]
umm... i have another questionnnn....
I cannot open the link that direct us to the gametype list....
is there any other link i can access??
I hope you can share it to me hehe...
thank youuu

**Comment by Exvinem** [comment]
and one more thing, can I put 2 different groups in the same world?

**Comment by Exvinem** [comment]
after i put 2 different groups, i want them to pvp with each group... is it possible?

**Comment by Sataniel98** [comment]
1. Game types have been removed.
2. Just use a game sign and a second group sign.
3. You can enable PVP in the game rules.
