### ISSUE TITLE
/dxl join returns nothing

### ISSUE THREAD

**Issue by jmcn99** [DRE2N/DungeonsXL#851]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

When /dxl join {dungeons} is called it returns nothing, the command is working as when you do /dxl join without the dungeon name it returns the error message that you need a dungeon name. Doesn't matter if the dungeon name exists or not it still returns nothing

**Reproduce**

(List steps to reproduce, e.g.:
Use /dxl join with a dungeon name

**Expected behavior**

Open the GUI

```

```

**Comment by Sataniel98** [comment]
Could you please show me the announcer script you're using?

**Comment by jmcn99** [comment]
description:
  - "test"

identifier: Hades

multiFloor: false

minGroupsPerGame: 2
minPlayersPerGroup: 1
maxGroupsPerGame: 4
maxPlayersPerGroup: 4

**Comment by OMR2K** [comment]
Try using /dxl play (name)

**Comment by Sataniel98** [comment]
That's not what this is about.

**Comment by OMR2K** [comment]
I have the same issue as well, it returns nothing
