### ISSUE TITLE
Reward inventory making it possible to remove all internal elements

### ISSUE THREAD

**Issue by scorninpc** [DRE2N/DungeonsXL#853]
Player can remove glasses and papers from reward inventory

**Description**
When i'm back to normal world, the inv reward open. I can get all elements inside, like the glasses and paper NEXT/PREV PAGE

**Reproduce**

1. Create a dungeon
2. Do a simple dungeon
3. Leave edit mod
4. Test with /dxl play
5. Complete de dungeon

**Expected behavior**

I supose i cannot remove glass and paper from inv rewards

**Screenshots / GIFs / videos**

https://youtu.be/iQwYOen7b_8

**Relevant infos**

None changed, my test server has essentials and dungeonsXL only
No plugin config changed
PaperMC 1.16.1 -> 80
No console error, no trace, nothing wrong on console

**Comment by DarkSumrak** [comment]
yes
https://radikal.ru/video/4rJO0a9bAlD

**Comment by Sataniel98** [comment]
Should be fixed.
