### ISSUE TITLE
An Internal Error has Occurred

### ISSUE THREAD

**Issue by NathanMCherry** [DRE2N/DungeonsXL#857]
**Description**
While trying to set up our first dungeon upon creating the dungeon we receive an internal error. After checking the list of dungeons using /dxl list, it was there but we received another internal error when we attempt to edit it.  It previously worked until we updated to 1.16.1. 

**Reproduce**
1. Create a new dungeon with /dxl create [name]
2. Internal error

**Expected behavior**
Upon creating a dungeon we expected it to teleport us to the dungeon to begin designing it not receive an internal error.

**Screenshots**
![2020-07-12_14 25 31](https://user-images.githubusercontent.com/51176000/87253922-ef536500-c44c-11ea-9a2c-b0edafc8500d.png)
[message.txt](https://github.com/DRE2N/DungeonsXL/files/4909176/message.txt)

**Comment by Sataniel98** [comment]
Do you have any plugins modifying a player's maximum health?
