### ISSUE TITLE
ItemsXL Serialize for Dungeon Requirements

### ISSUE THREAD

**Issue by eliyash31** [DRE2N/DungeonsXL#860]
Hello I've been struggling with the plugin ItemsXL it keeps disabling and I don't know how to make it work and no one is replying the issue I created there so I might as well suggest or question it here.

I want to make a custom item to be a requirement or a dungeon key for example to be a requirement for the players to enter the dungeon. The problem is IXL plugin keeps on making errors so how about using the IXL Serialize to make the custom item readable for the requirement just like loottables? that would be easy and we can use any custom item plugin that we want because of IXL Serialize command.

**Comment by Sataniel98** [comment]
That won't be necessary with the changes that have already been made to IXL in the 1.0 update.

**Comment by eliyash31** [comment]
what do you mean it won't fix? did you mean that this plugin will never work?

**Comment by Sataniel98** [comment]
That means the issue doesn't need to be fixed because the system you're referring to has already been changed from the ground up in the IXL commits since the latest release on SpigotMC.

**Comment by eliyash31** [comment]
Okay so would you mind telling us how we could use the plugin using the right format for custom item script? because the one that is on the wiki doesn't work it makes the plugin disabled I don't know what that happens, but when I use it in the DungeonsXL Loottables script it works very fine. Yet using the Custom Items Script disables the IXL plugin, why is that so when we are using the premade ixl script for the custom item.yml file

**Comment by Sataniel98** [comment]
The wiki script is not a drag and drop example, but the Beta is definitely functional even if error handling isn't good. It's been a while so I don't know what exactly has to be changed but at least the categories are examples that are not normally registered.
