### ISSUE TITLE
Error on spawning EliteMobs custom boss

### ISSUE THREAD

**Issue by OMR2K** [DRE2N/DungeonsXL#861]
I setup the sign '[Mob] owboss 1,1,EM D 10' and when I get close to that sign I get this error.

`15.07 13:10:18 [Server] WARN [DungeonsXL] Task #59963 for DungeonsXL v0.18-SNAPSHOT-1003 generated an exception
15.07 13:10:18 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'elitemobs' in plugin EliteMobs v7.1.33
15.07 13:10:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at de.erethon.dungeonsxl.api.mob.ExternalMobProvider.summon(ExternalMobProvider.java:74) ~[?:?]
15.07 13:10:18 [Server] INFO at de.erethon.dungeonsxl.sign.windup.MobSign.spawn(MobSign.java:143) ~[?:?]
15.07 13:10:18 [Server] INFO at de.erethon.dungeonsxl.sign.windup.MobSpawnTask.run(MobSpawnTask.java:43) ~[?:?]
15.07 13:10:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
15.07 13:10:18 [Server] INFO Caused by: java.lang.NullPointerException
15.07 13:10:18 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:313) ~[?:?]
15.07 13:10:18 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:253) ~[?:?]
15.07 13:10:18 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:116) ~[?:?]
15.07 13:10:18 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:185) ~[?:?]
15.07 13:10:18 [Server] INFO at com.magmaguy.elitemobs.worldguard.WorldGuardFlagChecker.checkFlag(WorldGuardFlagChecker.java:17) ~[?:?]
15.07 13:10:18 [Server] INFO at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.validSpawnLocation(EliteMobEntity.java:99) ~[?:?]
15.07 13:10:18 [Server] INFO at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.<init>(EliteMobEntity.java:185) ~[?:?]
15.07 13:10:18 [Server] INFO at com.magmaguy.elitemobs.custombosses.CustomBossEntity.<init>(CustomBossEntity.java:105) ~[?:?]
15.07 13:10:18 [Server] INFO at com.magmaguy.elitemobs.custombosses.CustomBossEntity.constructCustomBoss(CustomBossEntity.java:58) ~[?:?]
15.07 13:10:18 [Server] INFO at com.magmaguy.elitemobs.commands.SpawnCommand.spawnMob(SpawnCommand.java:99) ~[?:?]
15.07 13:10:18 [Server] INFO at com.magmaguy.elitemobs.commands.CommandHandler.onCommand(CommandHandler.java:94) ~[?:?]
15.07 13:10:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:10:18 [Server] INFO ... 13 more`

Is this a bug or a problem on my part?

**Comment by Sataniel98** [comment]
Neither, it's a bug in EliteMobs.
