### ISSUE TITLE
Error on Sign Spawning Custom EliteMob Boss

### ISSUE THREAD

**Issue by OMR2K** [DRE2N/DungeonsXL#862]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
When creating a mob sign that summons an EliteMob boss, I get this error:

`15.07 13:39:48 [Server] WARN [DungeonsXL] Task #104843 for DungeonsXL v0.18-SNAPSHOT-1003 generated an exception
15.07 13:39:48 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'elitemobs' in plugin EliteMobs v7.1.33
15.07 13:39:48 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at de.erethon.dungeonsxl.api.mob.ExternalMobProvider.summon(ExternalMobProvider.java:74) ~[?:?]
15.07 13:39:48 [Server] INFO at de.erethon.dungeonsxl.sign.windup.MobSign.spawn(MobSign.java:143) ~[?:?]
15.07 13:39:48 [Server] INFO at de.erethon.dungeonsxl.sign.windup.MobSpawnTask.run(MobSpawnTask.java:43) ~[?:?]
15.07 13:39:48 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
15.07 13:39:48 [Server] INFO Caused by: java.lang.NullPointerException
15.07 13:39:48 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:313) ~[?:?]
15.07 13:39:48 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:253) ~[?:?]
15.07 13:39:48 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:116) ~[?:?]
15.07 13:39:48 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:185) ~[?:?]
15.07 13:39:48 [Server] INFO at com.magmaguy.elitemobs.worldguard.WorldGuardFlagChecker.checkFlag(WorldGuardFlagChecker.java:17) ~[?:?]
15.07 13:39:48 [Server] INFO at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.validSpawnLocation(EliteMobEntity.java:99) ~[?:?]
15.07 13:39:48 [Server] INFO at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.<init>(EliteMobEntity.java:185) ~[?:?]
15.07 13:39:48 [Server] INFO at com.magmaguy.elitemobs.custombosses.CustomBossEntity.<init>(CustomBossEntity.java:105) ~[?:?]
15.07 13:39:48 [Server] INFO at com.magmaguy.elitemobs.custombosses.CustomBossEntity.constructCustomBoss(CustomBossEntity.java:58) ~[?:?]
15.07 13:39:48 [Server] INFO at com.magmaguy.elitemobs.commands.SpawnCommand.spawnMob(SpawnCommand.java:99) ~[?:?]
15.07 13:39:48 [Server] INFO at com.magmaguy.elitemobs.commands.CommandHandler.onCommand(CommandHandler.java:94) ~[?:?]
15.07 13:39:48 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-90]
15.07 13:39:48 [Server] INFO ... 13 more`

(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [mob] sign, [mob]/owboss (boss name)/3,1,EM/D10 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the sign that summons boss

**Expected behavior**

The custom mob was expected to spawn, however, it does not spawn and an error gets sent to console.

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
externalMobProviders:
  EM: elitemobs spawnmob %world% %x% %y% %z% %mob% 10

```

**Comment by Sataniel98** [comment]
It's a bug in EliteMobs, please report it to them.
