### ISSUE TITLE
Can Citizens be used in a dungeon?

### ISSUE THREAD

**Issue by Deathroner** [DRE2N/DungeonsXL#864]
Hi, I wanted to ask you about DungeonsXL, I have not used it yet, but I have the idea of creating a dungeon with missions inside.

In this case I plan to use the Citizens plugin together with the Quests plugin created by PikaMug and also the BetonQuests plugin.

Is it possible to use these plugins inside the dungeon?

My question is because when I am creating a dungeon, a flat world map is created for editing, and I would imagine it will have another ID at launch for all players.

**Comment by Sataniel98** [comment]
Citizens NPCs work in dungeons if they use the Citizens trait API to store their data. If they use other methods, behavior is undefined.
