### ISSUE TITLE
Plugins fails completely

### ISSUE THREAD

**Issue by eDexiam** [DRE2N/DungeonsXL#879]
**Description**
In a group when someone has the Dungeon cooldown (Which is 1 hour for my case) and we start a game it completely bricks the whole plugin, leaving us stuck in the lobby.

**Reproduce**

1. Make a group and invite someone
2. Play the dungeon once and finish it
3. Make a new group and invite them again
4. Press the ready sign and wait for the countdown
5. They get an error saying they can't play this dungeon again for X hours
6. The plugin bricks itself

**Expected behavior**
The plugin to not lock up

**Screenshots / GIFs / videos**

https://pastebin.com/XNLxnNth

**Comment by eDexiam** [comment]
Found another way to reproduce:

**Reproduce**
Disband a group while being in the lobby of a Dungeon

**Comment by Sataniel98** [comment]
Thank you for the report.
