### ISSUE TITLE
MustFinishAll feature in Floor Config File

### ISSUE THREAD

**Issue by Yccheetah** [DRE2N/DungeonsXL#881]
**The feature you'd like to know more about**
The MustFinishAll feature in the floor config. How do I configure it to send an error message when not all the dungeons specified in the MustFinishAll feature are completed? Right now it doesn't send anything when I try to enter a dungeon without having a specified dungeon completed, but it does work.
(e.g. game rules)

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration

**What did you already try?**
I looked in the wiki but there wasn't much on the MustFinishAll feature.

**Relevant configuration files**
DungeonsXL/maps/test/config.yml
```
# All of these Dungeons must be finished. If you do not want any, leave this empty.
mustFinishAll:
  - dungeona
```

**Comment by Sataniel98** [comment]
It doesn't send a message mostly for historic reasons. The "requirements" that are not inside the requirements section are older than the requirements API and didn't automatically get a message when messages were added to the "real" requirements. I've thought about reimplementing the old requirements with the API, but it doesn't have high priority yet.

**Comment by Sataniel98** [comment]
Done.
