### ISSUE TITLE
Config Color Not Working

### ISSUE THREAD

**Issue by DoubleNico** [DRE2N/DungeonsXL#882]
**The feature you'd like to know more about**
 I have a question with the language config
(e.g. game rules)

**Link to the wiki article (in case it exists)**
no
**What did you already try?**
To delete the config try again the problem is :https://imgur.com/M8Tq3lH , the player name and group are blue but I don t want blue
**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
killed: "&e&lHYPE&f&lMINE &a► &e&v1 &fa fost ucis de &e&v2&f. &e&v3&f are &e&v4 &fvieti ramase."
  killedKick: "&e&lHYPE&f&lMINE &a► &e&ev1&f a fost ucis de &e&ev2&f. &e&v3 &fare vieti ramase."
```

**Comment by Sataniel98** [comment]
You need to set this in the main config under groupColorPriority.
