### ISSUE TITLE
Player won't die and is not deducting life, also not teleporting back to checkpoint

### ISSUE THREAD

**Issue by eliyash31** [DRE2N/DungeonsXL#883]
Hello I need help, after testing the dungeon, my character won't die. it just keeps on staying to 1 hp and it won't even say that my lives are deducted .. it also don't teleport to the checkpoint

here is the pastebin link of my map/dungeon/config.yml
https://pastebin.com/aXcfV7nt

Minecraft Version 1.16.1
Plugin version v0.18-SNAPSHOT-1003

**Comment by Sataniel98** [comment]
Works fine for me. Note that behavior of using both initialLives and initialGroupLives is undefined

**Comment by eliyash31** [comment]
Hello Sir what do you mean by undefined initialLives and initialGroupLives? 

btw I only used the group lives, do I also have to use the the initialLives? 

because I only want group lives so that when the lives of group reaches to zero, then the game will end. but I didn't use the initialLives though, does that cause the problem right?

**Comment by eliyash31** [comment]
Btw, I also use that settings on my previews Dungeon and it worked pretty well but I decided to change the map and so I copy pasted the config in my other map or dungeon, and now both of the worlds have the same problem where they player is not dying but his inventory items will drop, his hp remains at 1hp or half of heart and is just dtaying in one place where he is constantly hitting by the zomvie and not dying at all. I haven't checked the console yet but I will try this again and post a pastebin here about the bug.

**Comment by eliyash31** [comment]
https://pastebin.com/x8G0LYzB
here is the pastebin of the console log
