### ISSUE TITLE
Player won't die and is not deducting life, also not teleporting back to checkpoint (reopen because not yet fixed) please check the console log pastebin

### ISSUE THREAD

**Issue by eliyash31** [DRE2N/DungeonsXL#884]
Hello I need help, after testing the dungeon, my character won't die. it just keeps on staying to 1 hp and it won't even say that my lives are deducted .. it also don't teleport to the checkpoint

here is the pastebin link of my map/dungeon/config.yml
https://pastebin.com/aXcfV7nt
I can say that this is a bug because it shows errors on console, please check it author you closed the issue I posted where I haven't tried it yet if it really fixed or not.
https://pastebin.com/x8G0LYzB - console log here please check thank you. I really need help with this :( 

Minecraft Version 1.16.1
Plugin version v0.18-SNAPSHOT-1003

**Comment by Malfrador** [comment]
This seems very similar to #871. However, I am also not able to reproduce it.
Are you using any other plugins that interfere with player deaths. e.g. plugins that remove experience when a player dies? Maybe test it on a server with just DXL and no other plugins.

**Comment by eliyash31** [comment]
Hello Sir thank you for the response! because I have this problem weeks ago and really need to fix this.
here is the list of plugins in my server.
Plugins (64): ActionHealth*, AdvancedTeleport, AdvanceParticle, AuthMe, AutoBroadcast*, BuycraftX, ChestShop, Citizens, ClearLag, CMI, CMIEInjector*, CMIPaperLib, CommandNPC*, CommandPanels, CoreProtect, CrazyCrates, CubCustomDrops, CustomItems, DiscordSRV, DragonSlayer, DungeonsXL, EntityTrackerFixer, FastAsyncWorldEdit, Geyser-Spigot, GriefPrevention, HeadsPlus, Holograms, HologramsPlaceholders*, ItemsXL, LastLoginAPI, LibsDisguises, LuckPerms, MineableSpawners, MinecraftServerManager, MobArena, Multiverse-Core*, MythicArtifacts, MythicMobs, MythicMobsExtension, OreAnnouncer, Parties, PlaceholderAPI, PlayerParticles, PlayerVaults, ProtocolLib, Rankup, ResourceWorld, SAML, SchematicBrushes, ServerRestorer, Shopkeepers, SkinsRestorer, TAB, VarLight, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, VoidGenerator, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard

also I only remember adding Multiverse and MobArena plugin before this problem happened. Also about Multiverse, it keeps on saying that the map of my DungeonsXL isn't familiar with him, that I need to do /multiverse import world . I'm scared to do it because it my cause bugs in my Dungeon World? could it be that this is the problem?

**Comment by Sataniel98** [comment]
Don't add dungeon worlds to Multiverse. It shouldn't cause any harm but might lead to unexpected behavior because Multiverse handles some things about worlds DXL would normally handle. The latest development build (1015) should resolve your problem. Please let me know if there are still errors. https://erethon.de/repo/de/erethon/dungeonsxl/dungeonsxl-dist/

**Comment by eliyash31** [comment]
Okay thank you so much! it fixed the problem :)
