### ISSUE TITLE
Bug 1.16.1

### ISSUE THREAD

**Issue by vHWhiiz** [DRE2N/DungeonsXL#889]
**Description**
Dungeonsxl ne marche pas en 1.16.1 et spam la console.
https://pastebin.com/pNPhSaqK

**Comment by Sataniel98** [comment]
The problem could possibly be already fixed. Please try using the latest build (https://erethon.de/repo/de/erethon/dungeonsxl/dungeonsxl-dist/).

Are there any other exceptions? (You can find them with Ctrl+F "at de.erethon" in the logs)

**Comment by vHWhiiz** [comment]
Sorry but dungeonsxl still doesn't work...and shows me this error message
but I don't know if this is the right error message :/.
https://pastebin.com/XNu3QnZJ

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le ven. 11 sept. 2020 à 19:07, Daniel Saukel <notifications@github.com> a
écrit :

**Comment by Sataniel98** [comment]
Should be fixed, please let me know if there's still something wrong.
