### ISSUE TITLE
Commands still not working???

### ISSUE THREAD

**Issue by doctorblanket** [DRE2N/DungeonsXL#891]
I updated to the latest version like you suggested, and while the console is no longer being spammed, the commands are still not working. Please help me.
Note: the commands stopped working after updating to 1.16.3

**Comment by doctorblanket** [comment]
Here's the error given on startup: https://pastebin.com/8BBftzBu

**Comment by Sataniel98** [comment]
Make sure Citizens and its addons are loaded correctly.

**Comment by doctorblanket** [comment]
I updated them to the latest version and that worked! Thank you!
