### ISSUE TITLE
Server freezes on /dxl create edit or play

### ISSUE THREAD

**Issue by ehetteNandaYo** [DRE2N/DungeonsXL#892]
https://paste.gg/p/anonymous/dcc3011527b845cb9730677c0e7b0d71/files/f64517e167b043f1b455bc924b7376b9/raw

![image](https://user-images.githubusercontent.com/62739770/92988059-38985300-f496-11ea-9478-d7b42a5b5001.png)

Dungeons 0.18-SNAPSHOT-1015
paper-150 1.16.2

**Comment by Sataniel98** [comment]
Yeah, because it's generating / loading a world.

**Comment by ehetteNandaYo** [comment]
I remember before it didnt hang the server for so long....

This is not normal, like, I do /dxl play server hangs for so long that it kicks me out and then when I log back in the I'm outside the dungeon.

https://paste.gg/p/anonymous/ec97a0e85e1447d2baedbeaeb23f8717/files/2730c565a7df4bc5ae5ae6b5d03b13a0/raw

**Comment by Sataniel98** [comment]
Make sure all worlds are converted to 1.16 in edit mode and saved sothat it doesn't convert them anew every time they are loaded. Worlds should be as small as possible.
