### ISSUE TITLE
keepInventoryOnDeath resets inventory instead of keeping it

### ISSUE THREAD

**Issue by Malfrador** [DRE2N/DungeonsXL#893]
**Description**

The gamerule keepInventoryOnDeath resets the inventory of the player who died to the inventory of the selected class. This means that items that the player picked up during the dungeon are lost and the player can not progress if those items are needed. This was not the case in earlier builds (775).

**Version**
DXL 0.18-Snapshot-1015
Paper-195 (1.16.3)

**Reproduce**

1. Create a dungeon with classes
2. Add a way for the player to get additional items (e.g. a chest, mob loot, etc.)
3. Play the dungeon and die
4. The inventory will be reset and will only contain the class items. All additional items will be lost.

**Expected behavior**

The inventory should be kept, including all additional items. The current behavior breaks dungeons that use keys or mob loot for unlocking certain areas. Maybe an additional resetInventoryOnDeath gamerule can be added, for use-cases that need those resets (PvP arenas?).

**Comment by Sataniel98** [comment]
resetClassInventoryOnRespawn muss false sein.
