### ISSUE TITLE
Leave sign triggered with distance works only once

### ISSUE THREAD

**Issue by RiCkYB-667** [DRE2N/DungeonsXL#899]
**Description**

I tried triggering a [Leave] sign with D 5 trigger. The first player can always trigger it by approaching, but no one else. It seems to stop checking for approaching players after the first player triggered it.

**Reproduce**

1. Create a new dungeon with /dxl create
2. Place [Leave] sign with D 5 trigger
3. Leave edit mode with /dxl leave
4. Join group with at least 2 players, use /dxl play
5. Try to trigger Leave sign with each player by approaching

**Expected behavior (?)**

Trigger dungeon leave for each player who approaches sign

**Comment by Sataniel98** [comment]
That's how the distance trigger works: It triggers the sign once for the first player in a distance and then disables itself. If it didn't, mob signs would enable and disable every time a player comes close to it. Use a Presence trigger (P 5) instead.
