### ISSUE TITLE
Preventing piglins/zoglins from zombifing.

### ISSUE THREAD

**Issue by GuazP** [DRE2N/DungeonsXL#905]
**The feature you'd like to know more about**

Prevent piglins and zoglins from turning into zombified versions.

**Link to the wiki article (in case it exists)**

//setbiome command from worldedit
&
https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration
worldEnvironment: NETHER
in config.yml

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
worldEnvironment: NETHER
```

More info:
Generally, I have most recent (3 days past - maybe already is newest version) of wordledit and dungeonsxl. But whenever I //setbiome, just some parts of terrain becoming new biome, other isn't. Generally I would like to prevent piglins from zombifing any way, if there is such?

**Comment by Sataniel98** [comment]
I guess in this case it makes sense to prevent all piglins from zombifying in the overworld. If a user wanted zombified piglins, he'd just spawn them zombified.
