### ISSUE TITLE
Group adapter API

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#91]
**Please describe the use case or the problem your request is related to.**
Just like DungeonsXL, many plugins have systems that group players together in parties. Having multiple party systems simultaneously however is confusing and messy. Plugins that have commonly been asked to be supported are:
* Heroes
* MCMMO
* RacesAndClasses
* Parties

**Describe the solution you'd like**
An adapter API that automatically synchronizes DXL groups with external groups.
* DGroup stores a collection of a new DGroupAdapter object.
* When players join or leave a group, methods of the adapter are invoked which, if it is implemented correctly, apply the same changes to the external group the adapter wraps (or possibly, if implemented by the external plugin, is).
* Adapter should also track changes done by the external plugin and apply them to their DGroup.
* DGroups shall be creatable through adapters.

DXL should contain implementations for as many famous, free plugins as possible.

Problems might occur with group systems that are persistent in contrast to DXL's transient groups.

**Describe alternatives you've considered**
It had been asked to have an option to "disable" DXL's group system, which is neither necessary nor realizable. There is no such thing as a Vault plugin for parties that is somehow close to being a de facto standard.

**Comment by Nvenom** [comment]
Any chance of this getting any notice? Im curious if party integration with heroes is possible, in the works or already done in some way.

**Comment by Sataniel98** [comment]
It's planned for the 1.0 release, which I planned to work on after the 0.15.x or 0.16 updates. Thank you, it's always nice to get some feedback concerning which kind of features are actually useful for servers. Gotta iron out quite a few bugs first, though.

**Comment by Sataniel98** [comment]
https://www.spigotmc.org/threads/dungeonsxl.78142/page-72#post-3362946
