### ISSUE TITLE
Requirements don't work

### ISSUE THREAD

**Issue by Davedave000** [DRE2N/DungeonsXL#912]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Requirements placed in the config of the first floor of a dungeon don't actually work. It recognizes illegal items but doesn't stop you from taking them into the dungeon. The fee also doesn't take money from your bal.

**Reproduce**

1. Make a dungeon script and some dungeon maps.
2. Edit the config for the first map.
3. Add requirements.
4. Reload the plugin.
5. Enter the dungeon with the forbidden items and the money for the fee. Neither will be taken away.

**Expected behavior**

I expected to not be allowed into the dungeon if I had forbidden items. I also expected to be charged the fee set in the config.

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/56517317/97506125-744c8680-1937-11eb-81f0-ba9e2a1b7411.png)

**Relevant configuration files**

```
requirements:
  forbiddenItems:
  - ENDER_PEARL
  - ELYTRA
  feeMoney: 9
```

**Comment by Sataniel98** [comment]
Are you sure you don't have the dxl.ignorerequirements permission node and aren't OP?

**Comment by Davedave000** [comment]
Seems like I did have op when I last tested it. It sorta works now but I found another bug while running it again. This is what I get for playtesting stuff when I've been awake for over 24 hours.
