### ISSUE TITLE
The CheckPoint Sign Dosen't Support For Group Or Team

### ISSUE THREAD

**Issue by PASAKON** [DRE2N/DungeonsXL#915]
I using Sign following wiki page like

1: [Checkpoint]
2:
3:
4:      D5

Checkpoint will work only first person who reached checkpoint
Other People will not get Checkpoint how make checkpoint per person in Dungeon ??

**Comment by Sataniel98** [comment]
Distance triggers fire only for the first player. Use the presence trigger (P5) instead.
