### ISSUE TITLE
CheckPoint Sign will not working then play Dungeon with team 

### ISSUE THREAD

**Issue by PASAKON** [DRE2N/DungeonsXL#916]
I'm create following wiki like

1:[Checkpoint]
2:
3:
4:      D5

it will work only first person who reach the point 
the second player the sign will not working

Im suing Script Sign 
0:
  - "[Checkpoint]"
  - ""
  - ""
  - "D5"
1:
  - "[Mob]"
  - "CheckPoint"
  - "1,1,MM"
  - "D20"

**Comment by Sataniel98** [comment]
I already answered that? Duplicate of #915

**Comment by PASAKON** [comment]
OH It's working now 

what P5 trigger means ?

**Comment by Sataniel98** [comment]
Presence triggers fire whenever a player is in distance (and the checkpoint sign ignores player who have already reached it). Distance triggers fire one time when the first player gets in distance. We need both sothat for example mob signs don't spawn mobs endlessly.
