### ISSUE TITLE
GROUP SIGN BUGS EVERY ONE CAN CREATE SO MANY GROUP NOT ONLY ONE GROUP

### ISSUE THREAD

**Issue by PASAKON** [DRE2N/DungeonsXL#918]
![ภาพหน้าจอ 2563-10-31 เวลา 22 07 23](https://user-images.githubusercontent.com/45531631/97782689-8d6a6700-1bc5-11eb-8fcc-169d4147cb65.png)

**Comment by Sataniel98** [comment]
This is already fixed.
