### ISSUE TITLE
Portal in main world breaks location in dungeon world

### ISSUE THREAD

**Issue by Yippu** [DRE2N/DungeonsXL#919]
**Description**

When running a dungeon and reaching the same location in that dungeon world as a portal in the main world, it "corrupts" the dungeonsxl player file, and sends the player back into the lobby.

**Reproduce**

Not sure if this is exactly how to do it, but here goes:

1- in the main world, create a DungeonsXL portal.
2- create a dungeon which has a path leading through the same coordinates as the portal in the main world
3- walk through the same coordinates as the portal

**Expected behavior**

I wanted to walk through the same coordinates without any issues, but instead it corrupts the player file and sends me back to the lobby.

**Screenshots / GIFs / videos**

https://youtu.be/d201FU0Jwt4

**Relevant configuration files**

N/A

**Comment by Sataniel98** [comment]
Thank you for the report :) Does [the latest build](https://erethon.de/repo/de/erethon/dungeonsxl/dungeonsxl-dist/) fix your problem?

**Comment by Yippu** [comment]
Yup! Thank you much :)
