### ISSUE TITLE
Incompatibilities between MysqlPlayerDataBridge and DungeonsXL

### ISSUE THREAD

**Issue by tiradorus** [DRE2N/DungeonsXL#920]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Each time a player disconnect into a dungeon, he lost all of his looted items. And i know why.

I have a large Bungeecord server, and the dungeons have their own servers (Less GPU usage)
So in that case, i have to use "MySqlPlayerDataBridge" (to transfer the items from a server to another by using a database where eveything is stored)
However, when a player DISCONNECT when playing the dungeon, the database do not accept it, and make a rollback for the player. He can see his looted items for at last ... 0.5s and then it disappear. To having a rollback caused by "MySqlPlayerDataBridge"

I know it's an incompatibility between your plugins, that's why just after that i'll contact the dev Of MYSQLPlayerData, if both of you can works together to make a compatible version of your respective plugins it could be very appreciated.

PS:
It's not a bug of the config file, 'cause everything works perfectly when the player just leave the dungeon without disconnect.

**Comment by Sataniel98** [comment]
They are aware of DungeonsXL and have an integration for it so I'm sure they can help you with it.

**Comment by Sataniel98** [comment]
I'll close this for now, but if any API additions are needed, let me know @brunyman.
