### ISSUE TITLE
Some trigger signs are not working. Others are working fine. It can be a bug 

### ISSUE THREAD

**Issue by eliyash31** [DRE2N/DungeonsXL#922]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

I created GateKeeper as a mob or entity for a player to kill to trigger a sign in order to proceed or to be teleported to the next stage. Trigger 1 to Trigger 15 works fine but Trigger 16 is always like this everytime I tried to join the server and go to stage 15.. 

**Reproduce**

(List steps to reproduce, e.g.:
1. /dxl edit DR_1
2. Place [Trigger] sign, [Trigger]/16/blank/M GK15
3. Save edit mode with /dxl save
4.  Leave edit mode with /dxl leave
5. Test with /dxl play DR_1
6. Try to check the sign and it is still there, not like the other trigger signs that they will be invisible when the dungeon is started.

 List steps to reproduce the mob GK15 (the mob will spawn but the trigger sign 16 will not work because maybe it caused a bug)
1. /dxl edit DR_1
2. Place [mob] sign, [Mob]/GK15/10,1,MM/D 3
3. Save edit mode with /dxl save
4.  Leave edit mode with /dxl leave
5. Test with /dxl play DR_1
6. Go to the mob sign with distance of 3 and wait for 10 seconds and try to wait for the mob to spawn and kill it.

**Expected behavior**

I expect that the Trigger Sign will be invisible just like the others meaning I can say that the sign is working fine.
But what happened is that it just stay visible and after killing the mob GK15 the sign is not working and won't trigger to teleport the player to another floor or area.

**Screenshots / GIFs / videos**

[Picture 1.jpg](https://imgur.com/a/LQrzqn9)

**Relevant configuration files**
##Mobs.yml in MythicMobs
https://pastebin.com/CkMfWmeb

**Comment by Sataniel98** [comment]
Thank you for the report. It's hard to reproduce a bug that occurs in 1 out of 16 cases with seemingly no difference. Did you try re-placing the sign? Did you try leaving the second line of the trigger sign empty to let it generate an ID automatically? If yes, what happens? Are there messages in the console?

**Comment by eliyash31** [comment]
Thank you for the response Author! I will be trying this out again tomorrow because it is already night time in our time.. please don't close this issue yet and I will give a feedback tomorrow once I try it out ☺️

**Comment by eliyash31** [comment]
Okay I think it just fixed after a server restart :D we will test this again if there will be another bug.. I wonder what happened at that time. I will close this for now thank you Author for the response!
