### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by ludgart** [DRE2N/DungeonsXL#923]
Hello, 

I saw in your source code that you are using the PlayerMoveEvent. To create a huge performance boots, it would be better to use an asynchronously thread. 

https://github.com/DRE2N/DungeonsXL/blob/7ad1071df139b07a94fe0c7913e8bb04ff7baa36/core/src/main/java/de/erethon/dungeonsxl/player/DPlayerListener.java#L410

Regards
ludgart

**Comment by Sataniel98** [comment]
Well thank you, please don't feel discouraged from sharing your thoughts, but that's just not how it works. Minecraft and its server software are inherently single-threaded software. You can't just switch to another thread whenever you feel like it. Plus, creating and maintaining threads is resource-intensive. The methods called here are practically all in O(n), so there's way more to lose than to gain.
