### ISSUE TITLE
Forbidden items does not work if you players rename the item.

### ISSUE THREAD

**Issue by Esronn** [DRE2N/DungeonsXL#926]
**Description**

I have forbidden a few items, specifically these:
`
requirements:
  forbiddenItems:
  - ENDER_PEARL
  - ELYTRA
  - CHORUS_FRUIT
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - ENDER_CHEST
  - WATER_BUCKET
  - BUCKET
  - LAVA_BUCKET
  - NETHERITE_PICKAXE
  - EMERALD
`
Players can still bring any of these items if they simply rename the item to anything.

**Reproduce**

1. Block item in requirements.
2. Rename item
3. Join the dungeon / map.

**Expected behavior**

The player should not be able to join because said item is forbidden.

**Screenshots / GIFs / videos**

None

**Relevant configuration files**

This is the config for the map.
```
requirements:
  forbiddenItems:
  - ENDER_PEARL
  - ELYTRA
  - CHORUS_FRUIT
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - ENDER_CHEST
  - WATER_BUCKET
  - BUCKET
  - LAVA_BUCKET
  - NETHERITE_PICKAXE
  - EMERALD
initialGroupLives: 2
invitedPlayers: []

```

**Comment by Esronn** [comment]
@Sataniel98 
Any progress on this? I'd love to use this plugin again once it's fixed.

**Comment by Sataniel98** [comment]
I'll work on it when I have time.

**Comment by Sataniel98** [comment]
Fix is done, you can get it here: https://erethon.de/repo/de/erethon/dungeonsxl/dungeonsxl-dist/

The list now also forbids items that are based on the entries, e.g. adding ENDER_PEARL also forbids all registered custom items that are based on ender pearls but usually have a different ID within our item system. See https://github.com/DRE2N/DungeonsXL/wiki/requirements#forbidden-items
