### ISSUE TITLE
GamePermission Seem Notworking

### ISSUE THREAD

**Issue by PASAKON** [DRE2N/DungeonsXL#927]
![ภาพหน้าจอ 2563-11-12 เวลา 20 58 32](https://user-images.githubusercontent.com/45531631/98949116-de654e00-2529-11eb-8124-02361fadd0cb.png)

im trying to add game permission to confit.yml path plugins/dungeonXL/maps/Dungeon1/confic.yml

but when im join the game and use /papi parse 2n0 %luckperms_has_permission_mth.dungeon1.playing%
it's will say "no" 

![ภาพหน้าจอ 2563-11-12 เวลา 21 00 48](https://user-images.githubusercontent.com/45531631/98949347-2b492480-252a-11eb-8e26-eace8bb6114b.png)

DungeonXL Laster Build: v0.18-SNAPSHOT-1063
Luckperms Version: v5.1.93
Vault Vertions: v1.7.3
Spigot: 1.15.2

**Comment by Sataniel98** [comment]
Yes, we're having problems with LuckPerms as well. Seems like they're not implementing transient permissions, at least not the way I expected them to. This still needs some work and research before the next DXL release can be finished.
