### ISSUE TITLE
[Bug][DXL] Mobs don't spawn in 1.16.3. (v0.18-SNAPSHOT-1063)

### ISSUE THREAD

**Issue by Azaxysminecraft** [DRE2N/DungeonsXL#929]
**Description**

Paper 1.16.3 latest build
- DXL Build: v0.18-SNAPSHOT-1063 (v0.18-SNAPSHOT-1063 does not work in 1.16.3).
- No error message. No error log.
- No spawn command visible in the terminal. We used to see them in 1.12.2.
- Tested dungeons used to work perfectly in 1.12.2.
- MM works well, mobs can spawn.
- Trigger issue?
- Two plugins on the test server: DXL and MM. MM works well.

**Reproduce**

The issue is showcased in the below video. 

[https://www.youtube.com/watch?v=GIGhKcGfvSw&feature=youtu.be](url)

**Expected behaviour**

Mobs should spawn using DXL in 1.16.3. 

**Screenshots / GIFs / videos**
The same video demonstrating the issue
[https://www.youtube.com/watch?v=GIGhKcGfvSw&feature=youtu.be](url)

Thanks for your help

**Comment by Sataniel98** [comment]
Thank you for the report. Does it work with newly placed MM signs?

**Comment by Azaxysminecraft** [comment]
Nop I tried, it does not work at all. I have the notification saying that the sign has been successfully created but it does not work, unfortunately.

**Comment by Sataniel98** [comment]
What I could reproduce is that there's a chance MythicMobs NPCs despawn right after being spawned: https://youtu.be/-i4qdJICS9Y That's nothing DXL has any say in whatsoever and it doesn't occur often enough to explain your problem. I'll need more details about your setup to find out what's wrong. Which version of MythicMobs are you running? Did you overwrite MM In the config?

**Comment by Azaxysminecraft** [comment]
Hi, 

Well, I found out the problem. Actually, it is not a bug. The plugin is working perfectly. As I said previously all our dungeons have been created in 1.12.2. 
https://imgur.com/7z4DLfo
Actually, it is all about the spawning delay. Our previous dungeons creator indicated 600, was it in milliseconds at the time? Or the feature wasn't working at the time which could be another explanation? Anyway, now the spawning value is indicated in seconds. Basically, we just had to wait 600 seconds to see our mobs spawn. 

Thanks a lot for your time.

**Comment by Sataniel98** [comment]
I see, thank you for letting me know.

It has always been seconds, but what has changed is that signs have been categorized into groups with similar functionality to make the behavior more predictable and to reduce code duplications. The delay of mob signs is now counted down once before the first mob is spawned, while previously, the delay only affected time between mobs spawned. So it used to not matter if the amount of mobs is 1.
