### ISSUE TITLE
Lock Mechanincs to prevent speedrun the dungeon ?

### ISSUE THREAD

**Issue by RafaSilva17** [DRE2N/DungeonsXL#930]
Lock Mechanincs to prevent speedrun the dungeon

(e.g. game rules)

https://github.com/DRE2N/DungeonsXL/wiki/floor-configuration

I was serching throw your wiki/domuntacion and didn´t find anything related to something to lock the path way to the conclusion of the floor, like for exemple only if you kill like 90% of the mobs of the floor you unlock/unblock the path way to the conclusion of the dungeon. I just wanted to know if ,with your plugin like it is right now, its possible to do that kind of things.

Thanks for the attention.

**Comment by Sataniel98** [comment]
You can use doors or block signs.
