### ISSUE TITLE
script sign is not written correctly.

### ISSUE THREAD

**Issue by eliyash31** [DRE2N/DungeonsXL#933]
**Description**

I already try to change the script.yml many times but it always says the sign is not written correctly.

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [script] sign, [Script]/halloween

**Expected behavior**

The sign should be created successfully since I wrote the correct name of the script.yml for mobs please refer to the picture I sent.

**Screenshots / GIFs / videos**

https://imgur.com/a/KjEwIGa

**Relevant configuration files**

0:
  - "[Mob]"
  - "HD_Zombie"
  - "2,5,MM"
  - "D 4"

```

```

**Comment by Sataniel98** [comment]
That screenshot looks like you put it into the mobs folder.

**Comment by eliyash31** [comment]
Oh okay I thought I'm gonna put on in the mobs folder since I'm using the script for spawning mobs. I think I got the problem now, I'll try to transfer it in the signs folder and see if it works thanks!
