### ISSUE TITLE
Lagg and rollback with map loading in 1.16

### ISSUE THREAD

**Issue by francisdu30** [DRE2N/DungeonsXL#941]
Heyo ! I have a dungeon, only one so i dont test if the lagg happens when the map is little bug with a map pretty fat every time when a player launch a dungeon all the server get a rollback of 5/10 seconds and the tps -3
1.16.2 server with last version of dxl
thx for your help

**Comment by francisdu30** [comment]
I have the same donjon on a 1.12 server and that dont happen, thx a lot for your work

**Comment by Sataniel98** [comment]
Well yes, copying and loading a world is of course somewhat expensive. If the world is large, lags are to be expected. Just make sure the map is up to date and doesn't need to convert every time it is loaded.

**Comment by francisdu30** [comment]
But my dungeon is not immense, is a project who can exist in every serious servers who like the univers of dxl and that cause 5/10  seconds of rollback for all the server and make lost 3 tps. You have a way to slowdown map loading into dxl for 1.16? In 1.12.2 that work without ressources cost problem with 3 dungeons instances in same time
I will try to convert before for see what happen and say you
Thx a lot have a good day

**Comment by francisdu30** [comment]
It was thattttttttt thx a lot, when i have convert the map before put it in the map folder of dxl that work
Thx a lot for your work
