### ISSUE TITLE
Quit Event Bug & Floor config Question

### ISSUE THREAD

**Issue by LoneDevilX** [DRE2N/DungeonsXL#948]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
1. Error occur when player leaves the server.
2. **Question: May I ask how can I set the floor levels orderly? Which means like player needs to finish LV 1 to go to LV 2, instead of randomly select the next dungeon level.  && The dungeon floor level doesn't repeat.**
3. **Question 2: How can player continue the LV 2 after the dungeon finished? Is it need to rejoin the DXL?**
(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

**Reproduce**

(List steps to reproduce, e.g.:
1. Player quit server will create the bug (No matter player did/didn't play the dungeon)

**Expected behavior**
1. Shouldn't have these error when the player quit the server.
(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Screenshots / GIFs / videos**
Bug report:
https://pastebin.ubuntu.com/p/9vgVz2xGRR/
(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
[dxl.zip](https://github.com/DRE2N/DungeonsXL/files/5701412/dxl.zip)

```

**Description of the question (1)**
How can I make the dungeon floor goes like this?:
1. Player join Dungeon level A as 1st floor
2. After finished, they will automatic teleport to dungeon level B as 2nd floor

If they died in the floor, they must recomplete the Dungeon level A 
Which means the dungeon floor can be setting which is the 1st floor, 2nd floor, 3rd floor and required player to finish it accordingly our settings.
And no repeat of the floor unless they finish the whole dungeon/died

**Description of the question(2)**
How can I make the dungeon continue after they finished 1 floor?
Continue dungeon according our settings

**Comment by Sataniel98** [comment]
Please create one issue per actual issue in the future.

> Error occur when player leaves the server.

I'll need to see the full stacktrace for this. You console might not show the stacktrace of repeating errors but they should be in the logs.

> Question: May I ask how can I set the floor levels orderly? Which means like player needs to finish LV 1 to go to LV 2, instead of randomly select the next dungeon level. && The dungeon floor level doesn't repeat.

Specify the next floor on the end sign: https://github.com/DRE2N/DungeonsXL/wiki/DungeonSign-End

> Question 2: How can player continue the LV 2 after the dungeon finished? Is it need to rejoin the DXL?

If players are supposed to be allowed to take breaks between floors, a solution with single floor dungeons and lv 2 needing lv 1 in the mustFinishAll game rule might be better.

**Comment by LoneDevilX** [comment]
So, may I ask, how do they actually connect through the floor_name? like the 'Dungeon config' given the name. How does the config track the actual floor?

Besides, this is my server LOG. You may check out the last part of the error.
[latest.log](https://github.com/DRE2N/DungeonsXL/files/5714164/latest.log)
And the dungeon config (floor) here the console said I have a wrong format. But I do copy the same format as the WIKI given.
[test.zip](https://github.com/DRE2N/DungeonsXL/files/5714337/test.zip)
