### ISSUE TITLE
Killing mobs and teleporting

### ISSUE THREAD

**Issue by JobazZzy** [DRE2N/DungeonsXL#950]
Can I make it so that after killing a certain number of mobs the player is teleported to specified coordinate?
I reread the WIKI for a long time. I'm either stupid or my English skills are failing me

**Comment by Sataniel98** [comment]
Unfortunately not. Mob triggers don't allow for any logics yet. If a mob with the given ID dies, it fires. A workaround is to register mobs as custom mobs with separate IDs, or to use the deprecated wave / progress trigger, which checks for killed mobs in the whole dungeon.

https://github.com/DRE2N/DungeonsXL/wiki/signs-legacy#wave-1

See also #383
