### ISSUE TITLE
TRIGGER ERROR

### ISSUE THREAD

**Issue by erposse90** [DRE2N/DungeonsXL#960]
Command sign with distance and interact trigger dont work and give this error..

10.01 02:23:31 [Server] Server thread/INFO []: [DungeonsXL] A sign at 174, 4, 103 is erroneous!
10.01 02:23:31 [Server] Server thread/INFO []: [DungeonsXL] CMD: An error occurred while triggering a sign of the type CMD. This is not a user error. Please report the following stacktrace to the developer of the plugin:
10.01 02:23:31 [Server] Server thread/WARN []: java.lang.NullPointerException
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.sign.windup.CommandSign.activate(CommandSign.java:167)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.api.sign.Windup.trigger(Windup.java:166)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.api.sign.DungeonSign.updateTriggers(DungeonSign.java:189)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.trigger.DistanceTrigger.onTrigger(DistanceTrigger.java:58)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.trigger.DistanceTrigger.triggerAllInDistance(DistanceTrigger.java:83)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:812)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.DungeonsXL$2.lambda$run$0(DungeonsXL.java:404)
10.01 02:23:31 [Server] Server thread/WARN []: at java.util.ArrayList.forEach(ArrayList.java:1257)
10.01 02:23:31 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.DungeonsXL$2.run(DungeonsXL.java:404)
10.01 02:23:31 [Server] Server thread/WARN []: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78)
10.01 02:23:31 [Server] Server thread/WARN []: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
10.01 02:23:31 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916)
10.01 02:23:31 [Server] Server thread/WARN []: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
10.01 02:23:31 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
10.01 02:23:31 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
10.01 02:23:31 [Server] Server thread/WARN []: at java.lang.Thread.run(Thread.java:748)
10.01 02:23:36 [Server] Server thread/INFO []: [DungeonsXL] A sign at 162, 4, 103 is erroneous!
10.01 02:23:36 [Server] Server thread/INFO []: [DungeonsXL] CMD: An error occurred while triggering a sign of the type CMD. This is not a user error. Please report the following stacktrace to the developer of the plugin:
10.01 02:23:36 [Server] Server thread/WARN []: java.lang.NullPointerException
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.sign.windup.CommandSign.activate(CommandSign.java:167)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.api.sign.Windup.trigger(Windup.java:166)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.api.sign.DungeonSign.updateTriggers(DungeonSign.java:189)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.trigger.DistanceTrigger.onTrigger(DistanceTrigger.java:58)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.trigger.DistanceTrigger.triggerAllInDistance(DistanceTrigger.java:83)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:812)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.DungeonsXL$2.lambda$run$0(DungeonsXL.java:404)
10.01 02:23:36 [Server] Server thread/WARN []: at java.util.ArrayList.forEach(ArrayList.java:1257)
10.01 02:23:36 [Server] Server thread/WARN []: at de.erethon.dungeonsxl.DungeonsXL$2.run(DungeonsXL.java:404)
10.01 02:23:36 [Server] Server thread/WARN []: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78)
10.01 02:23:36 [Server] Server thread/WARN []: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
10.01 02:23:36 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916)
10.01 02:23:36 [Server] Server thread/WARN []: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
10.01 02:23:36 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
10.01 02:23:36 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
10.01 02:23:36 [Server] Server thread/WARN []: at java.lang.Thread.run(Thread.java:748)
```

```

**Comment by Sataniel98** [comment]
Are there any other stacktraces before this happens?

**Comment by erposse90** [comment]
only lobby and leave sign

**Comment by Sataniel98** [comment]
Are there other error messages?

**Comment by erposse90** [comment]
Nop
