### ISSUE TITLE
Players keep the items they entered with upon death

### ISSUE THREAD

**Issue by AttractiveAxe** [DRE2N/DungeonsXL#964]
Hi! I have a question about how a particular gamerule works. I have keepInventoryOnEscape set to false for my test dugeon and have double checked that it is formatted correctly (I copy/pasted it from the example config on github). When a player dies or leaves the dungeon without an End sign, they lose the stuff they got in the dungeon but keep the stuff they went in with (keepInventoryOnEnter: true). Is this how the keepInventoryOnEscape gamerule is supposed to work or is it a bug? If intentional, is there a way around it? I want players to have to risk losing the gear they've earned in survival by going in to these dungeons

**Comment by Sataniel98** [comment]
Hi,
if keepInventoryOnEscape is false, the saved data is supposed to be reset. If it's true, the items from the dungeon will be kept (except for items marked as [dungeon items](https://github.com/DRE2N/DungeonsXL/wiki/dungeon-items)). So just throwing the main world inventory away isn't really supposed to happen (unless you set keepInventoryOnDeath to false). A workaround could be to kill the players as soon as they're teleported out of the dungeon, for example by teleporting them into a bedrock room full of lava or where a command block kills them. You can use [escapeLocation](https://github.com/DRE2N/DungeonsXL/wiki/game-rules#respawn-options) for this.

**Comment by AttractiveAxe** [comment]
keepInventoryOnDeath is also set to false but the players keep their stuff. In testing, a player would die and drop all their items (the things they brought in and the things they had found within the dungeon), but would then respawn in the main world with the same inventory they had taken in.

**Comment by Sataniel98** [comment]
> keepInventoryOnDeath is also set to false but the players keep their stuff. In testing, a player would die and drop all their items (the things they brought in and the things they had found within the dungeon), but would then respawn in the main world with the same inventory they had taken in.

That would require keepInventoryOnEscape to be true. keepInventoryOnDeath: false makes the player lose their state (which, in this case, is the state from the main world) on death, which means the players lose their inventory when they die and this "respawned" state is kept with keepInventoryOnEscape: true.

**Comment by AttractiveAxe** [comment]
Oh okay I get it now. Thanks!
