### ISSUE TITLE
Chinese Language Translation

### ISSUE THREAD

**Issue by RaymondW722** [DRE2N/DungeonsXL#966]
I found that the Chinese translation in (https://github.com/DRE2N/DungeonsXL/tree/translations) is no longer valid, this is new, please update it.

**Comment by RaymondW722** [comment]
chinese_Simplified
> announcer:
  click: "&4&l=> &6点击此处加入 &4&l<="
button: 
  accept: "&a[ 接受 ]"
  deny: "&4[ 拒绝 ]"
  okay: "&a[ OK ]"
cmd:
  announce:
    help: "/dxl announce [name] - 运行公告脚本"
  break:
    breakMode: "&6您现在可以打破DungeonsXL保护的方块."
    help: "/dxl break - 打破DungeonsXL保护的方块"
    protectedMode: "&6您现在无法再打破DungeonsXL保护的方块."
  chat:
    dungeonChat: "&6您已进入副本聊天模式。"
    help: "/dxl chat - 更改聊天模式"
    normalChat: "&6你已进入公共聊天模式。"
  chatspy:
    help: "/dxl chatspy - 开启/关闭 聊天监听"
    started: "&6 你开启了 聊天监听."
    stopped: "&6 你关闭了 聊天监听."
  create:
   help: "/dxl create [name] - 创建副本地图"
  delete:
    backups: "&6你确定要删除所有的备份吗?"
    help: "/dxl delete [name] - 删除副本地图"
    success: "&6成功删除地图 &4&v1&6."
  dungeonItem:
    dungeonItemHelp: "&6游戏结束后，即使各自的副本设置通常允许保留它，也会从玩家的背包中删除&4副本物品&6。."
    globalItemHelp: "&6游戏结束后，如果各个副本设置通常允许保留主世界背包，则 &4玩家 &6可以从副本中取回原有背包"
    help: "/dxl dungeonItem [true|false|info] - 游戏结束后，如果各个副本设置通常允许保留主世界背包，则 &4玩家 &6可以从副本中取回原有背包。"
    info: 
      dungeon: "&这个物品是 &4副本物品&6."
      global: "&6这个物品是 &4通用物品&6."
    set: 
      dungeon: "&6成功将此物品设为 &4副本物品&6."
      global: "&6成功将此物品设为 &4通用物品&6."
  edit:
    help: "/dxl edit [map] - 编辑副本地图"
  enter: 
    help: "/dxl enter ([joining group]) [target group] - 让小队A进入小队B的游戏"
    success: "&6小队 &4&v1 &6成功进入 &4&v2&6 的游戏."
  escape: 
    help: "/dxl escape - 放弃保存并离开编辑中的地图"
  game: 
    help: "/dxl game - 显示有关当前游戏会话的信息"
  group:
    help: 
      create: "/dxl group create [小队名] - 创建一个小队"
      disband: "/dxl group disband ([小队名]) - 解散小队"
      invite: "/dxl group invite [玩家名] - 邀请某人加入你的小队"
      join: "/dxl group join [小队名]- 加入小队"
      kick: "/dxl group kick [玩家名] - 踢出某人"
      main: "/dxl group - 展示小队指令"
      show: "/dxl group show [小队名] - 展示小队"
      uninvite: "/dxl group uninvite [玩家名] - 取消邀请玩家加入小队"
  help:
    help: "/dxl help [page] - 显示帮助页面"
  import:
    help: "/dxl import [world] - 从世界列表中导入世界作为副本地图"
    success: "&6成功导入世界 &4&v1&6."
  invite:
    help: "/dxl invite [player] [dungeon] - 邀请玩家编辑副本"
    success: "&6玩家 &4&v1&6 被成功邀请编辑地图 &4&v2&6."
  join:
    help: "/dxl join [announcement] - 打开菜单加入即将参加的游戏的小队"
  kick:
    help: "/dxl kick [player] - 将玩家踢出小队和副本"
    success: "&6Successfully 玩家 &4&v1&6 被踢出小队."
  leave:
    help: "/dxl leave - 离开当前小队和副本或编辑世界"
    success: "&6您已成功离开小队."
  list:
    help: "/dxl list ([dungeon|map|loaded]) ([dungeon]) - 列出所有副本"
  lives:
    group: "&4&v1 &6剩余 &4&v2 &6生命."
    help: "/dxl lives [玩家名] - 显示玩家剩余的生命"
    player: "&4&v1 &6剩余 &4&v2 &6生命."
  main:
    compatibility: "&eInternals: &o[&v1] &eVault: &o[&v2] &eItemsXL: &o[&v3]"
    help: "/dxl - 一般状态信息"
    helpInfo: "&7输入 &o/dxl help&r&7 以获取更多信息."
    loaded: "&e地图: &o[&v1] &e副本: &o[&v2] &e已加载: &o[&v3] &e玩家: &o[&v4]"
    welcome: "&7欢迎来到&4副本&fXL"
  msg:
    added: "&6新的讯息 (&4&v1&6) 已添加了."
    help: "/dxl msg [id] '[msg]' - 显示或编辑讯息"
    updated: "&6讯息 (&4&v1&6) 更新."
  play:
    help: "/dxl play [name] - 允许玩家在没有传送门的情况下玩副本"
  portal:
    help: "/dxl portal ([material=portal]) - 创建一个通向副本的传送门"
  reload:
    buttonCaliburn: "&9[ 重新载入副本内容 ]"
    caliburn: "&e自定义物品: &o[&v1] &e怪物: &o[&v2] &e战利品表: &o[&v3]"
    help: "/dxl reload - 重新加载插件"
    players: "&4Warning: 如果您重新加载插件，所有玩家将被踢出他们的游戏."
    success: "&7成功重新加载了DungeonsXL."
  rename:
    help: "/dxl rename [old name] [new name] - 将地图名称重命名。此命令不会破坏包含此地图的副本."
    success: "&6成功将&4&v1&6重命名地图为 &4&v2&6."
  resourcePack:
    help: "/dxl resourcepack [ID] - 下载在主配置文件中注册的资源包；使用“reset”去重置"
  save:
    help: "/dxl save - 保存当前的副本地图"
    success: "&6地图已保存."
  status:
    help: "/dxl status - 显示DungeonsXL的状态"
  test:
    help: "/dxl test - 以测试模式启动游戏"
  uninvite:
    help: "/dxl uninvite [player] [map] - 取消邀请玩家编辑地图"
    success: "&4&v1&6 已成功删除编辑地图&4&v2&6的权限."
dayOfWeek:
  0: "星期天"
  1: "星期一"
  2: "星期二"
  3: "星期三"
  4: "星期四"
  5: "星期五"
  6: "星期六"
error: 
  bed: "&4无法在副本使用床."
  blockOwnTeam: "&4这个方块属属于你们小队."
  chestIsOpened: "&4这个箱子已经被打开过了."
  cmd: "&4该命令无法在副本使用."
  cooldown: "&4该副本冷却时间为 &6&v1&4 小时! "
  dispenser: "&4无法使用这个发射器."
  drop: "&4无法丢弃该物品"
  enderchest: "&4在副本中无法使用末影箱!"
  inGroup: "&4玩家 &6&v1&4 已经是小队成员了."
  joinGroup: "&4你需要先加入一个小队!."
  leaveDungeon: "&4你必须先离开当前的副本."
  leaveGame: "&4你必须先离开当前的游戏."
  leaveGroup: "&4你必须先离开你的小队."
  msgFormat: "&4请使用 &6\" &4将信息包围起来."
  msgIdDoesNotExist: "&4Id为 &6&v1&4的信息不存在."
  msgNoInt: "&4条件 [id] 需要包含数字."
  nameInUse: "&4名字 &6&v1 &4已经被使用."
  nameTooLong: "&4名字不能超过15个字符."
  noGame: "&4你目前不参加游戏."
  noItemInMainHand: "&4您的主手上没有物品."
  noLeaveInTutorial: "&4您不能在教程中使用此命令."
  noPermissions: "&4没有权限."
  noProtectedBlock: "&4这不是由DungeonsXL保护的方块."
  noReadySign: "&4世界d &6&v1 &4似乎还没有准备好的迹象。 无法开始游戏，只有大厅地下城标志会被初始化。"
  noRewardsTime: "&4您在 &6&v1&4 之前无法获得奖励."
  noSuchAnnouncement: "&4此公告不存在."
  noSuchDungeon: "&4这个副本不存在."
  noSuchGroup: "&4小队 &6&v1&c不存在."
  noSuchMap: "&4世界 &6&v1&c不存在."
  noSuchPlayer: "&4玩家 &6&v1&4不存在."
  noSuchResourcePack: "&4该资源包 &6&v1 &4没有在配置文件中注册."
  noSuchShop: "&4商店 &v1 &4不存在......"
  notInDungeon: "&4你不在副本中."
  notInGame: "&4该小队 &6&v1&4 不是这个游戏的成员."
  notInGroup: "&4该玩家 &6&v1&4 不是小队 &6&v2 &4的成员."
  notInvited: "&4你没有收到小队 &6&v1&4的邀请."
  notLeader: "&4您不是小队的队长."
  notSaved: "&4地图 &6&v1&4 还没有保存到副本文件DungeonsXL/maps/中."
  ready: "&4请先选择你的职业."
  requirements: "&4你不符合副本的要求."
  selfNotInGroup: "&4您不在任何小队中."
  signWrongFormat: "&4这个牌子书写错误."
  tooManyInstances: "&4太多的副本正在运行请稍等一会儿."
  tooManyTutorials: "&4有太多的教程正在运行,请稍等一会儿."
  tutorialDoesNotExist: "&4教程副本不存在."
group: 
  bedDestroyed: "&6小队 &4&v1 &6的床被 &4&v2&6摧毁了!."
  congrats: "&6大吉大利!"
  congratsSub: "&l&4你的小队 &v1 &4获得了胜利."
  created: "&4&v1&6 创建了小队 &4&v2&6."
  death: "&4&v1 &6被击杀. &4&v2 剩余 &4&v3 &6人存活."
  deathKick: "&4&v1 &6被移除,因为 &4&v2 &6无人存活."
  defeated: "&4&4小队 &4v1 &6因为失去了最后一分而失败了."
  disbanded: "&4&v1&6 解散了小队 &4&v2&6."
  flagCaptured: "&4&v1&6 抢夺了小队 &4&v2&6 的旗帜!."
  flagLost: "&4&v1&6 因为死亡而丢失了 &4&v2&6 的旗帜."
  flagStealing: "&4&v1&6 正在夺取小队 &4&v2&6的旗帜!"
  invitedPlayer: "&4&v1&6 邀请了玩家 &4&v2&6 加入小队 &4&v3&6."
  joinedGame: "&6小队成功加入游戏."
  kickedPlayer: "&4&v1&6 从小队 &4&v3&6 将 &4&v2&6 踢了出去."
  killed: "&4&v1 &6被 &4&v2&6击杀. &4&v3&6 剩余 &4&v4 &6人存活."
  killedKick: "&4&v1&6 被 &4&v2&6击杀. &4&v3 无人存活."
  livesAdded: "&6你的小队获得 &4&v1&6 存活的奖励."
  livesRemoved: "&6你小队失去了 &4&v1&6 条生命."
  playerJoined: "&6玩家 &4&v1&6 加入了小."
  rewardChest: "&6您的小队获得了奖励宝箱."
  uninvitedPlayer: "&4&v1&6 收回 &4&v2&6 加入小队 &4&v3&6 的邀请."
  waveFinished: "&6你小队击败了第 &4&v1&6波怪物. 下一波怪物将在 &4&v2&6秒后出现.."
player: 
  blockInfo: "&6方块ID: &2&v1"
  checkpointReached: "&6到达检查点."
  death: "&4&v1 &6已经死亡,剩余 &4&v2 &6生命."
  deathKick: "&2&v1 &6已经死亡,被踢出副本."
  finishedDungeon: "&6成功通关副本."
  finished_Floor: "&&6成功完成当前关卡."
  invited: "&4&v1&6 邀请你加入小队 &4&v2&6."
  joinGroup: "&6成功加入小队."
  Kicked: "&4你被移出了小队 &6&v1&4."
  Killed: "&4&v1 &6被 &4&v2 &6击杀了,剩余 &4&v3 &6生命."
  KilledKick: "&4&v1&6 被 &4&v2 &6击杀了并且失去了生命."
  LeaveGroup: "&6成功离开小队!"
  LeftGroup: "&6玩家 &4&v1&6 离开了小队!"
  LivesAdded: "&6获得了剩余 &4&v1&6 生命的奖励."
  LivesRemoved: "&6你失去了 &4&v1&6 生命!"
  LootAdded: "&4&v1&6 被加入了你的奖励箱!"
  newLeader: "&6您现在是小队的新队长."
  Offline: "&玩家 &4&v1&6 离线了. 在 &4&v2&6 秒后将被踢出副本!"
  OfflineNever: "&6玩家 &4&v1&6 离线了. 但是他不会被系统自动移除副本!"
  portal:
    abort: "&6传送门创建被取消."
    created: "&6传送门已经被创建."
    introduction: "&6使用木剑点击门的两个角."
    progress: "&6第一个角已选取.请选取第二个角."
    rotate: "&6您想旋转传送门吗?"
  protectedBlockDeleted: "&6成功移除保护."
  ready: "&6你已经准备好开始副本了."
  signCopied: "&6成功复制牌子信息."
  signCreated: "&6成功创建副本牌子."
  timeKick: "&2&v1&6时间耗尽."
  timeLeft: "&v1你还有 &6&v2 &v1秒去完成这个副本."
  treasures: "&1宝藏"
  uninvited: "&4&v1&6 带回您的邀请到小队 &4&v2&6."
  unlimitedLives: "无限"
  waitForOtherPlayers: "&6等待小队成员..."
requirement: 
  fee: "&6你花费了 &4&v1 &6货币进入副本."
  feeItems: "物品"
  feeLevel: "等级"
  feeMoney: "货币"
  forbiddenItems: "禁止物品"
  groupSize: "小队人数上限"
  keyItems: "Keys"
  permission: "权限"
  timeframe: "时间范围"
reward: 
  general: "&6完成了副本,你获得了 &4&v1 &6."
sign: 
  end: "&a结束"
  floor: 
    1: "&a进入"
    2: "&a下一层"
  global: 
    full: "&4小队已满"
    isPlaying: "&4游戏中"
    joinGame: "&a加入游戏"
    joinGroup: "&a加入小队"
    newGame: "&a新游戏"
    newGroup: "&a新的小队"
  leave: "&a离开"
  ready: "&a准备"
  resourcePack: "&a下载资源包"
  wave: 
    1: "&a开始"
    2: "&a下一波"

**Comment by RaymondW722** [comment]
chinese_Traditional

> announcer:
  click: "&4&l=> &6點擊此處加入 &4&l<="
button: 
  accept: "&a[ 接受 ]"
  deny: "&4[ 拒絕 ]"
  okay: "&a[ OK ]"
cmd:
  announce:
    help: "/dxl announce [name] - 運行公告腳本"
  break:
    breakMode: "&6您現在可以打破DungeonsXL保護的方塊."
    help: "/dxl break - 打破DungeonsXL保護的方塊"
    protectedMode: "&6您現在無法再打破DungeonsXL保護的方塊."
  chat:
    dungeonChat: "&6您已進入副本聊天模式。"
    help: "/dxl chat - 更改聊天模式"
    normalChat: "&6你已進入公共聊天模式。"
  chatspy:
    help: "/dxl chatspy - 開啟/關閉 聊天監聽"
    started: "&6 你開啟了 聊天監聽."
    stopped: "&6 你關閉了 聊天監聽."
  create:
   help: "/dxl create [name] - 創建副本地圖"
  delete:
    backups: "&6你確定要刪除所有的備份嗎?"
    help: "/dxl delete [name] - 刪除副本地圖"
    success: "&6成功刪除地圖 &4&v1&6."
  dungeonItem:
    dungeonItemHelp: "&6遊戲結束後，即使各自的副本設置通常允許保留它，也會從玩家的背包中刪除&4副本物品&6。."
    globalItemHelp: "&6遊戲結束後，如果各個副本設置通常允許保留主世界背包，則 &4玩家 &6可以從副本中取回原有背包"
    help: "/dxl dungeonItem [true|false|info] - 遊戲結束後，如果各個副本設置通常允許保留主世界背包，則 &4玩家 &6可以從副本中取回原有背包。"
    info: 
      dungeon: "&這個物品是 &4副本物品&6."
      global: "&6這個物品是 &4通用物品&6."
    set: 
      dungeon: "&6成功將此物品設為 &4副本物品&6."
      global: "&6成功將此物品設為 &4通用物品&6."
  edit:
    help: "/dxl edit [map] - 編輯副本地圖"
  enter: 
    help: "/dxl enter ([joining group]) [target group] - 讓團隊A進入團隊B的遊戲"
    success: "&6團隊 &4&v1 &6成功進入 &4&v2&6 的遊戲."
  escape: 
    help: "/dxl escape - 放棄保存並離開編輯中的地圖"
  game: 
    help: "/dxl game - 顯示有關當前遊戲會話的資訊"
  group:
    help: 
      create: "/dxl group create [團隊名] - 創建一個團隊"
      disband: "/dxl group disband ([團隊名]) - 解散團隊"
      invite: "/dxl group invite [玩家名] - 邀請某人加入你的團隊"
      join: "/dxl group join [團隊名]- 加入團隊"
      kick: "/dxl group kick [玩家名] - 踢出某人"
      main: "/dxl group - 展示團隊指令"
      show: "/dxl group show [團隊名] - 展示團隊"
      uninvite: "/dxl group uninvite [玩家名] - 取消邀請玩家加入團隊"
  help:
    help: "/dxl help [page] - 顯示説明頁面"
  import:
    help: "/dxl import [world] - 從世界列表中導入世界作為副本地圖"
    success: "&6成功導入世界 &4&v1&6."
  invite:
    help: "/dxl invite [player] [dungeon] - 邀請玩家編輯副本"
    success: "&6玩家 &4&v1&6 被成功邀請編輯地圖 &4&v2&6."
  join:
    help: "/dxl join [announcement] - 打開菜單加入即將參加的遊戲的團隊
  kick:
    help: "/dxl kick [player] - 將玩家踢出團隊和副本"
    success: "&6Successfully 玩家 &4&v1&6 被踢出團隊."
  leave:
    help: "/dxl leave - 離開當前團隊和副本或編輯世界"
    success: "&6您已成功離開團隊."
  list:
    help: "/dxl list ([dungeon|map|loaded]) ([dungeon]) - 列出所有副本"
  lives:
    group: "&4&v1 &6剩餘 &4&v2 &6生命."
    help: "/dxl lives [玩家名] - 顯示玩家剩餘的生命"
    player: "&4&v1 &6剩餘 &4&v2 &6生命."
  main:
    compatibility: "&eInternals: &o[&v1] &eVault: &o[&v2] &eItemsXL: &o[&v3]"
    help: "/dxl - 一般狀態資訊"
    helpInfo: "&7輸入 &o/dxl help&r&7 以獲取更多資訊."
    loaded: "&e地圖: &o[&v1] &e副本: &o[&v2] &e已載入: &o[&v3] &e玩家: &o[&v4]"
    welcome: "&7歡迎來到&4副本&fXL"
  msg:
    added: "&6新的訊息 (&4&v1&6) 已添加了."
    help: "/dxl msg [id] '[msg]' - 顯示或編輯訊息"
    updated: "&6訊息 (&4&v1&6) 更新."
  play:
    help: "/dxl play [name] - 允許玩家在沒有傳送門的情況下玩副本"
  portal:
    help: "/dxl portal ([material=portal]) - 創建一個通向副本的傳送門"
  reload:
    buttonCaliburn: "&9[ 重新載入副本內容 ]"
    caliburn: "&e自訂物品: &o[&v1] &e怪物: &o[&v2] &e戰利品表: &o[&v3]"
    help: "/dxl reload - 重新載入外掛程式"
    players: "&4Warning: 如果您重新載入外掛程式，所有玩家將被踢出他們的遊戲."
    success: "&7成功重新載入了DungeonsXL."
  rename:
    help: "/dxl rename [old name] [new name] - 將地圖名稱重命名。此命令不會破壞包含此地圖的副本."
    success: "&6成功將&4&v1&6重命名地圖為 &4&v2&6."
  resourcePack:
    help: "/dxl resourcepack [ID] - 下載在主設定檔中註冊的資源包；使用“reset”去重置"
  save:
    help: "/dxl save - 保存當前的副本地圖"
    success: "&6地圖已保存."
  status:
    help: "/dxl status - 顯示DungeonsXL的狀態"
  test:
    help: "/dxl test - 以測試模式啟動遊戲"
  uninvite:
    help: "/dxl uninvite [player] [map] - 取消邀請玩家編輯地圖"
    success: "&4&v1&6 已成功刪除編輯地圖&4&v2&6的許可權."
dayOfWeek:
  0: "星期天"
  1: "星期一"
  2: "星期二"
  3: "星期三"
  4: "星期四"
  5: "星期五"
  6: "星期六"
error: 
  bed: "&4無法在副本使用床."
  blockOwnTeam: "&4這個方塊屬屬於你們團隊."
  chestIsOpened: "&4這個箱子已經被打開過了."
  cmd: "&4該命令無法在副本使用."
  cooldown: "&4該副本冷卻時間為 &6&v1&4 小時! "
  dispenser: "&4無法使用這個發射器."
  drop: "&4無法丟棄該物品"
  enderchest: "&4在副本中無法使用末影箱!"
  inGroup: "&4玩家 &6&v1&4 已經是團隊成員了."
  joinGroup: "&4你需要先加入一個團隊!."
  leaveDungeon: "&4你必須先離開當前的副本."
  leaveGame: "&4你必須先離開當前的遊戲."
  leaveGroup: "&4你必須先離開你的團隊."
  msgFormat: "&4請使用 &6\" &4將資訊包圍起來."
  msgIdDoesNotExist: "&4Id為 &6&v1&4的資訊不存在."
  msgNoInt: "&4條件 [id] 需要包含數位."
  nameInUse: "&4名字 &6&v1 &4已經被使用."
  nameTooLong: "&4名字不能超過15個字元."
  noGame: "&4你目前不參加遊戲."
  noItemInMainHand: "&4您的主手上沒有物品."
  noLeaveInTutorial: "&4您不能在教程中使用此命令."
  noPermissions: "&4沒有許可權."
  noProtectedBlock: "&4這不是由DungeonsXL保護的方塊."
  noReadySign: "&4世界d &6&v1 &4似乎還沒有準備好的跡象。 無法開始遊戲，只有大廳地下城標誌會被初始化。"
  noRewardsTime: "&4您在 &6&v1&4 之前無法獲得獎勵."
  noSuchAnnouncement: "&4此公告不存在."
  noSuchDungeon: "&4這個副本不存在."
  noSuchGroup: "&4團隊 &6&v1&c不存在."
  noSuchMap: "&4世界 &6&v1&c不存在."
  noSuchPlayer: "&4玩家 &6&v1&4不存在."
  noSuchResourcePack: "&4該資源包 &6&v1 &4沒有在設定檔中註冊."
  noSuchShop: "&4商店 &v1 &4不存在......"
  notInDungeon: "&4你不在副本中."
  notInGame: "&4該團隊 &6&v1&4 不是這個遊戲的成員."
  notInGroup: "&4該玩家 &6&v1&4 不是團隊 &6&v2 &4的成員."
  notInvited: "&4你沒有收到團隊 &6&v1&4的邀請."
  notLeader: "&4您不是團隊的隊長."
  notSaved: "&4地圖 &6&v1&4 還沒有保存到副本檔DungeonsXL/maps/中."
  ready: "&4請先選擇你的職業."
  requirements: "&4你不符合副本的要求."
  selfNotInGroup: "&4您不在任何團隊中."
  signWrongFormat: "&4這個牌子書寫錯誤."
  tooManyInstances: "&4太多的副本正在運行請稍等一會兒."
  tooManyTutorials: "&4有太多的教程正在運行,請稍等一會兒."
  tutorialDoesNotExist: "&4教程副本不存在."
group: 
  bedDestroyed: "&6團隊 &4&v1 &6的床被 &4&v2&6摧毀了!."
  congrats: "&6大吉大利!"
  congratsSub: "&l&4你的團隊 &v1 &4獲得了勝利."
  created: "&4&v1&6 創建了團隊 &4&v2&6."
  death: "&4&v1 &6被擊殺. &4&v2 剩餘 &4&v3 &6人存活."
  deathKick: "&4&v1 &6被移除,因為 &4&v2 &6無人存活."
  defeated: "&4&4團隊 &4v1 &6因為失去了最後一分而失敗了."
  disbanded: "&4&v1&6 解散了團隊 &4&v2&6."
  flagCaptured: "&4&v1&6 搶奪了團隊 &4&v2&6 的旗幟!."
  flagLost: "&4&v1&6 因為死亡而丟失了 &4&v2&6 的旗幟."
  flagStealing: "&4&v1&6 正在奪取團隊 &4&v2&6的旗幟!"
  invitedPlayer: "&4&v1&6 邀請了玩家 &4&v2&6 加入團隊 &4&v3&6."
  joinedGame: "&6團隊成功加入遊戲."
  kickedPlayer: "&4&v1&6 從團隊 &4&v3&6 將 &4&v2&6 踢了出去."
  killed: "&4&v1 &6被 &4&v2&6擊殺. &4&v3&6 剩餘 &4&v4 &6人存活."
  killedKick: "&4&v1&6 被 &4&v2&6擊殺. &4&v3 無人存活."
  livesAdded: "&6你的團隊獲得 &4&v1&6 存活的獎勵."
  livesRemoved: "&6你團隊失去了 &4&v1&6 條生命."
  playerJoined: "&6玩家 &4&v1&6 加入了小."
  rewardChest: "&6您的團隊獲得了獎勵寶箱."
  uninvitedPlayer: "&4&v1&6 收回 &4&v2&6 加入團隊 &4&v3&6 的邀請."
  waveFinished: "&6你團隊擊敗了第 &4&v1&6波怪物. 下一波怪物將在 &4&v2&6秒後出現.."
player: 
  blockInfo: "&6方塊ID: &2&v1"
  checkpointReached: "&6到達檢查點."
  death: "&4&v1 &6已經死亡,剩餘 &4&v2 &6生命."
  deathKick: "&2&v1 &6已經死亡,被踢出副本."
  finishedDungeon: "&6成功通關副本."
  finished_Floor: "&&6成功完成當前關卡."
  invited: "&4&v1&6 邀請你加入團隊 &4&v2&6."
  joinGroup: "&6成功加入團隊."
  Kicked: "&4你被移出了團隊 &6&v1&4."
  Killed: "&4&v1 &6被 &4&v2 &6擊殺了,剩餘 &4&v3 &6生命."
  KilledKick: "&4&v1&6 被 &4&v2 &6擊殺了並且失去了生命."
  LeaveGroup: "&6成功離開團隊!"
  LeftGroup: "&6玩家 &4&v1&6 離開了團隊!"
  LivesAdded: "&6獲得了剩餘 &4&v1&6 生命的獎勵."
  LivesRemoved: "&6你失去了 &4&v1&6 生命!"
  LootAdded: "&4&v1&6 被加入了你的獎勵箱!"
  newLeader: "&6您現在是團隊的新隊長."
  Offline: "&玩家 &4&v1&6 離線了. 在 &4&v2&6 秒後將被踢出副本!"
  OfflineNever: "&6玩家 &4&v1&6 離線了. 但是他不會被系統自動移除副本!"
  portal:
    abort: "&6傳送門創建被取消."
    created: "&6傳送門已經被創建."
    introduction: "&6使用木劍點擊門的兩個角."
    progress: "&6第一個角已選取.請選取第二個角."
    rotate: "&6您想旋轉傳送門嗎?"
  protectedBlockDeleted: "&6成功移除保護."
  ready: "&6你已經準備好開始副本了."
  signCopied: "&6成功複製牌子資訊."
  signCreated: "&6成功創建副本牌子."
  timeKick: "&2&v1&6時間耗盡."
  timeLeft: "&v1你還有 &6&v2 &v1秒去完成這個副本."
  treasures: "&1寶藏"
  uninvited: "&4&v1&6 帶回您的邀請到團隊 &4&v2&6."
  unlimitedLives: "無限"
  waitForOtherPlayers: "&6等待團隊成員..."
requirement: 
  fee: "&6你花費了 &4&v1 &6貨幣進入副本."
  feeItems: "物品"
  feeLevel: "等級"
  feeMoney: "貨幣"
  forbiddenItems: "禁止物品"
  groupSize: "團隊人數上限"
  keyItems: "Keys"
  permission: "許可權"
  timeframe: "時間範圍"
reward: 
  general: "&6完成了副本,你獲得了 &4&v1 &6."
sign: 
  end: "&a結束"
  floor: 
    1: "&a進入"
    2: "&a下一層"
  global: 
    full: "&4團隊已滿"
    isPlaying: "&4遊戲中"
    joinGame: "&a加入遊戲"
    joinGroup: "&a加入團隊"
    newGame: "&a新遊戲"
    newGroup: "&a新的團隊"
  leave: "&a離開"
  ready: "&a準備"
  resourcePack: "&a下載資源包"
  wave: 
    1: "&a開始"
    2: "&a下一波"

**Comment by RaymondW722** [comment]
[language.zip](https://github.com/DRE2N/DungeonsXL/files/5892009/language.zip)

**Comment by Sataniel98** [comment]
Thank you, I'll add them :)

**Comment by HuJunwei23333** [comment]
爱了爱了

**Comment by HuJunwei23333** [comment]
136行中间的引号

**Comment by HuJunwei23333** [comment]
可能是文本格式有问题我复制进去直接坏了，发个文件呗awa
![)I1YS3(AN~O1C1JJN5R6( T](https://user-images.githubusercontent.com/30760975/107519173-e6955e00-6bea-11eb-9dd2-12a903ecdca2.png)
汉化文本没有缩进格式aawa

**Comment by Sataniel98** [comment]
> 可能是文本格式有问题我复制进去直接坏了，发个文件呗awa
> ![)I1YS3(AN~O1C1JJN5R6( T](https://user-images.githubusercontent.com/30760975/107519173-e6955e00-6bea-11eb-9dd2-12a903ecdca2.png)
> 汉化文本没有缩进格式aawa

MD swallowed the indents, try these ones:

https://raw.githubusercontent.com/DRE2N/DungeonsXL/translations/languages/chinese.yml

https://raw.githubusercontent.com/DRE2N/DungeonsXL/translations/languages/chinese_traditional.yml
