### ISSUE TITLE
Removes Potion Effects

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#967]
So when someone joins to a dungeon the potion effects they have disappear is there anyway to change this its essential for my server

**Comment by Sataniel98** [comment]
Does it not keep them if you set keepInventoryOnEnter to true?

**Comment by ghost** [comment]
> Does it not keep them if you set keepInventoryOnEnter to true?

its kinda buggy sometimes it keeps it sometimes it doesnt
