### ISSUE TITLE
Despawn MythicMobs mobs when unloading a world.

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#969]
**Please describe the use case or the problem your request is related to.**

(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...];)

**Describe the solution you'd like**

(A clear and concise description of what you want to happen.)

**Describe alternatives you've considered**

(A clear and concise description of any alternative solutions or features you've considered.)

**Comment by Sataniel98** [comment]
I don't think this is our problem except something DXL does prevents them from being despawned. But MM should in principle despawn its mobs itself when a world is unloaded.
