### ISSUE TITLE
136行中间的引号

### ISSUE THREAD

**Issue by RaymondW722** [DRE2N/DungeonsXL#972]
136行中间的引号

  原句是这样的emmm
msgFormat: "&4Please use &6\" &4to mark the beginning and the end of the message."

**Comment by HuJunwei23333** [comment]
原来是没有缩进格式了，我复制进去就没有aaa

**Comment by Sataniel98** [comment]
Not sure if I understand the issue correctly but the \ symbol escapes the " so there's nothing wrong here. See https://github.com/DRE2N/DungeonsXL/blob/master/core/src/main/resources/languages/english.yml#L136

I can't read Chinese so please write in English, German or French if you need help.
