### ISSUE TITLE
How to generate dungeon?

### ISSUE THREAD

**Issue by aril3721** [DRE2N/DungeonsXL#973]
Pls somebody tech me how to generate a dungeon.

My server
Paper 1.12.2

**Comment by aril3721** [comment]
Uwu

**Comment by Malfrador** [comment]
DXL does not generate Dungeons. Dungeons are instanced worlds that you build yourself that are completely separated from the main world. It does not generate Minecraft "Dungeons", you might want to check out the spigot page to figure out what DXL does.

You can create a new dungeon world using /dxl create <name>. There is a "getting started" guide in the wiki.
