### ISSUE TITLE
DXL World crashes server randomly sometimes

### ISSUE THREAD

**Issue by cerberus402** [DRE2N/DungeonsXL#975]
https://pastebin.com/Rt98GSiU

DungeonsXL will randomly crash the server waiting for chunk loading/saving. This error has been occurring for me on versions 1.14.4, 1.15.2, as well as 1.16.5. I was never able to resolve the issue on my own.

This error occured right after I imported a world into DungeonsXL and went in to edit it. This happens regardless of dungeon size (I have it happen on small 100x100 dungeons, as well as larger dungeons), it just so happened this time to be chunk -214, -14. The chunk will be random every time.

This crash hard locks the server and causes rollbacks in player data.

**Comment by Sataniel98** [comment]
DungeonsXL does not seem to be involved anywhere in the logs, the classes are all internals that don't seem to be called by a plugin. I'm sorry but I can't help you with this.

**Comment by cerberus402** [comment]
But this only happens when the world is a dungeon? The world is fine as a normal world with multiverse, but then as soon as it's imported and becomes a dungeon these crashes happen. Surely that has to be related? They're all internal classes yes, but they are all related to loading and saving of chunks **in a dungeon game**.

**Comment by AGP333** [comment]
I have had a similar issue with my server randomly crashing when loading chunks. After some time the issue just stops happening without any changes.
