### ISSUE TITLE
ResourcePack sign.

### ISSUE THREAD

**Issue by goldenkuky209** [DRE2N/DungeonsXL#977]
Wiki says: "IDs may be registered in the main configuration file."
But when i go to the main config file there is nothing about Resource Packs.
Could you tell me how the sign works and what to put in the config?

**Comment by Sataniel98** [comment]
The section is called "resourcePacks" and it is a map of IDs and the pack's link, like

`resourcePacks: {"PackID": "https://example.com/MyRP.zip"}`

It was indeed missing in the wiki, so I've added an example. Thank you for letting me know.
