### ISSUE TITLE
Where do I create new classes & if its not too complicated to explain, how?

### ISSUE THREAD

**Issue by liavos** [DRE2N/DungeonsXL#982]
**The feature you'd like to know more about** Classes

(e.g. game rules)

**Link to the wiki article (in case it exists)**

**What did you already try?** I tried creating a class named Warrior in Plugins -> DungeonsXL -> scripts -> classes, i made a new document and i pasted the example class from the github wiki, when I try to activate it, it says that the sign wasn't written correctly even though it was according to the wiki.

**Relevant configuration files** 

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
items:
  - 261,1
  - 262,64
  - 268,1
  - 298,1
  - 299,1
  - 300,1
  - 301,1
  - 364,3
  - 363,10
  - 261,1,16
dog: true
```

**Comment by Malfrador** [comment]
Can't confirm, the example from the wiki works correctly for me.
Basically, if you want to create a class named "Warrior":
 
1. Create a Warrior.yml file in /plugins/DungeonsXL/scripts/classes/. Make sure .yml is actually the file ending, not part of the name - on Windows you might need to enable "Show File Extensions".
2.  Copy the contents from the wiki page, make sure the indentation is correct (there should be no spaces before the ``items:``
3.  Create a [Classes] sign like this
```
[Classes]
Warrior
```
Its "Classes", not "Class" for some unknown reason. Also the class name might be case-sensitive, so check that.
If you have further questions, feel free to join the [Discord](https://discord.com/invite/F5aYxfy)
