### ISSUE TITLE
Information about the Russian language in the Wiki section

### ISSUE THREAD

**Issue by Trimitor** [DRE2N/DungeonsXL#990]
**The feature you'd like to know more about**

Information about the Russian language in the Wiki section

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/translations

The link to the Russian translation of the language file is incorrect (the link leads to the Spanish translation)
```

```

**Comment by Sataniel98** [comment]
Oh, sorry. I've added them both at the same time and seem to have mixed the links up.
