### ISSUE TITLE
Unable to edit or play any Dungeons

### ISSUE THREAD

**Issue by Omega7343** [DRE2N/DungeonsXL#994]
**Description**

I am unable to enter or edit any of the 4 dungeons I have created, nor am I able to create any new dungeons. 
It gives me "An internal error has occurred".

Note: this happened not too long after I introduced the Sentry plugin for Citizens (was trying to create hostile NPCs) into my server, but I don't know if this is related.
**Reproduce**

Example: /dxl create Test produces: An internal error has occurred while attempting to perform this command.

**Expected behavior**

A new dungeon should be made. Or in the other cases, the message above should not appear, and I should be able to access the dungeons. 

**Screenshots / GIFs / videos**

<img width="620" alt="Screen Shot 2021-03-09 at 8 57 47 pm" src="https://user-images.githubusercontent.com/39729401/110453794-ae663a00-811a-11eb-99fb-7101e259c34b.png">
<img width="871" alt="Screen Shot 2021-03-09 at 9 02 51 pm" src="https://user-images.githubusercontent.com/39729401/110453985-dfdf0580-811a-11eb-834e-e2d2b9694d2b.png">
<img width="878" alt="Screen Shot 2021-03-09 at 9 02 44 pm" src="https://user-images.githubusercontent.com/39729401/110454012-e40b2300-811a-11eb-8021-b010138dfc92.png">
<img width="721" alt="Screen Shot 2021-03-09 at 9 02 36 pm" src="https://user-images.githubusercontent.com/39729401/110454016-e53c5000-811a-11eb-9de1-26ad1544693a.png">

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents so that others can see if there are any syntax errors.)

```
Log: https://mclo.gs/8tx5Ppr 
```

**Comment by Omega7343** [comment]
Also: [21:29:44] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1063

**Comment by Sataniel98** [comment]
Looks like Bukkit can't serialize a skull in your inventory. Might be a 1.8 specific problem. I'll see what I can do, but it shouldn't occur if you try it with an empty inventory (or at least without that skull).

**Comment by Omega7343** [comment]
Ok, I will try now and let you know. Thanks

**Comment by Omega7343** [comment]
Indeed that was the issue. I have no idea why though, is it, as you said, a 1.8 problem?

**Comment by Sataniel98** [comment]
I've fixed a related issue (https://github.com/DRE2N/ItemsXL/issues/20). If that doesn't help, I can't imagine it's not a problem with 1.8, so I'll close this.
