### ISSUE TITLE
keepInventory not working

### ISSUE THREAD

**Issue by HighlightedTwin** [DRE2N/DungeonsXL#995]
**Description**

I have a 1.16.3 server with the latest version of DXL installed. My past issue with it was the ready sign but now it's resolved. However, I noticed every time I enter the dungeon, my inventory is gone. Even after checking and making sure all values for both files I created had the input of 'true' nothing changes.

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Leave edit mode with /dxl leave
3. (Outside of dungeon) place a group sign
4. Test with via the group sign and/or /dxl test
5. Spawn into the dungeon lobby with the inventory.

**Expected behavior**

I was hoping that after all of the setting up in the files and testing out the dungeon, my inventory would be kept, instead, it just disappears but it's there after leaving the dungeon.

**Screenshots / GIFs / videos**

Screenshot before entering dungeon:
![2021-03-10_16 14 27](https://user-images.githubusercontent.com/80426715/110702700-df00af00-81c0-11eb-9c39-f880bc235a6a.png)

Screenshot when entering the dungeon:
![2021-03-10_16 15 20](https://user-images.githubusercontent.com/80426715/110702639-cc867580-81c0-11eb-8748-0da3c54502ec.png)

![2021-03-10_16 15 58](https://user-images.githubusercontent.com/80426715/110702505-9943e680-81c0-11eb-9a96-e60ce5aced11.png)

Screenshot when leaving the dungeon:
![2021-03-10_16 16 13](https://user-images.githubusercontent.com/80426715/110702594-b973a580-81c0-11eb-8111-51c78a3118d6.png)

**Relevant configuration files**

Console Errors: N/A

Config Files:
![Screenshot (18)](https://user-images.githubusercontent.com/80426715/110702148-23d81600-81c0-11eb-998b-b81d003a5c26.png)
![Screenshot (19)](https://user-images.githubusercontent.com/80426715/110702158-276b9d00-81c0-11eb-8cc5-eec5a39e059e.png)

```

```

**Comment by kit8379** [comment]
Same here. I set it in default config.yml but not work.

**Comment by titanium6** [comment]
For me with dungeonsxl-dist-0.18-SNAPSHOT-1081, it's working. In config file of your dungeon, try to write this and nothing else :
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true

i also tested in main config file to avoid write in all dungeon config file but here it's not working

**Comment by kit8379** [comment]
> For me with dungeonsxl-dist-0.18-SNAPSHOT-1081, it's working. In config file of your dungeon, try to write this and nothing else :
> keepInventoryOnEnter: true
> keepInventoryOnFinish: true
> keepInventoryOnEscape: true
> 
> i also tested in main config file to avoid write in all dungeon config file but here it's not working

Can you teach me how to put the dungeon config file?
I just know how to set default config

**Comment by titanium6** [comment]
Just create a file as named confil.yml in this directory plugins/DungeonsXL/maps/name_of_your_dungeon and copy/paste this
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true

Save and restart your server because for now dxl restart is broken

Take a look here https://github.com/DRE2N/DungeonsXL/wiki/simple-dungeon. it's good example and you can dowload an example dungeon.

**Comment by HighlightedTwin** [comment]
> Just create a file as named confil.yml in this directory plugins/DungeonsXL/maps/name_of_your_dungeon and copy/paste this
> keepInventoryOnEnter: true
> keepInventoryOnFinish: true
> keepInventoryOnEscape: true
> 
> Save and restart your server because for now dxl restart is broken
> 
> Take a look here https://github.com/DRE2N/DungeonsXL/wiki/simple-dungeon. it's good example and you can dowload an example dungeon.

This didn't work for me sadly.

**Comment by titanium6** [comment]
If you are in the latest version, i don't know why it's working for me and not for you :/
Maybe it's a sign issue. Have you test with command  /dxl play ? 

Is it work now @kit8379 ?

**Comment by kit8379** [comment]
> If you are in the latest version, i don't know why it's working for me and not for you :/
> Maybe it's a sign issue. Have you test with command /dxl play ?
> 
> Is it work now @kit8379 ?

I can make it work with your method

**Comment by HighlightedTwin** [comment]
> If you are in the latest version, i don't know why it's working for me and not for you :/
> Maybe it's a sign issue. Have you test with command /dxl play ?
> 
> Is it work now @kit8379 ?

It didn't work. I may just have to redo the files again. Maybe I messed up somewhere but I just don't know where.

**Comment by Sataniel98** [comment]
Sorry for the late reply. The problem with the game rule inheritance system is fixed now, binaries will be uploaded within the next hours. The keepInventory game rules should work fine unless another plugin interferes (Multiverse-Inventories, PerWorldInventories etc.). If you encounter any issues with the new build, please let me know.
